/* Exam 1 review: immediate feedback, immutable first responses, separate correction history. */
(function(L){
'use strict';
var X=L.EXAM1,U=L.util,E=L.engine,S=L.store,I=L.itemUI,esc=U.esc;
function topic(id){return X.topics.find(function(t){return t.id===id;});}
function uid(){return Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,9);}
function byId(id){return S.load().examRuns.find(function(r){return r.id===id;});}
function active(){return byId(S.load().examActive);}
function save(r){if(r)r.updated=Date.now();return S.save();}
function resolve(id){return E.resolve({id:id});}
function groups(form,section){var f=X.forms[form],out=[];
 if(!section||section==='mc')f.mc.forEach(function(id,i){out.push({n:i+1,section:'mc',ids:[id]});});
 if(!section||section==='sa')f.sa.forEach(function(id,i){out.push({n:i+26,section:'sa',ids:[id]});});
 if(!section||section==='inv')f.cases.forEach(function(id,i){var cs=E.caseById(id);out.push({n:i+34,section:'inv',caseId:id,ids:cs.items.map(function(it){return it.id;})});});
 return out;
}
function allIds(r){return r.groups.reduce(function(a,g){return a.concat(g.ids);},[]);}
function start(gs,title,opt){var r={id:'exam1-'+uid(),version:X.version,title:title,form:opt&&opt.form||null,mode:opt&&opt.mode||'review',groups:gs,answers:{},orders:{},matchOrders:{},flags:{},cur:0,started:Date.now(),updated:Date.now(),finished:null};
 if(opt&&opt.fresh){r.freshVersion=opt.fresh.version;r.seed=opt.fresh.seed;r.freshItems=U.clone(opt.fresh.items);r.freshKeys=opt.fresh.keys.slice();}
 S.load().examRuns.push(r);
 gs.forEach(function(g){g.ids.forEach(function(id){var it=resolve(id);if(it.o)r.orders[id]=I.makeOrder(it);if(it.t==='match')r.matchOrders[id]=U.shuffleNotIdentity(U.uniq(it.pairs.map(function(p){return p[1];}).concat(it.extra||[])));});});
 S.load().examActive=r.id;save(r);return r;
}
function startForm(f,sec){return start(groups(f,sec),'Set '+f+(sec?' · '+({mc:'Multiple choice',sa:'Short answer',inv:'Investigations'}[sec]):' · Complete review'),{form:f});}
function startFreshForm(f,seed){var made=L.freshMocks.create(f,S.load(),seed);return start(made.groups,'Fresh mock '+f,{form:f,mode:'fresh',fresh:made});}
function sourceItem(it){return (!it.media || (Array.isArray(it.media)?it.media.every(function(m){return m.kind==='img';}):it.media.kind==='img')) && !/in the diagram|shown|point [A-Z]|marker|blocks? [A-Z]|figure below|map below/i.test(it.q);}
function drillPool(tid,diagrams){return E.itemsFor(function(it){
 var promoted=(X.foundationIds||[]).indexOf(it.id)>=0;
 var topics=promoted&&X.foundationTopics&&X.foundationTopics[it.id]||L.examTopics(it);
 if((it.pool!=='exam1'&&!promoted)||it.t==='teach'||(tid&&topics.indexOf(tid)<0))return false;
 if(it.caseId){var cs=E.caseById(it.caseId);if(!cs||!cs.media||cs.media.kind!=='img')return false;}
 return diagrams&&it.caseId || sourceItem(it);
});}
function selectDrill(tid,diagrams,cid){
 var stats=E.conceptStats(),seen={},good={},lastSeen={};
 E.allAttempts().forEach(function(a){seen[a.i]=(seen[a.i]||0)+1;lastSeen[a.i]=a.t;});
 Object.keys(stats).forEach(function(c){var st=stats[c],hist=st.hist;
  if(st.reviewOpen&&st.lastMiss)hist=hist.slice(hist.indexOf(st.lastMiss)+1);
  good[c]={};hist.forEach(function(a){if(a.ok&&!a.h)good[c][a.root||a.i]=true;});
 });
 var pool=U.shuffle(drillPool(tid,diagrams).filter(function(it){return !cid||it.c===cid;}));
 pool.sort(function(a,b){return Number(!!good[a.c][a.masteryRoot||a.id])-Number(!!good[b.c][b.masteryRoot||b.id]) || (seen[a.id]||0)-(seen[b.id]||0) || (lastSeen[a.id]||0)-(lastSeen[b.id]||0);});
 var selected=[],used={},limit=cid?2:tid?(diagrams?5:8):20;
 function add(it){if(!it||used[it.id]||selected.length>=limit)return false;selected.push(it.id);used[it.id]=true;return true;}
 if(!tid&&diagrams){X.topics.forEach(function(t){add(pool.find(function(it){return !used[it.id]&&L.examTopics(it).indexOf(t.id)>=0;}));});}
 var cs=U.shuffle(U.uniq(pool.map(function(it){return it.c;}))).sort(function(a,b){return E.practicePriority(stats[a])-E.practicePriority(stats[b]) || stats[a].att-stats[b].att;});
 // Round-robin concepts, starting with open misses and unfinished mastery. Repeatedly
 // starting a drill must not strand a concept behind a larger neighboring question pool.
 while(selected.length<limit){var added=false;cs.forEach(function(c){var roots={};selected.forEach(function(id){var it=resolve(id);if(it.c===c)roots[it.masteryRoot||id]=true;});
  var it=pool.find(function(it){return it.c===c&&!used[it.id]&&!roots[it.masteryRoot||it.id];});if(add(it))added=true;
 });if(!added)break;}
 return selected;
}
function drill(tid,diagrams,cid){
 var selected=selectDrill(tid,diagrams,cid);
 var gs=selected.map(function(id,i){var it=resolve(id),cs=it.caseId&&E.caseById(it.caseId),t=topic(tid||L.examTopics(it)[0]);return {n:i+1,section:'drill',ids:[id],media:cs?cs.media:(it.media?null:diagrams?t.media[0]:null),sourceCase:cs?cs.title:null};});
 return start(gs,(cid?L.CONCEPTS[cid].name:tid?tid+' · '+topic(tid).title:'Source-figure practice')+' · '+(diagrams?'Diagram practice':'Topic practice'),{mode:'drill'});
}
function answer(r,id){return r.answers[id]||(r.answers[id]={draft:undefined,confidence:'m',first:null,tries:[],editing:false,updated:Date.now()});}
function latest(a){if(!a)return null;return a.tries.length?a.tries[a.tries.length-1]:a.first;}
function checked(r,id){var a=r.answers[id];return !!(a&&a.first&&a.first.grade);}
function completeResponse(it,v){if(it.t==='teach')return typeof v==='string'&&v.trim().length>0;if((it.t==='match'||it.t==='parts')&&(!Array.isArray(v)||v.length!==(it.pairs||it.parts).length))return false;return E.hasResponse(it,v);}
function check(r,id,cf){var it=resolve(id),a=answer(r,id);if(!completeResponse(it,a.draft))return false;
 if(a.first&&!a.editing)return false;
 var attempt={id:uid(),response:U.clone(a.draft),cf:cf||a.confidence||'m',assisted:!!a.first,at:Date.now(),self:it.t==='teach',grade:it.t==='teach'?null:E.grade(it,a.draft)};
 if(!a.first)a.first=attempt;else a.tries.push(attempt);
 a.editing=false;a.updated=Date.now();save(r);return attempt;
}
function selfMark(r,id,hits){var a=answer(r,id),last=latest(a),it=resolve(id);if(!last||!last.self||last.grade)return false;
 var want=(it.rubric||[]).length,n=hits.filter(function(x){return x;}).length;last.grade={ok:n===want,sc:want?n/want:0,rubric:hits.slice(),self:true};a.updated=Date.now();save(r);return true;}
function retry(r,id){var a=answer(r,id),last=latest(a);if(!last||!last.grade)return; a.editing=true;a.draft=undefined;a.updated=Date.now();save(r);}
function metrics(r,ids){ids=ids||allIds(r);var m={total:ids.length,checked:0,auto:0,autoTotal:0,autoCorrect:0,self:0,selfTotal:0,selfCorrect:0,corrected:0,needs:0,unanswered:0,mcCorrect:0,mcTotal:0};
 ids.forEach(function(id){var it=resolve(id),a=r.answers[id],first=a&&a.first,last=latest(a);if(it.t==='mc')m.mcTotal++;if(it.t==='teach')m.selfTotal++;else m.autoTotal++;
 if(!first||!first.grade){m.unanswered++;return;}m.checked++;if(first.self){m.self++;if(first.grade.ok)m.selfCorrect++;}else{m.auto++;if(first.grade.ok)m.autoCorrect++;}
 if(it.t==='mc'&&first.grade.ok)m.mcCorrect++;
 if(!first.grade.ok){if(last&&last.grade&&last.grade.ok)m.corrected++;else m.needs++;}
 });return m;
}
function topicMetrics(t){var stats=E.conceptStats(),cs=U.uniq(t.concepts).filter(E.hasPracticeContent),mastered=cs.filter(function(c){return stats[c].status==='mastered';}).length;
 var attempts=cs.reduce(function(out,c){return out.concat(stats[c].hist);},[]);
 var first=attempts.filter(function(a){return !a.correction;}),auto=first.filter(function(a){return !a.self;}),self=first.filter(function(a){return a.self;});
 return {mastered:mastered,concepts:cs.length,total:attempts.length,auto:auto.length,correct:auto.filter(function(a){return a.ok;}).length,
  needs:cs.filter(function(c){return stats[c].reviewOpen;}),corrected:attempts.filter(function(a){return a.correction&&a.ok;}).length,
  self:self.length,selfGood:self.filter(function(a){return a.ok;}).length};
}
function topicRecord(m){return m.total?m.total+' saved checks across all modes · '+m.correct+'/'+m.auto+' automatic first answers correct'+(m.self?' · '+m.selfGood+'/'+m.self+' written rubrics met':'')+(m.corrected?' · '+m.corrected+' correct correction'+(m.corrected===1?'':'s'):''):'No checked answers yet';}
function masteryDetails(t){var stats=E.conceptStats(),cs=U.uniq(t.concepts).filter(E.hasPracticeContent),left=cs.filter(function(c){return stats[c].status!=='mastered';}).length;
 return '<details class="mastery-details"><summary>Mastery details'+(left?' · '+left+' unfinished':' · all earned')+'</summary><p class="small muted">Every checked answer is saved. Repeating the same question adds practice history; mastery needs two different questions. Drafts count after you check them.</p><ul>'+cs.map(function(c){var st=stats[c];return '<li><b>'+esc(L.CONCEPTS[c].name)+'</b><p>'+esc(E.masteryNote(st))+'</p><p class="muted">'+st.att+' saved check'+(st.att===1?'':'s')+' · '+st.ok+' correct</p>'+((st.status!=='mastered'||st.reviewOpen)?'<button class="btn small" data-topic="'+t.id+'" data-concept="'+c+'">Practice concept</button>':'')+'</li>';}).join('')+'</ul></details>';
}
function statusHTML(){return '<p id="examSave" class="small '+(S.ok()?'muted':'noc')+'" role="status">'+(S.ok()?'Saved in this browser · drafts and feedback resume after reopening.':'Saving is blocked. Export a backup from Data before closing this tab.')+'</p>';}
function refreshSave(){var el=document.querySelector('#examSave');if(el){el.className='small '+(S.ok()?'muted':'noc');el.textContent=S.ok()?'Saved in this browser · '+new Date().toLocaleTimeString():'Saving failed. Keep this tab open and export a backup from Data.';}}
function touch(r){save(r);refreshSave();}
function top(){return '<p class="eyebrow">Tuesday, September 29 · Chapters 1–6</p><h1>Exam 1</h1><p class="lede">Study the professor’s review, then practice with your actual course figures. Check each answer immediately and work through corrections at your own pace.</p>';}
function buttons(){return '<nav class="row exam-tools" aria-label="Exam 1">'+[['','Mini-chapters'],['animations','Animated diagrams'],['figures','Figure workshop'],['writing','Short answers'],['sets','Full mocks'],['review','Review misses'],['history','My history']].map(function(x){return '<a class="btn" href="#exam1'+(x[0]?'/'+x[0]:'')+'">'+x[1]+'</a>';}).join('')+'<a class="btn" href="#data">Backup / restore</a></nav>';}
function stat(v,label,desc){return '<div class="stat"><b>'+esc(v)+'</b><span>'+esc(label)+'</span><small>'+esc(desc||'')+'</small></div>';}
function runStats(r){var m=metrics(r);return '<div class="grid4">'+stat(m.autoCorrect+'/'+m.autoTotal,'First-try automatic checks','Automatically checked parts; '+m.unanswered+' still unchecked.')+stat(m.corrected,'Corrected after feedback','First results remain unchanged.')+stat(m.needs,'Uncorrected in this run','Your live review queue also considers later practice.')+stat(m.selfCorrect+'/'+m.selfTotal,'Rubric fully met','Self-assessed explanations, shown separately.')+'</div>';}
function mapHTML(){var r=active(),h=top()+buttons()+statusHTML();
 h+='<div class="grid4">'+stat('25','Multiple choice','2 points each · 50 exam points')+stat('8','Short answers','Practice count · spoken range 6–8')+stat('7','Investigations','Practice count · spoken range 6–7')+stat(misses().length,'Open miss concepts','Shared with your main dashboard')+'</div>';
 if(r&&!r.finished&&!r.archived)h+='<div class="infobox"><b>Continue '+esc(r.title)+'</b><div class="row"><a class="btn pri" href="#exam1/take">Resume saved review</a></div></div>';
 h+='<section class="card"><h2>Your exam format</h2>'+L.EXAM_FACTS+I.srcChips(['R0924:lines 322–434; 4966–5000','SYL','CTX'])+'</section>';
  h+='<p class="small muted">These 16 groups organize his review; they are not 16 official exam categories. Every checked answer feeds the same mastery dashboard across all modes. Two different correct questions without hints, with medium/high confidence on the second, earn mastery permanently. New drills target unfinished concepts; recent misses remain in review.</p><div class="exam-topics">';
 X.topics.forEach(function(t){var m=topicMetrics(t);h+='<article class="card exam-topic"><p class="eyebrow">'+t.id+' · Reviewed Sep 24</p><h2><a href="#exam1/topic/'+t.id+'">'+esc(t.title)+'</a></h2><div class="progress" role="progressbar" aria-label="'+esc(t.title)+' mastery" aria-valuemin="0" aria-valuemax="'+m.concepts+'" aria-valuenow="'+m.mastered+'"><i style="width:'+U.pct(m.mastered,m.concepts)+'%"></i></div><p class="small">'+m.mastered+'/'+m.concepts+' concepts mastered · '+topicRecord(m)+(m.needs.length?' · <b class="warn">'+m.needs.length+' need work</b>':'')+'</p><div class="row"><a class="btn small pri" href="#exam1/topic/'+t.id+'">Learn</a><button class="btn small" data-topic="'+t.id+'">Practice topic</button><button class="btn small" data-diagram="'+t.id+'">Practice figure</button></div>'+masteryDetails(t)+'</article>';});
 return h+'</div>';
}
function topicHTML(id){var t=topic(id);if(!t)return '<h1>Topic unavailable</h1><a href="#exam1">Topic map</a>';var secs=U.uniq(t.concepts.map(function(c){return L.CONCEPTS[c].sec;}));
 return buttons()+'<p class="crumbs"><a href="#exam1">Exam 1</a> › '+id+'</p><h1>'+esc(t.title)+'</h1>'+masteryDetails(t)+'<p class="small">Review emphasis '+I.srcChips(['R0924:lines '+t.lines])+'</p><article class="card gcard">'+t.html+'<div class="traps">'+esc(t.trap)+'</div><p>Answer sources '+I.srcChips(t.sources)+'</p></article>'+(L.animatedDiagrams?L.animatedDiagrams.forTopic(id):'')+'<section class="card"><h2>The course figures</h2><p class="small muted">Original McGraw-Hill images from your slides and captures. Tap to enlarge. These are matches to the reviewed concepts; the exact exam images are unknown.</p>'+I.mediaHTML(t.media)+'</section><div class="row"><button class="btn pri" data-topic="'+id+'">Practice this topic</button><button class="btn" data-diagram="'+id+'">Practice its figure</button></div><section class="card"><h2>Related Guide sections</h2>'+secs.map(function(sec){var s=L.SECTIONS.find(function(x){return x.id===sec;});return '<p><a href="#guide/'+sec+'">'+esc(s.n+' '+s.title)+'</a></p>';}).join('')+'</section>';
}
function setsHTML(){var s=S.load(),current=active();return '<h1>Fresh mock exams</h1>'+buttons()+'<p class="lede">Generate a new exam with fresh observations, comparisons, and investigations. Questions already assigned in this browser are excluded across all three forms.</p><div class="infobox"><b>25 multiple choice → 8 short answers → 7 investigations.</b> Immediate feedback, saved first responses, and shared mastery. The original McGraw-Hill figures remain your references. Counts 8/7 are practice choices within the professor’s stated ranges.</div>'+(current&&current.freshVersion&&metrics(current).unanswered?'<p><a class="btn good" href="#exam1/take">Resume '+esc(current.title)+'</a> · Your saved exam keeps its questions.</p>':'')+'<p id="freshError" class="noc" role="status"></p><div class="exam-sets">'+['A','B','C'].map(function(f){var n=s.examRuns.filter(function(r){return r.freshVersion&&r.form===f;}).length;return '<section class="card"><h2>Mock '+f+'</h2><p>40 questions · 54 answer parts.<br>4 short terms + 4 written explanations.</p><p>'+({A:'Rock paths, boundaries, ocean-floor aging, isostasy, classification, pressure–temperature paths, and volcanoes.',B:'Rock paths, boundaries, ocean-floor aging, mineral structure, classification, melting mechanisms, and volcanoes.',C:'Rock paths, boundaries, isostasy, mineral structure, classification, Bowen’s series, and heat transfer.'}[f])+'</p><p class="small muted">'+n+' fresh exam'+(n===1?'':'s')+' saved for this form.</p><button class="btn pri" data-fresh-form="'+f+'">Generate mock '+f+'</button></section>';}).join('')+'</div><p class="small muted">Freshness is remembered in your saved progress, including backups. Concepts and course figures recur; observation combinations change. The curated pool is finite and stops instead of recycling questions when a required topic runs out. <a href="#exam1/history">Open a saved exam</a>.</p>';}
function historyHTML(){var s=S.load(),h='<h1>My study history</h1>'+buttons()+statusHTML();
 h+='<p class="small muted">Progress stays in this browser and origin. Use <a href="#data">Data → Export</a> to back up or move it. A new browser, a different local address, or clearing browser data needs an exported backup.</p>';
 if(!s.examRuns.length)h+='<p>No Exam 1 review runs yet.</p>';
 s.examRuns.slice().reverse().forEach(function(r){var m=metrics(r);h+='<article class="card"><h2>'+esc(r.title)+'</h2><p class="small">'+new Date(r.started).toLocaleString()+' · '+m.checked+'/'+m.total+' parts checked'+(m.unanswered?' · in progress':' · complete')+'</p><p>'+m.autoCorrect+'/'+m.auto+' first-try automatic checks · '+m.corrected+' corrected · '+m.needs+' uncorrected in this run</p><div class="row"><button class="btn" data-resume="'+r.id+'">'+(m.unanswered?'Resume':'Inspect answers')+'</button><a class="btn" href="#exam1/result/'+r.id+'">Summary</a></div></article>';});
 h+='<section class="card"><h2>Practice, cases, and Boss sessions</h2>'+((s.session?[s.session]:[]).concat((s.sessionHistory||[]).filter(function(x){return !s.session||x.id!==s.session.id;}))).slice().reverse().map(function(x){return '<p><b>'+esc(x.title)+'</b> · '+x.results.length+'/'+x.queue.length+' checked <button class="btn small" data-session-resume="'+x.id+'">'+(x.idx<x.queue.length?'Resume':'Inspect')+'</button></p>';}).join('')+'</section>';
 h+='<section class="card"><h2>Old-format mock history</h2><p class="small muted">Saved scores use the earlier question format and are kept separately.</p>';
 if(s.mockActive)h+='<div class="row"><a class="btn" href="#mock/take">Resume unfinished old-format mock</a><button class="btn" id="archiveOld">Archive unfinished old-format mock</button></div>';
 s.mocks.forEach(function(m){h+='<p><a href="#mock/result/'+m.id+'">'+esc(m.title)+' — '+m.score+'/'+m.total+'</a> <span class="small muted">old format</span></p>';});
 s.mockArchived.forEach(function(m){h+='<p>Archived unfinished old-format mock: '+esc(m.title)+' <button class="btn small" data-old-resume="'+m.id+'">Resume</button></p>';});
 return h+'</section>';
}
function sectionName(s){return {mc:'Section 1 · Multiple choice',sa:'Section 2 · Short answer',inv:'Section 3 · Investigations',drill:'Focused practice'}[s];}
function take(main){var r=active();if(!r){main.innerHTML='<h1>No active review</h1><a href="#exam1/sets">Choose a review set</a>';return;}var group=r.groups[r.cur]||r.groups[0],h='<div class="spread"><div><p class="eyebrow">'+esc(r.title)+'</p><h1>'+esc(sectionName(group.section))+'</h1></div><div class="row"><button class="btn" id="examFlag">'+((r.flags||{})[r.cur]?'★ Flagged':'Flag question')+'</button><a class="btn" href="#exam1">Save &amp; leave</a></div></div>'+statusHTML();
 h+='<p class="small">'+metrics(r).checked+'/'+allIds(r).length+' answer parts checked. Choose any question; every draft is saved.</p><nav class="mocknav exam-nav" aria-label="Questions">';
 var section='';r.groups.forEach(function(g,i){if(g.section!==section){if(section)h+='</div></div>';section=g.section;h+='<div class="navsec"><span class="tiny">'+esc(sectionName(section))+'</span><div class="cells">';}var all=g.ids.every(function(id){return checked(r,id);}),any=g.ids.some(function(id){return r.answers[id]&&r.answers[id].draft!==undefined;}),bad=g.ids.some(function(id){var last=latest(r.answers[id]);return last&&last.grade&&!last.grade.ok;});h+='<button class="'+(i===r.cur?'cur ':'')+(all?(bad?'r-no':'r-ok'):any?'ans':'')+'" data-q="'+i+'" aria-label="Question '+g.n+(all?', checked':any?', draft saved':', not checked')+'" '+(i===r.cur?'aria-current="step"':'')+'>'+g.n+((r.flags||{})[i]?' ★':'')+'</button>';});h+='</div></div></nav>';
 if(group.caseId){var cs=E.caseById(group.caseId);h+='<section class="card exam-figure"><h2>Q'+group.n+' · '+esc(cs.title)+'</h2><p>'+cs.stem+'</p>'+I.mediaHTML(cs.media)+'</section>';}
 else if(group.media)h+='<section class="card exam-figure"><h2>Q'+group.n+' · '+esc(group.sourceCase||'Course figure')+'</h2>'+(group.stem||'')+I.mediaHTML(group.media)+'</section>';
 group.ids.forEach(function(id,i){h+='<div id="exam-item-'+i+'"></div>';});
 h+='<div class="row spread"><button class="btn" id="examPrev" '+(r.cur===0?'disabled':'')+'>← Previous</button><div class="row"><a class="btn" href="#exam1/result/'+r.id+'">Progress summary</a><button class="btn pri" id="examNext">'+(r.cur===r.groups.length-1?'Finish review':'Next →')+'</button></div></div>';
 main.innerHTML=h;
 var map=main.querySelector('.exam-nav'),detail=document.createElement('details');detail.className='card question-map';detail.open=true;detail.innerHTML='<summary>Question map · green: checked correct · red: needs correction · ★ flagged</summary>';detail.appendChild(map);main.appendChild(detail);
 main.querySelector('#examFlag').onclick=function(){r.flags=r.flags||{};r.flags[r.cur]=!r.flags[r.cur];touch(r);L.app.route();};
 group.ids.forEach(function(id,i){renderAnswer(main.querySelector('#exam-item-'+i),r,id,'Q'+group.n+(group.ids.length>1?String.fromCharCode(97+i):''));});
 main.querySelectorAll('[data-q]').forEach(function(b){b.onclick=function(){r.cur=+b.dataset.q;touch(r);L.app.route();};});
 main.querySelector('#examPrev').onclick=function(){r.cur--;touch(r);L.app.route();};
 main.querySelector('#examNext').onclick=function(){if(r.cur<r.groups.length-1){r.cur++;touch(r);L.app.route();}else{r.finished=Date.now();touch(r);L.app.go('exam1/result/'+r.id);}};
}
function renderAnswer(host,r,id,label){var source=resolve(id),it=U.clone(source);delete it.caseId;var a=answer(r,id),last=latest(a),locked=!!last&&!a.editing,resp=locked?last.response:a.draft;
 // Source images only; never remap a figure-dependent old question to a different image.
 I.render(host,it,{mode:'mock',externalActions:true,header:label+' · '+L.examTopics(it).join(', '),order:r.orders[id],rights:r.matchOrders&&r.matchOrders[id],response:resp,locked:locked,onChange:function(v){a.draft=U.clone(v);a.updated=Date.now();touch(r);if(it.t==='mc'||it.t==='tf'){check(r,id,a.confidence||'m');L.app.route();return;}var b=host.querySelector('[data-check]');if(b)b.disabled=!completeResponse(it,v);}});
 if(!locked){var actions=host.querySelector('.actions');actions.innerHTML='<div class="row"><label class="small">Confidence <select class="exam-confidence" aria-label="Confidence"><option value="m">Medium</option><option value="l">Low / guessing</option><option value="h">High / certain</option></select></label><button class="btn pri" data-check '+(!completeResponse(it,a.draft)?'disabled':'')+'>'+(it.t==='teach'?'Check against model answer':'Check answer')+'</button></div>'+(a.first?'<p class="small muted">Correction attempt. Your first response and result stay unchanged.</p>':'');
 var cf=actions.querySelector('select');cf.value=a.confidence||'m';cf.onchange=function(){a.confidence=cf.value;a.updated=Date.now();touch(r);};
 if(it.t==='mc'||it.t==='tf'){actions.querySelector('[data-check]').remove();actions.insertAdjacentHTML('beforeend','<p class="small muted">Choose your confidence, then select an answer for immediate feedback.</p>');host.querySelector('.item').insertBefore(actions,host.querySelector('.answer'));return;}
 actions.querySelector('[data-check]').onclick=function(){if(check(r,id,actions.querySelector('select').value)){L.app.route();document.getElementById(host.id).scrollIntoView({block:'nearest'});}};return;}
 if(it.t==='teach'){var fb=host.querySelector('.feedback');fb.innerHTML='<div class="fb"><div class="verdict">Model answer · self-assessment</div><p>'+it.model+'</p><p class="small muted">Compare with your saved response above. Mark each point your answer actually includes.</p><div class="exam-rubric">'+it.rubric.map(function(p,i){return '<label><input type="checkbox" data-rubric="'+i+'" '+(last.grade&&last.grade.rubric[i]?'checked':'')+' '+(last.grade?'disabled':'')+'> '+esc(p)+'</label>';}).join('')+'</div>'+(last.grade?'<p><b>'+last.grade.rubric.filter(Boolean).length+'/'+it.rubric.length+' rubric points met.</b> Self-assessed.</p>':'<button class="btn pri" data-self>Save rubric check</button>')+'<div>'+I.srcChips(it.s)+'</div></div>';
 if(!last.grade)fb.querySelector('[data-self]').onclick=function(){selfMark(r,id,Array.prototype.map.call(fb.querySelectorAll('[data-rubric]'),function(el){return el.checked;}));L.app.route();};
 }else I.showFeedback(host,it,last.response,last.grade,{compactReasons:true});
 if(a.first&&a.first.grade){var first=a.first;host.insertAdjacentHTML('beforeend','<div class="exam-first small"><b>First try: '+(first.self?'self-assessed · ':'')+(first.grade.ok?'correct / rubric met':first.grade.sc>0?'partly correct':'needs work')+'</b>'+(a.tries.length?' · '+a.tries.length+' correction attempt'+(a.tries.length===1?'':'s'):'')+'<details><summary>Saved first response</summary><p>'+esc(responseText(it,first.response))+'</p></details></div>');}
 if(last.grade&&!last.grade.ok){host.insertAdjacentHTML('beforeend','<div class="row"><button class="btn" data-retry>Try a correction</button><a class="btn ghost" href="#exam1/topic/'+L.examTopics(it)[0]+'">Review this topic</a></div>');host.querySelector('[data-retry]').onclick=function(){retry(r,id);L.app.route();};}
 else if(last.grade&&a.tries.length)host.insertAdjacentHTML('beforeend','<p class="okc small">Corrected after feedback. Recheck this concept later with a different question.</p>');
 if(last.grade)host.insertAdjacentHTML('beforeend','<p class="mastery-feedback small">'+esc(E.masteryNote(E.conceptStats()[it.c]))+' <a href="#exam1/topic/'+L.examTopics(it)[0]+'">Mastery details</a></p>');
}
function responseText(it,v){if(v===undefined||v===null)return '(blank)';if(it.o&&!Array.isArray(v))return it.o[v]?it.o[v].t:String(v);if(Array.isArray(v))return v.join(' · ');return String(v);}
function resultHTML(id){var r=byId(id);if(!r)return '<h1>Review not found</h1><a href="#exam1/history">History</a>';var m=metrics(r),h='<h1>'+esc(r.title)+'</h1><p class="lede">'+(m.unanswered?m.unanswered+' parts still unchecked.':'All parts checked.')+' First attempts, corrections, and self-assessments remain separate.</p>'+statusHTML()+runStats(r);
 var mc=r.groups.filter(function(g){return g.section==='mc';}).reduce(function(a,g){return a.concat(g.ids);},[]);if(mc.length){var mm=metrics(r,mc);h+='<div class="card"><h2>Section 1 · '+mm.autoCorrect*2+'/'+mc.length*2+' first-try points</h2><p>'+mm.checked+'/'+mc.length+' questions checked. Two points each, following the professor’s format.</p></div>';}
 ['sa','inv'].forEach(function(s){var ids=r.groups.filter(function(g){return g.section===s;}).reduce(function(a,g){return a.concat(g.ids);},[]);if(ids.length){var mm=metrics(r,ids);h+='<section class="card"><h2>'+sectionName(s)+'</h2><p>'+mm.autoCorrect+'/'+mm.auto+' automatic parts correct on first try · '+mm.selfCorrect+'/'+mm.self+' explanations fully met their rubric · '+mm.corrected+' corrected · '+mm.unanswered+' unchecked.</p><p class="small muted">Raw practice results; the professor has not established a point split for these sections.</p></section>';}});
 h+='<div class="row"><button class="btn pri" data-resume="'+r.id+'">Continue / review answers</button><a class="btn" href="#exam1">Topic map</a><a class="btn" href="#data">Export progress backup</a></div><section class="card"><h2>Next review</h2><p>Use a different question after a break. Corrections here do not count as independent mastery.</p>';
 var cons=U.uniq(allIds(r).filter(function(id){var a=r.answers[id];return a&&a.first&&a.first.grade&&!a.first.grade.ok;}).map(function(id){return resolve(id).c;}));
 if(cons.length)h+='<button class="btn" id="examFollowup" data-concepts="'+esc(JSON.stringify(cons))+'">Different-question practice ('+Math.min(12,cons.length)+')</button>';else h+='<p>No checked misses to target yet.</p>';
 h+='</section><section class="card"><h2>By review topic</h2><div class="exam-topic-results">';X.topics.forEach(function(t){var ids=allIds(r).filter(function(id){return L.examTopics(resolve(id)).indexOf(t.id)>=0;});if(ids.length){var mm=metrics(r,ids);h+='<p><a href="#exam1/topic/'+t.id+'">'+t.id+' · '+esc(t.title)+'</a><br><span class="small">'+mm.autoCorrect+'/'+mm.auto+' automatic first tries · '+mm.corrected+' corrected · '+mm.needs+' need work</span></p>';}});h+='</div></section><section class="card"><h2>Question review</h2>';
 r.groups.forEach(function(g,i){h+='<details><summary>Q'+g.n+(g.caseId?' · '+esc(E.caseById(g.caseId).title):'')+'</summary>';g.ids.forEach(function(id){var it=resolve(id),a=r.answers[id],last=latest(a);h+='<div class="exam-summary-part"><p>'+it.q+'</p><p class="small"><b>First response:</b> '+esc(a&&a.first?responseText(it,a.first.response):'Not checked')+'</p>'+(a&&a.first&&a.first.grade?'<p class="small">First result: '+(a.first.grade.ok?'Correct / rubric met':'Needs work')+(a.first.self?' (self-assessed)':'')+'. '+(last!==a.first?'Latest correction: '+esc(responseText(it,last.response)): '')+'</p>':'')+'<button class="btn small" data-review-question="'+i+'" data-run="'+r.id+'">Open question and feedback</button></div>';});h+='</details>';});return h+'</section>';
}
function followup(cons){var r=active(),seen={};if(r)allIds(r).forEach(function(id){seen[id]=true;});var refs=[];cons.slice(0,12).forEach(function(c){var candidates=E.itemsFor(function(it){return it.c===c&&it.pool!=='exam1'&&it.pool!=='boss'&&!it.caseId&&it.t!=='teach'&&!it.media&&sourceItem(it)&&!seen[it.id];});if(candidates.length)refs.push({id:U.shuffle(candidates)[0].id});});if(!refs.length){L.app.go('exam1');return;}E.newSession('practice','Recheck after Exam 1 review',refs,{back:'exam1'});L.app.go('session');}
function wire(main){
 main.querySelectorAll('[data-fresh-form]').forEach(function(b){b.onclick=function(){b.disabled=true;try{startFreshForm(b.dataset.freshForm);L.app.go('exam1/take');}catch(e){var error=main.querySelector('#freshError');if(error)error.textContent=e.message;b.disabled=false;}};});
 main.querySelectorAll('[data-session-resume]').forEach(function(b){b.onclick=function(){var state=S.load(),r=(state.session&&state.session.id===b.dataset.sessionResume?state.session:(state.sessionHistory||[]).find(function(x){return x.id===b.dataset.sessionResume;}));if(!r)return;if(state.session&&state.session.id!==r.id){var at=state.sessionHistory.findIndex(function(x){return x.id===state.session.id;});if(at<0)state.sessionHistory.push(state.session);else state.sessionHistory[at]=state.session;}state.session=U.clone(r);state.session.idx=Math.min(state.session.idx,state.session.queue.length-1);save();L.app.go('session');};});
 main.querySelectorAll('[data-single]').forEach(function(b){b.onclick=function(){start([{n:1,section:'sa',ids:[b.dataset.single]}],'Short-answer workshop',{mode:'writing'});L.app.go('exam1/take');};});
 main.querySelectorAll('[data-fix-concept]').forEach(function(b){b.onclick=function(){followup([b.dataset.fixConcept]);};});
main.querySelectorAll('[data-form]').forEach(function(b){b.onclick=function(){startForm(b.dataset.form,b.dataset.section||null);L.app.go('exam1/take');};});main.querySelectorAll('[data-topic]').forEach(function(b){b.onclick=function(){drill(b.dataset.topic,false,b.dataset.concept);L.app.go('exam1/take');};});main.querySelectorAll('[data-diagram]').forEach(function(b){b.onclick=function(){drill(b.dataset.diagram==='all'?null:b.dataset.diagram,true);L.app.go('exam1/take');};});main.querySelectorAll('[data-resume]').forEach(function(b){b.onclick=function(){var r=byId(b.dataset.resume);S.load().examActive=r.id;r.archived=false;touch(r);L.app.go('exam1/take');};});
 main.querySelectorAll('[data-review-question]').forEach(function(b){b.onclick=function(){var r=byId(b.dataset.run);r.cur=+b.dataset.reviewQuestion;S.load().examActive=r.id;touch(r);L.app.go('exam1/take');};});
 var old=main.querySelector('#archiveOld');if(old)old.onclick=function(){var s=S.load();if(s.mockActive){s.mockArchived.push(s.mockActive);s.mockActive=null;save();L.app.route();}};
 main.querySelectorAll('[data-old-resume]').forEach(function(b){b.onclick=function(){var s=S.load();if(s.mockActive)s.mockArchived.push(s.mockActive);s.mockActive=s.mockArchived.find(function(m){return m.id===b.dataset.oldResume;});s.mockArchived=s.mockArchived.filter(function(m){return m.id!==b.dataset.oldResume;});save();L.app.go('mock/take');};});
 var f=main.querySelector('#examFollowup');if(f)f.onclick=function(){followup(JSON.parse(f.dataset.concepts));};
}
function misses(){var stats=E.conceptStats();return Object.keys(stats).filter(function(c){return stats[c].reviewOpen && (L.EXAM_CONCEPT_TOPICS[c]||[]).length;}).map(function(c){return {c:c,stat:stats[c],topics:L.EXAM_CONCEPT_TOPICS[c]};}).sort(function(a,b){return Number(b.stat.highConfidenceMiss)-Number(a.stat.highConfidenceMiss)||b.stat.last-a.stat.last;});}
function reviewHTML(){var ms=misses(),h='<h1>Review misses</h1>'+buttons()+statusHTML()+'<p class="lede">One shared queue across practice, cases, Boss drills, and mocks. Two correct, unhinted answers on different questions after the miss clear the concept for review; the second needs medium/high confidence. Earned mastery and first-response scores stay.</p>';
 if(!ms.length)h+='<div class="card">No open Exam 1 misses. <a href="#review">Check spaced reviews</a> or start another mock.</div>';
 h+='<div class="chapter-grid">'+ms.map(function(m){return '<article class="card chapter-card"><span class="badge">'+(m.stat.highConfidenceMiss?'High-confidence miss':'Review needed')+'</span><h3>'+esc(L.CONCEPTS[m.c].name)+'</h3><p class="small muted">'+(m.stat.status==='mastered'?'Mastery retained · ':'')+m.stat.ok+'/'+m.stat.att+' checks correct</p><div class="row"><button class="btn pri" data-fix-concept="'+m.c+'">Practice this now</button><a class="btn" href="#exam1/topic/'+m.topics[0]+'">Relearn</a>'+(m.stat.lastMiss&&m.stat.lastMiss.run?'<a class="btn" href="#exam1/result/'+m.stat.lastMiss.run+'">Saved feedback</a>':'')+'</div></article>';}).join('')+'</div>';return h;}
function figuresHTML(){return '<h1>Figure workshop</h1>'+buttons()+'<p class="lede">Observe → identify → explain. Practice with the original McGraw-Hill figures used in your course.</p><button class="btn pri" data-diagram="all">Mixed figure practice (20)</button><div class="chapter-grid">'+X.topics.map(function(t){return '<article class="card chapter-card"><span class="badge">'+t.id+'</span><h3>'+esc(t.title)+'</h3><div class="row"><a class="btn" href="#exam1/topic/'+t.id+'">Study figure</a><button class="btn pri" data-diagram="'+t.id+'">Practice</button></div></article>';}).join('')+'</div>';}
function writingHTML(){var items=E.itemsFor(function(it){return it.pool==='exam1'&&!it.caseId&&(it.t==='teach'||it.t==='fill');});return '<h1>Short-answer workshop</h1>'+buttons()+'<p class="lede">Recall the term or write a short explanation. Terms receive automatic feedback; explanations use an explicit rubric and feed the same mastery record as self-assessments.</p><div class="chapter-grid">'+items.map(function(it){return '<article class="card chapter-card"><span class="badge">'+(it.t==='teach'?'Explain':'Name the term')+'</span><p>'+it.q+'</p><button class="btn pri" data-single="'+it.id+'">Write and check</button></article>';}).join('')+'</div>';}
function view(main,args){var page=args[0]||'map';if(page==='take')take(main);else main.innerHTML=page==='topic'?topicHTML(args[1]):page==='animations'&&L.animatedDiagrams?L.animatedDiagrams.gallery(buttons()):page==='sets'?setsHTML():page==='figures'?figuresHTML():page==='writing'?writingHTML():page==='review'?reviewHTML():page==='history'?historyHTML():page==='result'?resultHTML(args[1]):mapHTML();wire(main);if(L.animatedDiagrams)L.animatedDiagrams.wire(main);}
L.exam1={view:view,topic:topic,groups:groups,start:start,startForm:startForm,startFreshForm:startFreshForm,drill:drill,drillPool:drillPool,selectDrill:selectDrill,active:active,byId:byId,answer:answer,check:check,selfMark:selfMark,retry:retry,metrics:metrics,topicMetrics:topicMetrics,allIds:allIds,latest:latest,misses:misses};
L.CONFIG.version='3.2.2 · shared mastery and motion studies (2026-09-27)';
})(window.L);
