/* Exam 2 workspace. Teaching shares the existing renderer, grading, and progress engine. */
(function(L){
'use strict';L.CONFIG.version='4.1.2 · Exam 2 reading emphasis (2026-10-08)';var U=L.util,E=L.engine,S=L.store,I=L.itemUI,esc=U.esc;
function topic(id){return L.EXAM2.topics.find(function(t){return t.id===id;});}
function chapterLabel(chs){var n=chs.length;if(!n)return 'No chapters';var contiguous=chs.every(function(ch,i){return !i||ch===chs[i-1]+1;});return (n===1?'Chapter ':'Chapters ')+(n>1&&contiguous?chs[0]+'–'+chs[n-1]:chs.join(', '));}
function conceptChapter(c){var sec=L.SECTIONS.find(function(s){return s.id===L.CONCEPTS[c].sec;});return sec?sec.ch:0;}
function metrics(t){var st=E.conceptStats(),ids=t?t.concepts:L.examScope.concepts('exam2');return {total:ids.length,mastered:ids.filter(function(c){return st[c].status==='mastered';}).length,review:ids.filter(function(c){return st[c].reviewOpen;}).length};}
function nav(){return L.exam1.ui.buttons('exam2');}
function resume(){var x=S.load().session;return x&&x.examId==='exam2'?'<a class="btn good" href="#session">Resume '+esc(x.title)+' · '+Math.min(x.idx+1,x.queue.length)+'/'+x.queue.length+'</a>':'';}
function start(refs,title,opt){if(!refs.length)return;E.newSession(opt&&opt.mode||'practice',title,refs,Object.assign({examId:'exam2',back:'exam2'},opt||{}));L.app.go('session');}
function drill(id,kind,concept){
 if(id==='E2T7'&&L.brittleDuctile&&!concept)return L.brittleDuctile.start(kind==='teach'?'writing':kind==='figure'?'labels':'mixed');
 var t=topic(id),cs=concept?[concept]:t?t.concepts:null,refs;
 if(kind==='figure'){
  var pool=E.itemsFor(function(it){return it.examId==='exam2'&&(!cs||cs.indexOf(it.c)>=0)&&it.media&&it.t!=='teach'&&!it.caseId;});
  var source=pool.filter(function(it){return it.sourceFigure;});if(source.length)pool=source;
  var seen={},stats=E.conceptStats();E.allAttempts().forEach(function(a){seen[a.i]=(seen[a.i]||0)+1;});
  pool=U.shuffle(pool).sort(function(a,b){return E.practicePriority(stats[a.c])-E.practicePriority(stats[b.c])||(seen[a.id]||0)-(seen[b.id]||0);});
  refs=pool.slice(0,t?5:20).map(function(it){return {id:it.id};});
  // Keep enough intervening tasks for the shared two/four-item retry gap.
  // Figure tasks remain first; supporting questions explain the same observations.
  if(t&&t.ch===7&&refs.length<5){
   var used=refs.map(function(r){return r.id;}),support=E.itemsFor(function(it){return it.examId==='exam2'&&it.t==='mc'&&!it.caseId&&it.pool!=='boss'&&t.concepts.indexOf(it.c)>=0&&used.indexOf(it.id)<0;});
   if(t.id==='E2T5')support=support.concat(E.itemsFor(function(it){return it.examId==='exam2'&&it.c==='c7-4-core'&&it.t==='mc'&&!it.caseId&&it.pool!=='boss';}));
   U.shuffle(support).slice(0,5-refs.length).forEach(function(it){refs.push({id:it.id});});
  }
 }else if(kind==='teach')refs=E.itemsFor(function(it){return it.examId==='exam2'&&it.t==='teach'&&(!cs||cs.indexOf(it.c)>=0)&&!it.caseId;}).map(function(it){return {id:it.id};});
 else refs=E.practiceRefs({n:concept?2:t?8:20,concepts:cs,examId:'exam2'});
 start(refs,(t?t.title:'Chapters 7–8 · mixed practice')+(kind==='figure'?' · Figure practice':''));
}
function filmHTML(t){if(t.id==='E2T7'&&L.brittleDuctile)return L.brittleDuctile.filmHTML();var f=L.EXAM2_FILMS&&L.EXAM2_FILMS[t.id];if(!f)return '<section class="card"><h2>Narrated process film</h2><p>The local film is being prepared for this topic.</p></section>';
 var base='videos/exam2/'+t.id,embedded=Array.isArray(f.cues)&&typeof window.VTTCue==='function';return '<section class="card ad-video" data-process-film="'+t.id+'"><p class="eyebrow">Narrated process film · Clear voice</p><h2>'+esc(t.title)+'</h2><p>'+esc(f.description)+'</p><video controls playsinline preload="metadata" poster="'+base+'.png" aria-label="Narrated animation: '+esc(t.title)+'"><source src="'+base+'.mp4" type="video/mp4">'+(embedded?'':'<track kind="captions" src="'+base+'.vtt" srclang="en" label="English narration">')+'Download the MP4 using the link below.</video><div class="ad-film-controls">'+(embedded?'<button type="button" class="btn small" data-e2-captions aria-pressed="false">Captions: off</button>':'')+'<div class="ad-chapters">'+f.stages.map(function(s){return '<button class="btn small" data-film-seek="'+s.start+'">'+esc(s.label)+'</button>';}).join('')+'</div><label>Speed <select data-film-speed aria-label="Playback speed"><option value="0.5">0.5×</option><option value="0.75">0.75×</option><option selected value="1">1×</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option></select></label></div><details class="ad-narration"><summary>Narration transcript</summary>'+f.stages.map(function(s){return '<p><strong>'+esc(s.label)+'.</strong> '+esc(s.text)+'</p>';}).join('')+'</details><div class="row"><button class="btn pri" data-e2-practice="'+t.id+'">Practice this topic</button><a class="btn small" download href="'+base+'.mp4">Save MP4</a><a class="btn small" href="'+base+'.vtt">Captions</a></div><p class="small muted">Original synthetic narration · AI Voice Generator, Clear. Teaching reconstruction preserves source relationships; distances and process time are schematic. Compare the original course figures below. Watching does not change mastery.</p></section>';}
var comparisons={
 E2T1:[['Setting','Diagnostic observations','How sediment arrives'],['River/floodplain','Channel sand or gravel; overbank mud','Flowing water, floods'],['Delta','River-mouth sediment body','A river slows in standing water'],['Dunes','Well-sorted wind-moved sand','Wind transport'],['Lagoon','Sheltered coastal water','Barrier or reef reduces wave energy'],['Deep ocean','Fine particles, tiny organism remains; local turbidites','Settling and underwater currents']],
 E2T2:[['Process','What changes','Do not confuse with'],['Physical weathering','Rock breaks into fragments','Transport away from the site'],['Chemical weathering','Minerals react or dissolve','Only rounding a grain'],['Transport and sorting','Position, shape, size distribution','Lithification'],['Compaction','Grains pack, pore space shrinks','Mineral binding'],['Cementation','New minerals bind grains','Heat-driven melting']],
 E2T3:[['Rock','Diagnostic texture','Interpretation limits'],['Breccia','Angular gravel-sized clasts','Several local or rapid deposition settings'],['Conglomerate','Rounded gravel-sized clasts','Abrasion can happen in streams or on beaches'],['Sandstone','Sand-sized grains','Composition and structures refine the setting'],['Mudstone/shale','Mud-sized grains; shale is fissile','Quiet water occurs on land and at sea']],
 E2T4:[['Rock','Composition or components','Formation'],['Limestone','Calcite; shells, ooids, or precipitates','Carbonate accumulation or precipitation'],['Dolostone','Dolomite','Commonly replacement by magnesium-bearing fluids'],['Chalk/coquina','Tiny carbonate skeletons / visible shell fragments','Different biological carbonate components'],['Chert','Microcrystalline silica','Silica accumulation or replacement'],['Evaporites/coal','Salts / plant-derived carbon','Evaporation / plant preservation and burial']],
 E2T5:[['Structure','Observation','Process'],['Bedding','Distinct layers or beds','Changes in deposition'],['Graded bedding','Coarse base becomes finer upward','Settling during waning flow'],['Cross bedding','Inclined laminae within bounding surfaces','Migrating dunes or ripples'],['Mud cracks','Polygonal cracks on exposed mud','Drying and shrinkage']],
 E2T6:[['Relation','Meaning','Limit'],['Transgression','Marine settings migrate landward','Relative sea level and sediment supply matter'],['Regression','Marine settings migrate seaward','Not always a global sea-level fall'],['Unconformity','An interval is missing','Erosion or nondeposition can create it'],['Reservoir and seal','Porous storage capped by low permeability','A reservoir alone does not prove petroleum'],['Facies sequence','Environment changes through time and space','Check layer orientation and continuity']],
 E2T7:[['Term','Meaning','Distinction'],['Stress','Force per unit area','Imposed loading'],['Strain','Shape or volume change','Response to loading'],['Elastic','Recoverable strain','Removal of stress restores shape'],['Brittle','Fracturing','Commonly upper, cooler crust'],['Ductile','Solid-state distributed deformation','Favored by heat, confinement, and slow deformation']],
 E2T8:[['Feature','Movement criterion','Typical association'],['Joint','No appreciable slip along fracture','Cooling, unloading, or stress'],['Normal fault','Hanging wall down','Extension'],['Reverse fault','Hanging wall up','Shortening'],['Thrust fault','Low-angle reverse fault','Shortening'],['Strike-slip fault','Mainly horizontal relative slip','Shear']],
 E2T9:[['Feature','Diagnostic relation','Check'],['Anticline','Older layers in core','Often arches upward when upright'],['Syncline','Younger layers in core','Often trough-shaped when upright'],['Monocline','Step-like bend','One flexure joining gentler limbs'],['Dome/basin','Layers dip outward/inward in all directions','Map pattern and age'],['Axial surface/plunge','Surface through hinges / axis inclination','Different geometric properties']],
 E2T10:[['Rock','Texture/composition','Common parent'],['Slate','Fine dull cleavage','Shale or mudrock'],['Phyllite','Fine grains, silky sheen','Mudrock'],['Schist','Visible aligned mica','Often mica-bearing protolith'],['Gneiss','Coarse compositional bands','Various sedimentary or igneous parents'],['Marble/quartzite','Interlocking calcite/quartz','Carbonate rock/quartz sandstone']],
 E2T11:[['Process/setting','What changes','Expected evidence'],['Recrystallization','Grains reorganize or grow','Interlocking crystals'],['Mineral reaction','Minerals change stability','New mineral assemblage'],['Chemical change by fluids','Components enter or leave','Chemical addition/removal'],['Contact','Strong local heating near intrusion','Thermal aureole'],['Regional/subduction','Burial/heating or high pressure at relative coolness','Fabrics, assemblages, pressure–temperature history']],
 E2T12:[['Evidence','Interpretation','Limit'],['Normal-fault system','Extension, horsts/grabens','Verify relative offsets'],['Folds and thrusts','Shortening','Several deformation stages may occur'],['Cleavage cutting bedding','Later fabric differs from original layering','Orientation and age need field relations'],['Sealed fault','Observed slip predates the sealing unit','Does not rule out movement elsewhere'],['New England patterns','Collision, metamorphism, later rifting','Use map legend and separate episodes']]
};
function table(rows,id){var body='<div class="e2-table"><table class="t"><thead><tr>'+rows[0].map(function(x){return '<th>'+esc(x)+'</th>';}).join('')+'</tr></thead><tbody>'+rows.slice(1).map(function(r){return '<tr>'+r.map(function(x){return '<td>'+esc(x)+'</td>';}).join('')+'</tr>';}).join('')+'</tbody></table></div>';return L.exam2Reading.wrap('compare-'+id,body);}
function studySourceHTML(it){
 var ns=U.uniq((it.s||it.src||[]).map(function(x){return x.split(':')[1];}).filter(function(n){return L.EXAM2_SOURCES[n];}));
 var content=ns.map(function(n){var b=L.EXAM2_SOURCES[n];return '<h3>'+esc(b.title)+'</h3><p class="small muted">'+esc(b.citation)+' · original lab explanation</p><p class="e2-passage">'+esc(b.pages[0].text)+'</p>'+I.mediaHTML({kind:'img',src:b.pages[0].image,alt:'Study diagram for '+b.title,cap:'Original lab schematic · distances and process time schematic'});}).join('');
 if(!ns.length)content='<p>The October 6 application distinguishes the crust–mantle boundary from mechanical boundaries. Much of Basin and Range has shallower Moho depths than the Rocky divisions in the supplied profile. A locally deep root does not establish average regional elevation: density, temperature, and dynamic support also matter. Isostatic balance does not require a liquid mantle.</p>'+I.mediaHTML({kind:'img',src:'assets/diagrams/exam2/moho.svg',alt:'Moho depth schematic',cap:'Original lab schematic from course observations · approximate depths'});
 return '<details class="e2-source"><summary>Direct source material</summary>'+content+'<p class="small muted">Full supplied pages remain in your local edition. These passages are original study explanations with course citations.</p></details>';
}
function sourceHTML(it){
 if(it&&it.practiceTrack==='e2-brittle'&&L.brittleDuctile)return L.brittleDuctile.sourceHTML(it);
 if(!it||it.examId!=='exam2')return '';if(L.EXAM2_SOURCE_MODE!=='private')return studySourceHTML(it);var ns=(it.s||it.src||[]).map(function(x){return x.split(':')[1];}).filter(function(n){return L.EXAM2_SOURCES[n];});ns=U.uniq(ns);
 if(!ns.length){return '<details class="e2-source"><summary>Direct source material</summary><p>October 6 ILEA and lecture application. The supplied answer screenshot was checked as a draft, not used as an official key.</p>'+I.mediaHTML({kind:'img',src:'assets/img/exam2/ilea-moho.jpg',alt:'Original Moho worksheet graph',cap:'October 6 original worksheet'})+'</details>';}
 var text=String(it.q||'')+' '+String(it.x||''),tokens=text.toLowerCase().match(/[a-z]{5,}/g)||[];
 return '<details class="e2-source"><summary>Direct source material</summary>'+ns.map(function(n){var b=L.EXAM2_SOURCES[n],rank=b.pages.filter(function(p){return !p.blank;}).map(function(p){var low=p.text.toLowerCase();return {p:p,score:tokens.reduce(function(a,w){return a+(low.indexOf(w)>=0?1:0);},0)};}).sort(function(a,b){return b.score-a.score||a.p.n-b.p.n;}).slice(0,2).sort(function(a,b){return a.p.n-b.p.n;});return '<h3>'+esc(b.title)+'</h3>'+rank.map(function(r){return '<details open><summary>PDF page '+r.p.n+' · matching course passage</summary><p class="e2-passage">'+esc(r.p.text)+'</p><a href="'+r.p.image+'" target="_blank" rel="noopener">Open original page</a>'+I.mediaHTML({kind:'img',src:r.p.display||r.p.image,alt:'Original textbook '+n+', PDF page '+r.p.n,cap:'Supplied textbook '+n+' · PDF page '+r.p.n+' · unchanged source content'})+'</details>';}).join('')+'<details><summary>All supplied pages for section '+n+'</summary><div class="e2-source-pages">'+b.pages.map(function(p){return '<a href="'+p.image+'" target="_blank" rel="noopener">Page '+p.n+'</a>';}).join('')+'</div></details>';}).join('')+'</details>';
}
function hub(ch){
 var available=L.EXAMS.exam2.available,shown=available.filter(function(c){return !ch||ch===c;}),ts=L.EXAM2.topics.filter(function(t){return shown.indexOf(t.ch)>=0;}),cs=U.uniq(ts.reduce(function(a,t){return a.concat(t.concepts);},[])),m=metrics({concepts:cs}),pending=L.EXAMS.exam2.chapters.filter(function(c){return available.indexOf(c)<0;}),sections=L.SECTIONS.filter(function(sec){return sec.examId==='exam2'&&shown.indexOf(sec.ch)>=0;}).length;
 var h='<p class="eyebrow">Exam 2 · '+chapterLabel(shown)+'</p><h1>'+(ch?esc(L.CHAPTERS[ch].name):'Exam 2')+'</h1><p class="lede">Study the course material, then practice with your actual course figures. Check each answer immediately and work through corrections at your own pace.</p>'+nav()+L.exam1.ui.status();
 h+='<div class="grid4"><div class="stat"><b>'+m.mastered+'/'+m.total+'</b><span>Concepts mastered</span><small>Shared across all checked work.</small></div><div class="stat"><b>'+sections+'</b><span>Supplied textbook sections</span><small>'+chapterLabel(shown)+'.</small></div><div class="stat"><b>'+ts.length+'</b><span>Focused teaching groups</span><small>Learn, topic practice, and figure practice.</small></div><div class="stat"><b>'+L.exam1.ui.misses('exam2').filter(function(x){return cs.indexOf(x.c)>=0;}).length+'</b><span>Open miss concepts</span><small>Shared with your main dashboard.</small></div></div>';
 if(resume())h+='<div class="infobox"><b>Continue your saved study session</b><div class="row">'+resume()+'</div></div>';
 h+='<section class="card"><h2>Your practice format</h2><p>Use supplied diagrams with shuffled word banks, classify rocks from their properties, recall complete named lists, and explain distinctions with geological examples. The current Exam 2 scope is Chapters 7–12; only Chapters 7–8 have been supplied. Full mocks remain locked while '+chapterLabel(pending)+' are missing.</p>'+I.srcChips(['TB7','TB8'])+'</section>';
 h+='<p class="small muted">Every checked answer feeds the same mastery dashboard across all modes. Two different correct questions without hints, with medium/high confidence on the second, earn mastery permanently. New drills target unfinished concepts; recent misses remain in review.</p>'+topicGrid(ch);
 return h+'<section class="card"><h2>'+chapterLabel(pending)+' · pending</h2><p>Missing chapters are excluded from practice and mastery totals. The current practice formats are preparation choices, not predictions of exact Exam 2 questions.</p><a class="btn" href="#exam2/sets">Mock status</a><a class="btn" href="#exam2/sources">Coverage and sources</a></section>';
}
function topicGrid(filter){return L.EXAMS.exam2.available.filter(function(ch){return !filter||filter===ch;}).map(function(ch){return '<h2>'+esc(L.CHAPTERS[ch].name)+'</h2><div class="exam-topics">'+L.EXAM2.topics.filter(function(t){return t.ch===ch;}).map(function(t){return L.exam1.ui.topicCard(t,'exam2');}).join('')+'</div>';}).join('');}
function sharedLesson(t){
 var cards=t.sections.reduce(function(a,n){var sec=L.SECTIONS.find(function(s){return s.n===n&&s.examId==='exam2';});return a.concat(L.GUIDE[sec.id]);},[]);
 var html=cards.map(function(cd){return '<h3>'+esc(cd.h)+'</h3>'+L.exam2Reading.cardHTML(cd,true);}).join('')+'<h3>Compare the distinctions</h3>'+table(comparisons[t.id],t.id)+sourceHTML({examId:'exam2',src:t.sources,q:t.title});
 return L.exam1.ui.topicLesson(t,{examId:'exam2',html:html,trap:cards[0].traps[0],motion:filmHTML(t),emphasis:'<p class="small muted">Textbook sections '+t.sections.join(', ')+'. Full notes and section checks are linked below; supplied lecture confirmation is identified in the Guide.</p>',mediaIntro:'Supplied textbook and Connect figures for these concepts. Tap to enlarge. Practice figure uses a word bank; reading and watching alone do not award mastery.'});
}
function learn(id,focus){if(id==='E2T7'&&(!focus||focus==='c8s1')&&L.brittleDuctile)return L.brittleDuctile.view(nav());var t=topic(id);if(!t)return hub();if(t.ch===7)return sharedLesson(t);var m=metrics(t),h='<h1>'+esc(t.title)+'</h1>'+nav()+'<p class="small muted">Chapter '+t.ch+' · '+t.sections.join(', ')+' · '+m.mastered+'/'+m.total+' concepts mastered</p>'+filmHTML(t)+'<section class="card"><h2>Compare the distinctions</h2>'+table(comparisons[id],id)+'<p><b>Use the sequence:</b> observe a diagnostic feature → identify/classify → explain the process → give a geological example.</p></section>';
 t.sections.forEach(function(n){var sec=L.SECTIONS.find(function(s){return s.n===n&&s.examId==='exam2';}),cards=L.GUIDE[sec.id];h+='<section id="lesson-'+n.replace('.','-')+'" class="e2-lesson'+(focus===sec.id?' e2-focused':'')+'"><h2>'+esc(n+' · '+sec.title)+'</h2><p class="e2-evidence">'+esc(sec.note)+'</p>';cards.forEach(function(cd){h+='<article class="card gcard">'+L.exam2Reading.cardHTML(cd)+'<div class="traps"><b>Common confusion.</b> '+esc(cd.traps[0])+'</div>'+I.mediaHTML(cd.media)+'<div class="row"><button class="btn small" data-e2-section="'+sec.id+'">Practice '+n+'</button><label class="small"><input type="checkbox" data-e2-read="'+cd.id+'"'+(S.load().guideRead[cd.id]?' checked':'')+'> Studied this lesson</label></div>'+sourceHTML({examId:'exam2',src:cd.src,q:cd.h})+'</article>';});h+='</section>';});
 return h+'<section class="card"><h2>Apply the topic</h2><div class="row"><button class="btn pri" data-e2-practice="'+id+'">Topic practice</button><button class="btn" data-e2-label="'+id+'">Label its figure</button><button class="btn" data-e2-write="'+id+'">Explain it in writing</button><a class="btn" href="#exam2/cases/e2-case-'+id+'">Investigate</a></div></section>';}
function practice(kind){var items=E.itemsFor(function(it){return it.examId==='exam2'&&(kind==='writing'?it.t==='teach':kind==='labels'?it.t==='match':!it.caseId&&it.pool!=='boss');});return '<h1>'+({writing:'Explain processes and examples',labels:'Figure labeling with word banks',practice:'Practice Chapters 7–8'}[kind])+'</h1>'+nav()+'<p>'+({writing:'Write your answer, record confidence, then compare with the model and check only rubric points present in your original response.',labels:'Observe each authored schematic and use its shuffled word bank. Compare the original course material after checking.',practice:'Choose a focused topic or mix the available material. Confidence comes before immediate feedback; misses return after intervening activities.'}[kind])+'</p><div class="row">'+resume()+'<button class="btn pri" data-e2-set="'+kind+'">Start '+(kind==='practice'?'mixed practice':kind)+'</button></div>'+topicGrid();}
function cases(id){var cs=L.CASES.filter(function(c){return c.examId==='exam2';});if(id){var x=cs.find(function(c){return c.id===id;});if(x)return '<h1>'+esc(x.title)+'</h1>'+nav()+'<section class="card">'+x.stem+(x.media?I.mediaHTML(x.media):'')+'<button class="btn pri" data-e2-case="'+id+'">Start investigation</button><p class="small muted">Original application questions. First answers are saved separately from later practice.</p></section>';}
 return '<h1>Investigate the geological evidence</h1>'+nav()+'<div class="exam-topics">'+cs.map(function(x){return '<article class="card"><h2>'+esc(x.title)+'</h2><p>Chapter '+x.ch+' · '+x.items.length+' linked questions</p><a class="btn pri" href="#exam2/cases/'+x.id+'">Open investigation</a></article>';}).join('')+'</div>';}
function boss(){return '<h1>Chapter Boss drills</h1>'+nav()+'<p>Each drill has 25 questions across one chapter. A completed drill records a first-answer score. Ending early preserves work and records an incomplete run.</p><div class="exam-topics">'+L.BOSSES.filter(function(b){return b.examId==='exam2';}).map(function(b){var hist=S.load().boss[b.id];return '<section class="card"><h2>'+esc(b.title)+'</h2><p>'+esc(b.desc)+'</p><p>Best complete run: '+(hist&&hist.best!==null?Math.round(hist.best*100)+'%':'none yet')+'</p><button class="btn pri" data-e2-boss="'+b.id+'">Start 25-question drill</button></section>';}).join('')+'</div>';}
function review(){return L.exam1.ui.review('exam2')+(L.brittleDuctile?L.brittleDuctile.reminderHTML():'');}
function progress(){var st=E.conceptStats(),m=metrics(),a=E.allAttempts().filter(function(a){return L.examScope.conceptOwner(a.c)==='exam2';});return '<h1>Exam 2 · Progress</h1>'+nav()+'<div class="card"><p><strong>'+m.mastered+'/'+m.total+' available concepts mastered.</strong> '+a.filter(function(x){return !x.self;}).length+' automatic attempts and '+a.filter(function(x){return x.self;}).length+' rubric self-checks.</p><p>Chapters 9–12 are pending and excluded. Earned mastery stays recorded; later misses signal review.</p></div>'+L.EXAM2.topics.map(function(t){return '<section class="card"><h2><a href="#exam2/topic/'+t.id+'">'+esc(t.title)+'</a></h2>'+t.concepts.map(function(c){var x=st[c];return '<p>'+esc(L.CONCEPTS[c].name)+' <span class="badge st-'+x.status+'">'+esc(x.status)+'</span> '+esc(E.masteryNote(x))+'</p>';}).join('')+'</section>';}).join('')+'<a class="btn" href="#data">Export both exams</a>';}
function history(){return L.exam1.ui.history('exam2');}
function sources(){return '<h1>Exam 2 · Coverage and sources</h1>'+nav()+'<section class="card"><h2>Current coverage</h2><p>Chapter 7 sections 7.1–7.16 and Chapter 8 sections 8.1–8.15 are supported by supplied textbook PDFs. Lecture-confirmed topics and textbook continuation are identified in each lesson. September 24 Exam 1 review is excluded.</p><p>Original practice emphasizes observation, classification, complete lists, word-bank labeling, and geological explanations. These exercises do not predict exact Exam 2 questions.</p><h3>Missing sources</h3><ul><li>Original Chapter 8 Connect assignment and assessment screenshots. The supplied written summaries are secondary evidence.</li><li>Individually matched Chapter 7 lecture confirmation beyond the supplied introduction.</li><li>Remaining Exam 2 Chapters 9–12.</li></ul><p>The October 6 answer screenshot is a supplied draft. The lab uses verified textbook evidence and graph readback.</p>'+(L.EXAM2_SOURCE_MODE==='private'?'<a href="docs/EXAM2_SOURCE_LEDGER.md">Private source ledger</a> · <a href="docs/EXAM2_VERIFICATION.md">Verification receipt</a>':'<a href="docs/EXAM2_RELEASE.md">Coverage and release notes</a>')+'</section>'+L.EXAM2.topics.map(function(t){return '<section class="card"><h2>'+esc(t.title)+'</h2>'+t.sections.map(function(n){var s=L.SECTIONS.find(function(s){return s.examId==='exam2'&&s.n===n;});return '<p><a href="#guide/'+s.id+'">'+n+' · '+esc(s.title)+'</a><br><span class="small muted">'+esc(s.note)+'</span></p>';}).join('')+'</section>';}).join('');}
function locked(){return '<h1>Exam 2 mocks · locked</h1>'+nav()+'<section class="card e2-pending"><h2>Full exam scope is still pending</h2><p>Chapters 7–8 are ready for focused study. Chapters 9–12 must be supplied and audited before Exam 2 mocks can be built. No Exam 2 mock pool or mock generator is enabled.</p><a class="btn pri" href="#exam2">Study available chapters</a></section>';}
function gallery(){return '<h1>Chapters 7–8 · Narrated process films</h1>'+nav()+'<div class="ad-motion-index">'+L.EXAM2.topics.map(function(t){return '<a class="card ad-film-tile" href="#exam2/topic/'+t.id+'"><img loading="lazy" src="'+(t.id==='E2T7'&&L.brittleDuctile?L.brittleDuctile.poster:'videos/exam2/'+t.id+'.png')+'" alt="Animation preview: '+esc(t.title)+'"><h2>'+esc(t.title)+'</h2><p>Watch, compare the original figures, then practice.</p></a>';}).join('')+'</div>';}
function view(main,args){
 var r=args[0]||'map',id=args[1],html;
 if(L.app&&L.app.sharedView&&['home','guide','practice','boss','progress','cases','sources','evidence','zhuang'].indexOf(r)>=0&&!(r==='cases'&&id)){L.app.sharedView(main,r,args.slice(1));return;}
 if(r==='topic')html=learn(id);
 else if(r==='guide'){var sec=L.SECTIONS.find(function(s){return s.id===id;});if(sec){var t=topic(L.EXAM2.topics.find(function(t){return t.sections.indexOf(sec.n)>=0;}).id);html=learn(t.id,sec.id);}else html='<h1>Exam 2 · Guide</h1>'+nav()+topicGrid(id&&+id.replace('ch',''));}
 else if(r==='animations')html=gallery();
 else if(r==='figures'||r==='labels')html=L.exam1.ui.figures('exam2',L.EXAM2.topics);
 else if(r==='writing')html=L.exam1.ui.writing('exam2');
 else if(r==='practice')html=practice(r);
 else if(r==='cases')html=cases(id);
 else if(r==='boss')html=boss();
 else if(r==='review')html=review();
 else if(r==='progress')html=progress();
 else if(r==='history')html=history();
 else if(['sources','evidence','zhuang'].indexOf(r)>=0)html=sources();
 else if(r==='mock'||r==='sets')html=locked();
 else html=hub(r==='chapter'?+id:0);
 main.innerHTML=html;wire(main);
}
function wire(main){
 if(L.brittleDuctile)L.brittleDuctile.wire(main);
 main.querySelectorAll('[data-e2-practice]').forEach(function(b){b.onclick=function(){drill(b.dataset.e2Practice,null,b.dataset.concept);};});
 main.querySelectorAll('[data-e2-mixed]').forEach(function(b){b.onclick=function(){drill();};});
 main.querySelectorAll('[data-e2-section]').forEach(function(b){b.onclick=function(){start(E.practiceRefs({n:8,sec:b.dataset.e2Section,examId:'exam2'}),'Section '+b.dataset.e2Section);};});
 main.querySelectorAll('[data-e2-read]').forEach(function(b){b.onchange=function(){S.load().guideRead[b.dataset.e2Read]=b.checked;S.save();};});
 main.querySelectorAll('[data-e2-label],[data-e2-write]').forEach(function(b){b.onclick=function(){var id=b.dataset.e2Label||b.dataset.e2Write,ty=b.dataset.e2Label?'match':'teach';if(id==='E2T7'&&L.brittleDuctile)return L.brittleDuctile.start(ty==='match'?'labels':'writing');start(E.itemsFor(function(it){return it.examId==='exam2'&&it.t===ty&&(it.topics||[]).indexOf(id)>=0;}).map(function(it){return {id:it.id};}),topic(id).title+' · '+(ty==='match'?'figure labeling':'writing'));};});
 main.querySelectorAll('[data-e2-set]').forEach(function(b){b.onclick=function(){if(b.dataset.e2Set==='practice')return drill();var ty=b.dataset.e2Set==='writing'?'teach':'match';start(U.shuffle(E.itemsFor(function(it){return it.examId==='exam2'&&it.t===ty&&!it.caseId;}).map(function(it){return {id:it.id};})),'Chapters 7–8 · '+b.dataset.e2Set);};});
 main.querySelectorAll('[data-e2-case]').forEach(function(b){b.onclick=function(){var cs=E.caseById(b.dataset.e2Case);start(E.caseRefs(cs.id),cs.title,{mode:'case',back:'exam2/cases'});};});
 main.querySelectorAll('[data-e2-boss]').forEach(function(b){b.onclick=function(){var boss=L.BOSSES.find(function(x){return x.id===b.dataset.e2Boss;});start(E.bossRefs(boss.id),boss.title,{mode:'boss',noRetry:true,bossId:boss.id,back:'exam2/boss'});};});
 main.querySelectorAll('[data-e2-diagram]').forEach(function(b){b.onclick=function(){drill(b.dataset.e2Diagram==='all'?null:b.dataset.e2Diagram,'figure');};});
 main.querySelectorAll('[data-e2-single]').forEach(function(b){b.onclick=function(){start([{id:b.dataset.e2Single}],'Short-answer workshop');};});
 main.querySelectorAll('[data-e2-resume]').forEach(function(b){b.onclick=function(){var s=S.load(),x=(s.session&&s.session.id===b.dataset.e2Resume?s.session:s.sessionHistory.find(function(x){return x.id===b.dataset.e2Resume;}));if(!x)return;if(s.session&&s.session.id!==x.id){var at=s.sessionHistory.findIndex(function(r){return r.id===s.session.id;});if(at<0)s.sessionHistory.push(U.clone(s.session));else s.sessionHistory[at]=U.clone(s.session);}s.session=U.clone(x);s.session.idx=Math.min(s.session.idx,s.session.queue.length-1);S.save();L.app.go('session');};});
 if(L.animatedDiagrams)L.animatedDiagrams.wire(main);
 main.querySelectorAll('[data-e2-captions]').forEach(function(b){var frame=b.closest('[data-process-film]'),v=frame.querySelector('video'),f=L.EXAM2_FILMS[frame.dataset.processFilm];if(!f||!f.cues||!v.addTextTrack||typeof window.VTTCue!=='function')return;var track=v.addTextTrack('captions','English narration','en');track.mode='hidden';f.cues.forEach(function(c){track.addCue(new window.VTTCue(c.start,c.end,c.text));});b.onclick=function(){track.mode=track.mode==='showing'?'hidden':'showing';b.setAttribute('aria-pressed',String(track.mode==='showing'));b.textContent='Captions: '+(track.mode==='showing'?'on':'off');};});
}
L.exam2={view:view,topic:topic,metrics:metrics,sourceHTML:sourceHTML,drill:drill,filmHTML:filmHTML};
})(window.L);
