/* Boss drills: fixed, integrative sets of 25+ questions. Boss-only items (pool 'boss') combine ideas across sections or
   chapters and never appear in ordinary practice or mocks; a set of core items and one investigation case complete each
   drill. Counts and pass targets are lab design choices. */
(function (L) {
  'use strict';
  var A = L.A, B = { pool: 'boss', mock: false };
  function bx(extra) { var o = { pool: 'boss', mock: false }; if (extra) for (var k in extra) o[k] = extra[k]; return o; }

  // ---------------- Boss 1: Chapters 1–2 ----------------
  A.mc('b1-01', 'c1-isostasy', 'Region X has 60-km-thick continental crust; region Y has 7-km-thick oceanic crust. A student says "Y is low because it is made of heavier elements from the core." What is the correct reasoning?',
    ['*Y floats lower because its crust is thinner and denser (isostasy)|Lecture 1b slides 15–16.', 'Y is low because oceanic crust contains heavy iron-nickel material from the core|Oceanic crust is basalt, not core metal.', 'X is high only because mountains were piled on it|Thickness itself raises it.', 'Elevation has nothing to do with crust|Isostasy links them.'], 'Lecture 1b slides 12–16.', ['L1B:12', 'L1B:15', 'L1B:16'], B);
  A.mc('b1-02', 'c1-lithos', 'Which statement correctly combines the composition layers and the strength layers?',
    ['*Lithosphere = crust + uppermost mantle; asthenosphere lies within the mantle|Lecture 1b slides 12–14.', 'The lithosphere is the same thing as the crust|It also includes rigid uppermost mantle.', 'The asthenosphere is the liquid outer core, just beneath the crust and mantle|It is hot, weak, mostly solid mantle.', 'The crust sits below the lithosphere|The crust is part of it.'], 'Lecture 1b slides 12–14.', ['L1B:12', 'L1B:14'], B);
  A.mc('b1-03', 'c1-obsinf', 'Which pair lists an observation and then an inference drawn from it?',
    ['*"The pebbles are rounded" → "They were transported by water or waves"|Seen, then interpreted.', '"The layers were deposited in a quiet lake" → "The layers are thin and gray"|Inference first.', '"The rock is 2 m thick" → "The rock is 2 m thick"|No inference.', '"A glacier carved this valley" → "The valley is U-shaped"|Reversed.'], 'Lecture 1b slides 3, 9, 19–22.', ['L1B:3', 'L1B:9', 'L1B:21'], B);
  A.mc('b1-04', 'c2-analog', 'A 300-million-year-old sandstone has large, sweeping cross-layers and very well-sorted, frosted grains. Using the Lecture 2 approach, how should you interpret its environment?',
    ['*Compare it with modern settings: it resembles wind-blown dune sand|Use the present to interpret the past (Lecture 2 slides 7–8; Lecture 1b slide 20).', 'It must be a lava flow because it is old|Sandstone is sedimentary.', 'It cannot be interpreted, because no one was there to watch the sand being deposited|Modern analogs let us interpret it.', 'It formed in a deep ocean trench|Well-sorted dune sand does not fit.'], 'Lecture 2 slides 7–8.', ['L2:7', 'L2:8', 'L1B:20'], B);
  A.mc('b1-05', 'c2-landscape', 'A flat-topped hill capped by a resistant lava layer is wider than it is tall. Over time, what sequence of landforms will erosion produce?',
    ['*Mesa → butte → small knobs|Lecture 2 slide 9.', 'Butte → mesa → plateau|Erosion shrinks landforms.', 'Mesa → volcano → caldera|No vent is involved.', 'It stays a mesa, because a resistant lava cap cannot be eroded|Everything erodes.'], 'Lecture 2 slide 9; textbook 6.1 (mesa is not a volcano).', ['L2:9', 'TB6:6.1'], B);
  A.mc('b1-06', 'c2-sequence', 'A granite contains inclusions of the shale around it, and the shale next to the granite is baked. A sandstone above both contains granite pebbles. Order the three rock units, oldest first.',
    ['*Shale → granite → sandstone|Contact effects and inclusions put shale first; pebbles of granite put sandstone last.', 'Granite → shale → sandstone|Shale inclusions in the granite show shale came first.', 'Sandstone → shale → granite|Sandstone contains granite pebbles, so it is younger.', 'Shale → sandstone → granite|The granite pebbles in the sandstone rule this out.'], 'Lecture 2 slides 10–13.', ['L2:11', 'L2:12', 'L2:13'], B);
  A.mc('b1-07', 'c2-maps', 'You need to know which rock unit lies beneath a proposed building site and how the units are oriented. Which pair of tools from Lecture 2 is most useful?',
    ['*A geologic map and a cross section|Lecture 2 slides 17–20.', 'A topographic map and a satellite photo|These show surface shape, not rock units.', 'A road map and a stratigraphic column|Wrong place and purpose.', 'A shaded-relief map of the area|Shows shape only.'], 'Lecture 2 slides 15–20.', ['L2:15', 'L2:17', 'L2:18', 'L2:20'], B);
  A.mc('b1-08', 'c2-time', 'On the Lecture 2 timescale, the Mesozoic ends and the Cenozoic begins at 66 Ma. Which Chapter 6 event does the textbook place at about that time?',
    ['*The Deccan Traps flood basalts in India|Textbook 6.5; Lecture 2 slide 23.', 'The Columbia Plateau flood basalts in the Pacific Northwest|17–5 Ma.', 'Eruption of the Siberian Traps|252 Ma, the Paleozoic–Mesozoic boundary.', 'Formation of Crater Lake|About 7,700 years ago.'], 'Lecture 2 slides 23–24 (boundaries 252 and 66 Ma); textbook 6.5.', ['L2:23', 'L2:24', 'TB6:6.5'], B);
  A.mc('b1-09', 'c2-models', 'For Upheaval Dome (Lecture 2), three models are rising salt, rising magma, and impact. Which new observation would most directly weaken the rising-magma model?',
    ['*Deep drilling finds no igneous rock beneath the dome|Magma should leave igneous rock.', 'The layers around the dome bend upward and dip away from its center|All three models could bend layers.', 'The dome is circular|Several models predict circular shapes.', 'Sandstone is exposed at the surface|Does not discriminate.'], 'Lecture 2 slides 30–32 (models); prediction reasoning is lab inference.', ['L2:30', 'L2:31', 'L2:32', 'DES'], bx({ tier: 4 }));
  A.mc('b1-10', 'c1-cycle', 'A basalt erupts, weathers into sediment that is deposited in a river, and the resulting rock is later buried and heated. Which rock types appear, in order?',
    ['*Igneous → sedimentary → metamorphic|The rock cycle (Lecture 1b slides 19–30).', 'Sedimentary → igneous → metamorphic|The basalt came first.', 'Metamorphic → sedimentary → igneous|Reversed.', 'Igneous → igneous → igneous|Weathering and burial change the rock type.'], 'Lecture 1b slides 19, 23, 26, 29.', ['L1B:19', 'L1B:23', 'L1B:26', 'L1B:29'], B);
  A.mc('b1-11', 'c1-shelf', 'A student draws the edge of North America at today\'s shoreline. Why would a geologist disagree?',
    ['*The continent continues underwater; its edge is the outer shelf edge|Lecture 1b slide 8.', 'Continents end at the highest mountain range|No.', 'The edge is wherever the surface rock changes from granite to basalt on land|The shelf edge marks it.', 'Shorelines never move, so they are the best boundary|Shorelines change with sea level.'], 'Lecture 1b slide 8; Sep 1.', ['L1B:8', 'T0901'], B);
  A.mc('b1-12', 'c2-data', 'Which set contains one quantitative and one qualitative observation about the same outcrop?',
    ['*"The dike is 1.5 m wide" and "the dike is dark gray"|Number, then description.', '"The dike is dark gray" and "the dike is fine-grained"|Both qualitative.', '"The dike is 1.5 m wide" and "the dike is 40 m long"|Both quantitative.', '"The dike is younger than the shale" and "the shale is older"|Both inferences.'], 'Lecture 2 slide 22.', ['L2:22'], B);
  L.BOSSES.push({ id: 'boss1', title: 'Chapters 1–2: Reading Earth and its history', chs: [1, 2], pass: 0.8, blurb: 'Layers and isostasy, observation versus inference, relative dating, maps, and testing competing models.', bossOnly: ['b1-01', 'b1-02', 'b1-03', 'b1-04', 'b1-05', 'b1-06', 'b1-07', 'b1-08', 'b1-09', 'b1-10', 'b1-11', 'b1-12'], coreN: 10, cases: ['k2-sequence'] });

  // ---------------- Boss 2: Chapter 3 ----------------
  A.mc('b2-01', 'c3-drift-evidence', 'Which combination made Wegener\'s case for moving continents, and what was missing?',
    ['*Coastline fit, fossils, rock belts, ancient climate; missing: a mechanism|Lecture 3 slides 11–15.', 'Magnetic stripes, GPS rates, and seafloor ages; missing was fossil evidence|Stripes and GPS came decades later.', 'Hot-spot tracks; missing was coastline fit|Not Wegener\'s evidence.', 'Earthquake depths; missing was rock evidence|Not his case.'], 'Lecture 3 slides 11–15.', ['L3:11', 'L3:12', 'L3:13', 'L3:14', 'L3:15'], B);
  A.mc('b2-02', 'c3-belts', 'On a world map, narrow belts of earthquakes and volcanoes surround large quiet regions. What does this pattern reveal?',
    ['*The belts mark plate boundaries; the quiet regions are plate interiors|Lecture 3 slides 16–19.', 'Earthquakes happen randomly|They are concentrated in belts.', 'The quiet regions are where plates are thinnest and weakest, so they cannot store stress|Not the inference.', 'Volcanoes occur only in plate interiors|Mostly at boundaries (hot spots excepted).'], 'Lecture 3 slides 16–19.', ['L3:16', 'L3:17', 'L3:18', 'L3:19'], B);
  A.mc('b2-03', 'c3-seafloorage', 'Seafloor near a ridge is young with almost no sediment; near a continent it is older with thick sediment. Which process explains both trends at once?',
    ['*Seafloor spreading, with sediment piling up as crust ages|Lecture 3 slides 41–42.', 'Sediment melts near ridges|Sediment is thin because the crust is young.', 'Continents shed new seafloor from their edges, which then drifts toward the ridge|Ridges produce it.', 'Subduction at the ridge|Ridges are divergent.'], 'Lecture 3 slides 22, 41–42.', ['L3:22', 'L3:41', 'L3:42'], B);
  A.mc('b2-04', 'c3-subduction', 'Why do earthquakes get deeper inland from a trench?',
    ['*They follow the slab as it descends beneath the other plate|Lecture 3 slides 25–27.', 'Deeper rocks are weaker, so earthquakes slowly migrate downward away from the coast|Not the explanation.', 'The continent is thicker inland|Crustal thickness does not explain the dipping pattern.', 'Magma chambers sink inland|No.'], 'Lecture 3 slides 25–27.', ['L3:25', 'L3:26', 'L3:27'], B);
  A.mc('b2-05', 'c3-transform', 'A mid-ocean ridge is offset by a transform fault, which continues beyond the ridge tips as fracture zones. Along this offset, where are earthquakes concentrated?',
    ['*On the transform segment between the offset ridge crests|Lecture 3 slides 31–33.', 'Along the entire length of each fracture zone, all the way to the continents|The outer parts are inactive scars.', 'Only at the ridge crests, never along the transform|Transforms also have earthquakes.', 'Nowhere; transforms are aseismic|They are seismically active.'], 'Lecture 3 slides 31–33; Sep 8.', ['L3:31', 'L3:32', 'L3:33', 'T0908'], B);
  A.mc('b2-06', 'c3-forces', 'Which force does Lecture 3 describe as pulling a plate from its subducting edge?',
    ['*Slab pull|The dense sinking slab pulls the rest of the plate.', 'Ridge push|Acts at the elevated ridge.', 'Isostasy|Controls elevation, not plate pull.', 'Magnetic force|Not a plate-driving force.'], 'Lecture 3 slide 34.', ['L3:34'], B);
  A.mc('b2-07', 'c3-rifting', 'East Africa shows a down-dropped valley, volcanoes, and shallow earthquakes within a continent. What stage of plate evolution does it represent, and what could it become?',
    ['*A continental rift that could become a narrow sea, then an ocean|Lecture 3 slide 24; Sep 1.', 'A continental collision that will eventually build a mountain belt like the Himalaya|That needs convergence.', 'A transform boundary becoming a trench|No.', 'A hot-spot chain that will stop moving|Not the interpretation.'], 'Lecture 3 slide 24; Sep 1.', ['L3:24', 'T0901'], B);
  A.mc('b2-08', 'c3-ringfire', 'Why do so many volcanoes and deep earthquakes ring the Pacific Ocean?',
    ['*The Pacific is bordered largely by subduction zones|Lecture 3 slides 27–28 (Ring of Fire).', 'The Pacific floor is the oldest crust on Earth, so it cracks more easily than younger crust|Not the reason given.', 'Hot spots are only found there|Hot spots are elsewhere too.', 'The Pacific is splitting at its margins|Its margins are mostly convergent.'], 'Lecture 3 slides 27–28.', ['L3:27', 'L3:28'], B);
  A.mc('b2-09', 'c3-collision', 'India colliding with Asia builds high mountains but few volcanoes. Why so few volcanoes?',
    ['*Buoyant continental crust will not subduct deeply, so arc melting stops|Lecture 3 slides 29–30; textbook 5.10.', 'Collision zones are far too cold for any melting to happen at any depth|Some crustal melting can occur.', 'The mountains block magma physically|Not the explanation.', 'Collisions are transform boundaries|They are convergent.'], 'Lecture 3 slides 29–30; textbook 5.10.', ['L3:29', 'L3:30', 'TB5:5.10'], B);
  A.mc('b2-10', 'c3-geometry', 'A plate moves away from a ridge on one side and toward a trench on the other. What does this tell you about plate size over time?',
    ['*It grows at the ridge and shrinks at the trench; size depends on the balance|Lecture 3 boundary geometry, slides 37–38.', 'Plates never change size|They can grow or shrink.', 'All plates shrink|Some grow.', 'Ridges and trenches cannot exist on the same plate, so the map must be wrong|They can.'], 'Lecture 3 slides 37–38.', ['L3:37', 'L3:38'], B);
  A.num('b2-11', 'c3-rates', 'The Atlantic widens about 2.5 cm per year. At that rate, how many kilometers wider does it get in 40 million years? (1 km = 100,000 cm)', 1000, 0, 'km', '2.5 × 40,000,000 = 100,000,000 cm = 1,000 km.', ['L3:36'], B);
  A.mc('b2-12', 'c3-magnetic', 'Magnetic stripes, seafloor ages, and hot-spot chains all point to the same conclusion. What is it?',
    ['*Plates move over time|Lecture 3 slides 39–43.', 'Earth\'s magnetic field never changes|It reverses.', 'Oceans are older than continents|Seafloor is young compared with continents.', 'Hot spots wander across the globe while the plates above them stay still|Lecture 3 treats plates as moving.'], 'Lecture 3 slides 39–43.', ['L3:39', 'L3:40', 'L3:41', 'L3:43'], B);
  L.BOSSES.push({ id: 'boss2', title: 'Chapter 3: Plate tectonics gauntlet', chs: [3], pass: 0.8, blurb: 'Evidence, boundaries, forces, rates, stripes, and hot spots, applied to new situations.', bossOnly: ['b2-01', 'b2-02', 'b2-03', 'b2-04', 'b2-05', 'b2-06', 'b2-07', 'b2-08', 'b2-09', 'b2-10', 'b2-11', 'b2-12'], coreN: 10, cases: ['k3-samerica'] });

  // ---------------- Boss 3: Chapter 4 ----------------
  A.mc('b3-01', 'c4-bonds', 'Halite dissolves easily in water; quartz does not. Which difference best explains this?',
    ['*Ionic bonds (halite) vs. a strong covalent Si–O framework (quartz)|Textbook 4.12–4.13.', 'Halite is organic|It is inorganic.', 'Quartz is less dense than water, so it floats instead of dissolving|Density is not the reason.', 'Halite is a silicate|It is a halide.'], 'Textbook 4.7, 4.12, 4.13.', ['TB4:4.7', 'TB4:4.12', 'TB4:4.13'], B);
  A.mc('b3-02', 'c4-silstruct', 'As silicate structures go from independent tetrahedra to frameworks, what changes systematically?',
    ['*Shared oxygens per tetrahedron rise from 0 to 4|Textbook 4.7.', 'The number of silicon atoms per tetrahedron increases|Always one.', 'The minerals become metallic and gain free electrons|No.', 'The charge per tetrahedron becomes more negative|Sharing reduces the need for cations.'], 'Textbook 4.7.', ['TB4:4.7'], B);
  A.mc('b3-03', 'c4-commonsil', 'A rock from the upper mantle and a rock from continental crust are compared. Which mineral pairing fits?',
    ['*Mantle: olivine, pyroxene; crust: quartz, feldspar|Textbook 4.10; Sep 8.', 'Mantle: quartz and feldspar; continental crust: olivine and pyroxene|Reversed.', 'Both: calcite and halite|Not dominant in either.', 'Mantle: iron metal; crust: gold|No.'], 'Textbook 4.8, 4.10.', ['TB4:4.8', 'TB4:4.10', 'T0908'], B);
  A.mc('b3-04', 'c4-mineraldef', 'Which is a mineral: (1) sugar crystals, (2) a quartz crystal, (3) coal, (4) window glass?',
    ['*Only the quartz crystal|Sugar and coal are organic; glass is not crystalline.', 'Quartz and window glass|Glass lacks ordered structure.', 'All four|Three fail a criterion.', 'Sugar and quartz|Sugar is organic and not natural rock material.'], 'Textbook 4.1.', ['TB4:4.1'], B);
  A.mc('b3-05', 'c4-tests', 'A gray metallic mineral forms cubes, has three cleavages at 90°, and feels very heavy. What single test best confirms it is galena and not magnetite?',
    ['*A magnet: magnetite is strongly magnetic; galena is not|Textbook 4.3, 4.9.', 'Color: galena is always silver, magnetite always black|Color does not separate them.', 'Luster: both are metallic|Does not separate them.', 'Acid: neither fizzes|Does not separate them.'], 'Textbook 4.3 and 4.9.', ['TB4:4.3', 'TB4:4.9'], B);
  A.mc('b3-06', 'c4-crysclast', 'Two rocks are both made of quartz grains. In rock 1 the grains interlock with no gaps; in rock 2 the grains are rounded and held by cement. Which statement is correct?',
    ['*Rock 1 is crystalline; rock 2 is clastic|Textbook 4.2; Sep 10.', 'Both are clastic, because both are made of the same quartz grains|Mineral does not decide texture.', 'Rock 2 is igneous|Cemented rounded grains are sedimentary.', 'Rock 1 is clastic because quartz is hard|Hardness does not decide texture.'], 'Textbook 4.2; Sep 10.', ['TB4:4.2', 'T0910'], B);
  A.mc('b3-07', 'c4-nonsil', 'A white mineral is soft (fingernail scratches it), does not fizz in acid, and its formula contains SO₄. What is it, and what family?',
    ['*Gypsum, a sulfate|Textbook 4.6, 4.9.', 'Calcite, a carbonate|Calcite fizzes and has CO₃.', 'Halite, a halide|NaCl has no SO₄.', 'Pyrite, a sulfide|Pyrite is metallic and FeS₂.'], 'Textbook 4.3, 4.6, 4.9.', ['TB4:4.6', 'TB4:4.9'], B);
  A.mc('b3-08', 'c4-shape', 'Two crystals of the same mineral: one grew in an open cavity with sharp faces, the other grew between earlier crystals and is irregular. What does the difference show?',
    ['*Crystal shape depends on whether growth was unimpeded, not only on composition|Textbook 4.4.', 'They must be different minerals|Same mineral.', 'The irregular one is glass|It is crystalline.', 'The sharp one grew faster in a hotter magma, which always makes faces|Not the stated cause.'], 'Textbook 4.4 and 5.8.', ['TB4:4.4', 'TB5:5.8'], B);
  A.mc('b3-09', 'c4-tetra', 'Why do silicate minerals almost always contain metal cations such as Fe, Mg, Ca, Na, or K?',
    ['*Each SiO₄ unit has a −4 charge that must be balanced|Textbook 4.7; Sep 10.', 'Metals make silicates harder|Not the reason.', 'Silicon cannot bond to oxygen at all unless a metal atom is present to hold them|It does in quartz.', 'Metals add color|Not the reason.'], 'Textbook 4.7; Sep 10.', ['TB4:4.7', 'T0910'], B);
  A.mc('b3-10', 'c4-abundance', 'Why are feldspars and quartz so common in continental crust?',
    ['*They are built mostly from the crust\'s most abundant elements|Textbook 4.10.', 'They are the only minerals that stay stable at Earth\'s surface|Others exist.', 'They formed from the core|No.', 'They are carbonates|They are silicates.'], 'Textbook 4.8, 4.10.', ['TB4:4.8', 'TB4:4.10'], B);
  A.mc('b3-11', 'c4-cleavage', 'A dark mineral in a granite has one perfect cleavage and peels into flexible sheets. Name it and its structure.',
    ['*Biotite, a sheet silicate|Textbook 4.5, 4.8.', 'Amphibole, a double chain|Two cleavages.', 'Olivine, independent tetrahedra|No cleavage.', 'Magnetite, an oxide|No sheet cleavage.'], 'Textbook 4.5, 4.7, 4.8.', ['TB4:4.5', 'TB4:4.8'], B);
  A.mc('b3-12', 'c4-water', 'Salt deposits in a desert basin formed from an evaporating lake. Which concept from Chapter 4 explains how the halite crystals formed?',
    ['*Evaporation concentrated Na⁺ and Cl⁻ until halite precipitated|Textbook 4.13.', 'Magma crystallized halite on the lake floor|Not the textbook mechanism.', 'Organisms built halite shells|No.', 'Wind carried halite crystals inland from the ocean and dropped them in the basin over time|Not the mechanism described.'], 'Textbook 4.13.', ['TB4:4.13'], B);
  L.BOSSES.push({ id: 'boss3', title: 'Chapter 4: Minerals from atoms up', chs: [4], pass: 0.8, blurb: 'Bonding, silicate structures, identification tests, and mineral families working together.', bossOnly: ['b3-01', 'b3-02', 'b3-03', 'b3-04', 'b3-05', 'b3-06', 'b3-07', 'b3-08', 'b3-09', 'b3-10', 'b3-11', 'b3-12'], coreN: 10, cases: ['k4-unknowns'] });

  // ---------------- Boss 4: Chapter 5 ----------------
  A.mc('b4-01', 'c5-partial', 'Mantle peridotite partially melts beneath a ridge; the magma cools in the crust. Which rock sequence results, from source to product?',
    ['*Peridotite (source) → mafic magma → basalt and gabbro|Textbook 5.6, 5.9.', 'Granite → mafic magma → peridotite|Source and product reversed.', 'Peridotite → felsic magma → rhyolite|Mantle partial melts are mostly mafic.', 'Basalt (source) → ultramafic magma → peridotite and dunite|Reversed.'], 'Textbook 5.6 and 5.9.', ['TB5:5.6', 'TB5:5.9'], B);
  A.mc('b4-02', 'c5-visc', 'Rank from least to most viscous: (1) hot, crystal-poor basalt; (2) cool rhyolite rich in crystals; (3) andesite at intermediate temperature.',
    ['*1, 3, 2|Temperature and silica both rise in viscosity toward rhyolite.', '2, 3, 1|Reversed.', '3, 1, 2|Basalt is least viscous.', '1, 2, 3|Rhyolite is most viscous.'], 'Textbook 5.7 C.', ['TB5:5.7'], B);
  A.mc('b4-03', 'c5-bowen', 'A magma crystallizes olivine and Ca-plagioclase, and those crystals settle to the chamber floor. What happens to the magma left above?',
    ['*It becomes more felsic|Textbook 5.6, 5.8.', 'It becomes ultramafic, because the settled crystals keep releasing Mg|Mafic components were removed.', 'It stays unchanged|Removing crystals changes the melt.', 'It turns into peridotite|The settled crystals form the mafic layer.'], 'Textbook 5.6 and 5.8.', ['TB5:5.6', 'TB5:5.8'], B);
  A.mc('b4-04', 'c5-melt3', 'Which pairing of setting and melting mechanism is correct?',
    ['*Mid-ocean ridge: decompression; subduction zone: adding water|Textbook 5.9–5.10.', 'Mid-ocean ridge: adding water; subduction zone: decompression|Reversed.', 'Both: heating by friction|Not the textbook mechanisms.', 'Hot spot: adding water only|Hot spots melt mainly by plume heat and decompression.'], 'Textbook 5.5, 5.9–5.11.', ['TB5:5.5', 'TB5:5.9', 'TB5:5.10', 'TB5:5.11'], B);
  A.mc('b4-05', 'c5-grain', 'Granite and rhyolite are chemically the same. Where would you expect to find each?',
    ['*Granite in a deep pluton; rhyolite in a lava flow or shallow body|Textbook 5.1, 5.6, 5.8.', 'Granite on the seafloor; rhyolite in the mantle|No.', 'Both only at mid-ocean ridges|Felsic magma is not typical there.', 'Granite in thick lava flows at the surface; rhyolite in deep plutons|Reversed.'], 'Textbook 5.1, 5.8.', ['TB5:5.1', 'TB5:5.8'], B);
  A.mc('b4-06', 'c5-rise', 'Why does mafic magma often stall and pond beneath continents but rise more easily through oceanic crust?',
    ['*It is denser than continental crust but not than oceanic crust|Textbook 5.7 B.2.', 'Continents are hotter than the mantle|No.', 'Oceanic crust contains more water, which pulls magma upward through it|Not the stated reason.', 'Mafic magma is too viscous for continents|Viscosity is not the cause here.'], 'Textbook 5.7.', ['TB5:5.7'], B);
  A.mc('b4-07', 'c5-special', 'A light-colored volcanic rock is full of vesicles; a dark one from the same region is also full of vesicles. What do they tell you about the region\'s magmas?',
    ['*Both felsic (pumice) and mafic (scoria) magmas erupted there|Textbook 5.3.', 'Only mafic magma erupted|Pumice is felsic to intermediate.', 'Both rocks are glass that formed with no gas at all in the magma|They have vesicles.', 'Vesicles form only in plutons|They form at low pressure.'], 'Textbook 5.3.', ['TB5:5.3'], B);
  A.mc('b4-08', 'c5-subduction', 'An island arc and a continental-margin arc both sit above subduction zones. Why are continental-arc magmas more often felsic?',
    ['*Mantle magma melts and assimilates thick continental crust|Textbook 5.10 B.', 'Oceanic crust is felsic|It is mafic.', 'The subducting slab is made of granite, which melts first|It is oceanic crust.', 'Island arcs have no water|Water is released in both.'], 'Textbook 5.10.', ['TB5:5.10', 'TB5:5.6'], B);
  A.mc('b4-09', 'c5-heat', 'What links Chapter 5\'s heat sources to plate tectonics?',
    ['*Radioactive heat, moved by convection and conduction|Textbook 5.4.', 'Sunlight heats the plates from above|No.', 'Magma is heated by earthquakes|No.', 'Heat flows downward from the crust into the core|The core is hottest.'], 'Textbook 5.4.', ['TB5:5.4'], B);
  A.mc('b4-10', 'c5-smallint', 'A sheet of basalt lies between two sandstone layers, and the sandstone both above and below it is baked. Its columnar joints are vertical. Is it a dike or a sill, and why are the joints vertical?',
    ['*A sill; joints are perpendicular to its cooling surfaces|Textbook 5.13.', 'A dike; dikes always have vertical joints, whatever their orientation|Dikes cut across layers; their joints are horizontal when the dike is vertical.', 'A laccolith; laccoliths have no joints|Not the geometry.', 'A lava flow; sills do not have joints|The baked sandstone above means magma intruded beneath existing rock, and sills commonly have columnar joints.'], 'Textbook 5.13.', ['TB5:5.13'], B);
  A.mc('b4-11', 'c5-ptread', 'On a P-T graph, rock at point M is solid, deep, and at 1,300 °C. It rises quickly to shallow depth with little cooling and becomes partly molten. Which Chapter 3 setting does this path match?',
    ['*A mid-ocean ridge or continental rift|Textbook 5.5, 5.9; Lecture 3 slides 22–24.', 'A subduction zone, where water is added|Different mechanism.', 'A transform fault|No melting mechanism there.', 'A continental collision with stalled subduction|Not decompression-dominated.'], 'Textbook 5.5, 5.9; Lecture 3.', ['TB5:5.5', 'TB5:5.9', 'L3:22', 'L3:23'], B);
  A.mc('b4-12', 'c5-classify', 'A rock has large plagioclase and amphibole crystals, ~60% silica, and cooled in a stock beneath a Cascade volcano. What is it, and what would its erupted equivalent be?',
    ['*Diorite; andesite|Intermediate, coarse vs. fine (textbook 5.2; 6.14 Cascade andesite).', 'Granite; rhyolite|Too much silica for 60%.', 'Gabbro; basalt|Too little silica.', 'Andesite; diorite|Reversed: the stock rock is coarse.'], 'Textbook 5.2, 5.3, 6.14.', ['TB5:5.2', 'TB5:5.3', 'TB6:6.14'], B);
  L.BOSSES.push({ id: 'boss4', title: 'Chapter 5: The igneous forge', chs: [5], pass: 0.8, blurb: 'Melting, magma evolution, viscosity, textures, classification, and settings, chained together.', bossOnly: ['b4-01', 'b4-02', 'b4-03', 'b4-04', 'b4-05', 'b4-06', 'b4-07', 'b4-08', 'b4-09', 'b4-10', 'b4-11', 'b4-12'], coreN: 10, cases: ['k5-melting'] });

  // ---------------- Boss 5: Chapter 6 ----------------
  A.mc('b5-01', 'c6-gasvisc', 'Kilauea erupts rivers of lava; Mount St. Helens exploded. Trace the difference to its root cause.',
    ['*Low-viscosity basalt lets gas escape; silica-rich magma traps it|Textbook 6.2; 5.7.', 'Kilauea has less magma|Volume is not the root cause.', 'St. Helens is closer to the ocean|No.', 'Kilauea\'s magma is colder, so its gas stays dissolved and never expands|Basalt is hotter.'], 'Textbook 6.2 and 5.7.', ['TB6:6.2', 'TB5:5.7'], B);
  A.mc('b5-02', 'c6-types', 'According to the textbook, which volcano types typically form during a single eruptive episode, and which are built by many eruptions?',
    ['*One episode: scoria cones, domes; many: shields, composites|Textbook 6.1.', 'One episode: shields and composites; many: scoria cones and domes|Reversed.', 'All are built in one eruption|No.', 'All are built by many eruptions|Scoria cones and domes usually form in one episode.'], 'Textbook 6.1.', ['TB6:6.1'], B);
  A.mc('b5-03', 'c6-shield', 'Hawaii\'s shield volcanoes and a hot-spot island chain are related how?',
    ['*A fixed hot spot builds shields that the plate carries away|Textbook 6.4, 5.11; Lecture 3 slide 43.', 'Each shield sits above its own separate small subduction zone in the Pacific|No.', 'The shields are composite volcanoes over a ridge|No.', 'The chain formed all at once|Ages differ.'], 'Textbook 6.4, 5.11; Lecture 3.', ['TB6:6.4', 'TB5:5.11', 'L3:43'], B);
  A.mc('b5-04', 'c6-flood', 'Why are flood basalts able to cover such huge areas compared with a composite volcano\'s lava?',
    ['*Huge, fast outpourings of fluid basalt from long fissures|Textbook 6.5.', 'They erupt only underwater|Most discussed are on land.', 'They are felsic and very gassy, so their ash spreads over whole regions|They are basaltic.', 'Composite volcanoes produce more magma|Flood basalts are the largest eruptions.'], 'Textbook 6.5.', ['TB6:6.5'], B);
  A.mc('b5-05', 'c6-disaster', 'St. Pierre (1902) and Armero (1985) were both destroyed. What killed people in each?',
    ['*St. Pierre: pyroclastic flow; Armero: lahar|Textbook 6.8, 6.12.', 'Both towns: fast lava flows down valleys|Neither.', 'St. Pierre: a lahar; Armero: a pyroclastic flow|Reversed.', 'Both: huge waves from caldera collapse|That was Krakatau.'], 'Textbook 6.8 and 6.12.', ['TB6:6.8', 'TB6:6.12'], B);
  A.mc('b5-06', 'c6-caldera', 'Why do calderas typically erupt felsic magma in huge volumes rather than basaltic lava?',
    ['*Big shallow felsic chambers trap gas, empty explosively, and collapse|Textbook 6.10.', 'Calderas form only on basaltic shields|Kilauea has a caldera, but big caldera eruptions are felsic.', 'Felsic magma is always hotter than basalt, so it boils away the chamber roof|It is cooler.', 'Basalt cannot erupt from calderas|Not stated.'], 'Textbook 6.10.', ['TB6:6.10'], B);
  A.mc('b5-07', 'c6-assess', 'A volcano has gentle slopes of basalt, an eroded shape, and no deposits younger than 1 million years. Another is steep, andesitic, and has fresh ash. Which assessment is best?',
    ['*The second poses the greater hazard|Textbook 6.12 A.', 'The first, because its fluid basalt flows much farther|Its age and style lower the hazard.', 'Both equal because both are volcanoes|Type and history matter.', 'Neither can be assessed without an eruption|Shape, rocks, and history allow assessment.'], 'Textbook 6.12.', ['TB6:6.12'], B);
  A.mc('b5-08', 'c6-monitor', 'At Mount St. Helens in 1980, which monitoring signal gave the most visible warning before the eruption?',
    ['*Rapid growth of a bulge on the north flank (ground deformation)|Textbook 6.8, 6.13.', 'A complete drop in earthquake activity for several months beforehand|Not described.', 'Cooling of the summit|Not described.', 'No warning signs|The bulge was recognized as dangerous.'], 'Textbook 6.8 and 6.13.', ['TB6:6.8', 'TB6:6.13'], B);
  A.mc('b5-09', 'c6-rainier', 'Link Mount Rainier to Chapters 3 and 5: which chain is correct?',
    ['*Subduction → water → mantle melting → andesite → composite|Textbook 6.14, 5.10; Lecture 3.', 'Hot spot → decompression → basalt → shield|That is Hawaii.', 'Continental rift → decompression → basalt → flood basalt plateau|Not Rainier.', 'Collision → no magma → no volcano|Rainier is active.'], 'Textbook 6.14 and 5.10; Lecture 3 slides 25–27.', ['TB6:6.14', 'TB5:5.10', 'L3:26'], B);
  A.mc('b5-10', 'c6-bashaz', 'Iceland sits on a mid-ocean ridge and a hot spot, under ice. Which hazard combination does the textbook describe there?',
    ['*Fissure eruptions, gas and climate effects, and meltwater floods|Textbook 6.6.', 'Only pyroclastic flows from rhyolite domes|Not the described set.', 'No hazards because basalt is gentle|Basaltic eruptions are still hazardous.', 'Lahars from andesitic stratovolcanoes only, with no basaltic hazards at all|Not the described set.'], 'Textbook 6.6.', ['TB6:6.6'], B);
  A.mc('b5-11', 'c6-colflow', 'Pompeii was first covered by falling tephra, then struck by pyroclastic flows. What does that sequence suggest about the eruption column?',
    ['*A gas-rich column rained tephra, then partly collapsed into flows|Textbook 6.2, 6.8.', 'The eruption switched from basaltic lava flows to rhyolitic lava flows|No lava flows described.', 'The wind reversed|Not the textbook explanation.', 'Pyroclastic flows always come before tephra fall|Pompeii shows the reverse.'], 'Textbook 6.2 and 6.8.', ['TB6:6.2', 'TB6:6.8'], B);
  A.mc('b5-12', 'c6-dome', 'After the 1980 blast, domes grew inside Mount St. Helens\'s crater. Why are domes typical late in a composite-volcano eruption?',
    ['*Degassed, viscous magma oozes out and piles up|Textbook 6.9.', 'Domes are made of fluid basalt|They are viscous andesite to rhyolite.', 'Domes form only in calderas|They also form in craters.', 'Late magma is hotter and more fluid, so it can only pile up near the vent|Not the reason.'], 'Textbook 6.9.', ['TB6:6.9'], B);
  L.BOSSES.push({ id: 'boss5', title: 'Chapter 6: Volcano warden', chs: [6], pass: 0.8, blurb: 'Eruption style, volcano types, disasters, calderas, and hazard assessment, from cause to consequence.', bossOnly: ['b5-01', 'b5-02', 'b5-03', 'b5-04', 'b5-05', 'b5-06', 'b5-07', 'b5-08', 'b5-09', 'b5-10', 'b5-11', 'b5-12'], coreN: 10, cases: ['k6-compare'] });

  // ---------------- Boss 6: Final integration ----------------
  A.mc('b6-01', 'c3-hotspot', 'Which single idea connects a Hawaiian shield volcano (Ch 6), decompression melting in a plume (Ch 5), and an age-progressive island chain (Ch 3)?',
    ['*A fixed mantle plume beneath a moving plate|Textbook 5.11, 6.4; Lecture 3 slide 43.', 'A subduction zone beneath Hawaii|None there.', 'A continental collision building the islands upward|No.', 'A transform fault|No.'], 'Textbook 5.11, 6.4; Lecture 3.', ['TB5:5.11', 'TB6:6.4', 'L3:43'], B);
  A.mc('b6-02', 'c5-divergent', 'New oceanic crust at a ridge is made of basalt and gabbro, rich in pyroxene and Ca-plagioclase. Which set of links is correct?',
    ['*Divergence → decompression melting → mafic magma → mafic minerals|Integrates Lecture 3, textbook 5.9, 4.8.', 'Subduction → water-fluxed melting → felsic magma → quartz and K-feldspar|Wrong setting.', 'Ch 3 transform → no melting → metamorphic rock|No.', 'Ch 1 isostasy → melting → granite|No.'], 'Lecture 3 slide 22; textbook 5.9, 4.8.', ['L3:22', 'TB5:5.9', 'TB4:4.8'], B);
  A.mc('b6-03', 'c1-isostasy', 'Why are continents high and ocean basins low, in terms of Chapters 1, 4, and 5?',
    ['*Thick, light felsic crust floats higher than thin, dense mafic crust|Lecture 1b slides 15–16; textbook 4.10, 5.2.', 'Continents rest on the inner core|No.', 'Ocean basins are filled with heavy seawater that presses them down into the mantle|Not the reason.', 'Continents are made of basalt|They are largely granitic.'], 'Lecture 1b slides 15–16; textbook 4.10, 5.2.', ['L1B:16', 'TB4:4.10', 'TB5:5.2'], B);
  A.mc('b6-04', 'c5-subduction', 'A subduction zone produces andesite volcanoes, deep earthquakes, and a trench. Which chapters\' ideas are all required to explain the andesite?',
    ['*Chapters 3, 4, and 5 together|Lecture 3; textbook 5.10, 4.8.', 'Only Chapter 6, which describes composite volcanoes|Ch 6 describes the volcano, not the magma origin.', 'Only Ch 1|Too general.', 'Ch 2 relative dating only|Not about magma.'], 'Lecture 3; textbook 5.10, 4.8, 6.7.', ['L3:26', 'TB5:5.10', 'TB4:4.8', 'TB6:6.7'], B);
  A.mc('b6-05', 'c2-sequence', 'A basalt dike cuts a sandstone, and a lava flow of the same basalt lies on top of the sandstone, overlain by shale with basalt pebbles. Which principle(s) show the shale is youngest?',
    ['*Superposition and inclusions|Lecture 2 slides 10–13.', 'Only cross-cutting relations, since the dike cuts the sandstone|The shale is not cut.', 'Contact effects alone|The shale was not baked.', 'None; relative age requires numeric dating|Relative principles suffice.'], 'Lecture 2 slides 10–13.', ['L2:10', 'L2:12', 'L2:13'], B);
  A.mc('b6-06', 'c4-commonsil', 'Olivine is common in the mantle, crystallizes first in Bowen\'s series, and has no cleavage. Which structural fact ties those together?',
    ['*Independent SiO₄ tetrahedra linked by Mg and Fe|Textbook 4.7, 4.8, 5.8.', 'It is a framework silicate like quartz, sharing all four oxygens|No.', 'It is a sheet silicate like mica|No.', 'It is a carbonate|No.'], 'Textbook 4.7, 4.8, 5.8.', ['TB4:4.7', 'TB4:4.8', 'TB5:5.8'], B);
  A.mc('b6-07', 'c6-assess', 'You are advising a town beside a steep andesitic volcano in a valley that drains the summit glacier. Which recommendation uses the most course ideas correctly?',
    ['*Plan for lahars, monitor the volcano, and set evacuation routes out of the valley|Textbook 6.12–6.14.', 'Build tall lava-flow barriers, because andesite lava flows fast and far down valleys|Andesite is viscous; lahars are the valley threat.', 'Ignore the volcano if it has not erupted in 200 years|Rainier last erupted in 1820 and is considered very dangerous.', 'Move the town downwind to avoid mudflows|Downwind increases ash hazard.'], 'Textbook 6.12, 6.13, 6.14.', ['TB6:6.12', 'TB6:6.13', 'TB6:6.14'], B);
  A.mc('b6-08', 'c3-magnetic', 'Iron-bearing minerals in a cooling basalt record Earth\'s magnetic field. Which pieces of the course does that single fact connect?',
    ['*Chapters 3, 4, and 5|Textbook 4.9, 5.9; Lecture 3 slides 39–41.', 'Chapter 6 only, because lava tubes preserve the magnetic field|Not the connection.', 'Ch 2 (topographic maps) only|No.', 'Ch 1 (atmosphere)|No.'], 'Textbook 4.9, 5.9; Lecture 3 slides 39–41.', ['TB4:4.9', 'TB5:5.9', 'L3:40'], B);
  A.mc('b6-09', 'c5-grain', 'A geologist finds the same felsic magma as a coarse granite pluton, a fine rhyolite lava, and a pumice-rich welded tuff. What controlled the difference?',
    ['*Where and how fast it solidified, and how it erupted|Textbook 5.1, 5.3, 6.2.', 'Three different source rocks melted to make three separate magmas|Same magma.', 'The minerals changed from felsic to mafic|All felsic.', 'Only the age of each rock|Setting and cooling rate control texture.'], 'Textbook 5.1, 5.3, 6.2.', ['TB5:5.1', 'TB5:5.3', 'TB6:6.2'], B);
  A.mc('b6-10', 'c1-method', 'A new crater is found. Which approach best reflects how the course treats geologic problems (Chapters 1–2)?',
    ['*Observe, propose several explanations, predict, and test|Lecture 1b slide 2; Lecture 2 slides 25–29.', 'Pick the most famous explanation and look for support|Confirmation bias.', 'Assume it is volcanic, because most craters on Earth are volcanic, and then map it|Not a test.', 'Wait until someone witnesses a similar event|Not required.'], 'Lecture 1b slide 2; Lecture 2 slides 25–29.', ['L1B:2', 'L2:25', 'L2:29'], B);
  A.mc('b6-11', 'c6-caldera', 'Yellowstone\'s calderas (Ch 6), the Columbia Plateau flood basalts (Ch 6), and a hot-spot track across Idaho (Ch 3) are linked how?',
    ['*One hot spot under a moving plate, first flood basalts, then calderas|Textbook 6.5, 6.11; Lecture 3 slide 43.', 'They are unrelated coincidences|The textbook links them.', 'They are all subduction volcanoes|No.', 'The calderas erupted first, and the flood basalts came later from the same hot spot|Flood basalts are 17–5 Ma; Yellowstone calderas are 2.1 Ma and younger.'], 'Textbook 6.5 and 6.11.', ['TB6:6.5', 'TB6:6.11', 'L3:43'], B);
  A.mc('b6-12', 'c4-bonds', 'Quartz is the last mineral to crystallize from felsic magma, has no cleavage, and resists weathering into beach sand. Which property underlies its hardness and lack of cleavage?',
    ['*A 3-D framework of strong Si–O covalent bonds with every oxygen shared|Textbook 4.7, 4.12; Bowen from 5.8.', 'Weak intermolecular forces holding sheets of atoms together|That is mica or graphite.', 'Metallic bonding|No.', 'It contains iron|Quartz is SiO₂.'], 'Textbook 4.7, 4.12, 5.8.', ['TB4:4.7', 'TB4:4.12', 'TB5:5.8'], B);
  A.mc('b6-13', 'c3-rifting', 'A continental rift erupts both basalt and rhyolite. Using Chapters 3 and 5, why both?',
    ['*Mantle melts to basalt; its heat melts crust to rhyolite|Lecture 3 slide 24; textbook 5.9, 5.11.', 'Rifts subduct ocean crust|Rifts are divergent.', 'Rhyolite comes from the core|No.', 'Basalt turns into rhyolite simply by cooling slowly in the rift, with no other process|Partial crystallization alone would not usually go that far here; crustal melting is the textbook route.'], 'Lecture 3 slide 24; textbook 5.9, 5.11.', ['L3:24', 'TB5:5.9', 'TB5:5.11'], B);
  A.mc('b6-14', 'c2-relief', 'Mauna Loa rises about 9,000 m from the seafloor but only about 4,170 m above sea level. Which Chapter 2 measurement does the 9,000 m describe?',
    ['*Relief between the seafloor base and the summit|Lecture 2 slide 19; textbook 6.4.', 'Elevation above sea level|That is 4,170 m.', 'Slope steepness|That needs horizontal distance.', 'Depth of the magma chamber below the summit|No.'], 'Lecture 2 slide 19; textbook 6.4.', ['L2:19', 'TB6:6.4'], B);
  L.BOSSES.push({ id: 'boss6', title: 'Final integration: Chapters 1–6', chs: [1, 2, 3, 4, 5, 6], pass: 0.8, blurb: 'Every question forces a link between chapters: plates to magma to minerals to volcanoes to landscapes.', bossOnly: ['b6-01', 'b6-02', 'b6-03', 'b6-04', 'b6-05', 'b6-06', 'b6-07', 'b6-08', 'b6-09', 'b6-10', 'b6-11', 'b6-12', 'b6-13', 'b6-14'], coreN: 12, cases: [] });

  // Deterministic core-item selection so each Boss is a fixed set (same questions every run; order shuffles).
  function chOf(c) { var con = L.CONCEPTS[c]; if (!con) return 0; var s = L.SECTIONS.filter(function (x) { return x.id === con.sec; })[0]; return s ? s.ch : 0; }
  L.BOSSES.forEach(function (b) {
    var byCon = {}, perCh = {};
    L.ITEMS.forEach(function (it) {
      if (it.pool === 'boss' || it.t === 'teach' || b.chs.indexOf(chOf(it.c)) < 0) return;
      if (!byCon[it.c]) { byCon[it.c] = []; var ch = chOf(it.c); (perCh[ch] = perCh[ch] || []).push(it.c); }
      byCon[it.c].push(it.id);
    });
    // interleave concepts across the boss's chapters, then take evenly spaced concepts; use each concept's second item
    var inter = [], k = 0, more = true;
    while (more) { more = false; b.chs.forEach(function (ch) { var l = perCh[ch] || []; if (k < l.length) { inter.push(l[k]); more = true; } }); k++; }
    var picked = [], stride = inter.length / b.coreN;
    for (var i = 0; i < b.coreN && i < inter.length; i++) { var ids = byCon[inter[Math.floor(i * stride)]]; picked.push(ids[Math.min(1, ids.length - 1)]); }
    b.refs = b.bossOnly.concat(picked);
  });
})((typeof window !== 'undefined' ? window : globalThis).L);
