/* Chapter 4; Earth Materials. Evidence: textbook 4.1–4.13 (4.14–4.16 skimmed only), Sep 8 and Sep 10 recordings.
   No Chapter 4 slide deck was supplied; the lecture recordings show the same textbook figures being discussed. */
(function (L) {
  'use strict';
  var A = L.A;
  function tb(n, cap) { return { kind: 'img', src: 'assets/img/tb45/figure-' + (n < 10 ? '0' + n : n) + '.jpg', cap: cap, alt: cap }; }
  function tp(name, cap) { return { kind: 'img', src: 'assets/img/tb/' + name + '.jpg', cap: cap, alt: cap }; }

  // ---------- 4.1 ----------
  A.section({ id: 'c4s1', ch: 4, n: '4.1', title: 'Rocks, minerals, and how minerals fit together', srcText: 'Textbook 4.1–4.2 · Rec. Sep 8, Sep 10', src: ['TB4:4.1', 'TB4:4.2', 'T0908', 'T0910'],
    concepts: [['c4-mineraldef', 'What counts as a mineral'], ['c4-rockmineral', 'Rocks → minerals → elements'], ['c4-crysclast', 'Crystalline vs. clastic']] });
  A.cards('c4s1', [
    { id: 'g4-1a', h: 'Five tests for “mineral”', c: ['c4-mineraldef'], src: ['TB4:4.1', 'T0908'],
      html: '<p>A mineral is a <b>naturally occurring, inorganic, crystalline solid with a relatively consistent (specific) chemical composition</b>. Fail any one and it is not a mineral:</p><table><tr><th>Criterion</th><th>Is</th><th>Is not</th></tr><tr><td>Natural</td><td>Natural diamond</td><td>Lab-grown (synthetic) diamond</td></tr><tr><td>Inorganic</td><td>Calcite crystal</td><td>A shell made by a creature, even of the same composition</td></tr><tr><td>Solid</td><td>Ice</td><td>Liquid water; liquid mercury</td></tr><tr><td>Ordered internal structure (crystalline)</td><td>Calcite</td><td>Volcanic glass (obsidian): atoms arranged randomly</td></tr><tr><td>Specific composition</td><td>Halite, NaCl, whatever the sample size</td><td>Conglomerate: different parts, different compositions</td></tr></table><p>“Minerals” on a vitamin label are chemical elements, not geologic minerals.</p>',
      traps: ['Calling obsidian a mineral: it is natural and solid but not crystalline.', 'Calling a seashell a mineral: same composition as calcite, but made by an organism.'] },
    { id: 'g4-1b', h: 'Levels of scale', c: ['c4-rockmineral'], src: ['TB4:4.1', 'T0908'],
      html: '<p>The professor\'s zoom (Sep 8): <b>landscape → outcrop → hand specimen → minerals → atoms</b>. <b>Rocks are made of minerals, and minerals are made of chemical elements.</b> Most rocks contain several minerals (granite: quartz, feldspar, and dark minerals); some contain one (limestone can be nearly all calcite; sandstone can be all quartz). A few minerals are one element (<b>native elements</b>, e.g., diamond = carbon). Very thin slices (<b>thin sections</b>, under 30 micrometers per the lecture) let light pass for microscope identification.</p>', media: tb(1, 'Textbook 4.1; Yosemite granite: landscape to rock to mineral') },
    { id: 'g4-1c', h: 'Crystalline vs. clastic', c: ['c4-crysclast'], src: ['TB4:4.2', 'T0910'],
      html: '<p>The professor\'s shortcut (Sep 10): in a <b>crystalline</b> rock the minerals <b>grew</b> in place, interlocking as they competed for space; in a <b>clastic</b> rock the pieces were <b>produced</b> from pre-existing rocks by weathering and then deposited. Crystalline rocks typically form by crystallizing magma, metamorphism, or precipitation from water (hot, or evaporating). Clastic rocks mostly form at the surface (dunes, rivers, beaches), though explosive eruptions also make clastic volcanic rocks.</p><p>Four things to observe in either: <b>types of minerals, sizes, shapes, and layering</b>.</p>',
      media: [tp('ch4-crystalline', 'Crystalline: interlocking grains that grew together (textbook 4.2)'), tp('ch4-clastic', 'Clastic: pieces derived from older rocks (textbook 4.2)')],
      traps: ['Calling a rock clastic just because it breaks into pieces when you hit it; clastic describes how it formed.'] }
  ]);
  A.ms('c4-mineraldef-s1', 'c4-mineraldef', 'Which of these are minerals? Select all that apply.',
    ['*Ice in a glacier|Natural, inorganic, solid, crystalline, H₂O.', '*A natural diamond|Native element carbon; meets all criteria.', 'Obsidian (volcanic glass)|No ordered internal structure.', 'A clam shell made of calcium carbonate|Made by an organism, so not inorganic.', 'Diamond grown in a laboratory|Not naturally occurring.'],
    'Textbook 4.1 uses these exact criteria; Sep 8 lecture: lab diamonds are not minerals; a shell made by an organism is not.', ['TB4:4.1', 'T0908']);
  A.mc('c4-mineraldef-m1', 'c4-mineraldef', 'Obsidian is natural, inorganic, and solid. Which criterion keeps it from being a mineral?',
    ['*Its atoms have no ordered, repeating arrangement|Volcanic glass is not crystalline.', 'It does not occur naturally; it is made in industrial furnaces|It forms naturally from lava.', 'It is organic|It is inorganic.', 'It contains more than one chemical element|Many minerals contain several elements.'], 'Textbook 4.1 (ordered internal structure).', ['TB4:4.1']);
  A.mc('c4-mineraldef-m2', 'c4-mineraldef', 'Liquid mercury is natural, inorganic, and found in rocks. Why is it not a mineral?',
    ['*It is not a solid|All minerals are solid.', 'It is made in laboratories|It occurs naturally.', 'It has more than one composition|It is a single element.', 'It is organic|It is inorganic.'], 'Textbook 4.1: liquid mercury is not considered a mineral.', ['TB4:4.1']);
  A.fill('c4-mineraldef-f1', 'c4-mineraldef', 'A naturally occurring, inorganic, crystalline solid with a specific chemical composition is a <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['mineral'], 'Textbook 4.1 definition.', ['TB4:4.1']);
  A.mc('c4-rockmineral-m1', 'c4-rockmineral', 'Which statement correctly relates rocks, minerals, and elements?',
    ['*Rocks are made of minerals, and minerals are made of chemical elements|Textbook 4.1.', 'Minerals are made of rocks, and rocks are made of chemical elements|Reversed levels.', 'Rocks are single elements, and minerals are mixtures of rocks|Reversed.', 'Elements are made of minerals|Elements are the most basic level here.'], 'Textbook 4.1.', ['TB4:4.1']);
  A.mc('c4-rockmineral-m2', 'c4-rockmineral', 'A limestone is almost 100% calcite. Is it a rock or a mineral?',
    ['*A rock made of one mineral|The textbook notes some rocks contain a single mineral (limestone, calcite).', 'A mineral, because it contains only calcite|The rock is an aggregate of many calcite grains.', 'Neither, because it formed in water|Water-formed rocks are still rocks.', 'An element, because it is pure|Calcite has several elements (Ca, C, O).'], 'Textbook 4.1.', ['TB4:4.1']);
  A.fill('c4-rockmineral-f1', 'c4-rockmineral', 'A mineral made of only one chemical element, such as diamond (carbon), is called a <u>&nbsp;&nbsp;&nbsp;&nbsp;</u> element.', ['native'], 'Textbook 4.1 and 4.6.', ['TB4:4.1']);
  A.mc('c4-crysclast-m1', 'c4-crysclast', 'A hand specimen has pink, white, clear, and black grains whose edges interlock with no gaps or cement between them. How did it most likely form?',
    ['*Minerals grew together in place; a crystalline rock|Interlocking grains that competed for space.', 'Weathered fragments were deposited and cemented; a clastic rock|Clastic grains are separate pieces, often with matrix between.', 'It is a single mineral with four colors|Different colors here are different minerals.', 'It cannot be interpreted without a microscope|Interlocking texture is visible in hand specimen.'], 'Textbook 4.2; Sep 10: crystalline minerals “grow,” clastic pieces are “produced.”', ['TB4:4.2', 'T0910'], { media: tp('ch4-crystalline', 'Specimen') });
  A.mc('c4-crysclast-m2', 'c4-crysclast', 'Why can a clastic grain be a whole piece of rock rather than a single mineral?',
    ['*Clasts are fragments broken from pre-existing rocks, so one clast can contain several minerals|Textbook 4.2 and Sep 8.', 'Clasts grow from magma as whole rock pieces, so each one contains several minerals|Growth in place is crystalline.', 'All clasts are single quartz crystals|Some are, but clasts can be rock fragments.', 'Clasts form only from volcanic glass|Most clasts come from weathered rock.'], 'Textbook 4.2.', ['TB4:4.2', 'T0908']);
  A.fill('c4-crysclast-f1', 'c4-crysclast', 'A rock made of pieces derived from pre-existing rocks is described as <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['clastic'], 'Textbook 4.2.', ['TB4:4.2']);
  A.fill('c4-crysclast-f2', 'c4-crysclast', 'A rock made of interlocking minerals that grew together is described as <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['crystalline'], 'Textbook 4.2.', ['TB4:4.2']);

  // ---------- 4.2 ----------
  A.section({ id: 'c4s2', ch: 4, n: '4.2', title: 'Identifying minerals: appearance and tests', srcText: 'Textbook 4.3 · Rec. Sep 8', src: ['TB4:4.3', 'T0908'],
    concepts: [['c4-appearance', 'Shape, cleavage, color, luster'], ['c4-tests', 'Hardness, streak, acid, magnetism, density']] });
  A.cards('c4s2', [
    { id: 'g4-2a', h: 'What you can see without a test', c: ['c4-appearance'], src: ['TB4:4.3', 'T0908'],
      html: '<ul><li><b>Crystal shape</b>: cubes, prisms, hexagons; reflects the atomic arrangement when growth is unobstructed.</li><li><b>Cleavage vs. fracture</b>: breaking along flat planes (cleavage) vs. irregular or curved surfaces (fracture).</li><li><b>Color</b>: useful but <b>not reliable</b>: quartz comes in many colors because of trace elements.</li><li><b>Luster</b>: how light bounces off: <b>metallic</b> or <b>nonmetallic</b> (glassy, pearly, silky, resinous, earthy).</li></ul>',
      traps: ['Identifying a mineral by color alone.'] },
    { id: 'g4-2b', h: 'Five simple tests', c: ['c4-tests'], src: ['TB4:4.3', 'T0908'],
      html: '<table><tr><th>Test</th><th>How</th><th>Classic result</th></tr><tr><td>Hardness</td><td>Scratch test; a harder material scratches a softer one</td><td>Mohs scale 1–10</td></tr><tr><td>Streak</td><td>Rub on unglazed porcelain</td><td>Hematite leaves a <b>reddish</b> streak</td></tr><tr><td>Effervescence</td><td>Drop of dilute HCl</td><td><b>Calcite</b> fizzes strongly (limestone)</td></tr><tr><td>Magnetism</td><td>Magnet or compass</td><td><b>Magnetite</b> is the strongest natural magnet</td></tr><tr><td>Density / specific gravity</td><td>Heft test; ratio to water</td><td>Galena feels heavy; typical rock ≈ 2.7</td></tr></table>' +
        '<p><b>Mohs scale:</b> 1 talc, 2 gypsum, 3 calcite, 4 fluorite, 5 apatite, 6 K-feldspar, 7 quartz, 8 topaz, 9 corundum, 10 diamond. Reference objects: fingernail 2.5, copper wire 3.5, window glass or knife blade 5.5. The numbers are <b>relative ranks</b>, not equal steps (diamond is far harder than corundum).</p>' +
        '<button class="btn small" data-guidegen="hardness">Practice scratch-test reasoning (5)</button> <button class="btn small" data-guidegen="mineralId">Practice mineral ID from properties (5)</button>',
      traps: ['Reading the Mohs numbers as proportional hardness.', 'Forgetting that the streak color can differ from the specimen color (hematite can look black or silver but streaks red).'] }
  ]);
  A.mc('c4-appearance-m1', 'c4-appearance', 'Five quartz crystals are purple, pink, clear, brown, and smoky gray. What does this show?',
    ['*Color is not a reliable way to identify some minerals|Textbook 4.3 and Sep 8: trace elements change quartz\'s color.', 'They are five different minerals|They share composition and properties.', 'Only the clear crystal is real quartz; the colored ones are other minerals|All are quartz.', 'Color always matches chemical formula|Trace impurities alter color without changing the mineral.'], 'Textbook 4.3.', ['TB4:4.3', 'T0908']);
  A.mc('c4-appearance-m2', 'c4-appearance', 'A student breaks a mineral and gets smooth, curved, shell-like surfaces rather than flat planes. What property is this?',
    ['*Conchoidal fracture|Quartz breaks this way.', 'One direction of cleavage|Cleavage produces flat parallel planes.', 'Metallic luster|Luster describes reflected light, not breakage.', 'Streak|Streak is the color of powder.'], 'Textbook 4.3, 4.5, 4.8.', ['TB4:4.3', 'TB4:4.8']);
  A.fill('c4-appearance-f1', 'c4-appearance', 'The way light reflects from a mineral\'s surface; for example metallic, glassy, or earthy; is its <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['luster', 'lustre'], 'Textbook 4.3.', ['TB4:4.3']);
  A.mc('c4-tests-m1', 'c4-tests', 'A mineral scratches a copper wire but not window glass. What is its approximate Mohs hardness?',
    ['*Between 3.5 and 5.5|Harder than copper (3.5), softer than glass (5.5).', 'Less than 2.5|It scratches copper, so it is harder than 3.5.', 'Greater than 5.5|It fails to scratch glass.', 'Exactly 7|Quartz (7) would scratch glass.'], 'Textbook 4.3 Mohs scale with common objects.', ['TB4:4.3']);
  A.mc('c4-tests-m2', 'c4-tests', 'A black, metallic-looking mineral leaves a reddish-brown streak on porcelain. Which mineral is the best match?',
    ['*Hematite|Textbook: hematite has a reddish streak regardless of specimen color.', 'Magnetite|Magnetite is black and strongly magnetic; its streak is dark gray (Sep 8).', 'Galena|Galena is gray, metallic, cubic, and very dense.', 'Pyrite|Pyrite is brassy yellow.'], 'Textbook 4.3 and 4.9.', ['TB4:4.3', 'TB4:4.9', 'T0908']);
  A.mc('c4-tests-m3', 'c4-tests', 'A white mineral bubbles vigorously when a drop of dilute hydrochloric acid is added. It is most likely:',
    ['*Calcite|The only common mineral that effervesces strongly with dilute HCl.', 'Quartz|Quartz does not react with dilute HCl.', 'Gypsum|Gypsum is soft but does not fizz.', 'Dolomite|Dolomite may not fizz unless powdered.'], 'Textbook 4.3 and 4.9.', ['TB4:4.3', 'TB4:4.9']);
  A.match('c4-tests-x1', 'c4-tests', 'Match each test to what it measures or detects.', [
    ['Scratch test', 'Hardness'], ['Porcelain plate', 'Streak (powder color)'], ['Dilute HCl', 'Effervescence of carbonate'], ['Heft test / specific gravity', 'Density'], ['Compass or magnet', 'Magnetism']], 'Textbook 4.3.', ['TB4:4.3']);
  A.fill('c4-tests-f1', 'c4-tests', 'The ranked scale of mineral hardness from talc (1) to diamond (10) is the <u>&nbsp;&nbsp;&nbsp;&nbsp;</u> scale.', ['Mohs', 'Mohs hardness', "Moh's", 'Moh'], 'Textbook 4.3.', ['TB4:4.3']);
  A.fill('c4-tests-f2', 'c4-tests', 'The color of a mineral\'s powder, seen by rubbing it on unglazed porcelain, is its <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['streak'], 'Textbook 4.3.', ['TB4:4.3']);

  // ---------- 4.3 ----------
  A.section({ id: 'c4s3', ch: 4, n: '4.3', title: 'Crystal shape and cleavage', srcText: 'Textbook 4.4–4.5 · Rec. Sep 8', src: ['TB4:4.4', 'TB4:4.5', 'T0908'],
    concepts: [['c4-shape', 'Atomic arrangement controls crystal shape'], ['c4-cleavage', 'Cleavage types and causes']] });
  A.cards('c4s3', [
    { id: 'g4-3a', h: 'Shape reflects the arrangement of atoms', c: ['c4-shape'], src: ['TB4:4.4', 'T0908'],
      html: '<p>Halite (NaCl): sodium and chlorine alternate in three perpendicular directions, a <b>cubic</b> arrangement, so halite grows and cleaves into cubes. Common atomic arrangements are the <b>cube</b>, the <b>tetrahedron</b> (one atom surrounded by four, a pyramid with a triangular base), and the <b>octahedron</b> (two four-sided pyramids joined base to base). Well-formed crystals grow <b>unimpeded</b>, usually into open space filled with water or magma; crystals that grow <b>around earlier crystals</b> take irregular shapes.</p>', media: [tb(5, 'Halite: Na and Cl alternate in three perpendicular directions (textbook 4.4)'), tb(10, 'Textbook 4.7; linked tetrahedra (a tetrahedral arrangement)')] },
    { id: 'g4-3b', h: 'Cleavage follows the weakest bonds', c: ['c4-cleavage'], src: ['TB4:4.5', 'T0908'],
      html: '<p>A mineral cleaves where bonds are weakest, along parallel planes. If no such planes exist, it fractures.</p><table><tr><th>Cleavage</th><th>Result</th><th>Example</th></tr><tr><td>One direction</td><td>Thin sheets</td><td>Micas (biotite, muscovite)</td></tr><tr><td>Two at ~90°</td><td>Right-angle steps</td><td>Pyroxene</td></tr><tr><td>Two not at 90° (~60°/120°)</td><td>Non-square corners</td><td>Amphibole</td></tr><tr><td>Three at 90°</td><td>Cubes, stair steps</td><td>Halite (also galena)</td></tr><tr><td>Three not at 90°</td><td>Rhombs</td><td>Calcite</td></tr><tr><td>None</td><td>Conchoidal fracture</td><td>Quartz</td></tr></table>',
      media: [{ kind: 'svg', name: 'cleavage', spec: { type: '1' } }, { kind: 'svg', name: 'cleavage', spec: { type: '2-90' } }, { kind: 'svg', name: 'cleavage', spec: { type: '2-60' } }, { kind: 'svg', name: 'cleavage', spec: { type: '3-90' } }, { kind: 'svg', name: 'cleavage', spec: { type: '3-rhomb' } }, { kind: 'svg', name: 'cleavage', spec: { type: 'none' } }],
      traps: ['Confusing crystal faces (grown) with cleavage planes (broken). Quartz has faces but no cleavage.', 'Pyroxene vs. amphibole: 90° vs. ~60/120°.'] }
  ]);
  A.mc('c4-shape-m1', 'c4-shape', 'Why do halite grains in table salt tend to be tiny cubes?',
    ['*Na and Cl alternate in three perpendicular directions|Textbook 4.4.', 'Salt factories cut the grains into cubes before packaging them|The cubic shape is natural.', 'All minerals form cubes when they crystallize slowly from evaporating water|Crystal shape depends on atomic arrangement.', 'Chlorine atoms are cube-shaped|Atoms are not cubes; their arrangement is.'], 'Textbook 4.4; Sep 8.', ['TB4:4.4', 'T0908']);
  A.mc('c4-shape-m2', 'c4-shape', 'In a granite, gray quartz fills irregular spaces between well-shaped feldspar crystals. What explains the quartz\'s irregular shape?',
    ['*The quartz grew last and had to fill the space left around earlier crystals|Textbook 4.4 (growth environment) and 5.8.', 'Quartz never forms crystal faces|Quartz can grow excellent faces in open space.', 'The quartz was partly melted and reshaped long after the granite formed|Irregular fill does not require remelting.', 'Quartz has cubic cleavage|Quartz has no cleavage.'], 'Textbook 4.4 C.', ['TB4:4.4', 'TB5:5.8']);
  A.match('c4-cleavage-x1', 'c4-cleavage', 'Match each mineral or group to its cleavage.', [
    ['Mica (biotite, muscovite)', 'One direction; thin sheets'], ['Pyroxene', 'Two directions at about 90°'], ['Amphibole', 'Two directions at about 60° and 120°'], ['Halite', 'Three directions at 90° (cubes)'], ['Calcite', 'Three directions not at 90° (rhombs)'], ['Quartz', 'No cleavage; conchoidal fracture']], 'Textbook 4.5 and 4.8; Sep 8.', ['TB4:4.5', 'TB4:4.8', 'T0908']);
  A.mc('c4-cleavage-m1', 'c4-cleavage', 'A dark mineral in an intermediate igneous rock breaks along two planes that meet at about 60° and 120°. Which group is it?',
    ['*Amphibole|Double-chain silicate with ~60°/120° cleavage.', 'Pyroxene|Pyroxene cleavages meet near 90°.', 'Biotite|One direction, sheets.', 'Olivine|No cleavage.'], 'Textbook 4.5, 4.7, 4.8.', ['TB4:4.5', 'TB4:4.8'], { media: { kind: 'svg', name: 'cleavage', spec: { type: '2-60', hideCaption: true } } });
  A.mc('c4-cleavage-m2', 'c4-cleavage', 'What causes a mineral to have cleavage?',
    ['*Planes of weaker bonds in its atomic structure|Textbook 4.5: force breaks the weakest links.', 'Heating during formation|Cleavage is structural, not thermal.', 'Trace impurities that also change its color|Color does not control breakage.', 'Its crystal faces|Faces form during growth; cleavage forms when it breaks.'], 'Textbook 4.5.', ['TB4:4.5']);
  A.fill('c4-cleavage-f1', 'c4-cleavage', 'The tendency of a mineral to break along flat, parallel planes of weak bonds is <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['cleavage'], 'Textbook 4.5.', ['TB4:4.5']);
  A.tf('c4-cleavage-t1', 'c4-cleavage', 'A mineral with well-formed flat crystal faces must also have cleavage.', false, 'Quartz grows flat faces but has no cleavage; faces form during growth, cleavage during breakage (textbook 4.5).', ['TB4:4.5']);

  // ---------- 4.4 ----------
  A.section({ id: 'c4s4', ch: 4, n: '4.4', title: 'Atoms, ions, and chemical bonds', srcText: 'Textbook 4.11–4.13 · Rec. Sep 8, Sep 10', src: ['TB4:4.11', 'TB4:4.12', 'TB4:4.13', 'T0908', 'T0910'],
    concepts: [['c4-atoms', 'Atoms, electrons, and ions'], ['c4-bonds', 'Bond types and mineral properties'], ['c4-water', 'Water dissolves and precipitates minerals']] });
  A.cards('c4s4', [
    { id: 'g4-4a', h: 'Atoms and ions', c: ['c4-atoms'], src: ['TB4:4.11', 'T0908'],
      media: [tb(12, 'Ionic bond: an electron transferred from Na to Cl (textbook 4.12)'), tb(45, 'Covalent bond: shared electrons (textbook 4.12)')],
      html: '<p>An atom has a nucleus of <b>protons (+)</b> and <b>neutrons (no charge)</b> surrounded by <b>electrons (−)</b>. The number of protons is the <b>atomic number</b>. Atoms are most stable with a full outer shell: sodium (1 outer electron) tends to <b>give</b> one; chlorine (7 outer electrons) tends to <b>take</b> one. An atom that gains or loses electrons is an <b>ion</b>: positive ions are <b>cations</b>, negative ions are <b>anions</b>.</p>' },
    { id: 'g4-4b', h: 'Four ways atoms hold together', c: ['c4-bonds'], src: ['TB4:4.12', 'T0910'],
      html: '<table><tr><th>Bond</th><th>Mechanism</th><th>Strength</th><th>Examples</th></tr><tr><td>Covalent</td><td>Atoms <b>share</b> electrons</td><td>Strongest</td><td>Diamond; Si–O inside a tetrahedron; water molecule</td></tr><tr><td>Ionic</td><td>Electron <b>transferred</b>; opposite charges attract</td><td>Moderate</td><td>Halite, fluorite</td></tr><tr><td>Metallic</td><td>Electrons shared freely among many atoms</td><td>Low</td><td>Gold, copper (pliable, conduct electricity)</td></tr><tr><td>Intermolecular</td><td>Weak attraction between molecules or sheets</td><td>Lowest</td><td>Between sheets of mica, clay, graphite</td></tr></table><p><b>Diamond vs. graphite</b> (Sep 10): both are pure carbon. Diamond\'s carbon atoms form a 3-D covalent framework; hardest mineral (10). Graphite has strong covalent sheets held by weak intermolecular forces, so sheets slide; soft enough for pencils.</p>',
      media: [tb(14, 'Diamond: 3-D covalent framework (textbook 4.12)'), tb(44, 'Graphite: strong sheets, weak connections (textbook 4.12)')],
      traps: ['Saying diamond and graphite differ in composition; they differ in arrangement and bonding.'] },
    { id: 'g4-4c', h: 'Water, dissolving, and ice (textbook 4.13)', c: ['c4-water'], src: ['TB4:4.13'],
      html: '<p>A water molecule is <b>polar</b>: the oxygen side is slightly negative, the hydrogen side slightly positive. That polarity pulls Na⁺ and Cl⁻ ions out of a halite crystal, so halite <b>dissolves</b>. When salty water <b>evaporates</b>, the ions become concentrated and bond again, so halite <b>precipitates</b>. Ice is a mineral; its hydrogen-bonded structure spaces molecules farther apart than in liquid water, so <b>ice is less dense and floats</b>. <span class="small muted">(Textbook section; not discussed in the supplied recordings.)</span></p>' }
  ]);
  A.mc('c4-atoms-m1', 'c4-atoms', 'A sodium atom gives one electron to a chlorine atom. What results?',
    ['*A positive sodium ion (cation) and a negative chloride ion (anion) that attract|Textbook 4.11–4.12.', 'Two neutral atoms that share a pair of electrons between them equally|That describes covalent bonding.', 'A negative sodium ion and a positive chlorine ion|Losing an electron makes sodium positive.', 'A metallic bond with free electrons|Metallic bonds share electrons among many metal atoms.'], 'Textbook 4.11–4.12; Sep 8.', ['TB4:4.11', 'TB4:4.12', 'T0908']);
  A.fill('c4-atoms-f1', 'c4-atoms', 'An atom that has gained or lost electrons and therefore carries an electrical charge is an <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['ion'], 'Textbook 4.11.', ['TB4:4.11']);
  A.fill('c4-atoms-f2', 'c4-atoms', 'The number of protons in an atom\'s nucleus is its atomic <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['number'], 'Textbook 4.11.', ['TB4:4.11']);
  A.mc('c4-bonds-m1', 'c4-bonds', 'Diamond and graphite are both pure carbon. Why is diamond extremely hard while graphite is soft enough to write with?',
    ['*Diamond is a 3-D covalent framework; graphite is covalent sheets held by weak forces|Textbook 4.12 C; Sep 10.',
     'Diamond packs more carbon into each atom than graphite does, so it is denser|Both are carbon; the arrangement differs.', 'Graphite is metallic and diamond is ionic|Neither statement matches the textbook.', 'Graphite is not a mineral|Graphite is a native-element mineral.'], 'Textbook 4.12 C.', ['TB4:4.12', 'T0910']);
  A.match('c4-bonds-x1', 'c4-bonds', 'Match each bond type to its mechanism.', [
    ['Covalent', 'Atoms share electrons'], ['Ionic', 'Electron transferred; opposite charges attract'], ['Metallic', 'Electrons move freely among many atoms'], ['Intermolecular force', 'Weak attraction between molecules or sheets']], 'Textbook 4.12.', ['TB4:4.12']);
  A.mc('c4-bonds-m2', 'c4-bonds', 'Mica is strongly bonded within its sheets but peels apart easily. Which bond explains the easy peeling?',
    ['*Weak intermolecular forces between the sheets|Textbook 4.12 table: bonds between sheets of mica are the weakest type.', 'Strong covalent bonds that link the sheets together|Strong bonds would resist peeling.', 'Metallic bonds within the sheets|Mica is not metallically bonded.', 'Ionic bonds that dissolve in air|Air does not dissolve mica.'], 'Textbook 4.12; Sep 8 and 10.', ['TB4:4.12', 'T0910']);
  A.mc('c4-water-m1', 'c4-water', 'Why does halite dissolve in water?',
    ['*Polar water molecules pull the Na⁺ and Cl⁻ ions apart|Textbook 4.13.', 'Water breaks the covalent bonds inside each sodium and chloride ion|Halite is ionically bonded.', 'Halite is less dense than water, so its grains float apart|Density is not the mechanism.', 'Water heats the salt until it melts|Dissolving is not melting.'], 'Textbook 4.13.', ['TB4:4.13']);
  A.tf('c4-water-t1', 'c4-water', 'Ice floats because its crystal structure holds water molecules farther apart than in liquid water.', true, 'Textbook 4.13: hydrogen bonds arrange molecules farther apart, so ice is less dense than water.', ['TB4:4.13']);

  // ---------- 4.5 ----------
  A.section({ id: 'c4s5', ch: 4, n: '4.5', title: 'Silicate minerals', srcText: 'Textbook 4.6–4.8, 4.10 · Rec. Sep 8, Sep 10', src: ['TB4:4.6', 'TB4:4.7', 'TB4:4.8', 'TB4:4.10', 'T0908', 'T0910'],
    concepts: [['c4-abundance', 'Why silicates dominate'], ['c4-tetra', 'The silicon-oxygen tetrahedron'], ['c4-silstruct', 'Five silicate structures'], ['c4-commonsil', 'Common light and dark silicates']] });
  A.cards('c4s5', [
    { id: 'g4-5a', h: 'Why most minerals are silicates', c: ['c4-abundance'], src: ['TB4:4.6', 'TB4:4.10', 'T0910'],
      html: '<p><b>Oxygen</b> is the most abundant element in the crust and <b>silicon</b> is second; together they make up about <b>three-quarters of the crust by weight</b> (textbook: 74%). The next most abundant are aluminum, iron, calcium, sodium, potassium, and magnesium. Because O and Si are so common and bond readily, <b>silicates are the largest and most common mineral family</b>: over 90% of the minerals in the crust. Everything else (carbonates, oxides, sulfides, sulfates, halides, native elements) is grouped as <b>non-silicates</b>.</p><p>For the <b>whole Earth</b>, iron is far more abundant than in the crust because the core is iron-nickel.</p>',
      traps: ['Saying silicon is the most abundant element in the crust; oxygen is.'] },
    { id: 'g4-5b', h: 'The building block: SiO₄ tetrahedron', c: ['c4-tetra'], src: ['TB4:4.7', 'T0910'],
      html: '<p>One small <b>silicon</b> atom sits in the center of <b>four oxygen</b> atoms arranged as a <b>tetrahedron</b>. Charge check (the professor did this on Sep 10): Si is +4, four O are −2 each (−8), so the unit carries a net <b>−4</b> charge. It must bond to <b>cations</b> (Fe, Mg, Ca, Na, K, Al) or share oxygens with other tetrahedra to become neutral.</p>', media: tb(9, 'Silicon-oxygen tetrahedron (textbook 4.7)') },
    { id: 'g4-5c', h: 'How tetrahedra link; and what that does to cleavage', c: ['c4-silstruct'], src: ['TB4:4.7', 'T0908', 'T0910'],
      html: '<table><tr><th>Structure</th><th>Oxygens shared</th><th>Example</th><th>Cleavage</th></tr><tr><td>Independent (isolated) tetrahedra</td><td>0</td><td><b>Olivine</b></td><td>None (bonds similar in all directions)</td></tr><tr><td>Single chains</td><td>2</td><td><b>Pyroxene</b></td><td>Two, near 90°</td></tr><tr><td>Double chains</td><td>2 and 3 (alternating)</td><td><b>Amphibole</b></td><td>Two, ~60°/120°</td></tr><tr><td>Sheets</td><td>3</td><td><b>Micas</b>, clays</td><td>One (sheets)</td></tr><tr><td>Framework</td><td>All 4</td><td><b>Quartz</b>, feldspars</td><td>Quartz: none; feldspar: two</td></tr></table>',
      media: [{ kind: 'svg', name: 'silicate', spec: { type: 'isolated', label: 'Independent tetrahedra' } }, { kind: 'svg', name: 'silicate', spec: { type: 'single', label: 'Single chains' } }, { kind: 'svg', name: 'silicate', spec: { type: 'double', label: 'Double chains' } }, { kind: 'svg', name: 'silicate', spec: { type: 'sheet', label: 'Sheets' } }, { kind: 'svg', name: 'silicate', spec: { type: 'framework', label: 'Framework' } }],
      traps: ['“Framework = no cleavage” is only true for quartz; feldspar is a framework silicate with two cleavages.'] },
    { id: 'g4-5d', h: 'Common light (felsic) and dark (mafic) silicates', c: ['c4-commonsil'], src: ['TB4:4.8', 'T0910'],
      html: '<p><b>Light / felsic</b> (upper continental crust): <b>quartz</b> (SiO₂, hardness 7, no cleavage, conchoidal fracture, clear to many colors), <b>K-feldspar</b> (pink to cream, two cleavages), <b>plagioclase</b> (white to gray; Na-rich to Ca-rich; straight striations), <b>muscovite</b> (clear-silvery mica, one cleavage).</p><p><b>Dark / mafic</b> (Mg- and Fe-rich; oceanic crust, mantle, lower crust): <b>amphibole</b> (long crystals, ~60/120° cleavage), <b>pyroxene</b> (stubby crystals, ~90° cleavage), <b>olivine</b> (olive green, no cleavage; most common mineral of the upper mantle), <b>garnet</b> (often deep red, 12-sided), <b>biotite</b> (black mica, one cleavage).</p><p><b>Clay minerals</b> are sheet silicates with weaker bonds; they mostly form by weathering.</p>',
      media: [tp('ch4-biotite-sheets', 'Mica peels into sheets: one direction of cleavage (textbook 4.5)')] }
  ]);
  A.mc('c4-abundance-m1', 'c4-abundance', 'Why are silicate minerals the largest and most common mineral family in Earth\'s crust?',
    ['*Oxygen and silicon are the two most abundant elements in the crust and bond together readily|Textbook 4.6/4.10; Sep 10: about three-quarters of the crust by weight.',
     'Silicon is the most abundant element in the universe, so every planet is mostly silicate|Hydrogen and helium dominate the universe.', 'Silicates are the only minerals that form from magma|Oxides and sulfides can also form from magma.', 'Iron is rare in the crust|Iron is fourth most abundant in the crust.'], 'Textbook 4.6 and 4.10.', ['TB4:4.6', 'TB4:4.10', 'T0910']);
  A.fill('c4-abundance-f1', 'c4-abundance', 'The most abundant element in Earth\'s crust by weight is <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['oxygen', 'O'], 'Textbook 4.10; Sep 8 and 10.', ['TB4:4.10', 'T0910']);
  A.mc('c4-abundance-m2', 'c4-abundance', 'Compared with the crust, why is iron much more abundant in the whole Earth?',
    ['*The core is mostly iron and nickel|Textbook 4.10: iron and nickel are especially abundant in the core.', 'Iron rusts and accumulates at the surface|Surface rusting does not change whole-Earth abundance.', 'The crust is made mostly of iron oxides|The crust is dominated by silicates.', 'Iron is created in the mantle by radioactive decay|Decay does not create iron in quantity.'], 'Textbook 4.10.', ['TB4:4.10']);
  A.mc('c4-tetra-m1', 'c4-tetra', 'What is the net electrical charge on a single silicon-oxygen tetrahedron (one Si⁴⁺ and four O²⁻)?',
    ['*−4|+4 + 4(−2) = −4. The professor worked this on Sep 10.', '0|It is not neutral on its own.', '+4|The four oxygens outweigh the silicon.', '−8|That counts only the oxygens.'], 'Sep 10 recording; textbook 4.7.', ['T0910', 'TB4:4.7']);
  A.mc('c4-tetra-m2', 'c4-tetra', 'How do isolated tetrahedra in olivine become an electrically neutral mineral?',
    ['*They bond to positively charged metal cations such as Fe²⁺ and Mg²⁺|Textbook 4.7–4.8: independent tetrahedra linked by iron or magnesium.', 'They share all four of their oxygens with neighboring tetrahedra|That is a framework silicate (quartz).', 'They bond to chlorine anions|Anions would add negative charge.', 'They do not need to become neutral|Minerals are neutral overall.'], 'Textbook 4.7–4.8.', ['TB4:4.7', 'TB4:4.8']);
  A.fill('c4-tetra-f1', 'c4-tetra', 'The four-sided pyramid formed by one silicon atom surrounded by four oxygen atoms is called a silicon-oxygen <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['tetrahedron', 'tetrahedra'], 'Textbook 4.7.', ['TB4:4.7']);
  A.parts('c4-silstruct-p1', 'c4-silstruct', 'Identify the silicate structure in each numbered diagram (top-view sketches).', [
    { label: '1', options: ['Independent tetrahedra', 'Single chains', 'Double chains', 'Sheets', 'Framework'], a: 'Independent tetrahedra', why: 'No shared oxygens.' },
    { label: '2', options: ['Independent tetrahedra', 'Single chains', 'Double chains', 'Sheets', 'Framework'], a: 'Single chains', why: 'Each tetrahedron shares two oxygens in a line.' },
    { label: '3', options: ['Independent tetrahedra', 'Single chains', 'Double chains', 'Sheets', 'Framework'], a: 'Sheets', why: 'Three oxygens shared in a continuous 2-D sheet.' }],
    'Textbook 4.7 B.', ['TB4:4.7'], { media: [{ kind: 'svg', name: 'silicate', spec: { type: 'isolated', label: '1' } }, { kind: 'svg', name: 'silicate', spec: { type: 'single', label: '2' } }, { kind: 'svg', name: 'silicate', spec: { type: 'sheet', label: '3' } }], mk: 'inv' });
  A.match('c4-silstruct-x1', 'c4-silstruct', 'Match each silicate structure to its representative mineral.', [
    ['Independent tetrahedra', 'Olivine'], ['Single chains', 'Pyroxene'], ['Double chains', 'Amphibole'], ['Sheets', 'Mica'], ['Framework (only Si–O)', 'Quartz']], 'Textbook 4.7; Sep 8 and 10.', ['TB4:4.7', 'T0910']);
  A.mc('c4-silstruct-m1', 'c4-silstruct', 'Quartz and feldspar are both framework silicates. Why does feldspar have cleavage but quartz does not?',
    ['*Feldspar has other elements that create weaker planes; quartz is all strong Si–O bonds|Textbook 4.7 B.5.', 'Quartz is a sheet silicate|Quartz is a framework silicate.', 'Feldspar shares no oxygens between its tetrahedra, so it splits between them|Feldspar is a framework (all four shared).', 'Cleavage depends only on color|Cleavage depends on bonding.'], 'Textbook 4.7.', ['TB4:4.7']);
  A.mc('c4-silstruct-m2', 'c4-silstruct', 'In a single-chain silicate, why does the mineral cleave parallel to the chains rather than across them?',
    ['*The chains themselves are strongly bonded; bonds between chains are weaker|Textbook 4.7 B.2.', 'The chains are weaker than the bonds between them, so they snap across|Reversed.', 'Single chains have no metal atoms|Cations link the chains.', 'Cleavage always runs perpendicular to chains|The textbook says parallel.'], 'Textbook 4.7.', ['TB4:4.7']);
  A.mc('c4-commonsil-m1', 'c4-commonsil', 'A green, glassy mineral with no cleavage dominates a chunk of rock brought up from the mantle by a volcano. It is most likely:',
    ['*Olivine|Olive green, no cleavage, most common mineral of the upper mantle.', 'Muscovite|Clear-silvery mica with one cleavage.', 'Quartz|Quartz is not the typical mantle mineral.', 'K-feldspar|Pink to cream with two cleavages; a crustal mineral.'], 'Textbook 4.8 and 4.10.', ['TB4:4.8', 'TB4:4.10']);
  A.match('c4-commonsil-x1', 'c4-commonsil', 'Sort each mineral into light (felsic) or dark (mafic) silicates.', [
    ['Quartz', 'Light / felsic'], ['Plagioclase (Na-rich)', 'Light / felsic'], ['Muscovite', 'Light / felsic'], ['Olivine', 'Dark / mafic'], ['Pyroxene', 'Dark / mafic'], ['Biotite', 'Dark / mafic']], 'Textbook 4.8 A–B.', ['TB4:4.8']);
  A.fill('c4-commonsil-f1', 'c4-commonsil', 'Dark silicate minerals rich in magnesium and iron, such as olivine and pyroxene, are called <u>&nbsp;&nbsp;&nbsp;&nbsp;</u> minerals.', ['mafic', 'ferromagnesian'], 'Textbook 4.8 B; Sep 10 (“ma” = magnesium, “fic” = iron).', ['TB4:4.8', 'T0910']);
  A.fill('c4-commonsil-f2', 'c4-commonsil', 'Light-colored silicate minerals rich in feldspar and silica, such as quartz and K-feldspar, are called <u>&nbsp;&nbsp;&nbsp;&nbsp;</u> minerals.', ['felsic', 'nonferromagnesian'], 'Textbook 4.8 A.', ['TB4:4.8']);

  // ---------- 4.6 ----------
  A.section({ id: 'c4s6', ch: 4, n: '4.6', title: 'Non-silicate minerals and where minerals occur', srcText: 'Textbook 4.6, 4.9, 4.10 · Rec. Sep 8, Sep 10', src: ['TB4:4.6', 'TB4:4.9', 'TB4:4.10', 'T0908', 'T0910'],
    concepts: [['c4-nonsil', 'Non-silicate mineral families'], ['c4-whereminerals', 'Minerals in Earth\'s layers and sands']] });
  A.cards('c4s6', [
    { id: 'g4-6a', h: 'Non-silicate families: read the formula', c: ['c4-nonsil'], src: ['TB4:4.6', 'TB4:4.9', 'T0910'],
      html: '<table><tr><th>Family</th><th>Key chemistry</th><th>Examples</th></tr><tr><td>Carbonates</td><td>Metal + CO₃</td><td>Calcite CaCO₃ (fizzes in HCl; limestone), dolomite CaMg(CO₃)₂</td></tr><tr><td>Oxides</td><td>Metal + O</td><td>Hematite Fe₂O₃ (red streak), magnetite Fe₃O₄ (magnetic)</td></tr><tr><td>Sulfides</td><td>Metal + S (no oxygen)</td><td>Pyrite FeS₂ (“fool\'s gold”), galena PbS (heavy, cubic), chalcopyrite</td></tr><tr><td>Sulfates</td><td>Metal + SO₄ (sulfur bonded to oxygen)</td><td>Gypsum (scratched by fingernail; wallboard)</td></tr><tr><td>Halides</td><td>Metal + Cl or F</td><td>Halite NaCl, fluorite</td></tr><tr><td>Native elements</td><td>One element</td><td>Gold, copper, sulfur, diamond, graphite</td></tr></table><p>Sep 10 tip: if the formula has no Si-O group, it is a non-silicate; sulfi<b>d</b>e = metal + sulfur; sulf<b>ate</b> = metal + sulfur <b>and oxygen</b>.</p>',
      media: tb(15, 'Carbonate minerals (textbook 4.9)'), traps: ['Sulfide vs. sulfate: look for oxygen (SO₄).', 'Calcite vs. dolomite: dolomite may not fizz unless powdered.'] },
    { id: 'g4-6b', h: 'Which minerals where', c: ['c4-whereminerals'], src: ['TB4:4.10', 'T0908', 'T0910'],
      html: '<ul><li><b>Continental crust:</b> much of it granite-like; quartz and feldspar; sedimentary cover with quartz, clays, feldspar, carbonates.</li><li><b>Oceanic crust:</b> basalt and gabbro; plagioclase, pyroxene, olivine.</li><li><b>Upper mantle:</b> mostly olivine and pyroxene.</li><li><b>Lower mantle:</b> high-pressure Fe-Mg silicates and oxides.</li><li><b>Core:</b> iron and nickel (outer molten, inner solid).</li></ul><p>Sep 10 example: sand at the <b>Mississippi River mouth</b> is mostly <b>silicate</b> grains (quartz, feldspar, etc.) carried from the Rocky Mountains, while <b>white Florida beach sand</b> includes <b>shell fragments; carbonate</b>, a non-silicate.</p>' }
  ]);
  A.match('c4-nonsil-x1', 'c4-nonsil', 'Match each mineral to its family.', [
    ['Calcite, CaCO₃', 'Carbonate'], ['Hematite, Fe₂O₃', 'Oxide'], ['Pyrite, FeS₂', 'Sulfide'], ['Gypsum, CaSO₄·2H₂O', 'Sulfate'], ['Halite, NaCl', 'Halide'], ['Gold, Au', 'Native element']], 'Textbook 4.6 and 4.9; Sep 10.', ['TB4:4.6', 'TB4:4.9', 'T0910']);
  A.mc('c4-nonsil-m1', 'c4-nonsil', 'A student says gypsum and pyrite belong to the same family because both contain sulfur. What is wrong?',
    ['*Gypsum is a sulfate (S with O); pyrite is a sulfide (S with a metal)|Textbook 4.6.', 'Pyrite contains no sulfur|Pyrite is FeS₂.', 'Gypsum is a silicate|Gypsum has no Si–O.', 'Both are halides, since sulfur behaves like chlorine in minerals|Halides contain Cl or F.'], 'Textbook 4.6; Sep 10.', ['TB4:4.6', 'T0910']);
  A.mc('c4-nonsil-m2', 'c4-nonsil', 'A brass-yellow, metallic mineral forms cubes with striated faces. Which is it?',
    ['*Pyrite|Pale bronze to brass-yellow cubes with striations; “fool\'s gold.”', 'Galena|Metallic gray cubes.', 'Gypsum|Soft, white to clear.', 'Hematite|Red streak; not brassy.'], 'Textbook 4.9.', ['TB4:4.9']);
  A.fill('c4-nonsil-f1', 'c4-nonsil', 'Minerals such as calcite and dolomite that contain a metal bonded to a CO₃ group are <u>&nbsp;&nbsp;&nbsp;&nbsp;</u> minerals.', ['carbonate', 'carbonates'], 'Textbook 4.9.', ['TB4:4.9']);
  A.fill('c4-nonsil-f2', 'c4-nonsil', 'Iron-oxide mineral with a consistent reddish streak: <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['hematite', 'haematite'], 'Textbook 4.3 and 4.9.', ['TB4:4.9']);
  A.mc('c4-whereminerals-m1', 'c4-whereminerals', 'White beach sand in Florida contains abundant shell fragments, while sand at the mouth of the Mississippi River is mostly quartz and other silicate grains. What mainly explains the difference, according to the Sep 10 lecture?',
    ['*River grains are eroded silicates; Florida sand includes carbonate shell bits|Sep 10 recording.', 'Florida sand is volcanic glass|Nothing indicates volcanic sand.', 'Mississippi sand formed by evaporation of salty water in the river delta|River sand is transported sediment.', 'Both are identical silicate sands in different light|The professor contrasted their compositions.'], 'Sep 10 recording.', ['T0910']);
  A.mc('c4-whereminerals-m2', 'c4-whereminerals', 'Which mineral set best represents the upper mantle?',
    ['*Olivine and pyroxene|Textbook 4.10.', 'Quartz and K-feldspar|Continental crust.', 'Calcite and dolomite|Sedimentary carbonates.', 'Iron and nickel metal|The core.'], 'Textbook 4.10.', ['TB4:4.10']);
})((typeof window !== 'undefined' ? window : globalThis).L);
