/* Chapter 5; Igneous Environments. Evidence: textbook 5.1–5.13 (5.14–5.15 partial), Sep 10 and Sep 15 recordings,
   classroom photo of the projected classification chart (IMG_5737). The Sep 15 recording reaches the P-T melting graphs and
   Bowen's reaction series (5.5–5.8); lecture coverage of 5.9–5.13 is unconfirmed in the supplied recordings. */
(function (L) {
  'use strict';
  var A = L.A;
  function tb(n, cap) { return { kind: 'img', src: 'assets/img/tb45/figure-' + (n < 10 ? '0' + n : n) + '.jpg', cap: cap, alt: cap }; }
  function tp(name, cap) { return { kind: 'img', src: 'assets/img/tb/' + name + '.jpg', cap: cap, alt: cap }; }
  function pt(sp) { return { kind: 'svg', name: 'pt', spec: sp }; }
  var LATE = '<p class="small muted">Textbook section. The supplied recordings end at Bowen\'s reaction series (Sep 15), so how much of this was covered in class is unconfirmed; the Sep 22 announcement puts all of Chapter 5 in Exam 1 scope.</p>';

  // ---------- 5.1 Textures ----------
  A.section({ id: 'c5s1', ch: 5, n: '5.1', title: 'Igneous textures and what they record', srcText: 'Textbook 5.1 · Rec. Sep 10, Sep 15', src: ['TB5:5.1', 'T0910', 'T0915'],
    concepts: [['c5-grain', 'Grain size records cooling rate'], ['c5-voltex', 'Porphyritic, vesicular, glassy, welded, breccia']] });
  A.cards('c5s1', [
    { id: 'g5-1a', h: 'Grain size is a cooling clock', c: ['c5-grain'], src: ['TB5:5.1', 'TB5:5.8'],
      html: '<p>Texture = the sizes, shapes, and arrangement of the pieces. The first question is always: <b>can I see the crystals without a lens?</b></p><table><tr><th>Term</th><th>What you see</th><th>What it records</th></tr><tr><td><b>Phaneritic</b> (coarse)</td><td>Crystals visible to the unaided eye</td><td>Slow cooling at depth</td></tr><tr><td><b>Aphanitic</b> (fine)</td><td>Crystals too small to see; may include ash or glass</td><td>Fast cooling at or near the surface</td></tr><tr><td><b>Pegmatite</b></td><td>Crystals centimeters to meters long</td><td>Water-rich magma lets atoms migrate far and fast; forms at moderate to deep levels, near chamber sides and top</td></tr><tr><td><b>Glassy</b></td><td>No crystals at all</td><td>Cooled too fast for crystals to form</td></tr></table><p>Textbook 5.8 shows the same felsic minerals as coarse granite (slow), medium granitic rock (medium), and fine rhyolite (very fast). Same ingredients, different cooling history.</p>',
      media: [tp('ch5-phaneritic', 'Phaneritic: crystals visible (textbook 5.1)'), tp('ch5-aphanitic', 'Aphanitic: crystals too small to see (textbook 5.1)'), tp('ch5-pegmatite-tex', 'Pegmatite: very large crystals (textbook 5.1)')],
      traps: ['Assuming a fine-grained rock must be mafic. Grain size tells cooling rate; color and minerals tell composition.', 'Thinking pegmatite means "cooled extra slowly." The textbook ties it to abundant dissolved water.'] },
    { id: 'g5-1b', h: 'Special textures and their settings', c: ['c5-voltex'], src: ['TB5:5.1', 'TB5:5.3'],
      html: '<ul><li><b>Porphyritic</b>: larger crystals (<b>phenocrysts</b>) in a finer matrix. Two-stage history: slow growth in a subsurface chamber, then rapid cooling after rising to near or on the surface.</li><li><b>Vesicular</b>: holes (<b>vesicles</b>) left by gas bubbles. Bubbles form only at <b>low pressure</b>, on or very near the surface. Most volcanic ash is <b>broken vesicle walls</b>.</li><li><b>Welded</b>: hot ash and pumice compacted by overlying material into flattened lenses. Typical of <b>pyroclastic flows</b> (hot when deposited). Ash that fell from a column cooled first, so it is usually <b>nonwelded</b>.</li><li><b>Volcanic breccia</b>: angular fragments in finer matrix; from explosions, lava that breaks while flowing, or volcanic mudflows and landslides.</li></ul>',
      media: [tp('ch5-porphyritic', 'Porphyritic: phenocrysts in a fine matrix (textbook 5.1)'), tp('ch5-vesicular', 'Vesicular: gas holes (textbook 5.1)'), tp('ch5-welded', 'Welded: flattened lenses (textbook 5.1)')],
      traps: ['Calling a porphyritic rock "two magmas." It is one magma with a two-stage cooling history.', 'Welded vs. nonwelded: the difference is how hot the ash was when buried, not its composition.'] }
  ]);
  A.mc('c5-grain-m1', 'c5-grain', 'Two rocks have the same minerals (quartz, K-feldspar, a little biotite). Rock X has crystals 5–10 mm across; rock Y has crystals you cannot see without a microscope. What is the best interpretation?',
    ['*Same composition; X cooled slowly at depth and Y cooled quickly at or near the surface|Grain size records cooling rate; minerals record composition.', 'X is felsic and Y is mafic|Identical minerals means identical composition class.', 'Y is older, so its crystals have shrunk|Crystals do not shrink with age.', 'X formed in a thick lava flow at the surface and Y in a deep, slowly cooled pluton|Reversed: slow cooling makes the big crystals.'], 'Textbook 5.1 and 5.8 (granite vs. rhyolite cooling histories).', ['TB5:5.1', 'TB5:5.8']);
  A.mc('c5-grain-m2', 'c5-grain', 'What does the textbook say allows pegmatite crystals to grow centimeters to meters long?',
    ['*Abundant dissolved water lets atoms migrate farther and faster|Textbook 5.1 B.9.', 'Extremely rapid cooling at the surface|Rapid cooling gives fine grains or glass.', 'Very high pressure at depth squeezing many small crystals together into large ones|Crystals are not fused by pressure.', 'Gas bubbles that expand the crystals|Bubbles make vesicles, not large crystals.'], 'Textbook 5.1.', ['TB5:5.1']);
  A.fill('c5-grain-f1', 'c5-grain', 'An igneous rock whose crystals are large enough to see with the unaided eye is described as <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['phaneritic', 'coarse-grained', 'coarse grained', 'coarse', 'coarsely crystalline'], 'Textbook 5.1.', ['TB5:5.1']);
  A.fill('c5-grain-f2', 'c5-grain', 'An igneous rock whose crystals are too small to see without magnification is described as <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['aphanitic', 'fine-grained', 'fine grained', 'fine'], 'Textbook 5.1.', ['TB5:5.1']);
  A.tf('c5-grain-t1', 'c5-grain', 'A very fine-grained igneous rock must have a mafic composition.', false, 'Grain size reflects cooling rate. Rhyolite is fine-grained and felsic (textbook 5.1–5.2).', ['TB5:5.1', 'TB5:5.2']);
  A.mc('c5-voltex-m1', 'c5-voltex', 'An andesite contains 5-mm feldspar crystals scattered in a gray matrix with no visible grains. Which history fits best?',
    ['*Crystals grew slowly in a magma chamber; then the magma rose and the rest cooled quickly|Porphyritic texture = two-stage cooling (textbook 5.1 B.8).', 'The whole rock cooled slowly deep underground|Then the matrix would also be coarse.', 'Two unrelated rocks were cemented together|The phenocrysts grew from the same magma.', 'Gas bubbles in the lava were later filled with feldspar crystals after the eruption ended|That describes filled vesicles, not phenocrysts.'], 'Textbook 5.1 and 5.6.', ['TB5:5.1', 'TB5:5.6'], { media: tp('ch5-porphyritic', 'Specimen') });
  A.mc('c5-voltex-m2', 'c5-voltex', 'Why do vesicles form in lava but not in magma that crystallizes 10 km underground?',
    ['*Dissolved gases come out as bubbles only at low pressure, on or near the surface|Textbook 5.1 B.1.', 'Deep magma contains no dissolved gas at all; gas enters only after eruption|Deep magma does contain dissolved gas; pressure keeps it dissolved.', 'Crystals fill every hole at depth|Holes do not form in the first place.', 'Vesicles are made by erosion after the rock is exposed|Vesicles are primary gas bubbles.'], 'Textbook 5.1 and 5.7.', ['TB5:5.1', 'TB5:5.7']);
  A.mc('c5-voltex-m3', 'c5-voltex', 'Deposit P contains flattened, lens-shaped pumice fused into hard rock. Deposit Q is loose, weakly consolidated ash and pumice. Which pairing of origins is most consistent with the textbook?',
    ['*P from a hot pyroclastic flow; Q from ash that fell out of an eruption column|Hot burial welds; ash that cooled in the air stays nonwelded.', 'P from ash that fell out of a column; Q from a hot pyroclastic flow|Reversed.', 'Both from lava flows|Lava flows do not make ash deposits.', 'P is metamorphic and Q is sedimentary|Both are volcanic tuffs.'], 'Textbook 5.1 B.6–7 and 5.3.', ['TB5:5.1', 'TB5:5.3'], { media: [tp('ch5-welded-tuff', 'Deposit P'), tp('ch5-nonwelded-tuff', 'Deposit Q')] });
  A.match('c5-voltex-x1', 'c5-voltex', 'Match each texture to the process that makes it.', [
    ['Porphyritic', 'Slow growth at depth, then rapid cooling'], ['Vesicular', 'Gas bubbles at low pressure'], ['Glassy', 'Cooling too fast for crystals'], ['Welded', 'Hot ash compacted under its own load'], ['Volcanic breccia', 'Angular fragments from explosion, breaking flow, or mudflow']], 'Textbook 5.1.', ['TB5:5.1']);
  A.fill('c5-voltex-f1', 'c5-voltex', 'The large crystals set in a finer matrix in a porphyritic rock are called <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['phenocrysts', 'phenocryst'], 'Textbook 5.1.', ['TB5:5.1']);
  A.fill('c5-voltex-f2', 'c5-voltex', 'Small holes left by gas bubbles in a volcanic rock are called <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['vesicles', 'vesicle'], 'Textbook 5.1.', ['TB5:5.1']);

  // ---------- 5.2 Classification ----------
  A.section({ id: 'c5s2', ch: 5, n: '5.2', title: 'Classifying igneous rocks', srcText: 'Textbook 5.2–5.3 · class chart photo · Rec. Sep 10, Sep 15', src: ['TB5:5.2', 'TB5:5.3', 'IMG5737', 'T0910', 'T0915'],
    concepts: [['c5-classify', 'Composition × grain size = rock name'], ['c5-silica', 'Silica content and minerals across the chart'], ['c5-special', 'Obsidian, pumice, scoria, tuff, breccia, pegmatite']] });
  A.cards('c5s2', [
    { id: 'g5-2a', h: 'The two-axis chart', c: ['c5-classify', 'c5-silica'], src: ['TB5:5.2', 'TB5:5.3', 'IMG5737'],
      html: '<p>Name an igneous rock with two questions: <b>what is it made of</b> (column) and <b>how big are the crystals</b> (row). This is the chart projected in class (your photo IMG_5737 shows textbook figure 05.03.b1), redrawn:</p>' +
        '<div data-hook="igclass"></div>' +
        '<table><tr><th></th><th>Felsic</th><th>Intermediate</th><th>Mafic</th><th>Ultramafic</th></tr><tr><td>Coarse (intrusive)</td><td>Granite</td><td>Diorite</td><td>Gabbro</td><td>Peridotite</td></tr><tr><td>Fine (volcanic)</td><td>Rhyolite</td><td>Andesite</td><td>Basalt</td><td>Komatiite (rare, very old ultramafic lava)</td></tr><tr><td>Silica</td><td>~70–77%</td><td>~60%</td><td>~44–50%</td><td>lowest</td></tr><tr><td>Key minerals</td><td>Quartz, K-feldspar, Na-plagioclase, biotite, muscovite</td><td>Plagioclase, amphibole, biotite ± pyroxene</td><td>Ca-plagioclase, pyroxene ± olivine</td><td>Olivine, pyroxene</td></tr></table>' +
        '<p>Left to right: <b>silica drops</b>, <b>Mg, Fe, Ca rise</b>, the rock <b>darkens</b>. The upper mantle is peridotite. Granodiorite sits between granite and diorite.</p>',
      media: [{ kind: 'svg', name: 'igchart', spec: {} }, tb(16, 'Textbook figure 05.03.b1, the chart projected in class (your photo IMG_5737)')],
      traps: ['Andesite vs. basalt: both fine-grained; andesite is intermediate (gray, often with feldspar or amphibole phenocrysts), basalt is mafic (dark gray to black).', 'Gabbro vs. basalt: same composition, different grain size.'] },
    { id: 'g5-2b', h: 'Rocks named for a texture', c: ['c5-special'], src: ['TB5:5.3'],
      html: '<table><tr><th>Rock</th><th>Defining feature</th><th>Usual composition</th></tr><tr><td><b>Obsidian</b></td><td>Shiny volcanic glass</td><td>Mostly felsic (rhyolite)</td></tr><tr><td><b>Pumice</b></td><td>Light-colored, full of vesicles; silica-rich magma traps gas</td><td>Felsic to intermediate</td></tr><tr><td><b>Scoria</b></td><td>Dark or reddish, many vesicles</td><td>Basalt or andesite</td></tr><tr><td><b>Tuff</b></td><td>Ash, pumice, crystals, fragments (welded or nonwelded)</td><td>Mostly felsic to intermediate</td></tr><tr><td><b>Volcanic breccia</b></td><td>Angular fragments in finer matrix</td><td>Almost any</td></tr><tr><td><b>Pegmatite</b></td><td>Crystals &gt; several cm</td><td>Any, but mostly granitic</td></tr></table>',
      media: [tp('ch5-obsidian', 'Obsidian (textbook 5.3)'), tp('ch5-pumice', 'Pumice (textbook 5.3)'), tp('ch5-scoria', 'Scoria (textbook 5.3)')],
      traps: ['Pumice vs. scoria: both vesicular. Pumice is light and felsic; scoria is dark and mafic.', 'Obsidian is dark but felsic. Color misleads for glass.'] }
  ]);
  A.cards('c5s2', [
    { id: 'g5-2c', h: 'Photo lineup: the chart in real rocks', c: ['c5-classify'], src: ['TB5:5.2'],
      html: '<p>Pairs across each row share a composition; only the grain size differs. Look for: visible crystals (coarse) vs. none (fine); light vs. dark overall color; green olivine in ultramafic rock.</p>',
      media: [tp('ch5-granite', 'Granite: coarse, felsic'), tp('ch5-rhyolite', 'Rhyolite: fine, felsic'), tp('ch5-diorite', 'Diorite: coarse, intermediate'), tp('ch5-andesite', 'Andesite: fine, intermediate, with phenocrysts'), tp('ch5-gabbro', 'Gabbro: coarse, mafic'), tp('ch5-basalt', 'Basalt: fine, mafic, vesicular'), tp('ch5-peridotite', 'Peridotite: coarse, ultramafic (olivine)')] }
  ]);
  A.parts('c5-classify-p2', 'c5-classify', 'Name each specimen from its photo (textbook 5.2 specimens, relabeled).', [
    { label: 'Specimen A', options: ['Granite', 'Rhyolite', 'Andesite', 'Gabbro', 'Peridotite'], a: 'Rhyolite', why: 'Light, no visible crystals: fine-grained felsic.' },
    { label: 'Specimen B', options: ['Granite', 'Rhyolite', 'Andesite', 'Gabbro', 'Peridotite'], a: 'Gabbro', why: 'Dark, coarse crystals: coarse mafic.' },
    { label: 'Specimen C', options: ['Granite', 'Rhyolite', 'Andesite', 'Gabbro', 'Peridotite'], a: 'Andesite', why: 'Gray fine matrix with light phenocrysts: intermediate volcanic.' },
    { label: 'Specimen D', options: ['Granite', 'Rhyolite', 'Andesite', 'Gabbro', 'Peridotite'], a: 'Peridotite', why: 'Green olivine crystals: ultramafic.' }],
    'Textbook 5.2 C photographs.', ['TB5:5.2'], { media: [tp('ch5-rhyolite', 'Specimen A'), tp('ch5-gabbro', 'Specimen B'), tp('ch5-andesite', 'Specimen C'), tp('ch5-peridotite', 'Specimen D')] });
  A.mc('c5-special-m3', 'c5-special', 'An outcrop shows angular rock fragments of many sizes set in a finer volcanic matrix. What is it, and which origins are possible?',
    ['*Volcanic breccia; several origins are possible|Textbook 5.1 and 5.3.', 'Pegmatite; from a water-rich magma deep underground|Pegmatite is very coarse crystals, not fragments.', 'Obsidian; from lava that cooled too fast to crystallize|Obsidian is glass without fragments.', 'Welded tuff; from ash that fell from a column and cooled in the air|Air-fall ash is usually nonwelded, and tuff is mostly ash.'], 'Textbook 5.1 A.11, B.2; 5.3.', ['TB5:5.1', 'TB5:5.3'], { media: tp('ch5-breccia', 'Outcrop') });
  A.parts('c5-classify-p1', 'c5-classify', 'Name the rock at each numbered position on the classification chart.', [
    { label: '1', options: ['Granite', 'Diorite', 'Gabbro', 'Rhyolite', 'Andesite', 'Basalt'], a: 'Diorite', why: 'Coarse row, intermediate column.' },
    { label: '2', options: ['Granite', 'Diorite', 'Gabbro', 'Rhyolite', 'Andesite', 'Basalt'], a: 'Rhyolite', why: 'Fine row, felsic column.' },
    { label: '3', options: ['Granite', 'Diorite', 'Gabbro', 'Rhyolite', 'Andesite', 'Basalt'], a: 'Basalt', why: 'Fine row, mafic column.' },
    { label: '4', options: ['Granite', 'Diorite', 'Gabbro', 'Rhyolite', 'Andesite', 'Basalt'], a: 'Gabbro', why: 'Coarse row, mafic column.' }],
    'Textbook 5.2–5.3 chart (shown in class, IMG_5737).', ['TB5:5.3', 'IMG5737'], { media: { kind: 'svg', name: 'igchart', spec: { markers: { 'coarse-1': 1, 'fine-0': 2, 'fine-2': 3, 'coarse-2': 4 }, hide: ['coarse-0', 'coarse-3', 'fine-1', 'fine-3'] } }, mk: 'inv' });
  A.mc('c5-classify-m1', 'c5-classify', 'A dark gray to black rock has no visible crystals except a few green olivine grains, and it has gas holes. What is it?',
    ['*Basalt|Fine-grained, mafic, often vesicular, olivine phenocrysts possible.', 'Gabbro|Gabbro is coarse-grained.', 'Rhyolite|Rhyolite is felsic and light-colored.', 'Diorite|Diorite is coarse and intermediate.'], 'Textbook 5.2 C.6.', ['TB5:5.2'], { media: tp('ch5-basalt', 'Specimen') });
  A.mc('c5-classify-m2', 'c5-classify', 'A coarse-grained rock is roughly half white plagioclase and half black amphibole, with no visible quartz. What is it?',
    ['*Diorite|Coarse, intermediate: plagioclase + amphibole.', 'Granite|Granite is dominated by quartz and feldspar.', 'Andesite|Andesite is the fine-grained equivalent.', 'Peridotite|Peridotite is olivine and pyroxene.'], 'Textbook 5.2 C.3.', ['TB5:5.2'], { media: tp('ch5-diorite', 'Specimen') });
  A.mc('c5-classify-m3', 'c5-classify', 'Which pair has the same composition but different grain size?',
    ['*Granite and rhyolite|Felsic; coarse vs. fine.', 'Granite and gabbro|Both coarse; different compositions.', 'Basalt and andesite|Both fine; different compositions.', 'Diorite and peridotite|Both coarse; different compositions.'], 'Textbook 5.2.', ['TB5:5.2']);
  A.match('c5-classify-x1', 'c5-classify', 'Match each fine-grained (volcanic) rock to its coarse-grained (intrusive) equivalent.', [
    ['Rhyolite', 'Granite'], ['Andesite', 'Diorite'], ['Basalt', 'Gabbro'], ['Komatiite', 'Peridotite']], 'Textbook 5.2–5.3.', ['TB5:5.2', 'TB5:5.3']);
  A.fill('c5-classify-f1', 'c5-classify', 'The coarse-grained ultramafic rock that makes up the upper mantle is <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['peridotite'], 'Textbook 5.2 C.7.', ['TB5:5.2']);
  A.fill('c5-classify-f2', 'c5-classify', 'The fine-grained igneous rock of intermediate composition, named for a South American mountain range, is <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['andesite'], 'Textbook 5.2 C.4.', ['TB5:5.2']);
  A.mc('c5-silica-m1', 'c5-silica', 'Moving from granite to gabbro on the chart, which change occurs?',
    ['*Silica decreases while magnesium, iron, and calcium increase|Textbook 5.3 composition box.', 'Silica increases while the rock gets lighter in color and poorer in iron|Reversed.', 'Grain size decreases from coarse to fine|Both are coarse.', 'Quartz becomes more abundant|Quartz is uncommon in mafic rocks.'], 'Textbook 5.3.', ['TB5:5.3']);
  A.mc('c5-silica-m2', 'c5-silica', 'A rock analysis reports about 60% silica. Which rock pair fits?',
    ['*Andesite or diorite|Intermediate ≈ 60% silica.', 'Granite or rhyolite|Felsic ≈ 70–77%.', 'Basalt or gabbro|Mafic ≈ 44–50%.', 'Peridotite|Ultramafic, lowest silica.'], 'Textbook 5.3.', ['TB5:5.3']);
  A.ms('c5-silica-s1', 'c5-silica', 'Which minerals are dominant in mafic or ultramafic rocks (in at least one of the two)? Select all that apply.',
    ['*Pyroxene|Mafic mineral.', '*Olivine|Mafic mineral; peridotite can be all olivine.', '*Calcium-rich plagioclase|Plagioclase in mafic rocks is Ca-rich.', 'Quartz|Felsic rocks.', 'Potassium feldspar|Felsic rocks.'], 'Textbook 5.3 B.7.', ['TB5:5.3']);
  A.parts('c5-silica-p1', 'c5-silica', 'Identify the mineral range shown by each numbered bar on the chart.', [
    { label: '1', options: ['Quartz', 'Potassium feldspar', 'Amphibole', 'Pyroxene', 'Olivine'], a: 'Quartz', why: 'Felsic end only.' },
    { label: '2', options: ['Quartz', 'Potassium feldspar', 'Amphibole', 'Pyroxene', 'Olivine'], a: 'Amphibole', why: 'Centered on intermediate rocks.' },
    { label: '3', options: ['Quartz', 'Potassium feldspar', 'Amphibole', 'Pyroxene', 'Olivine'], a: 'Olivine', why: 'Mafic to ultramafic end.' }],
    'Textbook 5.3 B chart.', ['TB5:5.3', 'IMG5737'], { media: { kind: 'svg', name: 'igchart', spec: { markers: { 'bar-0': 1, 'bar-4': 2, 'bar-6': 3 }, hide: ['bar-1', 'bar-5'] } }, mk: 'inv' });
  A.mc('c5-special-m1', 'c5-special', 'A light-colored rock is so full of gas holes that it floats in water. Which rock and composition?',
    ['*Pumice, usually felsic to intermediate|Silica-rich magma traps gas.', 'Scoria, usually felsic to intermediate in composition|Scoria is dark and basaltic or andesitic.', 'Obsidian, usually mafic|Obsidian is glass without vesicles and is mostly felsic.', 'Tuff, always mafic|Most tuff is felsic to intermediate.'], 'Textbook 5.3.', ['TB5:5.3'], { media: tp('ch5-pumice', 'Specimen') });
  A.mc('c5-special-m2', 'c5-special', 'Obsidian is black, yet the textbook classifies most of it as felsic. How can that be?',
    ['*It is glass with rhyolite chemistry; the dark color comes from the glass, not mafic minerals|Textbook 5.3.', 'It is really mafic, and the textbook simply uses a different color scale for glassy rocks|The textbook places it in the felsic field.', 'Obsidian contains abundant olivine|It has no or few crystals.', 'All black rocks are felsic|Basalt is black and mafic.'], 'Textbook 5.3 A.1 and B.3.', ['TB5:5.3'], { media: tp('ch5-obsidian', 'Specimen') });
  A.match('c5-special-x1', 'c5-special', 'Match each rock to its defining feature.', [
    ['Obsidian', 'Volcanic glass'], ['Scoria', 'Dark, abundant vesicles'], ['Pumice', 'Light, abundant vesicles'], ['Tuff', 'Consolidated ash and pumice'], ['Pegmatite', 'Crystals larger than several centimeters']], 'Textbook 5.3.', ['TB5:5.3']);
  A.fill('c5-special-f1', 'c5-special', 'A volcanic rock made of ash, pumice, crystals, and fragments, which may be welded or nonwelded, is called <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['tuff'], 'Textbook 5.3.', ['TB5:5.3']);
  A.fill('c5-special-f2', 'c5-special', 'A dark, vesicular volcanic rock of basaltic or andesitic composition is <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['scoria'], 'Textbook 5.3.', ['TB5:5.3']);

  // ---------- 5.3 Heat, temperature, pressure ----------
  A.section({ id: 'c5s3', ch: 5, n: '5.3', title: 'Heat, temperature, and pressure inside Earth', srcText: 'Textbook 5.4 · Rec. Sep 15', src: ['TB5:5.4', 'T0915'],
    concepts: [['c5-heat', 'Where Earth\'s heat comes from and how it moves'], ['c5-gradient', 'Geothermal gradient and interior temperatures']] });
  A.cards('c5s3', [
    { id: 'g5-3a', h: 'Why the interior is still hot', c: ['c5-heat'], src: ['TB5:5.4'],
      html: '<ul><li>Early-Earth events (impacts, core formation) account for only about <b>20%</b> of today\'s internal heat.</li><li>Most comes from <b>radioactive decay</b> of unstable atoms such as uranium and potassium; decay in the <b>mantle</b> supplies most of Earth\'s thermal energy. The textbook describes alpha, beta, and gamma decay.</li><li>Heat moves by <b>conduction</b> (direct contact), <b>radiant transfer</b> (thermal radiation), and <b>convection</b> (flow of a warm, less dense liquid or weak solid). Plate tectonics involves conduction and convection: rising asthenosphere at ridges, cooling lithosphere by conduction, sinking slabs.</li></ul>',
      media: tb(26, 'Temperature and pressure with depth (textbook 5.4)'),
      traps: ['Saying leftover heat from Earth\'s formation is the main source. Radioactive decay dominates.'] },
    { id: 'g5-3b', h: 'Numbers worth carrying', c: ['c5-gradient'], src: ['TB5:5.4', 'T0915'],
      html: '<table><tr><th>Place</th><th>Temperature</th></tr><tr><td>Surface rocks</td><td>~10–35 °C</td></tr><tr><td>Crust gradient</td><td><b>+20–40 °C per km</b> (the geothermal gradient)</td></tr><tr><td>Lower crust</td><td>~900 °C</td></tr><tr><td>Mantle</td><td>~1,400–1,500 °C, yet mostly solid because <b>high pressure</b> keeps it solid</td></tr><tr><td>Core</td><td>~3,000–5,000 °C (hottest)</td></tr></table><p>Sep 15: the professor framed melting as a competition between <b>temperature</b> (drives melting) and <b>pressure</b> (holds atoms in a solid). Pressure is proportional to depth.</p>' }
  ]);
  A.mc('c5-heat-m1', 'c5-heat', 'What supplies most of Earth\'s internal heat today, according to the textbook?',
    ['*Radioactive decay, mostly in the mantle|Textbook 5.4.', 'Heat left over from Earth\'s formation and early impacts|Only about 20%.', 'Friction from plates sliding past each other|Not the main source.', 'Sunlight absorbed by the crust|Solar heat does not reach the deep interior.'], 'Textbook 5.4.', ['TB5:5.4']);
  A.match('c5-heat-x1', 'c5-heat', 'Match each heat-transfer mechanism to an example from the textbook.', [
    ['Conduction', 'New lithosphere cools by contact with cooler rock and seawater'], ['Convection', 'Hot asthenosphere rises beneath a mid-ocean ridge'], ['Radiant transfer', 'A burner warms your hand through the air']], 'Textbook 5.4.', ['TB5:5.4']);
  A.fill('c5-heat-f1', 'c5-heat', 'Heat transfer by the flow of a warm, less dense liquid or weak solid is called <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['convection'], 'Textbook 5.4.', ['TB5:5.4']);
  A.num('c5-gradient-n1', 'c5-gradient', 'Surface rock is 15 °C. Using a geothermal gradient of 25 °C per km, what is the temperature 8 km down? (°C)', 215, 0, '°C', '15 + 25 × 8 = 215 °C. The textbook gives 20–40 °C/km for the crust.', ['TB5:5.4']);
  A.mc('c5-gradient-m1', 'c5-gradient', 'The mantle is about 1,400–1,500 °C, hotter than the ~900 °C lower crust. Why is most of the mantle solid?',
    ['*High pressure at mantle depths keeps the rock solid|Textbook 5.4; Sep 15 temperature-vs-pressure framing.', 'Mantle rocks are made of minerals that cannot melt|Mantle rocks melt under the right conditions.', 'The mantle is kept cool by heat flowing out of it into the core|The core is hotter than the mantle.', 'Water in the mantle freezes the rock|Water lowers melting temperatures.'], 'Textbook 5.4.', ['TB5:5.4', 'T0915']);
  A.fill('c5-gradient-f1', 'c5-gradient', 'The rate at which temperature increases with depth is the <u>&nbsp;&nbsp;&nbsp;&nbsp;</u> gradient.', ['geothermal'], 'Textbook 5.4.', ['TB5:5.4']);

  // ---------- 5.4 Melting ----------
  A.section({ id: 'c5s4', ch: 5, n: '5.4', title: 'How rocks melt: reading the P-T graph', srcText: 'Textbook 5.5–5.6 · Rec. Sep 15', src: ['TB5:5.5', 'TB5:5.6', 'T0915'],
    concepts: [['c5-melt3', 'Three ways to melt'], ['c5-ptread', 'Reading a pressure-temperature graph'], ['c5-partial', 'Partial melting and source rock']] });
  A.cards('c5s4', [
    { id: 'g5-4a', h: 'The graph the professor walked through (Sep 15)', c: ['c5-ptread', 'c5-melt3'], src: ['TB5:5.5', 'T0915'],
      html: '<p>Temperature runs left to right (hotter →); pressure runs <b>top to bottom</b> (deeper ↓). The <b>melting curve (solidus)</b> separates solid (left) from liquid (right). A rock melts when it moves from the solid field across the curve. Three ways to get there:</p><ol><li><b>Heating</b>: same pressure, higher temperature (move right).</li><li><b>Decompression</b>: already-hot rock rises fast enough that it does not cool; pressure drops and the rock crosses the curve (move up). The rock must be hot and rise fast.</li><li><b>Adding water</b>: temperature and pressure unchanged; water shifts the curve to lower temperature, <b>by as much as 500 °C</b>, so the rock is suddenly in the liquid field.</li></ol><button class="btn small" data-guidegen="pt">Practice P-T paths (5)</button>',
      media: [pt({ points: [['A', 20, 20], ['B', 62, 20], ['C', 62, 80]], paths: [[22, 20, 58, 20], [62, 78, 62, 25, '#2e6da4']] }), pt({ wet: true, points: [['D', 48, 70]] }), tb(28, 'Textbook 5.5: melting by heating'), tb(29, 'Textbook 5.5: decompression melting'), tb(30, 'Textbook 5.5: adding water (wet vs. dry curves)')],
      traps: ['Reading pressure as increasing upward. On these graphs deeper = lower on the page.', 'Thinking water melts rock by heating it. Water lowers the melting temperature; T and P can stay the same.'] },
    { id: 'g5-4b', h: 'Partial melting makes magma more felsic than its source', c: ['c5-partial'], src: ['TB5:5.6', 'TB5:5.5'],
      html: '<p>Melting starts <b>40–150 km</b> down in the source area. Complete melting is rare. <b>Felsic minerals melt at lower temperatures</b> than mafic ones, so the first melt is <b>more felsic than the source</b>.</p><ul><li>Mantle (ultramafic) → partial melting → mostly <b>mafic</b> magma.</li><li>Mafic source → partial melting → can yield <b>intermediate</b> magma.</li><li>Continental crust (felsic source) → <b>felsic</b> magma.</li></ul>',
      traps: ['Expecting mantle melts to be ultramafic. Partial melting of ultramafic mantle yields mafic magma.'] }
  ]);
  A.mc('c5-melt3-m1', 'c5-melt3', 'Beneath a mid-ocean ridge, hot mantle rock rises as the plates pull apart and begins to melt without being heated further. Which melting mechanism is this?',
    ['*Decompression melting|Pressure drops as the hot rock rises (textbook 5.5, 5.9).', 'Adding water|No water addition is described.', 'Heating by radioactive decay|The rock is not heated further.', 'Friction between plates|Not a melting mechanism in the textbook.'], 'Textbook 5.5 and 5.9.', ['TB5:5.5', 'TB5:5.9']);
  A.mc('c5-melt3-m2', 'c5-melt3', 'Water released from a subducting slab rises into hot mantle rock above it. The temperature and pressure of that mantle rock do not change, yet it melts. Why?',
    ['*Water lowers the rock\'s melting temperature, by as much as 500 °C|Textbook 5.5 and 5.10.', 'Water carries extra heat up from the slab and raises the rock above its melting point|Water does not supply the heat.', 'Water increases the pressure|Pressure is unchanged.', 'Water dissolves the rock completely|Melting is not dissolving.'], 'Textbook 5.5 and 5.10.', ['TB5:5.5', 'TB5:5.10']);
  A.ms('c5-melt3-s1', 'c5-melt3', 'Which changes can cause a solid rock to begin melting? Select all that apply.',
    ['*Raising its temperature at constant pressure|Heating.', '*Lowering the pressure on a hot rock quickly|Decompression.', '*Adding water to a hot rock|Lowers the melting temperature.', 'Increasing the pressure at constant temperature|Moves the rock deeper into the solid field.', 'Removing water from a hot rock|Raises the melting temperature.'], 'Textbook 5.5; Sep 15.', ['TB5:5.5', 'T0915']);
  A.fill('c5-melt3-f1', 'c5-melt3', 'Melting caused by a drop in pressure on hot rock that rises without cooling much is <u>&nbsp;&nbsp;&nbsp;&nbsp;</u> melting.', ['decompression'], 'Textbook 5.5.', ['TB5:5.5']);
  A.parts('c5-ptread-p1', 'c5-ptread', 'Use the graph. For each point, say what the rock is and what one change would melt it.', [
    { label: 'Point A', options: ['Solid; heat it at the same depth', 'Liquid already', 'Solid; increase the pressure'], a: 'Solid; heat it at the same depth', why: 'A is left of the curve; moving right crosses it.' },
    { label: 'Point B', options: ['Solid; heat it', 'Liquid already', 'Solid; add pressure'], a: 'Liquid already', why: 'B is right of the curve.' },
    { label: 'Point C', options: ['Solid; raise it quickly toward the surface', 'Liquid already', 'Solid; cool it'], a: 'Solid; raise it quickly toward the surface', why: 'C is hot but deep; decompression moves it up across the curve.' }],
    'Textbook 5.5; Sep 15 walk-through of a similar graph.', ['TB5:5.5', 'T0915'], { media: pt({ points: [['A', 15, 30], ['B', 70, 30], ['C', 65, 85]] }) });
  A.mc('c5-ptread-m1', 'c5-ptread', 'On the graph, point D is on the solid side of the dry melting curve but on the liquid side of the wet curve. What happens if water is added to rock at D?',
    ['*It begins to melt without any change in temperature or pressure|The wet curve now applies.', 'Nothing happens, because water only affects melting at the surface where pressure is low|Water lowers the melting temperature at depth.', 'It becomes more solid because water cools it|Water lowers the melting curve.', 'It must first be heated by 500 °C|The shift of the curve does the work.'], 'Textbook 5.5.', ['TB5:5.5'], { media: pt({ wet: true, points: [['D', 48, 70]] }) });
  A.tf('c5-ptread-t1', 'c5-ptread', 'On the textbook\'s melting graphs, pressure increases toward the bottom of the graph because deeper rock is under more pressure.', true, 'Textbook 5.5 and 5.8 plot pressure (depth) increasing downward; Sep 15 described pressure as representing depth.', ['TB5:5.5', 'T0915']);
  A.mc('c5-partial-m1', 'c5-partial', 'Why is magma from the mantle mostly mafic even though the mantle is ultramafic?',
    ['*The lower-melting, less mafic parts melt first, so the melt is less mafic than the source|Textbook 5.6 B.2–3.', 'The mantle is secretly mafic|Its overall composition is ultramafic.', 'Mafic oceanic crust is what actually melts, not the ultramafic mantle below it|Most mafic magma comes from mantle partial melting.', 'Crystal settling adds silica during melting|Settling happens during crystallization.'], 'Textbook 5.6.', ['TB5:5.6']);
  A.mc('c5-partial-m2', 'c5-partial', 'A mafic rock at depth is partially melted. The first magma produced is most likely:',
    ['*Intermediate|Partial melting yields a magma more felsic than its source.', 'Ultramafic|That is less felsic than the source.', 'Identical to the source|Only complete melting would do that.', 'Pure quartz|Magma is a silicate melt, not one mineral.'], 'Textbook 5.6 B.2.', ['TB5:5.6']);
  A.fill('c5-partial-f1', 'c5-partial', 'Melting in which only some minerals melt, leaving most of the source unmelted, is <u>&nbsp;&nbsp;&nbsp;&nbsp;</u> melting.', ['partial'], 'Textbook 5.6.', ['TB5:5.6']);

  // ---------- 5.5 Chambers and movement ----------
  A.section({ id: 'c5s5', ch: 5, n: '5.5', title: 'Magma chambers, movement, and viscosity', srcText: 'Textbook 5.6–5.7, 5.12 A · Rec. Sep 15', src: ['TB5:5.6', 'TB5:5.7', 'TB5:5.12', 'T0915'],
    concepts: [['c5-change', 'Crystal settling, assimilation, magma mixing'], ['c5-rise', 'Why and how magma rises'], ['c5-visc', 'Viscosity controls']] });
  A.cards('c5s5', [
    { id: 'g5-5a', h: 'Changing a magma after it forms', c: ['c5-change'], src: ['TB5:5.6', 'TB5:5.12', 'T0915'],
      html: '<table><tr><th>Process</th><th>What happens</th><th>Result</th></tr><tr><td><b>Crystallization</b></td><td>Mafic minerals crystallize first</td><td>Remaining magma becomes more felsic</td></tr><tr><td><b>Crystal settling</b></td><td>Heavy mafic crystals sink; light felsic crystals may float</td><td>Chamber bottom more mafic, top more felsic</td></tr><tr><td><b>Assimilation</b></td><td>Hot magma melts wall rocks and incorporates them</td><td>Composition shifts toward the wall rock</td></tr><tr><td><b>Magma mixing</b></td><td>Two magmas meet and blend</td><td>Intermediate between the two (irregular contacts show both were molten)</td></tr></table>',
      media: [tb(36, 'Crystal settling and floating (textbook 5.6)'), tb(37, 'Assimilation and magma mixing (textbook 5.6)')] },
    { id: 'g5-5b', h: 'Getting to the surface is hard', c: ['c5-rise'], src: ['TB5:5.7', 'TB5:5.6', 'T0915'],
      html: '<p>Melt occupies about <b>10% more volume</b> than the rock it came from, so it is <b>less dense</b> and rises. It moves by <b>filling fractures</b> (magma pressure pries them open; tectonic stretching controls their orientation → <b>dikes</b>) or by <b>blocks of roof and wall rock breaking off</b> and sinking into the magma, making room above (the Sep 15 lecture, as transcribed, calls this <b>stoping</b>).</p><p>Four controls on how high it gets: <b>magma pressure</b> from the weight of overlying rock; <b>density</b> (mafic magma may stall at the base of the less dense crust); <b>gas pressure</b> (bubbles form at shallow depth, lowering density, speeding ascent); <b>tectonic stress</b> (opens steep paths or traps magma). <b>Most magma solidifies at depth.</b></p>',
      traps: ['Assuming most magma erupts. The textbook says most solidifies underground.'] },
    { id: 'g5-5c', h: 'Viscosity: resistance to flow', c: ['c5-visc'], src: ['TB5:5.7'],
      html: '<table><tr><th>Factor</th><th>More viscous (piles up)</th><th>Less viscous (spreads thin, travels far)</th></tr><tr><td><b>Temperature</b> (most important)</td><td>Cooler</td><td>Hotter</td></tr><tr><td>Composition</td><td>Felsic: many long Si-O chains</td><td>Mafic: fewer, shorter chains</td></tr><tr><td>Dissolved water</td><td>Less water</td><td>More water (breaks chains)</td></tr><tr><td>Crystal content</td><td>Many crystals</td><td>Few crystals</td></tr></table><p>Textbook breakfast analogy: orange juice ≈ hot, crystal-poor basalt; thick oatmeal ≈ crystal-rich felsic magma.</p>',
      traps: ['Naming composition as the most important control. The textbook names temperature.'] }
  ]);
  A.mc('c5-change-m1', 'c5-change', 'A layered intrusion has olivine- and pyroxene-rich layers at its base and feldspar-rich rock near its top. Which process best explains this?',
    ['*Crystal settling: dense mafic crystals sank and lighter felsic crystals floated|Textbook 5.6 B.6–8.', 'Assimilation of the roof rocks, which were richer in olivine and pyroxene|Assimilation mixes in wall rock; it does not sort by density.', 'Decompression melting|A melting process, not a sorting process.', 'Weathering after exposure|Layering formed in the chamber.'], 'Textbook 5.6.', ['TB5:5.6']);
  A.mc('c5-change-m2', 'c5-change', 'A rock shows light felsic and dark basaltic material with an extremely irregular, swirled boundary. What does the irregular boundary indicate?',
    ['*Both were molten when they came into contact: magma mixing|Textbook 5.6 B.9.', 'The basalt was already solid and was later cut by a felsic dike|A dike would have sharp, straight contacts.', 'The rocks were glued together by weathering|Weathering does not swirl rocks.', 'The felsic magma assimilated a solid basalt block|Assimilation of solid blocks leaves fragments, not swirls of two melts.'], 'Textbook 5.6.', ['TB5:5.6']);
  A.match('c5-change-x1', 'c5-change', 'Match each process to its effect on a magma.', [
    ['Crystallizing mafic minerals', 'Remaining melt becomes more felsic'], ['Assimilation', 'Wall rock melted and incorporated'], ['Magma mixing', 'Composition intermediate between two magmas'], ['Crystal settling', 'Base of chamber becomes more mafic']], 'Textbook 5.6.', ['TB5:5.6']);
  A.fill('c5-change-f1', 'c5-change', 'When a hot magma melts the walls of its chamber and incorporates that material, the process is called <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['assimilation'], 'Textbook 5.6 B.10.', ['TB5:5.6']);
  A.mc('c5-rise-m1', 'c5-rise', 'Why does newly formed magma tend to rise?',
    ['*Melt is about 10% larger in volume, so it is less dense|Textbook 5.7 A.', 'Magma is attracted upward by Earth\'s magnetic field|Not a mechanism.', 'Magma is always hotter than 5,000 °C|Magma is far cooler than the core.', 'Gravity pulls the surrounding solid rock sideways and out of its way|Buoyancy drives magma up.'], 'Textbook 5.7.', ['TB5:5.7']);
  A.mc('c5-rise-m2', 'c5-rise', 'Mafic magma from the mantle stops rising and pools at the base of the continental crust. Which control explains that best?',
    ['*Density: the mafic magma is denser than the continental crust above it|Textbook 5.7 B.2.', 'Viscosity: mafic magma is far too viscous to move through crust|Mafic magma is relatively fluid.', 'Gas pressure: bubbles made it heavier|Bubbles make magma lighter.', 'Temperature: the crust is hotter than the magma|The magma is hotter.'], 'Textbook 5.7.', ['TB5:5.7']);
  A.tf('c5-rise-t1', 'c5-rise', 'According to the textbook, most magma solidifies underground rather than erupting.', true, 'Textbook 5.7 B: most magmas solidify at depth.', ['TB5:5.7']);
  A.mc('c5-visc-m1', 'c5-visc', 'Which magma would be the most viscous?',
    ['*A relatively cool, crystal-rich, silica-rich magma with little water|Every factor points to high viscosity.', 'A very hot, crystal-poor basaltic magma|Least viscous.', 'A hot, water-rich felsic magma with few crystals and many silicate chains|Heat and water lower viscosity.', 'A mafic magma with few silicate chains|Fewer chains = less viscous.'], 'Textbook 5.7 C.', ['TB5:5.7']);
  A.mc('c5-visc-m2', 'c5-visc', 'Which factor does the textbook call the most important control on magma viscosity?',
    ['*Temperature|Textbook 5.7 C.3.', 'Silica content|Most significant compositional variable, but not overall.', 'Crystal content|A real control, but secondary.', 'Magma volume|Not listed as a viscosity control.'], 'Textbook 5.7 C.', ['TB5:5.7']);
  A.mc('c5-visc-m3', 'c5-visc', 'Why does silica-rich magma resist flow?',
    ['*Si-O tetrahedra link into long chains that do not move easily past one another|Textbook 5.7 C.5.', 'Silica is heavier than iron|Density is not viscosity.', 'Silica-rich magma is always hotter, and hotter magma is thicker|Felsic magma is usually cooler.', 'Silica makes more gas bubbles|Not the reason given.'], 'Textbook 5.7.', ['TB5:5.7']);
  A.fill('c5-visc-f1', 'c5-visc', 'A material\'s resistance to flow is its <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['viscosity'], 'Textbook 5.7 C.', ['TB5:5.7']);

  // ---------- 5.6 Solidification and Bowen ----------
  A.section({ id: 'c5s6', ch: 5, n: '5.6', title: 'Solidification and Bowen\'s reaction series', srcText: 'Textbook 5.8 · Rec. Sep 15', src: ['TB5:5.8', 'T0915'],
    concepts: [['c5-cool', 'How magma loses heat and solidifies'], ['c5-bowen', 'Crystallization order (Bowen)']] });
  A.cards('c5s6', [
    { id: 'g5-6a', h: 'Losing heat', c: ['c5-cool'], src: ['TB5:5.8'],
      html: '<p>Magma cools by <b>conduction</b> into wall rocks (which may be metamorphosed or melted), <b>radiation and conduction</b> at the surface, <b>releasing gases</b>, and <b>convection of groundwater</b> heated by the magma (possibly the main cooling path for some magmas). Solidification starts at different temperatures: <b>mafic &gt; 1,100 °C</b>, <b>intermediate ~950 °C</b>, <b>felsic ~800 °C</b>. A rising magma\'s path on a temperature-depth graph: melt at depth → rise → cool across the melting curve (crystallize) → later uplift to the surface.</p>' },
    { id: 'g5-6b', h: 'Bowen\'s reaction series', c: ['c5-bowen'], src: ['TB5:5.8', 'T0915'],
      html: '<p>Minerals crystallize in the <b>reverse</b> of the order they melt: <b>mafic first, felsic last</b>.</p><ul><li><b>Discontinuous side</b>: olivine → pyroxene → amphibole → biotite.</li><li><b>Continuous side</b>: plagioclase from <b>Ca-rich</b> (high T) to <b>Na-rich</b> (low T).</li><li><b>Last</b>: K-feldspar, muscovite, quartz.</li></ul><p>Consequences: early crystals grow unimpeded and have good shapes; late crystals fill the gaps (irregular). Removing early mafic crystals leaves the melt <b>less mafic</b> (MgO falls, SiO₂ rises). Felsic magmas lack the Mg to grow olivine; mafic magmas lack the Si to grow much quartz.</p>',
      media: [{ kind: 'svg', name: 'bowen', spec: {} }, tb(34, 'Textbook 5.8: Bowen\'s reaction series')],
      traps: ['Putting quartz first because it is "hardest." Hardness is irrelevant; quartz crystallizes last.'] }
  ]);
  A.mc('c5-cool-m1', 'c5-cool', 'Which magma begins to solidify at the highest temperature?',
    ['*Mafic (above ~1,100 °C)|Textbook 5.8.', 'Intermediate (~950 °C)|Lower than mafic.', 'Felsic (~800 °C)|Lowest.', 'All solidify at the same temperature|The textbook gives different temperatures.'], 'Textbook 5.8.', ['TB5:5.8']);
  A.mc('c5-cool-m2', 'c5-cool', 'Groundwater near a shallow magma body is heated, rises, and is replaced by cooler water. What is this heat-transfer process, and what does it do to the magma?',
    ['*Convection of water; it carries heat away and helps the magma cool|Textbook 5.8 A.4.', 'Conduction; the warm water heats the magma further and keeps it molten|Heat flows from magma to water.', 'Radiation; it only works on the surface|The process described is flow.', 'Decompression; it melts more rock|Not a heat-transfer mechanism.'], 'Textbook 5.8.', ['TB5:5.8']);
  A.order('c5-bowen-o1', 'c5-bowen', 'Put these minerals in the order they crystallize from a cooling magma, first to last.', ['Olivine', 'Pyroxene', 'Amphibole', 'Biotite', 'Quartz'], 'Bowen\'s reaction series (textbook 5.8; Sep 15).', ['TB5:5.8', 'T0915']);
  A.parts('c5-bowen-p1', 'c5-bowen', 'Identify the minerals at the numbered positions of the reaction series.', [
    { label: '1', options: ['Olivine', 'Amphibole', 'Ca-rich plagioclase', 'Na-rich plagioclase', 'Quartz'], a: 'Olivine', why: 'First mafic mineral at highest temperature.' },
    { label: '2', options: ['Olivine', 'Amphibole', 'Ca-rich plagioclase', 'Na-rich plagioclase', 'Quartz'], a: 'Ca-rich plagioclase', why: 'High-temperature end of the continuous branch.' },
    { label: '3', options: ['Olivine', 'Amphibole', 'Ca-rich plagioclase', 'Na-rich plagioclase', 'Quartz'], a: 'Quartz', why: 'Among the last minerals at lowest temperature.' }],
    'Textbook 5.8 B.', ['TB5:5.8'], { media: { kind: 'svg', name: 'bowen', spec: { markers: { d0: 1, pca: 2, l2: 3 } } }, mk: 'inv' });
  A.mc('c5-bowen-m1', 'c5-bowen', 'In a gabbro, dark pyroxene crystals have sharp crystal faces while white plagioclase fills the spaces between them. What does this texture tell you?',
    ['*Pyroxene crystallized first; plagioclase filled in later|Textbook 5.8 B.5–6.', 'The plagioclase crystallized first and pushed the pyroxene into shape|Late minerals fill gaps.', 'The rock cooled in two separate magma chambers, one for each mineral|One chamber can produce this.', 'The pyroxene was added by assimilation|Not required by the texture.'], 'Textbook 5.8.', ['TB5:5.8']);
  A.mc('c5-bowen-m2', 'c5-bowen', 'As olivine and pyroxene crystallize and are removed from a mafic magma, how does the remaining melt change?',
    ['*It becomes less mafic: lower in Mg and Fe, relatively richer in silica|Textbook 5.8 "How crystallization changes the composition of magma."', 'It becomes more mafic, because heavy minerals concentrate Mg and Fe in the melt|Mafic components are being removed.', 'It stays the same|Crystals remove elements from the melt.', 'It becomes ultramafic|Opposite direction.'], 'Textbook 5.8.', ['TB5:5.8']);
  A.tf('c5-bowen-t1', 'c5-bowen', 'As a rock is heated, the first minerals to melt are the same minerals that were the first to crystallize when its magma cooled.', false, 'Textbook 5.8 B: minerals crystallize in the opposite order from which they melt. Felsic minerals (quartz, K-feldspar) melt first on heating but crystallize last on cooling; olivine crystallizes first and melts last.', ['TB5:5.8']);
  A.fill('c5-bowen-f1', 'c5-bowen', 'The idealized sequence in which minerals crystallize from a cooling magma is <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>\'s reaction series.', ['Bowen', "Bowen's", 'Bowens'], 'Textbook 5.8 B.', ['TB5:5.8']);

  // ---------- 5.7 Tectonic settings ----------
  A.section({ id: 'c5s7', ch: 5, n: '5.7', title: 'Where magma forms: plate settings', srcText: 'Textbook 5.9–5.11 (lecture coverage unconfirmed)', src: ['TB5:5.9', 'TB5:5.10', 'TB5:5.11'],
    concepts: [['c5-divergent', 'Mid-ocean ridges and oceanic crust'], ['c5-subduction', 'Subduction-zone magma'], ['c5-hotspotmag', 'Hot spots and plumes']] });
  A.cards('c5s7', [
    { id: 'g5-7a', h: 'Mid-ocean ridges: ~60% of Earth\'s magma', c: ['c5-divergent'], src: ['TB5:5.9'],
      html: LATE + '<p>Plates separate; solid asthenosphere rises; pressure drops → <b>decompression melting</b> → mafic magma. Oceanic crust, top to bottom: <b>pillow basalt</b> (lava erupted into water) → <b>sheeted dikes</b> (parallel to the rift, perpendicular to spreading) → <b>gabbro</b> (solidified chambers, sometimes layered by crystal settling) → ultramafic mantle that was partially melted. Slices of this sequence exposed on land are called <b>ophiolites</b>.</p>',
      media: tb(38, 'Magma at a mid-ocean ridge (textbook 5.9)') },
    { id: 'g5-7b', h: 'Subduction zones: ~one-fifth of Earth\'s magma', c: ['c5-subduction'], src: ['TB5:5.10'],
      html: LATE + '<p>The sinking slab heats up; water-bearing minerals (such as mica) break down; water rises into the overlying mantle and <b>lowers its melting temperature</b> → mafic magma. Rising through thick continental crust, magma heats and partly melts it, producing <b>intermediate or felsic</b> magma. Most subduction magma never erupts; what does erupts is mostly <b>andesite</b>, in <b>island arcs</b> (ocean-ocean) or <b>mountain-belt volcanoes</b> (ocean-continent).</p>',
      media: tb(39, 'Subduction-zone magma (textbook 5.10)') },
    { id: 'g5-7c', h: 'Hot spots', c: ['c5-hotspotmag'], src: ['TB5:5.11'],
      html: LATE + '<p>Most hot spots are the surface expression of a <b>mantle plume</b>: hot, less dense <b>solid</b> mantle rising like a lava-lamp blob (some may start at the core-mantle boundary). In oceans, plume melting plus decompression builds large volcanoes (Hawaii); a plate moving over a fixed plume makes a <b>chain of islands and seamounts</b>. In continents, plume heat makes mafic magma in the mantle and can melt crust to make <b>felsic</b> magma; the two may mix. Example: the <b>White Mountain batholith</b> (New Hampshire), interpreted as hot-spot related.</p>',
      traps: ['Saying a mantle plume is liquid. The plume and surrounding mantle are both solid.'] }
  ]);
  A.mc('c5-divergent-m1', 'c5-divergent', 'Drilling down through normal oceanic crust, in what order would you encounter these rock units?',
    ['*Pillow basalt, then sheeted dikes, then gabbro, then ultramafic mantle|Textbook 5.9 B.', 'Gabbro, then pillow basalt, then sheeted dikes|Gabbro is deepest crust.', 'Sheeted dikes, then granite, then basalt|Granite is not part of oceanic crust.', 'Ultramafic mantle, then gabbro, then sheeted dikes, then pillow basalt|That is bottom-to-top.'], 'Textbook 5.9.', ['TB5:5.9']);
  A.mc('c5-divergent-m2', 'c5-divergent', 'About what share of Earth\'s magma forms at mid-ocean ridges, according to the textbook?',
    ['*About 60%|Textbook 5.9 introduction.', 'About 20%|That is the subduction-zone share.', 'About 5%|Far too low.', 'Nearly 100%|Other settings also make magma.'], 'Textbook 5.9 and 5.10.', ['TB5:5.9']);
  A.fill('c5-divergent-f1', 'c5-divergent', 'Rounded mounds of basalt formed when lava erupts into water are called <u>&nbsp;&nbsp;&nbsp;&nbsp;</u> basalts.', ['pillow'], 'Textbook 5.9 B.1.', ['TB5:5.9']);
  A.mc('c5-subduction-m1', 'c5-subduction', 'What directly causes the mantle above a subducting plate to melt?',
    ['*Water released from minerals in the slab lowers the mantle\'s melting temperature|Textbook 5.10 A.', 'Friction heats the slab until it melts|Not the textbook mechanism.', 'The slab melts completely as soon as it enters the hot mantle below the trench|The slab dehydrates; the overlying mantle melts.', 'Decompression as the slab sinks|A sinking slab is under increasing pressure.'], 'Textbook 5.10.', ['TB5:5.10']);
  A.mc('c5-subduction-m2', 'c5-subduction', 'Subduction magma usually begins mafic, yet most volcanoes above subduction zones erupt andesite. What explains the change?',
    ['*Rising magma melts and mixes with the overriding crust and partly crystallizes|Textbook 5.10 B.', 'Seawater dragged down with the slab mixes into the magma and adds silica|Water lowers melting; it does not add silica this way.', 'Andesite forms by decompression at ridges|Wrong setting.', 'The slab itself is andesite|The slab is oceanic crust (basalt, gabbro).'], 'Textbook 5.10.', ['TB5:5.10']);
  A.mc('c5-hotspotmag-m1', 'c5-hotspotmag', 'A mantle plume is described as rising like a blob in a lava lamp. What is the key difference from the lava lamp?',
    ['*The plume and the surrounding mantle are both solid|Textbook 5.11 A.2.', 'The plume is colder and denser than the surrounding mantle|It is hotter.', 'The plume sinks instead of rising|It rises.', 'The plume is made of liquid iron|It is hot mantle rock.'], 'Textbook 5.11.', ['TB5:5.11']);
  A.mc('c5-hotspotmag-m2', 'c5-hotspotmag', 'Why can a continental hot spot produce both basalt and rhyolite?',
    ['*Mantle melts to basalt, and that heat melts crust to rhyolite|Textbook 5.11 A.5.', 'Hot spots erupt only felsic magma|Mafic magma is also produced.', 'The plume itself is layered, with basalt on top of rhyolite|Plumes are solid mantle.', 'Continental crust is mafic|Continental crust is felsic.'], 'Textbook 5.11.', ['TB5:5.11']);

  // ---------- 5.8 Intrusions ----------
  A.section({ id: 'c5s8', ch: 5, n: '5.8', title: 'Plutons and small intrusions', srcText: 'Textbook 5.6, 5.12–5.13 (lecture coverage unconfirmed)', src: ['TB5:5.6', 'TB5:5.12', 'TB5:5.13'],
    concepts: [['c5-pluton', 'Intrusive vs. extrusive; plutons and batholiths'], ['c5-smallint', 'Dikes, sills, laccoliths, necks, columnar joints']] });
  A.cards('c5s8', [
    { id: 'g5-8a', h: 'Where the rock solidified', c: ['c5-pluton'], src: ['TB5:5.6', 'TB5:5.12'],
      html: LATE + '<ul><li><b>Extrusive / volcanic</b>: solidified on the surface (lava or ash).</li><li><b>Intrusive</b>: solidified below the surface. <b>Plutonic</b> ≈ intrusive at considerable depth (more than several km).</li><li>A solidified magma chamber is a <b>pluton</b>; a smaller one with steep sides is a <b>stock</b>; one or more contiguous plutons covering a huge region is a <b>batholith</b> (e.g., the <b>Sierra Nevada batholith</b>, gray granite solidified at depth then uplifted). Most batholiths form from many magma pulses over a long time.</li></ul>',
      media: [tp('ch5-granite', 'Granite: a common plutonic rock (textbook 5.2)'), tb(31, 'Textbook 5.6: a magma system from source to surface')] },
    { id: 'g5-8b', h: 'Small intrusions: read the geometry', c: ['c5-smallint'], src: ['TB5:5.13'],
      html: '<table><tr><th>Feature</th><th>Geometry</th></tr><tr><td><b>Dike</b></td><td>Sheet that <b>cuts across</b> layers; usually steep</td></tr><tr><td><b>Sill</b></td><td>Sheet <b>parallel</b> to layers; usually subhorizontal; lifts rocks above it</td></tr><tr><td><b>Laccolith</b></td><td>Sill that inflates into a lump, <b>doming</b> the layers above</td></tr><tr><td><b>Volcanic neck</b></td><td>Resistant solidified conduit left after erosion (Shiprock, NM: breccia, formed beneath an explosion crater)</td></tr><tr><td><b>Columnar joints</b></td><td>Five- or six-sided columns from contraction during cooling; <b>perpendicular</b> to the cooling unit (vertical in a flat flow or sill, horizontal in a vertical dike)</td></tr></table>',
      media: [{ kind: 'svg', name: 'intrusions', spec: {} }, tb(40, 'Dike (textbook 5.13)'), tb(41, 'Sill (textbook 5.13)'), tb(42, 'Laccolith (textbook 5.13)'), tb(43, 'Columnar joints (textbook 5.13)')],
      traps: ['Dike vs. sill is about the relation to layering, not steepness. A dike in flat-lying rock is steep; a sill in tilted rock is tilted.'] }
  ]);
  A.mc('c5-pluton-m1', 'c5-pluton', 'A granite body exposed over a huge region of California consists of many plutons emplaced over a long time. What is it called?',
    ['*A batholith|Textbook 5.12 (Sierra Nevada batholith).', 'A sill|Sills are thin sheets.', 'A volcanic neck|A neck is a single conduit.', 'A lava flow|Granite is intrusive.'], 'Textbook 5.12.', ['TB5:5.12']);
  A.mc('c5-pluton-m2', 'c5-pluton', 'Granite now forms high peaks in the Sierra Nevada. How did a rock that crystallized kilometers underground reach the surface?',
    ['*It was uplifted and the overlying rocks were eroded away|Textbook 5.12.', 'It erupted as lava and cooled slowly on the surface|Surface lava cools fast and is fine-grained.', 'It rose upward as a solid block through the crust after it had cooled|Uplift and erosion expose it.', 'Glaciers carried it up from depth|Glaciers erode; they do not lift plutons.'], 'Textbook 5.12 C; 5.8 cooling history (path 4).', ['TB5:5.12', 'TB5:5.8']);
  A.match('c5-pluton-x1', 'c5-pluton', 'Match each term to its meaning.', [
    ['Extrusive', 'Solidified on the surface'], ['Intrusive', 'Solidified below the surface'], ['Pluton', 'A solidified magma chamber'], ['Batholith', 'Contiguous plutons covering a huge region']], 'Textbook 5.6 and 5.12.', ['TB5:5.6', 'TB5:5.12']);
  A.fill('c5-pluton-f1', 'c5-pluton', 'Any igneous rock that forms from magma extruded onto the surface is called an <u>&nbsp;&nbsp;&nbsp;&nbsp;</u> rock.', ['extrusive', 'volcanic'], 'Textbook 5.6.', ['TB5:5.6']);
  A.parts('c5-smallint-p1', 'c5-smallint', 'Name each numbered intrusion in the cross section.', [
    { label: '1', options: ['Dike', 'Sill', 'Laccolith', 'Batholith'], a: 'Dike', why: 'Cuts across the layers.' },
    { label: '2', options: ['Dike', 'Sill', 'Laccolith', 'Batholith'], a: 'Sill', why: 'Parallel to the layers.' },
    { label: '3', options: ['Dike', 'Sill', 'Laccolith', 'Batholith'], a: 'Laccolith', why: 'Domes the overlying layers.' }],
    'Textbook 5.13 A.', ['TB5:5.13'], { media: { kind: 'svg', name: 'intrusions', spec: { markers: true } }, mk: 'inv' });
  A.mc('c5-smallint-m1', 'c5-smallint', 'A vertical basalt dike cuts horizontal sandstone. Which way do the columnar joints in the dike run?',
    ['*Horizontal, perpendicular to the dike walls|Joints form perpendicular to the cooling unit (textbook 5.13).', 'Vertical, parallel to the dike walls|That orientation is for flat flows and sills.', 'Randomly|Cooling surfaces control the orientation.', 'Parallel to the sandstone layers only by coincidence|The dike walls control it.'], 'Textbook 5.13.', ['TB5:5.13']);
  A.mc('c5-smallint-m2', 'c5-smallint', 'A steep tower of resistant, fragmented mafic rock rises above a flat desert with dikes radiating from it. What is it most likely?',
    ['*A volcanic neck exposed by erosion|Shiprock, NM (textbook 5.13 B).', 'A laccolith that domed the desert floor|Laccoliths are domed sills.', 'A young scoria cone of loose cinders|Cones are loose, not resistant towers with radiating dikes.', 'A mesa|Mesas are flat-topped layered remnants.'], 'Textbook 5.13.', ['TB5:5.13']);
  A.fill('c5-smallint-f1', 'c5-smallint', 'A sheetlike intrusion that runs parallel to the layers of the host rock is a <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['sill'], 'Textbook 5.13.', ['TB5:5.13']);
  A.fill('c5-smallint-f2', 'c5-smallint', 'A sheetlike intrusion that cuts across the layers of the host rock is a <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['dike', 'dyke'], 'Textbook 5.13.', ['TB5:5.13']);
  A.teach('c5-smallint-t1', 'c5-smallint', 'Sketch-and-explain: in two or three sentences, explain how you would tell a sill from a buried lava flow, both lying parallel to the layers.', 'A sill intrudes after the rocks above it existed, so it bakes (heats) the rocks both above and below it and may send offshoots upward; a lava flow cooled on the surface, so only the rock beneath it is baked, and its top may be vesicular or weathered before the next layer was deposited.', ['Mentions which layers are heated or baked', 'Mentions that a flow was at the surface (vesicular or eroded top) while a sill was not', 'Connects to relative age: the sill is younger than the rock above it'], ['TB5:5.13', 'DES'], { tier: 4 });
})((typeof window !== 'undefined' ? window : globalThis).L);
