/* Chapter 6; Volcanoes and Volcanic Hazards. Evidence: textbook 6.1–6.14 (6.15 capture incomplete) only.
   No Chapter 6 slide deck or recording was supplied, so classroom emphasis is unconfirmed; the Sep 22 announcement
   puts Chapters 1–6 in Exam 1 scope. */
(function (L) {
  'use strict';
  var A = L.A;
  function tf6(n, cap) { return { kind: 'img', src: 'assets/img/tb6/figure-' + (n < 10 ? '0' + n : n) + '.jpg', cap: cap, alt: cap }; }
  function tp(name, cap) { return { kind: 'img', src: 'assets/img/tb/' + name + '.jpg', cap: cap, alt: cap }; }
  function vol(type, label) { return { kind: 'svg', name: 'volcano', spec: { type: type, label: label } }; }
  var TBO = '<p class="small muted">Chapter 6 is textbook-only in this package (no Ch 6 deck or recording was supplied), so this card follows the textbook; class emphasis is unknown.</p>';

  // ---------- 6.1 ----------
  A.section({ id: 'c6s1', ch: 6, n: '6.1', title: 'What is (and is not) a volcano; four volcano types', srcText: 'Textbook 6.1 (textbook-only chapter)', src: ['TB6:6.1'],
    concepts: [['c6-volcdef', 'Recognizing a volcano'], ['c6-types', 'Scoria cone, shield, composite, dome']] });
  A.cards('c6s1', [
    { id: 'g6-1a', h: 'A volcano is a vent', c: ['c6-volcdef'], src: ['TB6:6.1'],
      html: TBO + '<p>A <b>volcano</b> is a <b>vent</b> where magma and other volcanic products erupt onto the surface. Most have a <b>crater</b>; magma also erupts from <b>fissures</b> (linear cracks) and <b>calderas</b> (huge circular depressions). Clues of recent activity: fresh ash on slopes, unweathered flows without developed soil.</p><p><b>Not every hill of volcanic rock is a volcano.</b> A <b>mesa</b> capped by a lava flow is an eroded remnant of a once-extensive flow; it did not form over a vent. The old fissure may show up as a <b>dike</b> nearby.</p>',
      media: [tp('ch6-mesa-photo', 'Mesa capped by volcanic rock (textbook 6.1)'), tp('ch6-mesa-sequence', 'How a lava flow becomes a mesa (textbook 6.1)')],
      traps: ['Calling a basalt-capped mesa a volcano. It is not over a vent.'] },
    { id: 'g6-1b', h: 'Four volcano types that build hills and mountains', c: ['c6-types'], src: ['TB6:6.1', 'TB6:6.3', 'TB6:6.4', 'TB6:6.7', 'TB6:6.9'],
      html: '<table><tr><th>Type</th><th>Shape and size</th><th>Made of</th><th>Built by</th></tr><tr><td><b>Scoria (cinder) cone</b></td><td>Small cone, summit crater; usually ≤ 300 m high</td><td>Loose basaltic (less often andesitic) scoria, bombs</td><td>One episode, months to years</td></tr><tr><td><b>Shield volcano</b></td><td>Broad, gentle slopes; can be tens of km wide (largest type)</td><td>Mostly basaltic lava flows</td><td>Many eruptions</td></tr><tr><td><b>Composite volcano</b> (stratovolcano)</td><td>Symmetrical, moderately steep, thousands of m high</td><td>Interlayered lava, pyroclastic deposits, mudflows; mostly andesite</td><td>Many eruptions over a long time</td></tr><tr><td><b>Volcanic dome</b></td><td>Dome, up to hundreds of m high</td><td>Viscous felsic or intermediate lava piled over the vent</td><td>Usually one episode</td></tr></table><p>Smallest: scoria cones and domes. Largest: shields, then composites.</p>',
      media: [tp('ch6-block-scoria-cone', 'Scoria cone (textbook 6.1)'), tp('ch6-block-shield', 'Shield volcano (textbook 6.1)'), tp('ch6-block-composite', 'Composite volcano (textbook 6.1)'), tp('ch6-block-dome', 'Volcanic dome (textbook 6.1)')],
      traps: ['Composite volcanoes are tall and steep but on average much smaller than shield volcanoes.'] }
  ]);
  A.mc('c6-volcdef-m1', 'c6-volcdef', 'A flat-topped hill has a cap of basalt over soft sedimentary layers, and no crater. A dike cuts the landscape a few kilometers away. What is the hill?',
    ['*A mesa: an eroded remnant of a lava flow from a vent elsewhere|Textbook 6.1 B.', 'A small shield volcano that has lost its summit crater to erosion|A shield is built over its vent.', 'A scoria cone buried by sediment|Scoria cones are cones of loose scoria.', 'A volcanic dome|Domes are piles of viscous lava over a vent.'], 'Textbook 6.1 B.', ['TB6:6.1'], { media: tp('ch6-mesa-photo', 'The hill') });
  A.fill('c6-volcdef-f1', 'c6-volcdef', 'A linear crack from which lava erupts is a <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['fissure'], 'Textbook 6.1.', ['TB6:6.1']);
  A.tf('c6-volcdef-t1', 'c6-volcdef', 'Every hill made of volcanic rock is a volcano.', false, 'A mesa capped by a lava flow is volcanic rock but did not form over a vent (textbook 6.1 B).', ['TB6:6.1']);
  A.match('c6-types-x1', 'c6-types', 'Match each volcano type to its description.', [
    ['Scoria cone', 'Small cone of loose basaltic fragments built in months to years'], ['Shield volcano', 'Broad, gentle slopes of basaltic lava flows'], ['Composite volcano', 'Steep, layered lava, pyroclastic deposits, and mudflows'], ['Volcanic dome', 'Mound of viscous lava piled over the vent']], 'Textbook 6.1.', ['TB6:6.1']);
  A.mc('c6-types-m1', 'c6-types', 'Which volcano type is the largest on Earth?',
    ['*Shield volcano|Textbook 6.4: Mauna Loa is the world\'s largest volcano.', 'Composite volcano|Tall and steep, but much smaller on average.', 'Scoria cone|Among the smallest.', 'Volcanic dome|Among the smallest.'], 'Textbook 6.1 and 6.4.', ['TB6:6.1', 'TB6:6.4']);
  A.order('c6-types-o1', 'c6-types', 'Order these typical volcano types from smallest to largest.', ['Scoria cone', 'Composite volcano', 'Shield volcano'], 'Textbook 6.1 relative sizes.', ['TB6:6.1']);
  A.mc('c6-types-m2', 'c6-types', 'Which profile shows a composite volcano?',
    ['*Profile 2|Steep, symmetrical, tall.', 'Profile 1|Broad and gentle: a shield.', 'Profile 3|Small cone: a scoria cone.', 'None of them|Profile 2 fits.'], 'Textbook 6.1.', ['TB6:6.1'], { media: [vol('shield', 'Profile 1'), vol('composite', 'Profile 2'), vol('scoria', 'Profile 3')] });

  // ---------- 6.2 ----------
  A.section({ id: 'c6s2', ch: 6, n: '6.2', title: 'What controls eruption style', srcText: 'Textbook 6.2 (with 5.7 viscosity)', src: ['TB6:6.2', 'TB5:5.7'],
    concepts: [['c6-erupt', 'Lava flows, domes, fountains, tephra'], ['c6-colflow', 'Eruption column vs. pyroclastic flow'], ['c6-gasvisc', 'Gas, viscosity, and explosiveness']] });
  A.cards('c6s2', [
    { id: 'g6-2a', h: 'Ways magma comes out', c: ['c6-erupt', 'c6-colflow'], src: ['TB6:6.2'],
      html: TBO + '<ul><li><b>Lava flow</b>: magma flows away from the vent.</li><li><b>Lava dome</b>: highly viscous (silica-rich) lava piles up around the vent.</li><li><b>Lava fountain</b>: gas-rich, low-viscosity (basaltic) lava sprayed into the air.</li><li><b>Tephra</b>: ash, pumice, and fragments thrown into the air; tephra sand-sized or smaller is <b>volcanic ash</b>.</li></ul><p><b>Eruption column</b> vs. <b>pyroclastic flow</b>: the difference is mainly <b>gas content</b>. Lots of gas carries tephra high into the atmosphere; less gas cannot support the column, which collapses into a hot, dense cloud that races downhill at <b>&gt; 100 km/h</b> and <b>&gt; 500 °C</b>.</p>',
      media: tp('ch6-column-vs-flow', 'Eruption column and pyroclastic flow (textbook 6.2)'),
      traps: ['Thinking a pyroclastic flow is lava. It is hot gas plus ash and rock fragments.'] },
    { id: 'g6-2b', h: 'Gas + viscosity = explosiveness', c: ['c6-gasvisc'], src: ['TB6:6.2', 'TB5:5.7'],
      html: '<p>Magma holds dissolved H₂O, CO₂, and SO₂. Like opening a soda, dropping pressure near the surface lets bubbles form. In <b>viscous felsic</b> magma, bubbles cannot escape; gas pressure builds and the eruption is <b>explosive</b>. In <b>fluid basaltic</b> magma, bubbles escape easily; eruptions are <b>fairly nonexplosive</b> (lava fountains are small, local explosions). The textbook\'s chain: <b>composition → viscosity → gas trapped or released → eruption style → volcano shape, rock types, hazards</b>.</p>',
      media: tp('ch6-gas-bubbles', 'Dissolved gas forms bubbles as pressure drops (textbook 6.2)') }
  ]);
  A.mc('c6-erupt-m1', 'c6-erupt', 'Basaltic lava with a high initial gas content sprays hundreds of meters into the air in glowing jets. What is this?',
    ['*A lava fountain|Textbook 6.2 A.3.', 'A pyroclastic flow|That is a collapsing ash cloud.', 'A lava dome|Domes are slow, viscous piles.', 'A lahar|A lahar is a volcanic mudflow.'], 'Textbook 6.2.', ['TB6:6.2']);
  A.fill('c6-erupt-f1', 'c6-erupt', 'Material thrown into the air during an explosive eruption, including ash and pumice, is called <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['tephra', 'pyroclastic material', 'pyroclasts', 'pyroclastic debris'], 'Textbook 6.2.', ['TB6:6.2']);
  A.mc('c6-colflow-m1', 'c6-colflow', 'According to the textbook, what mainly determines whether erupting tephra rises in a column or collapses into a pyroclastic flow?',
    ['*The gas content of the magma|More gas keeps the column aloft; less gas lets it collapse.', 'The height of the volcano|Not the stated control.', 'The color of the ash|Irrelevant.', 'Whether the volcano is on an island|Irrelevant.'], 'Textbook 6.2 A.', ['TB6:6.2']);
  A.mc('c6-colflow-m2', 'c6-colflow', 'Why are pyroclastic flows so deadly?',
    ['*They move faster than 100 km/h and are hotter than 500 °C|Textbook 6.2.', 'They move slowly but bury everything in their path under molten lava|Lava flows are the slow ones.', 'They are made of cold mud|That is a lahar.', 'They only release poisonous gas|They are clouds of hot ash, gas, and rock.'], 'Textbook 6.2.', ['TB6:6.2']);
  A.tf('c6-colflow-t1', 'c6-colflow', 'A pyroclastic flow is a fast-moving river of molten lava.', false, 'It is a hot, dense cloud of ash, rock fragments, and gas (textbook 6.2).', ['TB6:6.2']);
  A.mc('c6-gasvisc-m1', 'c6-gasvisc', 'Two magmas contain the same amount of dissolved gas. One is rhyolitic, one basaltic. Which is more likely to erupt explosively, and why?',
    ['*The rhyolitic magma, because its viscosity traps the gas|Textbook 6.2 C.', 'The basaltic magma, because it is hotter and heat drives explosions|Heat lowers viscosity and lets gas escape.', 'Both equally, because gas content is the same|Viscosity controls whether gas escapes.', 'Neither; gas never causes explosions|Gas drives explosive eruptions.'], 'Textbook 6.2.', ['TB6:6.2', 'TB5:5.7']);
  A.order('c6-gasvisc-o1', 'c6-gasvisc', 'Put the textbook\'s chain of control in order, from cause to consequence.', ['Magma composition (silicate chains)', 'Viscosity', 'Gas trapped or released', 'Eruption style', 'Volcano shape and hazards'], 'Textbook 6.2 "Composition, viscosity, and eruptive style."', ['TB6:6.2']);
  A.mc('c6-gasvisc-m2', 'c6-gasvisc', 'Why do bubbles appear in magma as it nears the surface?',
    ['*Lower confining pressure lets dissolved gas come out of solution|The soda-bottle analogy (textbook 6.2 B).', 'Air leaks down into the magma from the atmosphere above the vent|Gas was dissolved in the magma already.', 'Crystals release gas as they grow|Not the textbook explanation.', 'Heat from the Sun boils the magma|Irrelevant.'], 'Textbook 6.2.', ['TB6:6.2']);

  // ---------- 6.3 ----------
  A.section({ id: 'c6s3', ch: 6, n: '6.3', title: 'Basaltic volcanoes, shields, and flood basalts', srcText: 'Textbook 6.3–6.5', src: ['TB6:6.3', 'TB6:6.4', 'TB6:6.5'],
    concepts: [['c6-basaltic', 'Scoria cones and lava flow features'], ['c6-shield', 'Shield volcanoes (Hawaii)'], ['c6-flood', 'Flood basalts']] });
  A.cards('c6s3', [
    { id: 'g6-3a', h: 'A basaltic eruption, start to finish', c: ['c6-basaltic'], src: ['TB6:6.3'],
      html: TBO + '<p>Early: gas-rich magma makes a <b>lava fountain</b>; falling clots build a <b>scoria cone</b> (months to years, ≤ ~300 m). Later: degassed magma pours out as <b>lava flows</b>, often from the base of the cone.</p><table><tr><th>Feature</th><th>What it is</th></tr><tr><td>Vesicular basalt</td><td>Trapped gas bubbles</td></tr><tr><td>Nonvesicular basalt</td><td>Magma low in gas (never had it or lost it)</td></tr><tr><td>Volcanic bombs</td><td>Large blobs or blocks ejected</td></tr><tr><td><b>Lava tube</b></td><td>Solid roof insulates flowing lava, which travels farther; drained tube = cave</td></tr><tr><td><b>Aa</b></td><td>Rough, jagged, broken-up surface</td></tr><tr><td><b>Pahoehoe</b></td><td>Smooth, ropy surface; grows as tongues, often tube-fed</td></tr></table>',
      media: [tp('ch6-aa', 'Aa lava (textbook 6.3)'), tp('ch6-pahoehoe', 'Pahoehoe lava (textbook 6.3)'), tp('ch6-lava-tube', 'Lava tube (textbook 6.3)'), tp('ch6-vesicular-basalt', 'Vesicular basalt (textbook 6.3)'), tp('ch6-nonvesicular-basalt', 'Nonvesicular basalt (textbook 6.3)'), tp('ch6-scoria', 'Scoria (textbook 6.3)')],
      traps: ['Aa and pahoehoe are both basaltic; the difference is surface texture, not composition.'] },
    { id: 'g6-3b', h: 'Shield volcanoes', c: ['c6-shield'], src: ['TB6:6.4'],
      html: '<p>Built by many low-viscosity basaltic flows, so slopes are <b>gentle</b>. The largest form over <b>hot spots</b> on oceanic plates. <b>Mauna Loa</b> is the world\'s largest volcano (about 9,000 m above the seafloor). <b>Kilauea</b> is probably the most active; its summit <b>caldera</b> formed when magma withdrew and the ground collapsed. Eruptions come from <b>fissures</b> fed by sheetlike magma bodies. Lava entering the sea adds new land; lava erupted into water forms <b>pillows</b>.</p>',
      media: [tp('ch6-kilauea-caldera', 'Kilauea summit caldera (textbook 6.4)'), tp('ch6-pillow', 'Pillow basalt: lava erupted into water (textbook 6.4)')] },
    { id: 'g6-3c', h: 'Flood basalts: the largest eruptions', c: ['c6-flood'], src: ['TB6:6.5'],
      html: '<p>Vast, commonly km-thick stacks of basalt flows fed by <b>long fissures</b>; single flows can exceed 1,000 km³. Most probably begin when a <b>mantle plume</b> first reaches the lithosphere.</p><ul><li><b>Columbia Plateau</b> (WA, OR, ID): 300+ flows, 17–5 Ma; linked to the hot spot now under Yellowstone.</li><li><b>Siberian Traps</b>: 252 Ma, same time as a major extinction.</li><li><b>Deccan Traps</b> (India): about 65–66 Ma, same time as the dinosaur extinction.</li></ul><p>Climate effects: SO₂ aerosols reflect sunlight (cooling); CO₂ warms. Which dominates is unclear.</p>',
      traps: ['The textbook states timing coincidences with extinctions and asks whether they are related; it does not claim proof.'] }
  ]);
  A.mc('c6-basaltic-m4', 'c6-basaltic', 'Two basalt samples came from the same eruption. Sample 1 is riddled with holes; sample 2 is dense with none. What best explains the difference?',
    ['*Sample 1 trapped gas bubbles; sample 2 formed from gas-poor magma|Textbook 6.3 A.4–5.', 'Sample 1 is felsic and sample 2 is mafic|Both are basalt.', 'Sample 2 was weathered until its holes filled with water|Not the textbook explanation.', 'Sample 1 cooled deep underground, where gas bubbles grow largest|Bubbles form at low pressure near the surface.'], 'Textbook 6.3.', ['TB6:6.3'], { media: [tp('ch6-vesicular-basalt', 'Sample 1'), tp('ch6-nonvesicular-basalt', 'Sample 2')] });
  A.mc('c6-shield-m3', 'c6-shield', 'Rounded, stacked lava bodies like these are exposed high on a mountainside today. What do they tell you about where the lava erupted?',
    ['*Underwater, despite where they are now|Textbook 6.4 B.4 and 5.9.', 'On a dry mountain slope during a lava fountain|Fountains make scoria, not pillows.', 'Inside a lava tube that later collapsed|Tubes do not make pillows.', 'From a viscous rhyolite dome|Pillows form from fluid basalt.'], 'Textbook 6.4 and 5.9.', ['TB6:6.4', 'TB5:5.9'], { media: tp('ch6-pillow', 'Outcrop') });
  A.mc('c6-basaltic-m1', 'c6-basaltic', 'A basaltic lava flow has a smooth, ropy, billowing surface. What is it called?',
    ['*Pahoehoe|Textbook 6.3 A.9.', 'Aa|Aa is rough and jagged.', 'Tuff|Tuff is consolidated ash.', 'Obsidian|Obsidian is glass, usually felsic.'], 'Textbook 6.3.', ['TB6:6.3'], { media: tp('ch6-pahoehoe', 'Flow surface') });
  A.mc('c6-basaltic-m2', 'c6-basaltic', 'Why do lava flows fed by lava tubes travel farther than flows moving in open channels?',
    ['*The solid roof insulates the lava so it stays hot and fluid longer|Textbook 6.3 A.7.', 'The tube walls make the lava more viscous so it holds together|Opposite.', 'Tubes add gas to the lava|Not the mechanism.', 'Tube-fed lava is felsic|It is basaltic.'], 'Textbook 6.3.', ['TB6:6.3']);
  A.mc('c6-basaltic-m3', 'c6-basaltic', 'Why does a scoria cone usually form early in a basaltic eruption, with lava flows coming later?',
    ['*Early magma is gas-rich and fountains; later degassed magma simply flows|Textbook 6.3 B.', 'Early magma is felsic and explosive, and later magma is basaltic and fluid|Both are basaltic.', 'Lava flows must cool before scoria can form|Order is reversed.', 'The cone forms only after the flows stop|The cone comes first.'], 'Textbook 6.3.', ['TB6:6.3']);
  A.fill('c6-basaltic-f1', 'c6-basaltic', 'A rough, jagged basaltic lava flow made of broken blocks is called <u>&nbsp;&nbsp;&nbsp;&nbsp;</u> lava.', ['aa', "a'a", 'aʻa'], 'Textbook 6.3.', ['TB6:6.3']);
  A.mc('c6-shield-m1', 'c6-shield', 'Why do shield volcanoes have broad, gentle slopes?',
    ['*They are built of low-viscosity basaltic lava that flows far before solidifying|Textbook 6.4 B.3.', 'They are made of loose scoria piled at its natural angle of repose|That describes a scoria cone.', 'Glaciers flattened them|Not the explanation.', 'They erupt mostly pyroclastic flows|Shields erupt mostly lava.'], 'Textbook 6.4.', ['TB6:6.4']);
  A.mc('c6-shield-m2', 'c6-shield', 'How did the caldera at the summit of Kilauea form?',
    ['*Magma was removed from an underground chamber and the land above collapsed|Textbook 6.4 A.4.', 'A meteorite struck the summit|No.', 'Erosion by rivers carved a basin|No.', 'The summit exploded outward sideways, as Mount St. Helens did in 1980|Not the textbook explanation.'], 'Textbook 6.4.', ['TB6:6.4']);
  A.fill('c6-shield-f1', 'c6-shield', 'The Hawaiian shield volcano described by the textbook as the world\'s largest volcano is Mauna <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['Loa'], 'Textbook 6.4.', ['TB6:6.4']);
  A.mc('c6-flood-m1', 'c6-flood', 'What feeds flood basalt eruptions, according to the textbook?',
    ['*Long fissures carrying fluid basalt, commonly above a plume head|Textbook 6.5 B–C.', 'A single tall composite volcano that erupts repeatedly for millions of years|Flood basalts are not central-vent eruptions.', 'Melting of continental ice sheets|Not the source.', 'Felsic calderas|Flood basalts are basaltic.'], 'Textbook 6.5.', ['TB6:6.5']);
  A.match('c6-flood-x1', 'c6-flood', 'Match each flood basalt to its textbook fact.', [
    ['Columbia Plateau', '17–5 million years ago; tied to the Yellowstone hot spot'], ['Siberian Traps', '252 million years ago; major extinction at the same time'], ['Deccan Traps', 'About 65–66 million years ago; dinosaur extinction at the same time']], 'Textbook 6.5.', ['TB6:6.5']);

  // ---------- 6.4 ----------
  A.section({ id: 'c6s4', ch: 6, n: '6.4', title: 'Hazard vs. risk; basaltic hazards', srcText: 'Textbook 6.6', src: ['TB6:6.6'],
    concepts: [['c6-hazrisk', 'Hazard vs. risk'], ['c6-bashaz', 'Hazards of basaltic eruptions']] });
  A.cards('c6s4', [
    { id: 'g6-4a', h: 'Hazard is the danger; risk is the consequence', c: ['c6-hazrisk'], src: ['TB6:6.6'],
      html: TBO + '<p>A <b>hazard</b> is a potentially dangerous situation or event (a lava flow that could erupt). <b>Risk</b> is an assessment of whether that hazard could affect society: lives, property, jobs, crops, climate. The same lava flow is a high risk for a subdivision in its path (Royal Gardens, Kilauea) and almost no risk in an uninhabited desert.</p>',
      traps: ['Using hazard and risk interchangeably. Risk requires people or things of value exposed to the hazard.'] },
    { id: 'g6-4b', h: 'What basaltic eruptions do', c: ['c6-bashaz'], src: ['TB6:6.6'],
      html: '<ul><li><b>Falling objects</b>: scoria and <b>bombs</b> near the vent.</li><li><b>Ash</b>: buries structures, breathing problems; Eyjafjallajökull (Iceland, 2010) shut down European air travel.</li><li><b>Gases</b>: CO₂ asphyxiates; H₂S paralyzes; SO₂, HCl, and fluorine compounds kill crops and livestock and poison water.</li><li><b>Lava flows</b>: usually slow enough to walk away from, but burn and bury everything in their path.</li><li><b>Floods</b>: eruptions under ice release catastrophic meltwater floods (<b>jökulhlaup</b>, Iceland 1996).</li><li><b>Climate</b>: Laki (Iceland, 1783), the largest recorded eruption (16 km³), released SO₂; aerosols dimmed sunlight, followed by crop failure and famine.</li></ul>' }
  ]);
  A.mc('c6-hazrisk-m1', 'c6-hazrisk', 'A lava flow is advancing through uninhabited desert. Another identical flow is advancing toward a town. Which statement is correct?',
    ['*The hazard is similar; the risk is much higher for the flow approaching the town|Risk depends on what is exposed.', 'The risk is identical for both, because the two lava flows are identical|Risk depends on exposure.', 'The desert flow is not a hazard|It is still a dangerous event.', 'Hazard and risk mean the same thing|The textbook distinguishes them.'], 'Textbook 6.6 A.', ['TB6:6.6']);
  A.fill('c6-hazrisk-f1', 'c6-hazrisk', 'An assessment of whether a hazard might affect people, property, or society is called <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['risk'], 'Textbook 6.6 A.', ['TB6:6.6']);
  A.mc('c6-bashaz-m1', 'c6-bashaz', 'A basaltic eruption beneath an Icelandic ice sheet melts huge volumes of ice. What is the main hazard downstream?',
    ['*A catastrophic meltwater flood (jökulhlaup) carrying ice, rock, and debris|Textbook 6.6 D.', 'A pyroclastic flow from a collapsing column of ash and hot gas|Not the described hazard.', 'A caldera collapse|Not described.', 'A tsunami in the open ocean|Not the described hazard.'], 'Textbook 6.6.', ['TB6:6.6']);
  A.mc('c6-bashaz-m2', 'c6-bashaz', 'How did the 1783 Laki fissure eruption affect people far from Iceland?',
    ['*SO₂ aerosols dimmed sunlight, cooling Europe; crops failed|Textbook 6.6 "Laki."', 'Lava flows crossed to mainland Europe and burned farmland|Lava stayed in Iceland.', 'A pyroclastic flow crossed the Atlantic|No.', 'It caused a global flood|No.'], 'Textbook 6.6.', ['TB6:6.6']);
  A.ms('c6-bashaz-s1', 'c6-bashaz', 'Which are hazards of basaltic eruptions described in the textbook? Select all that apply.',
    ['*Volcanic bombs near the vent|Falling objects.', '*Poisonous and suffocating gases|CO₂, H₂S, SO₂, HCl.', '*Lava flows that burn and bury structures|Destructive even if slow.', 'Lava domes collapsing into pyroclastic flows|Associated with viscous felsic/intermediate magma.'], 'Textbook 6.6.', ['TB6:6.6']);

  // ---------- 6.5 ----------
  A.section({ id: 'c6s5', ch: 6, n: '6.5', title: 'Composite volcanoes, domes, and their disasters', srcText: 'Textbook 6.7–6.9', src: ['TB6:6.7', 'TB6:6.8', 'TB6:6.9'],
    concepts: [['c6-composite', 'Composite volcano structure and lahars'], ['c6-disaster', 'Vesuvius, Pelée, St. Helens'], ['c6-dome', 'Growth and collapse of domes']] });
  A.cards('c6s5', [
    { id: 'g6-5a', h: 'Composite volcanoes', c: ['c6-composite'], src: ['TB6:6.7'],
      html: TBO + '<p>Also called <b>stratovolcanoes</b>; common above <b>subduction zones</b> (Ring of Fire). Built over long periods from <b>interlayered</b> lava flows, pyroclastic flows, tephra falls, and mudflows, cut by dikes and sills. Most common rock: <b>andesite</b>. Hazards: tall eruption columns (ash drifts hundreds of km), <b>pyroclastic flows</b> (most violent), and <b>lahars</b>, volcanic mudflows made when rain or snowmelt mixes with loose ash and rock on steep slopes.</p>',
      media: [tp('ch6-sthelens-section', 'Mount St. Helens cross section before 1980 (textbook 6.8)')] },
    { id: 'g6-5b', h: 'Three composite-volcano disasters', c: ['c6-disaster'], src: ['TB6:6.8'],
      html: '<table><tr><th>Event</th><th>What happened</th></tr><tr><td><b>Vesuvius, AD 79</b></td><td>Earthquakes and an eruption column dropped tephra on Pompeii, then six pyroclastic flows (three hit Pompeii); ~20,000 (Pompeii) and ~5,000 (Herculaneum) died. Naples (4+ million) sits in the zone today.</td></tr><tr><td><b>Mount Pelée, 1902</b> (Martinique)</td><td>Warning signs ignored; a pyroclastic flow at ~500 km/h hit St. Pierre; almost all ~30,000 residents died, mostly by breathing hot gas and ash.</td></tr><tr><td><b>Mount St. Helens, 1980</b></td><td>A <b>bulge</b> grew on the north flank from rising magma; an earthquake triggered a massive <b>landslide</b> of the bulge, dropping the pressure on the magma → <b>lateral blast</b> and an eruption column.</td></tr></table>',
      media: tp('ch6-sthelens-sequence', 'Bulge, landslide, lateral blast (textbook 6.8)') },
    { id: 'g6-5c', h: 'Volcanic domes', c: ['c6-dome'], src: ['TB6:6.9'],
      html: '<p>Viscous andesite to rhyolite piles up over the vent; surfaces are rubble of angular blocks. Domes <b>grow</b> from inside (inflation) or by thick lava breaking out. Domes are <b>destroyed</b> by <b>collapse</b> of steep flanks (small pyroclastic flows) or by <b>explosion</b> when solidified magma plugs the conduit and trapped gas builds up. <b>Mount Unzen</b> (Japan): a dome-collapse pyroclastic flow killed 43 journalists and volcanologists. Dome rocks include <b>obsidian</b> with flow bands.</p>',
      media: tp('ch6-dome-photo', 'Rubbly volcanic dome (textbook 6.9)') }
  ]);
  A.mc('c6-composite-m1', 'c6-composite', 'Why are composite volcanoes especially prone to lahars?',
    ['*Steep, high slopes with snow, rain, and loose ash|Textbook 6.7 A.3.', 'They erupt only water and steam instead of lava|No.', 'Their lava is extremely fluid and runs quickly into valleys as mud|Composite lavas are viscous.', 'They are built on flat plains far from rivers|Valleys drain them.'], 'Textbook 6.7.', ['TB6:6.7']);
  A.fill('c6-composite-f1', 'c6-composite', 'A volcanic mudflow of water, ash, and rock is called a <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['lahar', 'mudflow'], 'Textbook 6.7.', ['TB6:6.7']);
  A.mc('c6-composite-m2', 'c6-composite', 'A geologic cross section shows interlayered andesite flows, welded tuff, and old mudflow deposits around a central conduit. What kind of volcano is it?',
    ['*A composite volcano|Interlayered products = composite (textbook 6.7–6.8).', 'A shield volcano|Mostly basaltic flows.', 'A scoria cone|Loose scoria only.', 'A flood basalt|Stacked basalt flows from fissures.'], 'Textbook 6.7 and 6.8.', ['TB6:6.7', 'TB6:6.8'], { media: tp('ch6-sthelens-section', 'Cross section') });
  A.order('c6-disaster-o1', 'c6-disaster', 'Put the 1980 Mount St. Helens events in order.', ['Rising magma bulges the north flank', 'An earthquake triggers a landslide of the bulge', 'Pressure on the magma drops suddenly', 'Lateral blast and eruption column'], 'Textbook 6.8 C.', ['TB6:6.8']);
  A.mc('c6-disaster-m1', 'c6-disaster', 'What killed almost all of the ~30,000 people in St. Pierre in 1902?',
    ['*A pyroclastic flow from Mount Pelée|Textbook 6.8 B.', 'A lava flow from Mount Pelée|Lava flows are slower.', 'A tsunami from a caldera collapse|That was Krakatau.', 'A lahar from melting snow|That was Armero (Nevado del Ruiz).'], 'Textbook 6.8.', ['TB6:6.8']);
  A.mc('c6-disaster-m2', 'c6-disaster', 'At Pompeii in AD 79, what came first?',
    ['*Earthquakes and an eruption column that dropped loose tephra on the town|Textbook 6.8 A.3–4.', 'A fast lava flow that filled the streets before anyone could leave|No lava flow is described.', 'A caldera collapse and tsunami|Not described.', 'A lahar from melting glaciers|Not described.'], 'Textbook 6.8.', ['TB6:6.8']);
  A.mc('c6-dome-m1', 'c6-dome', 'Magma solidifies in the conduit beneath a growing dome, and gas pressure builds beneath the plug. What is the likely outcome?',
    ['*An explosion that destroys part of the dome|Textbook 6.9 B.4.', 'The dome quietly deflates as the gas seeps away|Trapped gas does not vanish.', 'A broad shield volcano forms on top of it|Wrong magma type.', 'A lava tube drains|Unrelated.'], 'Textbook 6.9.', ['TB6:6.9']);
  A.mc('c6-dome-m2', 'c6-dome', 'What happened at Mount Unzen, Japan?',
    ['*A dome collapse sent a pyroclastic flow that killed 43 people|Textbook 6.9.', 'A flood basalt covered the city|No.', 'A caldera eruption buried the island|No.', 'A lahar from the melting summit ice cap destroyed the city|That was Nevado del Ruiz, Colombia.'], 'Textbook 6.9.', ['TB6:6.9']);

  // ---------- 6.6 ----------
  A.section({ id: 'c6s6', ch: 6, n: '6.6', title: 'Calderas', srcText: 'Textbook 6.10–6.11', src: ['TB6:6.10', 'TB6:6.11'],
    concepts: [['c6-caldera', 'How calderas form'], ['c6-calddis', 'Caldera eruptions: Crater Lake, Santorini, Krakatau, Yellowstone']] });
  A.cards('c6s6', [
    { id: 'g6-6a', h: 'Collapse while erupting', c: ['c6-caldera'], src: ['TB6:6.10'],
      html: TBO + '<p>A <b>caldera</b> is a large basin-shaped volcanic depression with steep walls. Formation happens <b>at the same time</b> as the eruption:</p><ol><li><b>Felsic magma</b>, mostly from crustal melting, accumulates in a shallow chamber.</li><li>Eruptions begin; the chamber empties and its <b>roof subsides</b> along curved fractures.</li><li>Eruption columns and pyroclastic flows; much tephra falls back in, making thick <b>tuff</b>; wall landslides add blocks.</li><li>Late magma builds <b>domes</b> inside; sediment and lakes may fill the basin.</li></ol><p>Example: <b>Valles Caldera</b> (NM), ~22 km across, ~2 million years old.</p>',
      media: [tp('ch6-caldera-1', 'Stage 1 (textbook 6.10)'), tp('ch6-caldera-2', 'Stage 2'), tp('ch6-caldera-3', 'Stage 3'), tp('ch6-caldera-4', 'Stage 4')],
      traps: ['A crater and a caldera are not the same: calderas are huge and form by collapse into an emptied chamber.'] },
    { id: 'g6-6b', h: 'Caldera disasters and Yellowstone', c: ['c6-calddis'], src: ['TB6:6.10', 'TB6:6.11'],
      html: '<ul><li><b>Crater Lake</b> (Mount Mazama), ~7,700 years ago; eruption > 50× the 1980 St. Helens eruption; Wizard Island is a later scoria cone.</li><li><b>Santorini (Thera)</b>, ~3,500 years ago; collapse probably generated a destructive wave toward Minoan Crete.</li><li><b>Krakatau, 1883</b>: caldera collapse, pyroclastic flows, huge waves; almost 40,000 deaths; loudest recorded sound. Anak Krakatau grew from 1927.</li><li><b>Yellowstone</b>: three huge caldera eruptions in the last 2.1 million years; youngest caldera 640,000 years ago; ash from northern Mexico to southern Canada.</li></ul>',
      media: [tp('ch6-crater-lake', 'Crater Lake caldera (textbook 6.10)'), tp('ch6-yellowstone-track', 'Yellowstone hot-spot track (textbook 6.11)')] }
  ]);
  A.order('c6-caldera-o1', 'c6-caldera', 'Put the stages of caldera formation in order.', ['Felsic magma accumulates in a shallow chamber', 'Eruptions begin and the chamber roof starts to subside', 'Large eruption columns and pyroclastic flows; tephra fills the caldera', 'Late domes grow and sediment fills the basin'], 'Textbook 6.10 B.', ['TB6:6.10'], { media: [tp('ch6-caldera-1', 'A'), tp('ch6-caldera-3', 'B')] });
  A.mc('c6-caldera-m1', 'c6-caldera', 'Why is welded tuff much thicker inside a caldera than outside it?',
    ['*The floor sank during the eruption and trapped thick tephra|Textbook 6.10 A.3.', 'Wind blew all the ash inward|Not the explanation.', 'The tuff outside the caldera was later eroded away almost completely|Thinner tuff remains outside.', 'Lava flows later turned into tuff|Tuff forms from ash.'], 'Textbook 6.10.', ['TB6:6.10']);
  A.fill('c6-caldera-f1', 'c6-caldera', 'A large, basin-shaped volcanic depression formed when the roof of an emptying magma chamber collapses is a <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['caldera'], 'Textbook 6.10.', ['TB6:6.10']);
  A.match('c6-calddis-x1', 'c6-calddis', 'Match each caldera to its textbook fact.', [
    ['Crater Lake (Mount Mazama)', 'About 7,700 years ago; later scoria cone Wizard Island'], ['Santorini', 'About 3,500 years ago; wave toward Minoan Crete'], ['Krakatau', '1883; almost 40,000 deaths, mostly from waves and pyroclastic flows'], ['Yellowstone', 'Three huge eruptions in 2.1 million years; youngest caldera 640,000 years ago']], 'Textbook 6.10–6.11.', ['TB6:6.10', 'TB6:6.11']);
  A.mc('c6-calddis-m1', 'c6-calddis', 'What made the 1883 Krakatau eruption so deadly?',
    ['*Collapse and pyroclastic flows made huge waves that hit crowded coasts|Textbook 6.11 B.', 'A slow basaltic lava flow spread over all of the nearby inhabited islands|No.', 'Carbon dioxide gas only|Not the main cause.', 'A lahar from glaciers|No glaciers involved.'], 'Textbook 6.11.', ['TB6:6.11']);

  // ---------- 6.7 ----------
  A.section({ id: 'c6s7', ch: 6, n: '6.7', title: 'Assessing and monitoring volcanic hazards', srcText: 'Textbook 6.12–6.14', src: ['TB6:6.12', 'TB6:6.13', 'TB6:6.14'],
    concepts: [['c6-assess', 'Reading a volcano\'s danger and the safest places'], ['c6-monitor', 'Monitoring signals'], ['c6-rainier', 'Mount Rainier and the Cascades']] });
  A.cards('c6s7', [
    { id: 'g6-7a', h: 'Assessing danger', c: ['c6-assess'], src: ['TB6:6.12'],
      html: TBO + '<p><b>What type of volcano?</b> Shape (steep = viscous, explosive, landslide-prone; gentle = basaltic), rock type (welded tuff, rhyolite, andesite = more dangerous than basalt), age and history (fresh shape, dated layers, oral histories).</p><p><b>Where is the risk highest?</b></p><ol><li><b>Proximity</b>: the biggest factor.</li><li><b>Valleys</b>: channel lava, small pyroclastic flows, and mudflows; ridges are safer.</li><li><b>Wind direction</b>: ash and pumice go downwind (prevailing wind).</li><li><b>Particulars</b>: steep sides, a dome that could collapse.</li></ol><p><b>Armero, 1985</b>: an eruption of Nevado del Ruiz (Colombia) melted snow and ice; a mudflow down a valley killed more than 20,000 people in a town that geologists had warned about.</p><button class="btn small" data-guidegen="hazard">Practice village-risk maps (5)</button>',
      media: { kind: 'svg', name: 'hazard', spec: { valleys: ['M380 190 Q 300 250 200 330', 'M380 190 Q 470 120 560 60'], wind: [420, 240, 600, 300], villages: [{ x: 210, y: 320, label: 'P' }, { x: 610, y: 300, label: 'Q' }, { x: 170, y: 90, label: 'R' }] } } },
    { id: 'g6-7b', h: 'Monitoring', c: ['c6-monitor'], src: ['TB6:6.13'],
      html: '<table><tr><th>Signal</th><th>Instrument</th><th>Why it matters</th></tr><tr><td>Ground shaking</td><td>Seismometers</td><td>Moving magma breaks rock; rhythmic tremor can precede eruptions (Pinatubo 1991)</td></tr><tr><td>Gas output</td><td>SO₂ measurements (ground, aircraft)</td><td>Rising, degassing magma; SO₂ rose sharply days before Pinatubo</td></tr><tr><td>Heat flow</td><td>Thermal instruments, satellites</td><td>Magma warming the volcano</td></tr><tr><td>Ground deformation</td><td>GPS, tiltmeters, precise surveying, satellite radar</td><td>Magma inflating the mountain</td></tr></table>' },
    { id: 'g6-7c', h: 'Mount Rainier', c: ['c6-rainier'], src: ['TB6:6.14'],
      html: '<p>An <b>andesitic composite volcano</b> above the <b>Cascadia subduction zone</b> (Juan de Fuca plate subducting eastward beneath North America: ocean-continent). At least <b>11</b> significant pyroclastic eruptions in 10,000 years; most recent <b>1820</b>. The USGS considers its <b>mudflows the greatest volcanic hazard in the Cascades</b>: melted ice cap or big landslides send slurries down valleys toward Tacoma\'s suburbs, some built on a mudflow only about 600 years old. Ash would probably go east with prevailing winds.</p>',
      media: [tp('ch6-cascadia-block', 'Cascadia setting (textbook 6.14)'), tp('ch6-rainier-section', 'Rainier cross section (textbook 6.14)'), tp('ch6-rainier-hazard', 'Rainier hazard zones (textbook 6.14)'), tp('ch6-cascade-eruptions', 'Cascade eruptions in the past 4,000 years (textbook 6.14)')] }
  ]);
  A.mc('c6-assess-m1', 'c6-assess', 'Which single factor does the textbook call the biggest in determining potential risk around a volcano?',
    ['*Proximity to the volcano|Textbook 6.12 B.1.', 'Wind direction|Important, but not the biggest.', 'Elevation above sea level|Not listed as the main factor.', 'The color of the volcano|Irrelevant.'], 'Textbook 6.12.', ['TB6:6.12']);
  A.mc('c6-assess-m2', 'c6-assess', 'Two towns sit 15 km from a steep andesitic volcano: one on a ridge, one on the floor of a valley that drains the summit. Which is at greater risk from lahars and small pyroclastic flows, and why?',
    ['*The valley town, because valleys channel mudflows and small pyroclastic flows|Textbook 6.12 B.2.', 'The ridge town, because it is higher and closer to the summit\'s elevation|Flows follow low ground.', 'Equal risk at equal distance|Topography changes the risk.', 'Neither; lahars only occur on shield volcanoes|Lahars are typical of composite volcanoes.'], 'Textbook 6.12 and 6.14.', ['TB6:6.12', 'TB6:6.14']);
  A.ms('c6-assess-s1', 'c6-assess', 'Which observations suggest a volcano is more dangerous? Select all that apply.',
    ['*Steep slopes|Viscous magma, landslide-prone.', '*Layers of welded tuff|Past felsic pyroclastic flows.', '*A fresh, uneroded shape with recent dark deposits|Recent activity.', 'Gentle slopes built of basalt flows|Less explosive.', 'Deeply eroded, soil-covered flanks with no recent deposits|Suggests long inactivity.'], 'Textbook 6.12 A.', ['TB6:6.12']);
  A.mc('c6-assess-m3', 'c6-assess', 'What killed more than 20,000 people at Armero, Colombia, in 1985?',
    ['*A lahar from snow and ice melted by the eruption|Textbook 6.12.', 'A pyroclastic flow moving at about 500 km/h into the town|That was St. Pierre.', 'Heavy ash fall that collapsed roofs across the town|Not the main cause.', 'A caldera-collapse wave|That was Krakatau.'], 'Textbook 6.12.', ['TB6:6.12']);
  A.mc('c6-assess-m4', 'c6-assess', 'Cone 1 has sharp slopes, a crisp summit crater, and little vegetation. Cone 2 is rounded, gullied, and covered in grass. Which is more likely to have erupted recently?',
    ['*Cone 1: a fresh, uneroded shape suggests recent activity|Textbook 6.12 A.3 (age and history).', 'Cone 2: vegetation grows fastest on the youngest volcanic rock|Soil and vegetation take time to develop.', 'Both equally: shape says nothing about age|Erosion state is an age indicator.', 'Neither: scoria cones erupt only once, so both are safe forever|Volcanic fields can produce new cones.'], 'Textbook 6.1 A.5 and 6.12 A.3.', ['TB6:6.1', 'TB6:6.12'], { media: [tp('ch6-young-cone', 'Cone 1'), tp('ch6-eroded-cone', 'Cone 2')] });
  A.match('c6-monitor-x1', 'c6-monitor', 'Match each instrument to what it detects.', [
    ['Seismometer', 'Ground shaking from moving magma'], ['Tiltmeter', 'Tilting of the flank as magma inflates or deflates'], ['GPS station', 'Tiny changes in position and elevation'], ['SO₂ spectrometer', 'Increase in gas output']], 'Textbook 6.13.', ['TB6:6.13']);
  A.mc('c6-monitor-m1', 'c6-monitor', 'Days before a 1991 eruption, sulfur dioxide output from Mount Pinatubo increased dramatically. What did this likely indicate?',
    ['*Magma was rising and losing its dissolved gas|Textbook 6.13 B.', 'The volcano had become extinct|The opposite.', 'Groundwater was cooling the magma|Not indicated by rising SO₂.', 'A lahar was about to occur without an eruption|Not the inference.'], 'Textbook 6.13.', ['TB6:6.13']);
  A.fill('c6-monitor-f1', 'c6-monitor', 'Changes in the shape of a volcano\'s surface as magma inflates it are called ground <u>&nbsp;&nbsp;&nbsp;&nbsp;</u>.', ['deformation'], 'Textbook 6.13 D.', ['TB6:6.13']);
  A.mc('c6-rainier-m1', 'c6-rainier', 'According to the USGS (as quoted in the textbook), what is the greatest volcanic hazard from Mount Rainier?',
    ['*Mudflows (lahars) traveling down valleys|Textbook 6.14 C.', 'Fast basaltic lava flows reaching Seattle and Tacoma|Rainier erupts viscous andesite.', 'A flood basalt eruption|Not Rainier\'s style.', 'Caldera collapse and tsunami|Not the stated hazard.'], 'Textbook 6.14.', ['TB6:6.14']);
  A.mc('c6-rainier-m2', 'c6-rainier', 'Why do Cascade volcanoes such as Mount Rainier exist?',
    ['*Juan de Fuca subduction; water-fluxed mantle melting feeds andesite|Textbook 6.14 B and 5.10.', 'A hot spot lies beneath western Washington, like the one under Hawaii|Cascades are subduction-related.', 'North America is rifting apart there|Not a rift.', 'Two continents are colliding|Ocean-continent convergence.'], 'Textbook 6.14.', ['TB6:6.14', 'TB5:5.10']);
  A.fill('c6-rainier-f1', 'c6-rainier', 'The oceanic plate subducting beneath the Pacific Northwest to feed the Cascade volcanoes is the Juan de <u>&nbsp;&nbsp;&nbsp;&nbsp;</u> plate.', ['Fuca'], 'Textbook 6.14.', ['TB6:6.14']);
})((typeof window !== 'undefined' ? window : globalThis).L);
