/* Original curated questions: three disjoint sets. No Connect questions copied. */
(function(L){
'use strict';
var X=L.EXAM1, A=L.A, forms=['A','B','C'];
// q | key | distractor | distractor | distractor | explanation. Keys rotated when authored.
var rows={
T1:[
['A buried sandstone is heated and compressed without melting. Which rock category can result?','Metamorphic','Igneous','Loose sediment','Magma','Metamorphism changes solid rock. Igneous rock requires cooling from melt; sediment requires breakdown.'],
['Which change directly produces an igneous rock?','A melt cools and crystallizes','Sand grains are cemented together','Solid shale is heated and folded','A granite boulder breaks apart','Igneous rock forms from cooling melt; cementation forms sedimentary rock and solid-state change forms metamorphic rock.'],
['A granite outcrop weathers; its grains travel downstream and are buried. What completes the clastic sedimentary route?','Compaction and cementation','Partial melting and eruption','Heating without melting','Crystallization from magma','Sediment becomes clastic sedimentary rock by lithification, commonly compaction and cementation.'],
['Which pair correctly distinguishes two steps in a river-to-sandstone route?','Transport moves grains; deposition drops them','Weathering moves grains; erosion cements them','Deposition melts grains; cooling sorts them','Cementation removes grains; burial transports them','Transport is movement. Deposition is settling or dropping sediment; later lithification makes the rock.'],
['Which rock-cycle statement permits the direct route from granite to gneiss?','Igneous rock can metamorphose without becoming sediment','Igneous rock must first become a sedimentary rock','Every path must pass through surface lava','Every metamorphic change requires complete melting','Rock-cycle pathways branch. Heat and pressure can transform an igneous rock directly while it remains solid.'],
['A sedimentary rock melts completely and the melt later solidifies. The final rock is…','Igneous','Metamorphic','Sedimentary','Unconsolidated sediment','After melting, classification follows the new formation process: solidifying magma makes igneous rock.']
],
T2:[
['Which list puts the course’s four broad time divisions in oldest-to-youngest order?','Precambrian → Paleozoic → Mesozoic → Cenozoic','Paleozoic → Precambrian → Cenozoic → Mesozoic','Cenozoic → Mesozoic → Paleozoic → Precambrian','Precambrian → Mesozoic → Paleozoic → Cenozoic','The lecture uses Precambrian, then Paleozoic, Mesozoic, and Cenozoic. Precambrian occupies most of Earth history.'],
['Which broad block immediately precedes the Cenozoic in the course timescale?','Mesozoic','Precambrian','Paleozoic','Quaternary','Mesozoic lies between Paleozoic and Cenozoic. Quaternary is a subdivision of the Cenozoic.'],
['Which of the course’s four broad blocks contains the greatest span of Earth history?','Precambrian','Paleozoic','Mesozoic','Cenozoic','Precambrian spans most of the roughly 4.5-billion-year history before the later fossil-rich divisions.']
],
T3:[
['Why was Wegener’s drift proposal initially unconvincing to many geologists despite matching fossils?','It lacked a convincing mechanism for continental motion','It contained no evidence from fossils or ancient climates','It required continents to remain fixed forever','It had already mapped all seafloor magnetic reversals','Matching fossils supported drift, but Wegener could not adequately explain the driving mechanism.'],
['Basalt bands of alternating magnetic polarity form matching patterns on opposite sides of a ridge. What do they support?','Crust forms at the ridge and moves outward','Continents migrate while the ocean floor remains fixed','Old crust is created only beside deep trenches','Every dark band formed during a different ice age','Basalt locks in magnetic polarity as it cools; reversals recorded on spreading crust make paired patterns.'],
['Compared with young oceanic lithosphere near a ridge, old undisturbed lithosphere farther away is generally…','Cooler, denser, and thicker','Hotter, less dense, and thicker','Cooler, less dense, and thinner','Hotter, denser, and thinner','Cooling increases density and adds rigid mantle to the lithosphere, which thickens and subsides.'],
['Which thickness generally increases as an oceanic plate cools away from a ridge?','The rigid mantle portion of the lithosphere','The basaltic oceanic crust at the same rate as age','The thickness of a continent riding the ridge','The liquid outer core beneath the ocean','Lithosphere thickens as mantle cools. This is different from thickening the basaltic oceanic crust.'],
['Two points on opposite sides of one ridge are equally distant from its axis. With constant symmetric spreading, their crust is…','Approximately the same age','Older only on the northern side','Youngest on the side nearest a continent','Unrelated in age because polarity differs','The stated symmetric spreading history makes equal distances correspond to equal ages.'],
['Ocean floor generally becomes deeper with increasing age away from a ridge because it…','Cools, becomes denser, and subsides','Warms, becomes lighter, and sinks','Accumulates magma faster than at the ridge','Changes from basalt into continental granite','Thermal contraction and increased density accompany cooling and subsidence.']
],
T4:[
['At a boundary, arrows on the two plates point away from each other. Which pairing fits?','Divergent — constructive','Transform — destructive','Convergent — conservative','Transform — constructive','Divergence separates plates; ridges create oceanic crust, hence constructive.'],
['Two plates slide sideways past one another without creating or consuming crust. This boundary is…','Transform / conservative','Divergent / constructive','Subduction / destructive','Collision / constructive','Transform motion is parallel to the boundary and conserves crust across it.'],
['Which named basin best illustrates an early stage of opening after continental rifting?','Red Sea','Central Pacific trench system','Himalayan mountain belt','Interior of the Antarctic continent','The Red Sea is a young opening ocean basin; the Himalaya is a collision zone.'],
['A schematic shows four connected plate regions separated by three boundaries. How many plates are shown?','Four','Three','Six','Seven','Count regions separated by boundaries. Boundaries are not themselves plates.'],
['At an oceanic trench, a plate bends downward beneath another plate. What happens to the descending oceanic lithosphere?','It is consumed by subduction','It is created by seafloor spreading','It slides past without descending','It becomes a new continental rift','Subduction recycles oceanic lithosphere into the mantle; this is a destructive boundary.'],
['Which statement best fits the Atlantic basin in the classroom opening-ocean comparison?','New oceanic crust forms along its central spreading ridge','Its entire floor is a single continental collision zone','All its crust is consumed at its central transform fault','Its width proves that every plate along it is shrinking','The Mid-Atlantic Ridge creates crust during divergence. Net plate growth still depends on all boundaries.']
],
T5:[
['Which set groups Earth by composition rather than mechanical behavior?','Crust, mantle, core','Lithosphere, asthenosphere, outer core','Rigid plate, weak layer, solid center','Continental plate, oceanic plate, ridge','Crust, mantle, and core differ in composition. Lithosphere/asthenosphere distinguishes mechanical behavior.'],
['The lithosphere–asthenosphere boundary separates…','Rigid plate material from hotter, weaker mantle','Continental crust from oceanic crust','The iron core from silicate mantle','Solid inner core from liquid outer core','LAB marks a mechanical transition; the lithosphere includes crust and uppermost mantle.'],
['Two equal-density wooden blocks float in water. The thicker block’s top stands higher because…','A thicker block extends both farther down and farther up','The thicker block must have become less dense','The water below it stops applying pressure','The thinner block contains denser water','At equal density the submerged fraction is the same. A thicker block has a greater absolute exposed height.'],
['Which material belongs to the lithosphere?','Crust plus rigid uppermost mantle','Only continental crust above sea level','Only the weak, flowing part of the mantle','All mantle and all core material','A plate is not just crust. Its rigid upper mantle is part of the lithosphere.'],
['At equal thickness, which floating crustal block tends to sit lower?','The denser block','The less dense block','The block with fewer minerals','Both must sit at identical levels','Greater density requires a larger submerged fraction in the buoyancy analogy.'],
['How can the asthenosphere flow while remaining mostly solid?','Hot solid rock deforms slowly over geologic time','Only fully liquid rock can move at depth','Every mineral dissolves into groundwater first','The asthenosphere is a continuous open magma chamber','Mechanical weakness and slow solid-state deformation allow mantle flow without complete melting.']
],
T6:[
['In a hot-spot chain, ages increase westward from an active eastern volcano. Relative to a stationary hot spot, the plate moved…','Westward','Eastward','Vertically only','Toward both ends at equal rates','Older volcanoes were carried west as new activity remained above the hot spot.'],
['Which pair is used to contrast an oceanic and a continental hot spot?','Hawaii and Yellowstone','Atlantic Ridge and Himalaya','Red Sea and San Andreas fault','Andes and Aleutian trench','Hawaii is oceanic; Yellowstone is continental. Both are used in hot-spot discussion.'],
['A plume ascends from deeper mantle before producing melt near shallower levels. What is it mainly during ascent?','Unusually hot, mostly solid mantle','A hollow pipe filled with ocean water','Continental crust sinking into the core','Liquid iron rising from the outer core','A plume is hot buoyant mantle. Decompression can cause partial melting as it rises.']
],
T7:[
['On a graph with depth increasing downward, a vertical upward rock path at constant temperature represents…','Decreasing pressure','Increasing temperature','Increasing pressure','Constant pressure','Upward on this depth axis means shallower and lower pressure, with unchanged temperature.'],
['A rock path crosses the solidus toward higher temperature. What happens at that crossing?','Melting begins','All rock instantly becomes liquid','The first sediment is deposited','The core changes from liquid to solid','The solidus marks the onset of melting, not necessarily complete melting.'],
['Water shifts a mantle rock’s solidus toward lower temperatures. A rock between wet and dry solidi can…','Begin melting after water is added without extra heating','Remain solid because pressure alone controls melting','Freeze because all water additions remove heat','Melt only if pressure rises at the same time','Water lowers the threshold for melting; the same P–T point can then lie in the melt-present field.']
],
T8:[
['Large phenocrysts are surrounded by a fine groundmass. Which cooling history best explains them?','Slow growth followed by faster cooling','Rapid quenching followed by sediment cementation','Uniform rapid cooling with no earlier growth','Uniform deep cooling at one steady rate','Porphyritic texture commonly records earlier slow crystal growth followed by faster cooling.'],
['Which texture records cooling too rapid for crystals to grow?','Glassy','Coarse crystalline','Pegmatitic','Entirely phaneritic','A glass lacks crystals because atoms did not organize into crystalline structures before solidification.'],
['What favors exceptionally large crystals in pegmatite according to the assigned textbook?','Water-rich melt that helps atoms move and grow crystals','Complete lack of dissolved water in all magmas','Quenching lava immediately in cold seawater','Gas cavities forcing grains to fuse together','The textbook emphasizes dissolved water facilitating atom transport and crystal growth.'],
['A felsic melt cools slowly at depth. Which texture should generally result?','Coarse-grained','Glassy','Fine-grained','Unconsolidated ash','Slower cooling allows crystals more time to grow. Composition remains a separate property.'],
['What does a fine-grained texture by itself tell you most directly?','Crystal growth was limited by relatively rapid cooling','The rock must contain a high proportion of iron','The rock must be basalt rather than rhyolite','The rock must have crystallized slowly at depth','Texture constrains cooling history; mineral composition is needed to distinguish basalt from rhyolite.'],
['Which feature defines a porphyritic texture?','Large crystals in a finer groundmass','Only equally large interlocking crystals','Only holes with no crystalline material','Sedimentary pebbles glued together','A contrast between phenocrysts and finer groundmass defines porphyritic texture.']
],
T9:[
['Round cavities in a freshly solidified lava are most directly evidence of…','Gas bubbles trapped during solidification','Large crystals removed by metamorphism','Sediment grains cemented under pressure','Metallic bonds stretched into spheres','Vesicles preserve gas-bubble spaces, commonly formed as pressure falls near the surface.'],
['Which description best fits typical pumice rather than typical scoria?','Light-colored, highly vesicular volcanic glass','Dark, relatively thick-walled mafic fragments','Coarse crystals with no bubble cavities','A compact rock rich in olivine and pyroxene','Pumice is commonly light and very vesicular; scoria is usually darker with thicker walls.'],
['Why can lava develop bubbles as it approaches the surface?','Lower pressure allows dissolved gases to separate','Higher pressure forces new gas into solid crystals','Surface water turns every mineral directly into gas','Cooling creates bubbles without any gas present','Reduced pressure promotes gas exsolution and expansion; solidification can preserve vesicles.']
],
T10:[
['Which pair shares a felsic composition but differs in typical cooling texture?','Granite and rhyolite','Granite and basalt','Gabbro and rhyolite','Peridotite and andesite','Granite is coarse and rhyolite is fine, but both are felsic.'],
['A rock is coarse-grained and mafic, with pyroxene and Ca-rich plagioclase. Its chart name is…','Gabbro','Basalt','Granite','Diorite','Gabbro occupies the coarse/mafic cell. Basalt is its fine-grained counterpart.'],
['An intermediate volcanic rock has crystals too small to see. Which name fits the chart?','Andesite','Diorite','Rhyolite','Peridotite','Andesite is fine-grained and intermediate. Diorite is coarse-grained and intermediate.'],
['Which mineral association best supports a felsic composition?','Quartz and potassium feldspar','Olivine and abundant pyroxene','Pyroxene and calcium-rich plagioclase','Only iron-rich minerals and no feldspar','Quartz and K-feldspar favor felsic compositions; mafic and ultramafic associations differ.'],
['Peridotite is generally classified as…','Coarse-grained and ultramafic','Fine-grained and felsic','Coarse-grained and intermediate','Glassy and sedimentary','Peridotite is a coarse ultramafic rock rich in olivine and pyroxene.'],
['Which observation is needed along with mineral composition to place a rock in the correct classification-chart row?','Its crystal size or texture','Its latitude when collected','The age of its nearest river','The direction of local magnetic north','The chart uses composition as one axis and texture as the other.']
],
T11:[
['What is the basic silicate structural unit?','One silicon surrounded by four oxygen atoms','Four silicon surrounding one oxygen atom','One iron surrounded by four calcium atoms','Four oxygen atoms with no central atom','The silicon–oxygen tetrahedron contains one Si and four O.'],
['Which distinction separates sulfates from sulfides?','Sulfates have an oxygen-bearing sulfate anion group','Sulfides always contain a silicate tetrahedron','Sulfates are defined by a positive sodium ion','Sulfides must contain only metallic bonds','Sulfate uses SO₄²⁻; sulfide uses S²⁻. The anion or anion group names the mineral family.'],
['Which pair is the most abundant in Earth’s crust and helps explain silicate dominance?','Oxygen and silicon','Iron and nickel','Calcium and carbon','Sodium and chlorine','O and Si dominate crustal composition and combine in the tetrahedra of silicates.'],
['Which silicate structure is characteristic of mica?','Sheets','Isolated tetrahedra','Single chains','Double chains','Micas contain sheets of linked tetrahedra. Olivine is isolated, pyroxene single-chain, and amphibole double-chain.'],
['Which bonding description is covalent?','Atoms share electron pairs','Oppositely charged ions attract','Electrons move freely through a metal','Weak attractions act between molecular units','Covalent bonding shares electron pairs. The other choices describe ionic, metallic, and molecular attractions.'],
['Which list contains the eight abundant crustal elements emphasized in the review?','O, Si, Al, Fe, Ca, Na, K, Mg','O, Si, Au, Ag, Pt, Cu, Pb, Hg','Fe, Ni, H, He, C, N, S, Cl','Si, Al, Ca, Na, K, Mg, U, Li','The emphasized eight are oxygen, silicon, aluminum, iron, calcium, sodium, potassium, and magnesium.']
],
T12:[
['Which mineral typically crystallizes earlier at higher temperature in Bowen’s discontinuous series?','Olivine','Quartz','Muscovite','Potassium feldspar','Olivine forms at high temperature; quartz, muscovite, and K-feldspar are lower-temperature minerals.'],
['Relative to its source, the first partial melt is generally…','More silica-rich','Identical in every mineral proportion','Always pure quartz','Always more ultramafic','Lower-melting components enter the liquid preferentially, often enriching it in silica relative to the residue/source.'],
['Which high-to-low-temperature order follows Bowen’s discontinuous branch?','Olivine → pyroxene → amphibole → biotite','Biotite → amphibole → pyroxene → olivine','Quartz → olivine → biotite → pyroxene','Amphibole → olivine → quartz → pyroxene','The discontinuous branch progresses from olivine through pyroxene and amphibole to biotite during cooling.'],
['In the simplified course comparison, minerals that crystallize last during cooling tend to…','Melt first during subsequent heating','Melt last during subsequent heating','Never melt under any conditions','Turn directly into sediment at depth','The general order reverses: lower-temperature minerals crystallize late but melt earlier on heating.'],
['Why can partial melting of ultramafic mantle yield basalt without yielding rhyolite?','Basalt is more silica-rich than its ultramafic source','Every partial melt must have the same felsic composition','Only continental crust can produce a partial melt','Basalt has less silica than all ultramafic rocks','“More silica-rich than the source” is relative. It does not require a felsic final magma.'],
['During cooling, plagioclase in Bowen’s continuous branch evolves generally from…','Calcium-rich toward sodium-rich','Sodium-rich toward calcium-rich','Potassium-rich toward pure quartz','Iron-rich toward pure olivine','The continuous branch represents changing plagioclase composition from Ca-rich at high temperature toward Na-rich at lower temperature.']
],
T13:[
['At a mid-ocean ridge, hot solid mantle rises and melts as pressure drops. The mechanism is…','Decompression melting','Flux melting from slab water','Cooling and crystallization','Cementation during burial','Rising mantle experiences a pressure decrease, which can carry it across its solidus.'],
['What commonly triggers melting in mantle above a subducting slab?','Water released from slab minerals lowers the solidus','The whole slab melts instantly through friction','Pressure drops because the slab sinks deeper','Seawater cools mantle until it becomes liquid','Released water enters the overlying mantle and lowers its melting temperature.'],
['A basaltic intrusion heats adjacent continental rock until it partly melts. Which mechanism acts on that wall rock?','Addition of heat','Removal of heat','Decompression alone','Compaction and cementation','The described energy transfer increases the wall rock’s temperature and may cross its solidus.'],
['Which setting–mechanism pairing is correct?','Rising hot-spot mantle — decompression','Sinking oceanic slab — decreasing pressure','Cold sediment burial — rapid quenching','Mid-ocean ridge mantle — water from a subducting slab','Upwelling at a hot spot can produce melting by pressure decrease.'],
['A mantle rock is held at the same pressure and temperature while water is added. Why can melting begin?','Water lowers the melting threshold','Water necessarily heats it by hundreds of degrees','Water turns silicate minerals into iron','Water raises the pressure enough to melt it','The wet solidus lies at lower temperature, allowing melting at the same P and T.'],
['Which combination lists all three melting mechanisms emphasized in the review?','Add heat, lower pressure, add water','Remove heat, raise pressure, remove water','Add heat, raise pressure, compact grains','Lower pressure, cool rapidly, cement grains','Heating, decompression, and adding volatiles are the three routes into melting.']
],
T14:[
['Broad, gently sloping volcanoes built by fluid basaltic flows are typically…','Shield volcanoes','Composite volcanoes','Cinder cones','Lava domes','Low-viscosity basalt spreads far, building the broad shield profile.'],
['Mount Fuji and Mount St. Helens are classroom examples of…','Composite volcanoes','Only basaltic shield volcanoes','Single loose scoria cones','Mid-ocean spreading ridges','These are composite/stratovolcano examples with steeper profiles and varied eruption products.'],
['Why can a scoria cone be steep even when its magma is basaltic?','Loose ejected fragments pile up around its vent','All basalt has greater viscosity than rhyolite','Every steep volcano forms from a continental collision','The cone is built by slow cooling deep underground','Cone shape reflects accumulation of fragments, so slope alone does not determine magma silica content.']
],
T15:[
['Hot water rises in a pot while cooler water sinks along the sides. Heat transport by this circulation is…','Convection','Conduction','Radiation','Crystallization','Bulk movement of the fluid carries heat: convection.'],
['Heat passes from magma into stationary neighboring rock across their contact. The transfer is chiefly…','Conduction','Convection','Radiation through empty space','Decompression','Conduction transfers heat through matter/contact without bulk movement of the material.'],
['A lava surface emits thermal energy as electromagnetic waves. This is…','Radiation','Conduction','Convection','Partial melting','Electromagnetic emission is radiation; it does not require moving hot material or direct contact.']
],
T16:[
['At ocean–continent convergence, which plate normally descends and why?','Oceanic lithosphere, because it is denser','Continental crust, because it is less dense','Both plates equally, because density is irrelevant','Neither plate, because all convergence is transform','Relatively dense oceanic lithosphere generally subducts beneath buoyant continental crust.'],
['India’s collision with Asia is most directly associated with…','Continental crust thickening into the Himalaya','A new ocean spreading between two continents','An island chain above a stationary oceanic hot spot','A transform boundary creating new basaltic crust','Continent–continent collision shortens and thickens buoyant continental crust.'],
['At ocean–ocean convergence, all else equal, which plate is more likely to subduct?','The older, colder, denser oceanic plate','The younger, warmer, less dense oceanic plate','Whichever plate is nearest a continent regardless of density','Both plates must rise because both are oceanic','Cooling makes old oceanic lithosphere denser and more susceptible to sinking.']
]
};
var primary={T1:'c1-cycle',T2:'c2-time',T3:'c3-seafloorage',T4:'c3-boundtypes',T5:'c1-lithos',T6:'c3-hotspot',T7:'c5-ptread',T8:'c5-grain',T9:'c5-special',T10:'c5-classify',T11:'c4-tetra',T12:'c5-bowen',T13:'c5-melt3',T14:'c5-visc',T15:'c5-heat',T16:'c3-subduction'};
var concepts={T1:['c1-cycle','c1-igintro','c1-sedenv','c1-sedenv','c1-cycle','c1-cycle'],T3:['c3-drift-problem','c3-magnetic','c3-seafloorage','c3-seafloorage','c3-seafloorage','c3-seafloorage'],T5:['c1-layers','c1-lithos','c1-isostasy','c1-lithos','c1-isostasy','c1-lithos'],T8:['c5-voltex','c5-grain','c5-grain','c5-grain','c5-grain','c5-voltex'],T11:['c4-tetra','c4-nonsil','c4-abundance','c4-silstruct','c4-bonds','c4-abundance'],T12:['c5-bowen','c5-partial','c5-bowen','c5-bowen','c5-partial','c5-bowen'],T14:['c6-shield','c6-composite','c6-types'],T16:['c3-subduction','c3-collision','c3-subduction']};
Object.keys(rows).forEach(function(tid){var topic=X.topics.find(function(t){return t.id===tid;});rows[tid].forEach(function(r,i){var form=forms[i%3],id='e1v1-'+form+'-'+tid+'-mc'+(i<3?'1':'2'),o=r.slice(1,5).map(function(v,k){return (k===0?'*':'')+v+'|'+(k===0?'Correct. ':'This does not fit the described process. ')+r[5];});var rot=(i+parseInt(tid.slice(1),10))%4;o=o.slice(rot).concat(o.slice(0,rot));A.mc(id,(concepts[tid]||[])[i]||primary[tid],r[0],o,r[5],topic.sources,{pool:'exam1',mock:false,topics:[tid],emphasis:['R0924:lines '+topic.lines]});X.forms[form].mc.push(id);});});
// Four exact terms and four actual explanations per form; eight distinct primary topics.
var short={
A:[
 ['T4','c3-boundtypes','Name the boundary type whose plates slide past each other.',['transform','transform boundary','transform fault','conservative','conservative boundary'],'Relative sliding is transform/conservative motion.'],
 ['T5','c1-isostasy','Name the buoyancy relationship used to explain crustal thickness and elevation.',['isostasy'],'Thickness and density affect the elevation of floating crustal blocks.'],
 ['T8','c5-voltex','Name the texture with large phenocrysts in a finer groundmass.',['porphyritic','porphyritic texture'],'Two crystal-size populations commonly record two cooling stages.'],
 ['T15','c5-heat','Name heat transfer by the bulk circulation of warm and cool material.',['convection','convective heat transfer'],'Moving material carries heat.'],
 ['T1','c1-cycle','Explain how a granite can become a sedimentary rock without first melting.','Weathering breaks down granite; erosion and transport move sediment; deposition and burial are followed by compaction and cementation.',['Includes breakdown of the granite by weathering','Includes transport and deposition of sediment','Includes lithification by compaction/cementation']],
 ['T3','c3-magnetic','Explain why matching magnetic stripe patterns support seafloor spreading.','Basalt cools at a ridge and records magnetic polarity. Reversals occur through time while crust moves outward, producing matching patterns on opposite sides.',['Basalt records polarity as it cools','Polarity changes through time','New crust moves outward on both sides']],
 ['T12','c5-partial','Explain why a partial melt can differ in composition from its source.','Minerals melt at different temperatures. Lower-melting components enter the liquid first, making it generally more silica-rich than the source and leaving a different residue.',['Different components have different melting behavior','Only some material melts','Melt is generally more silica-rich relative to its source']],
 ['T13','c5-subduction','Explain how water from a subducting slab can generate magma above the slab.','Water released by minerals in the slab enters the overlying mantle and lowers its solidus, allowing partial melting without requiring the slab itself to melt completely.',['Water is released from slab minerals','Water enters the overlying mantle','Water lowers the melting temperature']]
],
B:[
 ['T1','c1-cycle','What broad rock category forms by alteration of solid rock through heat and pressure?',['metamorphic','metamorphic rock'],'Metamorphism changes rock in the solid state.'],
 ['T7','c5-ptread','On the textbook pressure–temperature graphs, what variable is on the horizontal axis?',['temperature'],'Temperature increases from left to right on these graphs.'],
 ['T9','c5-voltex','Name the cavities left by gas bubbles in a volcanic rock.',['vesicles','vesicle'],'Gas bubbles can be preserved as lava solidifies.'],
 ['T11','c4-nonsil','A non-silicate mineral contains the SO₄²⁻ anion group. Name its mineral family.',['sulfate','sulphate','sulfates','sulphates'],'The sulfate group includes sulfur and oxygen.'],
 ['T4','c3-boundtypes','Explain why a ridge is called constructive and a subduction zone destructive.','A ridge creates new oceanic crust as plates separate. A subduction zone consumes oceanic lithosphere as one plate descends beneath another.',['Ridges create new oceanic crust','Plates separate at a ridge','Subduction consumes descending oceanic lithosphere']],
 ['T5','c1-lithos','Distinguish the lithosphere from the asthenosphere, including what the lithosphere contains.','Lithosphere is rigid crust plus uppermost mantle. Asthenosphere is underlying hotter, weaker, mostly solid mantle capable of slow flow.',['Lithosphere includes crust and uppermost mantle','Lithosphere is rigid','Asthenosphere is weaker and mostly solid']],
 ['T8','c5-grain','Explain why texture alone cannot tell you whether a rock is felsic or mafic.','Crystal size mainly reflects crystal growth and cooling history. Composition depends on chemistry/minerals; both felsic and mafic rocks can be coarse or fine.',['Texture records growth/cooling conditions','Composition requires mineral or chemical information','Both compositions can have different grain sizes']],
 ['T14','c5-visc','Explain why fluid basalt commonly makes broad shield volcanoes.','Low-viscosity basaltic lava travels far from the vent before solidifying. Repeated spreading flows accumulate a broad, gently sloping profile.',['Basaltic lava is relatively low viscosity','Lava spreads far from the vent','Repeated flows build a broad low-angle shape']]
],
C:[
 ['T2','c2-time','Name the broad division that follows the Paleozoic and precedes the Cenozoic.',['Mesozoic'],'Course sequence: Precambrian, Paleozoic, Mesozoic, Cenozoic.'],
 ['T10','c5-classify','Name the coarse-grained counterpart of basalt in the igneous chart.',['gabbro'],'Both are mafic; gabbro is coarse and basalt fine.'],
 ['T13','c5-melt3','Name melting caused chiefly by a pressure decrease as hot rock rises.',['decompression','decompression melting'],'Pressure decreases can carry hot mantle across its solidus.'],
 ['T14','c5-visc','Name the property that describes a magma’s resistance to flow.',['viscosity'],'Higher viscosity means greater resistance to flow.'],
 ['T3','c3-seafloorage','Explain which part of an oceanic plate thickens as it cools, distinguishing it from oceanic crust.','The mantle portion cools and becomes rigid, thickening the lithosphere. Basaltic oceanic crust does not simply thicken at the same rate; sediment cover can accumulate separately.',['Cooling converts more upper mantle into rigid lithosphere','Distinguishes lithosphere from oceanic crust','Does not confuse mantle thickening with sediment accumulation']],
 ['T6','c3-hotspot','Explain how the age pattern of a hot-spot chain can reveal plate-motion direction.','As the plate moves over a relatively stationary hot spot, former volcanoes are carried away. Ages increase in the motion direction from the current active center.',['Assumes a relatively stationary hot spot','Older volcanoes move with the plate','Direction from active/young toward older traces motion']],
 ['T11','c4-bonds','Distinguish ionic bonding from covalent bonding.','Ionic bonding is attraction between oppositely charged ions, commonly after electron transfer. Covalent bonding involves atoms sharing electron pairs.',['Ionic bonding involves charged ions','Opposite charges attract','Covalent bonding shares electron pairs']],
 ['T16','c3-collision','Explain why the India–Asia collision builds high mountains instead of a new oceanic island arc.','Two buoyant continents collide and resist deep subduction, causing shortening and thickening of continental crust. An oceanic island arc instead accompanies ocean–ocean subduction.',['Identifies continent–continent collision','Buoyant crust resists deep subduction','Shortening and thickening build mountains']]
]};
forms.forEach(function(f){short[f].forEach(function(r,i){var id='e1v1-'+f+'-sa'+(i+1),t=X.topics.find(function(t){return t.id===r[0];}),extra={pool:'exam1',mock:false,topics:[r[0]],emphasis:['R0924:lines '+t.lines]};if(i<4)A.fill(id,r[1],r[2],r[3],r[4],t.sources,extra);else A.teach(id,r[1],r[2],r[3],r[4],t.sources,extra);X.forms[f].sa.push(id);});});
})(window.L);
