/* Topic-specific writing prompts and rubrics; self-assessed, never remote AI grading. */
(function(L){
'use strict';
var writing=[
['E2T1','Name four land environments and four shoreline/ocean environments from this topic. Compare the sediment and transport in a delta, dune field, and lagoon. Give a geological example.',
'Land examples include mountain slopes, rivers/floodplains, deltas, dunes, glaciers, lakes, and wetlands. Coastal/ocean examples include beaches, tidal flats, barrier islands, lagoons, reefs, shelves/slopes, and deep ocean. A delta receives river-borne sediment where flow slows in standing water; dunes are wind-built, commonly well-sorted sand; a lagoon is sheltered coastal water behind a barrier or reef. The textbook examples show that one rock type can occur in several settings. The Chapter 7 introduction follows the Fraser River from glaciated mountains through lakes and braided channels to its delta beside Vancouver. This is a supplied geological example connecting source, transport and deposition.',
['Names four supplied land environments.','Names four supplied shoreline or ocean environments.','Correctly compares water transport at a delta, wind transport at dunes, and shelter in a lagoon.','Gives a supported example and uses sediment/structure evidence rather than one rock name.']],
['E2T2','Name the four chemical-weathering pathways in 7.3. Then distinguish weathering, transport, deposition, compaction, and cementation with one connected rock-to-sediment example.',
'The four listed chemical pathways are dissolution, oxidation, hydrolysis, and biological reactions. Physical weathering breaks material without necessarily changing mineral composition; chemical weathering changes or removes minerals. Transport carries the products and can abrade or sort them. Deposition occurs when material accumulates. Burial causes compaction, packing grains and reducing pores. Cementation precipitates minerals between grains and binds them. For example, weathered rock supplies quartz grains and clay to a stream; sand settles as the stream slows, is buried, and becomes sandstone through compaction and cementation.',
['Names all four listed chemical-weathering pathways.','Separates producing sediment from moving and depositing it.','Distinguishes compaction from cementation.','Connects a geological example through the processes without requiring melting.']],
['E2T3','Classify breccia, conglomerate, sandstone, and mudrock by diagnostic texture. Distinguish shale from other mudrock and explain why rounding does not prove a unique depositional setting.',
'Breccia contains angular gravel-sized clasts; conglomerate contains rounded gravel-sized clasts. Sandstone is dominated by sand-sized grains. Mudrock contains finer silt/clay-sized particles; shale splits readily along thin layers, whereas other mudstone may not. Composition can refine sandstone classification, such as feldspar-rich arkose. Abrasion can round clasts during stream transport or repeated wave action without long travel. Interpret an environment using grain size, shape, sorting, structures, fossils, and regional context. The supplied stream and beach conglomerate examples demonstrate this ambiguity.',
['Correctly classifies all four texture groups.','Identifies fissility as the shale distinction.','Explains abrasion and gives both stream and beach possibilities.','Uses another diagnostic clue or supported geological example to refine an interpretation.']],
['E2T4','Compare limestone, chalk, coquina, dolostone, evaporites, and coal. Explain ooid formation and give one carbonate setting from the supplied sources.',
'Limestone is primarily calcite and can be biological or precipitated. Chalk contains very small carbonate skeletal remains; coquina contains recognizable shell fragments. Dolostone is dominated by dolomite and commonly forms when magnesium-bearing fluids alter carbonate. Evaporites precipitate dissolved minerals as water becomes concentrated; coal is plant-derived organic material preserved and changed during burial. Ooids grow concentric carbonate coatings around grains rolled by agitated shallow water. A reef, shallow carbonate bank, lake carbonate deposit, or travertine-forming spring is a supplied geological example; these settings have different processes.',
['Distinguishes the six requested rock examples by composition or components.','Explains precipitation versus biological/organic accumulation.','Connects agitation and precipitation to ooid coatings.','Gives a supplied carbonate setting and connects it to its formation process.']],
['E2T5','Distinguish bedding, graded beds, cross beds, and mud cracks. Explain how two of these structures form and how they help interpret a depositional environment.',
'Bedding separates distinct depositional layers. A graded bed commonly fines upward as a sediment-bearing flow wanes and coarse particles settle before fine ones. Cross beds are inclined internal laminae deposited on the down-current side of migrating dunes or ripples; sets may be truncated by later migration. Mud cracks form as exposed wet mud dries and shrinks. Cross beds can form in wind dunes, streams, deltas, or shorelines, so their scale and context matter. Mud cracks support exposure and drying, while graded beds support changing flow and settling during a depositional event.',
['Correctly distinguishes all four structures.','Explains coarse-first settling and upward fining.','Explains migration and inclined lee-side deposition of cross beds.','Uses a supported setting or drying/exposure interpretation without claiming one structure uniquely proves every environment.']],
['E2T6','Explain transgression and regression using an upright facies sequence. Name the observations used to reconstruct the Denver or plateau history, then distinguish a reservoir, a seal, and a missing interval.',
'Transgression shifts marine environments landward; regression shifts marine environments seaward. In a simplified continuous upright sequence, marine mud above coastal sand supports transgression; coastal sand above marine mud supports shallowing or progradation. Relative water level, basin movement, and sediment supply all contribute. Denver coarse mountain-derived units record sediment shed from highlands, followed by other environments and later tilting/erosion. Plateau interpretation combines grains, structures, fossils, coal/plant material, and exposure evidence. A porous reservoir stores fluid; a low-permeability seal inhibits escape. An unconformity records erosion or nondeposition, not a uniform time duration.',
['Correctly distinguishes landward and seaward shoreline shifts.','Reads the stated upright facies order and notes an additional control besides global sea level.','Uses at least two actual rock attributes in a Denver or plateau example and separates later deformation.','Distinguishes reservoir/seal from an unconformity or missing interval.']],
['E2T7','Name the three types of differential stress and distinguish stress from strain. Sketch or describe the supplied strength–depth curve, including its axes, upper trend, transition, and lower trend.',
'Compression pushes inward, tension pulls outward, and shear acts in opposing directions along neighboring material. Stress is force per area; strain is a resulting change in shape or volume. In the supplied continental-crust graph, depth increases downward and strength increases rightward. Increasing confinement strengthens the brittle upper crust against fracture and slip. The curve reaches a maximum near a gradual brittle–ductile transition. At greater depth, increased temperature makes solid rock easier to deform ductilely, so the curve returns left toward lower strength. Neither the transition nor solid-state flow requires melting. Its depth varies with conditions.',
['Names compression, tension, and shear with the correct directions.','Separates stress from strain.','Reads both axes and describes increasing upper-crust strength followed by a maximum.','Explains deeper thermal weakening and solid-state flow; does not turn a schematic transition depth into a universal constant.']],
['E2T8','Define a joint and the hanging wall/footwall. Name normal, reverse, thrust, and strike-slip faults by relative movement, and give a supplied structural example.',
'A joint is a fracture without appreciable displacement parallel to the surface. A fault records relative movement. On an inclined plane, the hanging wall lies above it and the footwall below it. Hanging-wall-down movement is normal faulting, commonly associated with extension. Hanging-wall-up movement is reverse faulting, commonly associated with shortening; a thrust is a low-angle reverse fault. Strike-slip movement is mainly horizontal; oblique slip combines components. Basin and Range normal-faulted blocks provide a supplied example. Cooling columnar joints or unloading fractures provide joint examples. Trace matching markers rather than classify by cliff height alone.',
['Defines joint versus fault using displacement.','Locates hanging wall and footwall relative to the plane.','Correctly distinguishes all four requested fault types.','Gives a supported example and connects observed movement to the interpretation.']],
['E2T9','Name anticline, syncline, monocline, dome, and basin. Distinguish limbs, hinge, axial surface, and plunge, then explain how layer ages strengthen fold identification.',
'An upright anticline arches upward and has older layers in the core; an upright syncline forms a trough with younger layers in the core. A monocline is a step-like bend. A dome dips outward in several directions; a basin dips inward. Limbs are the sides of a fold and the hinge region has greatest curvature. An axial surface connects hinges through successive layers. Plunge is the inclination of the fold axis into the ground; it differs from axial-surface tilt. Older versus younger central layers supports anticline/syncline identification even when later deformation has complicated the simple shape. Folding commonly accommodates shortening.',
['Correctly distinguishes all five named structures.','Defines limbs, hinge, and axial surface.','Separates axis plunge from axial-surface tilt.','Uses layer ages and a supported shortening or map-pattern example.']],
['E2T10','Distinguish foliation, lineation, and relict bedding. Compare slate, phyllite, schist, gneiss, marble, and quartzite using texture and composition.',
'Foliation is planar alignment, flattening, or compositional banding; lineation is a linear alignment of elongated or stretched features. Relict bedding is an original sedimentary feature preserved through later change. Slate is fine and dull with cleavage; phyllite has a silky sheen; schist has visible aligned platy minerals; gneiss has coarse mineral bands. In a suitable shale-derived course model these can reflect progressively greater metamorphic conditions, but not every parent follows that path. Marble is recrystallized carbonate; quartzite is recrystallized quartz-rich sandstone. These commonly lack strong foliation, so composition is essential for identification.',
['Distinguishes planar, linear, and inherited features.','Correctly compares the four foliated rock examples.','Connects marble and quartzite to different compositions and parents.','Limits the progressive shale sequence to suitable starting composition.']],
['E2T11','Describe recrystallization, mineral reactions, pressure solution, and chemical change by fluids. Compare contact, regional, and subduction settings in pressure–temperature terms.',
'Recrystallization reorganizes or grows grains while rock remains solid. Mineral reactions create new stable minerals. Pressure solution dissolves material at highly stressed grain edges and redistributes it, helping create cleavage. Fluids can transport components into or out of rock and promote reactions. Contact metamorphism is dominated by local heating near magma, commonly without deformation. Regional metamorphism affects a broad area with heating and deformation; burial raises pressure. A relatively cool descending slab can experience high pressure at lower temperature than other rocks at similar depth. Mineral assemblages depend on both conditions and parent composition, so grade is not a single universal thermometer.',
['Correctly describes the four requested processes.','Keeps metamorphism in the solid state and distinguishes it from melting.','Compares heating near magma, regional burial/deformation, and high-pressure relatively cool subduction.','Uses composition and field relations as limits on mineral-based interpretation.']],
['E2T12','Connect extension, shortening, and shear to structures. Explain a dip slope and the timing of a sealed fault, then distinguish the older collision and later rifting in New England.',
'Extension can produce normal-fault systems, relatively raised horsts, and down-dropped grabens. Shortening can produce folds and reverse/thrust faults; sideways shear can produce strike-slip movement. Resistant inclined beds can form dip slopes, while fractured zones can erode more readily. Relief alone does not identify the structure. A fault cutting layers is younger than those layers; an unfaulted continuous unit sealing the break is younger than the observed movement. Bedding and cleavage may record different stages. New England preserves older Paleozoic collision-related deformation and metamorphism, later Mesozoic rifting, and still later erosion/deposition. Separate observations, relative order, and unsupported exact dates.',
['Correctly connects the three tectonic motions to structures.','Defines dip slope and notes a control from rock resistance/erosion.','Orders deposition, cutting movement, and the sealing unit from visible relations.','Separates collision, metamorphism, later rifting, and later surface history in a supported example.']]
];
writing.forEach(function(w){var it=L.ITEMS.find(function(it){return it.id==='e2-'+w[0]+'-teach';});it.q=w[1];it.model=w[2];it.rubric=w[3];it.coverage=L.EXAM2.topics.find(function(t){return t.id===w[0];}).concepts.slice();});
})(window.L);
