/* Sep 24 review: topic groupings are editorial. Answer authorities remain distinct from exam emphasis. */
(function(L){
'use strict';
var A=L.A;
L.SOURCES.R0924={t:'Professor Zhuang, Sep 24 Exam 1 review (stronger ASR transcript)',f:'EXAM ONE/Howe-Russel Geosciences Complex 4 copy.md',tier:1,unit:'',note:'Used for review emphasis and section format. Line references count the supplied file, including student header. ASR wording cross-checked against course slides/textbook; no claim of verbatim audio verification.'};
L.SOURCES.N0924={t:'Student exam-format header attached to Sep 24 transcript',f:'EXAM ONE/Howe-Russel Geosciences Complex 4 copy.md, lines 1–11',tier:3,unit:'',note:'The 8 short-answer count is a student note; spoken closing range is 6–8.'};
L.CONFIG.version='3.1.0 · Exam 1 review (2026-09-24)';
L.CHAPTERS[1].evidence='Lecture 1b; Sep 24 review confirms rock cycle, layers, and isostasy.';
L.CHAPTERS[6].evidence='Textbook; Sep 24 review confirms volcano shapes and viscosity. Other emphasis unconfirmed.';
L.SOURCES.TB6.note='Sep 24 review explicitly emphasizes volcano shapes and viscosity; it does not establish emphasis for every Chapter 6 topic.';
var topics=[
['T1','Rock cycle and its many paths',['c1-cycle','c1-sedenv','c1-igintro'],['L1B:19','L1B:23','L1B:26','L1B:29'],'529–800','examCycle',
 '<p><b>Igneous</b> rock forms when magma or lava cools and crystallizes. <b>Sedimentary</b> rock forms from sediment through deposition and lithification (compaction and cementation), or from material precipitated from water. <b>Metamorphic</b> rock is changed by heat, pressure, and fluids while remaining solid.</p><p>Practice the verbs: weathering breaks rock down; erosion removes it; transport moves it; deposition drops it. Burial can compact sediment or lead to metamorphism. Melting produces magma; cooling produces igneous rock. Uplift exposes rock to surface processes.</p><p><b>There is no mandatory starting point or single loop.</b> Granite can become metamorphic directly, or weather into sediment. Sedimentary rock can be buried and eventually melt.</p>',
 'Melting resets the route to magma. Metamorphism alone does not melt the rock.'],
['T2','Major divisions of geologic time',['c2-time'],['L2:23','L2:24'],'821–905','',
 '<p>Oldest → youngest: <b>Precambrian → Paleozoic → Mesozoic → Cenozoic.</b> These are the four broad blocks used in this course; Precambrian spans more than one formal eon. Earth is about <b>4.5 billion years</b> old.</p><p>Attach one landmark to each: most of Earth history; early diverse life on land and sea; dinosaurs; recent mammal-rich time. The review emphasizes the major blocks and their order, without requiring every period name.</p>',
 'The transcript says “million” at one point; the course timescale shows billions of years for Earth history.'],
['T3','Drift, spreading, stripes, and oceanic plate aging',['c3-drift-evidence','c3-drift-problem','c3-mor','c3-magnetic','c3-seafloorage'],['L3:12','L3:13','L3:14','L3:15','L3:23','L3:40','L3:41','L3:42'],'905–1300','examSeafloor',
 '<p>Wegener linked continental fits, fossils, rocks, and past climates, but lacked a convincing driving mechanism. Seafloor spreading supplied a testable process: new basalt forms at a ridge and records magnetic polarity as it cools. Matching reversal patterns on both sides support spreading.</p><p>Away from an undisturbed ridge, oceanic lithosphere is generally <b>older, cooler, denser, thicker, and lower</b>. The mantle part of the lithosphere thickens as it cools. Sediment cover also generally thickens with age.</p><p><b>Keep three thicknesses separate:</b> oceanic crust stays roughly similar in thickness; cooling mantle lithosphere thickens; sediment can accumulate on top.</p>',
 'Magnetic stripes are a record of field reversals, not different-colored continents. Age depends on ridge distance and spreading history.'],
['T4','Read plate maps and boundary types',['c3-boundtypes','c3-rifting','c3-transform','c3-geometry'],['L3:19','L3:20','L3:21','L3:22','L3:24','L3:31','L3:37'],'1300–1705','examPlates',
 '<table><tr><th>Relative motion</th><th>Boundary</th><th>Crustal budget</th></tr><tr><td>Apart</td><td>Divergent / constructive</td><td>Creates oceanic crust at ridges</td></tr><tr><td>Together</td><td>Convergent / destructive in subduction</td><td>Consumes oceanic lithosphere at trenches</td></tr><tr><td>Slide past</td><td>Transform / conservative</td><td>Neither creates nor consumes crust</td></tr></table><p>Count connected plate regions, not arrows, continents, or boundary lines. Relative motion determines boundary type. At a ridge, crust is added; at a subduction zone, oceanic lithosphere is consumed. Practice identifying these processes from the arrows and features shown.</p><p><b>Red Sea:</b> a young opening ocean basin. <b>Atlantic:</b> a mature spreading basin. <b>Pacific:</b> extensive subduction around its margins. This is a teaching comparison, not a single guaranteed future path for all oceans.</p>',
 'Continental collision makes thickened mountains; “destructive” does not mean all convergent crust immediately disappears.'],
['T5','Earth layers, the LAB, and isostasy',['c1-layers','c1-lithos','c1-isostasy'],['L1B:12','L1B:14','L1B:15','L1B:16'],'1716–2090','lithos',
 '<p><b>Composition:</b> crust, mantle, core. Oceanic crust is more mafic; continental crust is generally more felsic. The core is dominated by iron and nickel; its outer part is liquid and inner part solid.</p><p><b>Mechanical behavior:</b> the lithosphere is rigid crust plus uppermost mantle. The underlying asthenosphere is hotter, weak, and mostly solid; it can flow over geologic time. <b>LAB = lithosphere–asthenosphere boundary.</b> It is not the crust–mantle boundary.</p><p><b>Isostasy:</b> equally dense thicker blocks float higher and extend deeper; equally thick denser blocks sit lower. Thick continental crust helps explain the higher elevation of the Denver region compared with the Gulf Coast. The wooden-block analogy illustrates buoyancy, not a wholly liquid mantle.</p>',
 'Exact city crust-thickness numbers in the ASR are unclear, so the practice tests the supported relationship.'],
['T6','Hot spots and mantle plumes',['c3-hotspot','c5-hotspotmag'],['L3:43','TB5:5.11'],'2090–2300','',
 '<p>A <b>mantle plume</b> is rising unusually hot mantle, mostly solid before melting. At shallower depths, decompression can produce magma. A moving plate over a relatively stationary hot spot can leave a chain that gets older away from the active center.</p><p><b>Hawaii</b> illustrates an oceanic hot spot and basaltic volcanism. <b>Yellowstone</b> illustrates a continental hot spot; hot mantle-derived magma can transfer heat to continental crust and generate more silica-rich melts.</p>',
 'An island chain traces plate motion relative to a hot spot; it does not require a plate boundary at every volcano.'],
['T7','Read a pressure–temperature melting diagram',['c5-ptread'],['TB5:5.5','T0915'],'2280–2335','examPT',
 '<p>Read the axes first: temperature increases to the right; on these diagrams pressure/depth increases downward. The <b>solidus</b> marks the beginning of melting. Crossing into the melt-present field does not imply the entire rock is liquid.</p><p>A rightward path heats rock at similar pressure. An upward path reduces pressure at similar temperature. Water moves the solidus to a lower temperature, so melting can begin without heating the rock further.</p>',
 'A rising rock moves upward on a depth axis. Check which side of the applicable solidus each point occupies.'],
['T8','Textures reveal cooling history',['c5-grain','c5-voltex'],['TB5:5.1','TB5:5.8'],'2320–2540','',
 '<p><b>Coarse / phaneritic:</b> visible crystals, slower cooling. <b>Fine / aphanitic:</b> very small crystals, faster cooling. <b>Glassy:</b> cooling so fast crystals fail to grow. <b>Porphyritic:</b> large phenocrysts in a fine groundmass, commonly slow growth followed by faster cooling.</p><p><b>Pegmatitic:</b> exceptionally large crystals. The textbook emphasizes water-rich melt that allows efficient movement of atoms; “simply the slowest cooling” is an incomplete explanation.</p>',
 'Texture records growth conditions; composition is a separate axis. Fine-grained does not automatically mean mafic.'],
['T9','Vesicles, pumice, and scoria',['c5-special','c5-voltex'],['TB5:5.1','TB5:5.3'],'2540–2700','',
 '<p><b>Vesicles</b> are holes left by gas bubbles as pressure falls and lava solidifies. <b>Pumice</b> is highly vesicular, commonly light-colored, silica-rich volcanic glass; many pieces float. <b>Scoria</b> is commonly dark, mafic to intermediate, with thicker walls and fewer bubbles than pumice.</p><p>Glassy and vesicular describe different properties: a glass can contain vesicles, and a vesicular rock need not be pure glass.</p>',
 'A vesicle is a gas-bubble cavity, not a large crystal or evidence of deep slow cooling.'],
['T10','Igneous composition × texture chart',['c5-classify','c5-silica'],['TB5:5.2','TB5:5.3','IMG5737'],'2700–3000','igchart',
 '<p>Choose the composition column, then the texture row. Coarse/fine pairs: <b>granite/rhyolite</b> (felsic), <b>diorite/andesite</b> (intermediate), <b>gabbro/basalt</b> (mafic). <b>Peridotite</b> is coarse and ultramafic.</p><p>Felsic rocks commonly contain quartz and K-feldspar. Mafic rocks commonly contain pyroxene and Ca-rich plagioclase, sometimes olivine. Ultramafic rocks are rich in olivine and pyroxene. These mineral associations constrain the composition; crystal size then constrains the rock name.</p>',
 'Granite and rhyolite can have similar composition even though they crystallized at different rates.'],
['T11','Elements, silicates, anions, and bonds',['c4-abundance','c4-tetra','c4-silstruct','c4-commonsil','c4-nonsil','c4-bonds'],['TB4:4.6','TB4:4.7','TB4:4.8','TB4:4.9','TB4:4.12'],'3000–3400','silicate',
 '<p>The eight common crustal elements: <b>O, Si, Al, Fe, Ca, Na, K, Mg</b>. Oxygen and silicon dominate. A silicate tetrahedron contains <b>one Si surrounded by four O</b>. Tetrahedra can occur independently or link into single chains, double chains, sheets, or frameworks.</p><p>Examples: olivine isolated; pyroxene single chains; amphibole double chains; mica sheets; quartz and feldspar frameworks. Non-silicate groups are named by their principal anion or anion group: <b>sulfide S²⁻, sulfate SO₄²⁻, carbonate CO₃²⁻, oxide O²⁻</b>.</p><p><b>Ionic:</b> attraction between charged ions. <b>Covalent:</b> shared electron pairs. <b>Metallic:</b> mobile shared electrons. <b>Van der Waals / molecular:</b> weaker attractions between units or layers.</p>',
 'Sulfide and sulfate differ chemically; sulfate includes oxygen. The transcript’s ion charge is unreliable, so the key follows the textbook.'],
['T12','Bowen’s series and partial melting',['c5-bowen','c5-partial','c5-cool'],['TB5:5.5','TB5:5.8'],'3400–3720','bowen',
 '<p>Cooling, high → low temperature: <b>olivine → pyroxene → amphibole → biotite</b> in the discontinuous branch. Plagioclase changes from Ca-rich toward Na-rich in the continuous branch. K-feldspar, muscovite, and quartz are low-temperature minerals.</p><p>For the simplified course model, heating reverses the general order: lower-melting components enter the liquid first. A <b>partial melt is generally more silica-rich than its source</b>. That does not make every partial melt rhyolite: mantle peridotite can yield basalt, which is more silica-rich than its ultramafic source.</p>',
 'The first mineral to crystallize on cooling is not the first to melt on heating.'],
['T13','Three melting mechanisms and tectonic settings',['c5-melt3','c5-divergent','c5-subduction','c5-hotspotmag'],['TB5:5.5','TB5:5.9','TB5:5.10','TB5:5.11'],'3730–4150','examPT',
 '<p><b>Add heat:</b> hot magma transfers heat to surrounding rock. <b>Lower pressure:</b> rising mantle undergoes decompression beneath ridges and hot spots. <b>Add water/volatiles:</b> slab-derived water lowers the melting temperature of the overlying mantle in subduction zones.</p><p>Connect setting → process → graph. Ridge: upwelling, pressure decrease. Subduction: water released from minerals in the slab, lower solidus. Continental hot spot: mantle decompression plus heat transfer into crust can both matter.</p>',
 'Subduction magma is not explained by saying the entire slab simply melts from friction.'],
['T14','Viscosity and volcano shape',['c5-visc','c6-types','c6-gasvisc','c6-shield','c6-composite'],['TB5:5.7','TB6:6.1','TB6:6.3','TB6:6.4','TB6:6.7','TB6:6.8'],'4150–4350','volcano',
 '<p><b>Viscosity</b> is resistance to flow. More silica and lower temperature generally increase viscosity. Fluid basalt spreads to build broad <b>shield volcanoes</b>. More viscous magma and alternating eruption products build steeper <b>composite volcanoes</b> such as Mount Fuji and Mount St. Helens.</p><p><b>Cinder/scoria cones</b> are small, steep accumulations of loose fragments around a vent; their steep slopes do not mean the magma must be felsic. Gas escape, composition, temperature, and crystals all influence eruption behavior.</p>',
 'Shape is evidence about processes. A steep cinder cone and a composite volcano can form by different mechanisms.'],
['T15','Convection, conduction, and radiation',['c5-heat'],['TB5:5.4','TB5:5.8'],'4350–4590','examHeat',
 '<p><b>Convection:</b> heat carried by moving material—warm, less dense material rises and cooler, denser material sinks. The boiling-pot circulation is the review analogy.</p><p><b>Conduction:</b> heat moves through material or across contact without bulk movement—magma heats its wall rock; heat passes through the pot wall. <b>Radiation:</b> heat carried by electromagnetic waves—hot lava emits thermal radiation.</p><p>Plume ascent carries heat by convection; transfer from magma into neighboring crust can occur by conduction. Distinguish heat transfer from the separate pressure decrease that causes decompression melting.</p>',
 'Radiation wording is unclear in the ASR. Its definition and example here are supported by textbook 5.4 and 5.8.'],
['T16','Convergent boundaries and density',['c3-subduction','c3-collision'],['L3:25','L3:26','L3:28','L3:29','L3:30'],'4600–4740','boundary',
 '<p><b>Ocean–ocean:</b> one oceanic plate subducts, commonly the older, colder, denser one; an island arc can form. <b>Ocean–continent:</b> denser oceanic lithosphere subducts beneath buoyant continental crust; a continental volcanic arc can form.</p><p><b>Continent–continent:</b> buoyant continental crust resists deep subduction; collision thickens crust and builds mountains. India–Asia and the Himalaya are the class example.</p>',
 '“Which one sinks?” requires the plate types and density/age context. Ocean–ocean convergence does not mean both plates sink together.']
];
L.EXAM1={version:1,topics:topics.map(function(t){return {id:t[0],title:t[1],concepts:t[2],sources:t[3],lines:t[4],diagram:t[5],html:t[6],trap:t[7]};}),forms:{A:{mc:[],sa:[],cases:[]},B:{mc:[],sa:[],cases:[]},C:{mc:[],sa:[],cases:[]}}};
// Only supplied McGraw-Hill source images; no generated diagrams in Exam 1.
function img(path,cap){return {kind:'img',src:'assets/img/'+path,cap:cap,alt:cap};}
var sourceImages={
T1:[img('slides/l1b-slide-29.jpg','McGraw-Hill rock cycle · Lecture 1b, slide 29')],
T2:[img('atlas/geologic-timescale-ch2.jpg','McGraw-Hill geologic time scale · Lecture 2, slide 24')],
T3:[img('slides/l3-slide-40.jpg','McGraw-Hill magnetic reversals and spreading · Lecture 3, slide 40'),img('slides/l3-slide-42.jpg','McGraw-Hill seafloor age and sediment · Lecture 3, slide 42'),img('slides/l3-slide-23.jpg','McGraw-Hill ridge cross section · Lecture 3, slide 23')],
T4:[img('slides/l3-slide-20.jpg','McGraw-Hill three boundary types · Lecture 3, slide 20'),img('slides/l3-slide-37.jpg','McGraw-Hill two-plate boundary geometry · Lecture 3, slide 37'),img('slides/l3-slide-24.jpg','McGraw-Hill continental rifting · Lecture 3, slide 24')],
T5:[img('slides/l1b-slide-16.jpg','McGraw-Hill floating wood blocks · Lecture 1b, slide 16'),img('slides/l1b-slide-14.jpg','McGraw-Hill lithosphere and asthenosphere · Lecture 1b, slide 14'),img('slides/l1b-slide-12.jpg','McGraw-Hill compositional layers · Lecture 1b, slide 12')],
T6:[img('slides/l3-slide-43.jpg','McGraw-Hill hot-spot chain · Lecture 3, slide 43')],
T7:[img('tb45/figure-28.jpg','McGraw-Hill heating graph · section 5.5'),img('tb45/figure-29.jpg','McGraw-Hill decompression graph · section 5.5'),img('tb45/figure-30.jpg','McGraw-Hill wet and dry melting graph · section 5.5')],
T8:[img('tb/ch5-porphyritic.jpg','McGraw-Hill porphyritic specimen · section 5.1'),img('tb/ch5-pegmatite-tex.jpg','McGraw-Hill pegmatitic specimen · section 5.1')],
T9:[img('tb/ch5-pumice.jpg','McGraw-Hill pumice specimen · section 5.3'),img('tb/ch5-scoria.jpg','McGraw-Hill scoria specimen · section 5.3')],
T10:[img('exam1/class-chart.jpg','Your classroom photograph of McGraw-Hill figure 05.03.b1')],
T11:[img('tb45/figure-09.jpg','McGraw-Hill silicon–oxygen tetrahedron · section 4.7'),img('tb45/figure-10.jpg','McGraw-Hill linked tetrahedra · section 4.7')],
T12:[img('tb45/figure-34.jpg','McGraw-Hill Bowen reaction series · section 5.8')],
T13:[img('tb45/figure-29.jpg','McGraw-Hill decompression graph · section 5.5'),img('slides/l3-slide-26.jpg','McGraw-Hill slab water and mantle melting · Lecture 3, slide 26')],
T14:[img('tb/ch6-block-shield.jpg','McGraw-Hill shield volcano · section 6.1'),img('tb/ch6-block-composite.jpg','McGraw-Hill composite volcano · section 6.1'),img('tb/ch6-block-scoria-cone.jpg','McGraw-Hill scoria cone · section 6.1')],
T15:[img('exam1/heat-transfer.png','McGraw-Hill stove and convection-cell figure 05.04.b4 · section 5.4'),img('exam1/heat-tectonics.png','McGraw-Hill heat transfer in tectonics · section 5.4')],
T16:[img('slides/l3-slide-25.jpg','McGraw-Hill ocean–ocean convergence · Lecture 3, slide 25'),img('slides/l3-slide-30.jpg','McGraw-Hill continental collision · Lecture 3, slide 30')]
};
L.EXAM1.topics.forEach(function(t){t.media=sourceImages[t.id];delete t.diagram;});
L.EXAM_CONCEPT_TOPICS={};
L.EXAM1.topics.forEach(function(t){t.concepts.forEach(function(c){(L.EXAM_CONCEPT_TOPICS[c]=L.EXAM_CONCEPT_TOPICS[c]||[]).push(t.id);});});
L.examTopics=function(it){if(it.topics)return it.topics;var ts=L.EXAM_CONCEPT_TOPICS[it.c]||[];
 if((it.c==='c5-voltex'||it.c==='c5-special')&&/weld|breccia|tuff|pyroclastic/i.test(it.q||''))return [];
 if(it.c==='c5-heat'&&/supplies most|radioactive|percent|formation/i.test(it.q||''))return [];
 return ts;};
// Six targeted Guide additions keep original cards and IDs intact.
[['T1','c1s7'],['T3','c3s8'],['T4','c3s3'],['T5','c1s4'],['T14','c6s1'],['T15','c5s3']].forEach(function(p){var t=L.EXAM1.topics.find(function(x){return x.id===p[0];});A.cards(p[1],[{id:'exam1-guide-'+t.id,h:'Exam 1 focus: '+t.title,c:t.concepts.filter(function(c){return L.CONCEPTS[c].sec===p[1];}),src:t.sources.concat(['R0924:lines '+t.lines]),html:t.html,traps:[t.trap],media:t.media}]);});
L.SECTIONS.find(function(s){return s.id==='c1s7';}).note='Sep 24 review explicitly confirms rock cycle, three rock types, and multiple pathways. Other continuation topics retain their original evidence limits.';
L.SECTIONS.find(function(s){return s.id==='c1s7';}).flag='rock cycle reviewed Sep 24';
L.COVERAGE[0][2]='Sep 24 explicitly revisits rock cycle, layers, and isostasy. Other continuation content keeps its original limits.';
L.COVERAGE[4][2]='Sep 24 explicitly reviews textures, classification, Bowen, partial melting, heat transfer, and melting settings. It does not establish equal emphasis for every Chapter 5 detail.';
L.COVERAGE[5][2]='Sep 24 confirms viscosity and volcano types/examples. Remaining Chapter 6 topics are textbook supported; their review emphasis is unconfirmed.';
L.CONFLICTS=L.CONFLICTS.filter(function(x){return !/Exam format evidence|mock|Chapter 6|Ch 6|not ready|40–50%/i.test(x);});
L.CONFLICTS.unshift('<b>Sep 24 supersedes the preliminary format.</b> 25 multiple-choice questions × 2 = 50 points (50% of exam points). The spoken closing range is 6–8 short answers and 6–7 investigations. This lab uses 8 and 7 as practice defaults. Section 2/3 point split and exact topic placement remain unconfirmed.');
L.CONFLICTS.push('<b>Review transcription.</b> The first 11 lines are student notes. The 16 topic groups are editorial. Ambiguous ASR scientific claims are resolved using slides/textbook; exact city crust thicknesses are not tested.');
// Refresh dated blanket coverage notices while preserving card IDs and original teaching.
Object.keys(L.GUIDE).forEach(function(sec){L.GUIDE[sec].forEach(function(card){
 card.html=card.html.replace(/<p class="small muted">Textbook section\. The supplied recordings end at Bowen[^<]*<\/p>/g,'<p class="small muted">Sep 24 review explicitly covers melting mechanisms and their tectonic settings. Additional details in this section are broader textbook study.</p>');
 card.html=card.html.replace(/<p class="small muted">Chapter 6 is textbook-only[^<]*<\/p>/g,'<p class="small muted">Textbook source. Sep 24 review emphasizes volcano types, examples, and viscosity; other details here remain broader course material.</p>');
 if(card.id==='g1-7c'){card.h='Metamorphic rocks, rock cycle, and Earth’s spheres';card.html=card.html.replace('<span class="badge flag">continuation</span>','<span class="badge flag">Rock cycle reviewed Sep 24</span>');}
});});
L.EXAM_FACTS='<ul class="facts"><li><b>Tuesday, Sep 29 · Chapters 1–6.</b> 10:30 AM, Howe-Russell W130. Paper exam; no notes or devices.</li><li><b>Section 1:</b> 25 multiple-choice questions × 2 points = 50 points (50% of exam points).</li><li><b>Section 2:</b> short definitions and concepts; the professor’s closing range was 6–8 questions.</li><li><b>Section 3:</b> 6–7 investigations involving diagrams, matching, and explanations.</li><li><b>Practice defaults:</b> 8 short answers and 7 investigations, immediate feedback, untimed. Exact question wording, topic-to-section placement, and Section 2/3 weights are unknown.</li></ul>';
})(window.L);
