/* Chapters 7–8, additive private release. Original teaching and questions.
   Original retrieval practice; private calibration remains local. No Exam 2 mocks. */
(function(L){
'use strict';
var A=L.A;
L.EXAMS={exam1:{id:'exam1',label:'Exam 1',chapters:[1,2,3,4,5,6],available:[1,2,3,4,5,6],mocks:true},exam2:{id:'exam2',label:'Exam 2',chapters:[7,8,9,10,11,12],available:[7,8],mocks:false}};
L.CHAPTERS[7]={name:'Ch 7 · Sedimentary Environments and Rocks',short:'Ch 7',evidence:'Supplied textbook 7.1–7.16, completed Connect captures, classroom sources. Lecture-confirmation limits are shown per lesson.'};
L.CHAPTERS[8]={name:'Ch 8 · Deformation and Metamorphism',short:'Ch 8',evidence:'Textbook 8.1–8.15; October 1 and 6 transcripts; classroom strength diagram; October 6 ILEA. Later textbook material is labeled continuation.'};
L.SOURCES.TB7={t:'Exploring Geology · supplied Chapter 7 PDFs',f:'TEST TWO/TEXTBOOK PAGES/CHAPTER 7',tier:2,unit:'section'};
L.SOURCES.TB8={t:'Exploring Geology · supplied Chapter 8 PDFs',f:'TEST TWO/TEXTBOOK PAGES/CH 8',tier:2,unit:'section'};
L.SOURCES.E2DNA=L.EXAM2_SOURCE_MODE==='private'?{t:'Professor DNA · October 6 intake',f:'AGENIC/PROFESSOR_DNA.md',tier:3,note:'Private format calibration; no Exam 2 quotas or predictions.'}:{t:'Original practice design',f:'',tier:4,note:'Observation, classification, lists, word banks, and explanations are practice formats.'};
L.SOURCES.E2T1001={t:'Recorded lecture · October 1',f:'TEST TWO/RECORDED LECTURES/10:1:26.txt',tier:2,note:'ASR; technical terms checked against textbook. Stress through metamorphic fabrics.'};
L.SOURCES.E2T1006={t:'Recorded lecture · October 6',f:'TEST TWO/RECORDED LECTURES/10:06:26.md',tier:2,note:'ASR; Moho/isostasy ILEA, stress, metamorphic fabrics/processes/settings. Ends before continental collision discussion.'};
L.SOURCES.E2T0924={t:'Recorded lecture · September 24',f:'TEST TWO/RECORDED LECTURES/9:24:26.txt',tier:2,note:'Exam 1 review excluded. Only Chapter 7 continuation at lines 345–357 is relevant here.'};
L.SOURCES.E2C7={t:'Completed Chapter 7 Connect captures',f:'TEST TWO/MCGRAWHILL BULLSHIZ/CH 7',tier:2,note:'Private examples for style and representation; new practice is original.'};
L.SOURCES.E2C8={t:'Chapter 8 Connect summaries',f:'TEST TWO/MCGRAWHILL BULLSHIZ/CH 8',tier:3,note:'Secondary written summaries; original screenshots unavailable. Keys cross-checked with textbook; image-specific claims gated.'};
L.SOURCES.E2ILEA={t:'October 6 ILEA · original worksheet photograph',f:'TEST TWO/ILEAs/ILEA 10:06:26/ilea 10:6:26.jpg',tier:2,note:'Answer screenshot is a draft, not an official key. Numerical readback follows the visible graph.'};
L.SOURCES.E2PHOTO={t:'Classroom rock-strength diagram photograph',f:'TEST TWO/in class pix/important diagram.JPG',tier:2,note:'Matched to textbook 8.1, PDF page 7.'};
var groups=[
 ['E2T1',7,'Land, shoreline, and ocean environments',['7.1','7.2']],
 ['E2T2',7,'From weathered rock to sedimentary rock',['7.3','7.4','7.5']],
 ['E2T3',7,'Read clastic rocks and their settings',['7.8','7.9','7.10']],
 ['E2T4',7,'Chemical, biological, and carbonate rocks',['7.6','7.11']],
 ['E2T5',7,'Read layers, graded beds, and cross beds',['7.7']],
 ['E2T6',7,'Changing environments and sedimentary history',['7.12','7.13','7.14','7.15','7.16']],
 ['E2T7',8,'Stress, strain, and the brittle–ductile transition',['8.1','8.2']],
 ['E2T8',8,'Joints, faults, and relative movement',['8.3','8.4']],
 ['E2T9',8,'Folds: geometry, orientation, and shortening',['8.5']],
 ['E2T10',8,'Metamorphic fabrics and rock identification',['8.6','8.7']],
 ['E2T11',8,'Metamorphic processes and pressure–temperature settings',['8.8','8.9']],
 ['E2T12',8,'Tectonic settings, landscapes, and structural history',['8.10','8.11','8.12','8.13','8.14','8.15']]
];
L.EXAM2={version:1,topics:groups.map(function(g){return {id:g[0],ch:g[1],title:g[2],sections:g[3],concepts:[],sources:g[3].map(function(n){return 'TB'+g[1]+':'+n;}),media:[]};}),mocksReady:false};
function topic(n){return L.EXAM2.topics.find(function(t){return t.sections.indexOf(n)>=0;});}
function concept(n){return 'c'+n.replace('.','-')+'-core';}
function support(n){
 if(n.split('.')[0]==='8' && +n.split('.')[1]<=8)return 'Lecture-confirmed topic · October 1/6; factual detail checked against the textbook.';
 if(n==='8.9')return 'Lecture-confirmed in part · October 6 reached subduction/contact/regional settings; collision material continues in the textbook.';
 if(n==='7.14')return 'Lecture-confirmed introduction · September 24 ending; detailed coverage follows the textbook.';
 return 'Textbook-backed coverage · supplied chapter material; this section is not individually confirmed by the supplied lecture excerpts.';
}
function lesson(n,title,html,trap,q1,o1,x1,q2,o2,x2){
 var ch=+n.split('.')[0],sec='c'+n.replace('.','s'),c=concept(n),t=topic(n),src=['TB'+ch+':'+n];
 A.section({id:sec,ch:ch,n:n,title:title,srcText:'Textbook '+n+' · '+support(n),src:src,examId:'exam2',note:support(n),concepts:[[c,title]]});t.concepts.push(c);
 var book=L.EXAM2_SOURCES[n],pages=book.pages,selected=pages.filter(function(p){return p.n===2||/Strength of Continental Crust|Graded Beds|Cross Beds|transgression|regional metamorphism|hanging wall|axial surface/i.test(p.text);}).slice(0,4);
 if(!selected.length)selected=pages.slice(0,1);
 var media=selected.map(function(p){return {kind:'img',src:p.display||p.image,alt:p.authored?'Study diagram for '+title:'Supplied textbook '+n+', PDF page '+p.n+': '+title,cap:p.authored?'Original lab schematic · supports textbook section '+n:'Exploring Geology · '+n+' · PDF page '+p.n+' (original page render)'};});
 A.cards(sec,[{id:'g'+n.replace('.','-')+'a',h:title,c:[c],src:src,html:html,media:media,traps:[trap],examId:'exam2'}]);
 t.media=t.media.concat(media.slice(0,1));
 [[q1,o1,x1],[q2,o2,x2]].forEach(function(q,i){A.mc('e2-'+n+'-m'+(i+1),c,q[0],q[1],q[2],src,{examId:'exam2',mock:false,topics:[t.id],hint:'Identify the diagnostic observation before choosing a name. Revisit textbook '+n+'.',evidence:'docs/EXAM2_SOURCE_LEDGER.md'});});
}

lesson('7.1','Sedimentary environments on land',
 '<p>Begin with the setting, then ask what transports sediment and where it loses energy. Steep mountain streams can move gravel and boulders. A stream can split and rejoin into braided channels; on gentler terrain, meandering channels flood adjacent flat land. <b>Fluvial</b> means stream or river processes. Floodplains accumulate mud and sand during floods.</p><p>A <b>delta</b> grows where a stream enters standing water and slows. Wind selectively moves sand and finer particles; dunes commonly contain well-sorted sand. Glaciers carry a wide size range and release sediment as they melt. Lakes combine active shorelines with quieter deeper water. Wetlands preserve plant material where saturation limits oxidation.</p><p>Use several clues together: grain size, sorting, sedimentary structures, and plant or shell remains. A single sandstone does not uniquely identify a desert. Compare modern environments with the original overview before interpreting an ancient rock.</p>',
 'A delta is a depositional body at a stream mouth; it is not the same as a floodplain along the channel.',
 'A river enters a lake. Its current slows and sediment builds outward from its mouth. Which feature is forming?',
 ['*Delta|Sediment accumulates at the mouth as flow slows.','Floodplain|A floodplain lies beside a river and receives flood deposits.','Sand dune|Wind builds a dune.','Glacial moraine|A glacier deposits this material.'],'A delta forms where a stream enters standing water and drops sediment.',
 'Which pair of observations best fits deposition on a river floodplain?',
 ['*Fine sediment and repeated overbank floods|Floodwater carries mud and sand over flat ground.','Coarse blocks and collapse from a cliff|This fits a steep slope.','Shell debris and tidal flooding|This fits a coastal setting.','Well-sorted sand and wind migration|This fits dunes.'],'Floodplains receive fine material when water spreads beyond the channel.');
lesson('7.2','Shoreline and ocean environments',
 '<p>Beaches accumulate sediment moved by waves and currents; their grains depend on local supply. A <b>lagoon</b> is sheltered water behind a reef or barrier island. A <b>reef</b> is constructed by organisms, commonly in shallow, warm, clear water. A barrier island is a long, narrow sand body separated from shore by lagoon or marsh.</p><p>Continental shelves and slopes receive sand, mud, and carbonate sediment. Material can move downslope in a <b>turbidity current</b>, a sediment-laden water flow. Deep seafloor commonly receives fine dust and the remains of small marine organisms. Tidal flats alternate between flooding and exposure; coastal dunes form when wind moves shoreline sand inland.</p><p>Distinguish a sheltered lagoon from open shelf water and a river delta from a reef. Ocean depth alone does not determine the sediment: supply, water clarity, organisms, and transport also matter.</p>',
 'Warm clear reef water and muddy river-fed water are different environments, even when both are shallow.',
 'A shallow coastal water body lies behind a narrow sand island and is protected from large waves. What is it?',
 ['*Lagoon|The barrier shelters a lagoon.','Continental slope|The slope lies beyond the shelf.','Submarine canyon|A canyon cuts the slope.','Open-ocean basin|This is deep ocean rather than sheltered coastal water.'],'Sheltered nearshore water behind a barrier or reef is a lagoon.',
 'What carries a mixture of sediment and water from a continental slope toward deeper water?',
 ['*Turbidity current|A dense sediment-laden current flows downslope.','Coastal dune migration|This is wind transport on land.','Reef growth|Organisms construct reef material.','Tidal exposure|This exposes a flat at low tide.'],'Turbidity currents transport sand and mud downslope under water.');
lesson('7.3','Weathering produces clasts and dissolved material',
 '<p><b>Physical weathering</b> breaks rock without requiring a chemical change. Near-surface fracturing, frost or mineral wedging, thermal expansion, and biological activity can loosen pieces. Expansion on unloading and roots growing in cracks are physical mechanisms. Thermal expansion is included in the textbook with a caution about its relative importance.</p><p><b>Chemical weathering</b> changes minerals. Dissolution carries soluble material away; oxidation combines susceptible material with oxygen; hydrolysis commonly turns silicate minerals into clay and dissolved products. Organisms can produce acids and drive chemical reactions.</p><p>Starting composition and environmental conditions determine the products. Resistant quartz can survive transport while less stable minerals break down. Physical breakup exposes fresh surfaces to chemical reactions, so both processes can work together. Weathering produces material; erosion removes it, and transport carries it elsewhere.</p>',
 'Weathering, erosion, and transport are related processes with different meanings.',
 'Water reacts with feldspar and produces clay minerals plus dissolved substances. Which process best describes the change?',
 ['*Hydrolysis|Water reacts chemically with silicate minerals.','Frost wedging|Freezing water physically opens fractures.','Compaction|Burial packs grains together.','Cementation|Minerals bind deposited grains.'],'Hydrolysis changes mineral composition and commonly produces clay.',
 'A root widens a fracture and separates pieces of bedrock without changing their minerals. This is mainly:',
 ['*Physical weathering|The rock is broken apart.','Chemical precipitation|Dissolved material forms new solid minerals.','Regional metamorphism|Buried rock changes under heat and pressure.','Hydrolysis|Water reacts with minerals.'],'Mechanical breakup by a growing root is physical weathering.');
lesson('7.4','Clast size, shape, sorting, and transport',
 '<p>Describe <b>size</b>, <b>roundness</b>, and <b>sorting</b> independently. Gravel includes granules, pebbles, cobbles, and boulders; sand is smaller than gravel; silt and clay together are mud. The grain-size table in the original page is the authority for exact boundaries. Clay can refer to a particle size or a mineral group.</p><p>Angular grains have sharp edges; abrasion during transport can round them. Sorting describes the range of sizes. Well-sorted sediment has a narrow range; poorly sorted sediment mixes sizes. Rounding and sorting can develop during repeated transport, but do not infer a unique travel distance from either alone.</p><p>The material transported depends on the agent, current strength, clast size and density, and available sediment. Wind selectively moves sand and finer particles; glaciers can carry a broad mixture. Strong water currents can move larger clasts than weak currents. Observe all three properties before assigning a rock name or environment.</p>',
 'Rounded does not mean well sorted; roundness and size range are separate properties.',
 'A deposit contains rounded pebbles, sand, and clay. Which description follows directly from those observations?',
 ['*Rounded and poorly sorted|The clasts are rounded but span a wide size range.','Angular and well sorted|Neither property fits.','Rounded and well sorted|Roundness does not remove the broad size range.','Angular and poorly sorted|Sorting fits, but roundness does not.'],'A broad range of grain sizes is poor sorting, regardless of grain roundness.',
 'A current weakens while carrying gravel, sand, and mud. Which fraction normally becomes difficult to carry first?',
 ['*Gravel|Larger clasts generally require stronger currents.','Clay|Fine clay can remain suspended.','Dissolved ions|Dissolved substances are not clasts.','All sizes together|Different sizes respond differently.'],'Coarse clasts generally settle before finer suspended material as flow weakens.');
lesson('7.5','Clastic rocks and lithification',
 '<p>Classify a clastic rock by the particles preserved within it. Rounded gravel forms <b>conglomerate</b>; angular gravel forms <b>breccia</b>. Sand forms sandstone; silt forms siltstone. Fine clay-rich sediment can form shale, whose aligned grains allow thin sheets to split apart. Quartz sandstone is quartz rich; arkose contains abundant feldspar; graywacke contains mixed grains and rock fragments.</p><p><b>Lithification</b> changes loose sediment into rock. Compaction moves grains closer together and expels pore fluids. Cementation precipitates mineral material in the pores and binds grains. Compaction is particularly substantial in initially water-rich mud. Common cements include carbonate, silica, and iron-bearing material.</p><p>Composition, grain size, and roundness carry different information. Sandstone is a size-based name; feldspar content adds a compositional distinction. A red stain may be cement or oxidation rather than the original grains. Read the clast chart and the compaction sequence separately.</p>',
 'Cementation adds binding material; compaction reduces pore space by packing grains.',
 'A rock contains large, angular fragments surrounded by finer sediment. Which name is most appropriate?',
 ['*Breccia|Large angular clasts distinguish breccia.','Conglomerate|Its large clasts are rounded.','Siltstone|Its dominant clasts are much finer.','Quartz sandstone|Its dominant grains are sand-sized quartz.'],'Breccia is a coarse clastic rock with angular fragments.',
 'Minerals precipitate between deposited sand grains and bind them together. Which part of lithification is occurring?',
 ['*Cementation|New mineral material binds grains.','Compaction|This packs existing grains more closely.','Transport|This carries sediment to a new location.','Weathering|This breaks down exposed material.'],'Mineral precipitation in pores produces cementation.');
lesson('7.6','Nonclastic sedimentary rocks',
 '<p>Some sedimentary rocks form from dissolved substances or organic material rather than chiefly from transported rock fragments. Evaporation concentrates dissolved ions and can precipitate <b>evaporites</b>, including rock salt and gypsum. Chemical precipitation also forms minerals where water chemistry changes.</p><p>Organisms extract dissolved substances to build shells and skeletons. Accumulation of carbonate remains can form limestone; silica-rich remains can contribute to chert. Plant material accumulates in waterlogged environments and, after burial and alteration, can form coal. These origins overlap: a biochemical rock can include fragments of organisms, yet its material originated through biological extraction from water.</p><p>Use the dominant material and formation process to interpret the rock. Halite is a mineral; rock salt is a rock composed mostly of halite. Coal records organic accumulation and preservation, whereas an evaporite records concentration and precipitation from water.</p>',
 'Chemical sedimentary rocks are not all evaporites; precipitation and biological accumulation also matter.',
 'A restricted basin loses water through evaporation and leaves halite behind. What sedimentary rock can result?',
 ['*Rock salt|Halite accumulates as an evaporite.','Quartz sandstone|Quartz sand requires a clastic source.','Coal|Coal forms from plant material.','Conglomerate|This requires rounded coarse clasts.'],'Evaporation concentrates dissolved ions until salt minerals precipitate.',
 'Which observation best supports an organic origin for coal?',
 ['*Accumulated plant material in a wetland|Waterlogged vegetation can be preserved and buried.','Rounded pebbles in a river channel|These form coarse clastic sediment.','Salt crystals in an evaporating basin|These form evaporites.','Interlocking crystals beside an intrusion|This suggests metamorphism.'],'Coal originates from accumulated plant material preserved and changed during burial.');
lesson('7.7','Layering and sedimentary structures',
 '<p>Beds preserve changes in sediment supply, current strength, environment, or sea level. A boundary can mark erosion or a pause in deposition; not every layer represents an equal amount of time. Layer thickness and composition must be interpreted with other evidence.</p><p><b>Graded bedding</b> commonly places coarse grains at the bottom and successively finer grains above, recording waning current strength. A settling jar models this sorting. <b>Cross beds</b> are inclined layers within a larger bed, formed as dunes or ripples migrate. Their shape can preserve flow direction. Large cross beds commonly occur in wind-blown dunes; smaller examples also occur in streams and shorelines.</p><p>Separate a graded bed from a whole sequence that changes upward. One event can produce a graded bed; a succession of environments can produce a longer fining- or coarsening-upward sequence. Observe contacts, internal layers, and grain-size trends before explaining the process.</p>',
 'Inclined cross beds inside one bed do not by themselves prove later tectonic tilting.',
 'One bed changes from coarse sand at its base to fine silt at its top. Which interpretation best fits?',
 ['*A depositing current weakened over time|Finer sediment settled after coarser material.','The depositing current strengthened over time|This favors upward coarsening.','The entire bed melted and recrystallized|This would destroy its sedimentary texture.','A fault moved the upper half downward|Fault displacement does not explain this size trend.'],'Normal grading records the settling of progressively finer particles as transport energy wanes.',
 'Curved inclined layers occur inside a larger sandstone bed. What process can produce them?',
 ['*Migration of a sand dune or ripple|Sediment builds inclined layers on the moving bedform.','Cooling contraction of lava|This produces joints, not cross beds.','Growth of a metamorphic foliation|This creates a mineral fabric.','Horizontal slip on a fault|This offsets preexisting layers.'],'Migrating bedforms produce cross beds as sediment accumulates on their sloping surfaces.');
lesson('7.8','Breccia and conglomerate environments',
 '<p>Both rocks contain large clasts, so start by describing <b>roundness</b>. Breccia has angular fragments and commonly poor sorting. It forms where material is broken and accumulates with limited abrasion, including steep slopes, talus, landslides, and debris-flow deposits. Angular fragments alone do not prove one specific origin.</p><p>Conglomerate contains rounded coarse clasts and finer matrix. Streams, beaches, and other energetic environments can transport coarse material and round it. Alluvial fans can preserve a mixture of stream and debris-flow deposits; environments are not defined by a single rock name.</p><p>Compare size distribution, clast support versus matrix, bedding, and association with neighboring deposits. Grain rounding supports abrasion, while the coarse grain size supports transport or accumulation capable of handling large pieces.</p>',
 'A coarse clastic rock is not automatically a high-energy river deposit; slope processes also move large blocks.',
 'Angular blocks accumulate beneath a cliff with little transport. Which deposit-to-rock pairing fits best?',
 ['*Talus to breccia|Angular slope debris can lithify into breccia.','Quiet lake mud to conglomerate|Quiet lake mud lacks coarse rounded clasts.','Wind dune sand to breccia|Dunes chiefly accumulate sand.','Reef skeletons to conglomerate|Reefs chiefly build carbonate deposits.'],'A nearby source and limited abrasion favor angular clasts in breccia.',
 'A river deposit has rounded cobbles surrounded by sand. On lithification, which rock name fits?',
 ['*Conglomerate|Rounded coarse clasts are diagnostic.','Breccia|Its coarse clasts would be angular.','Shale|Shale is very fine grained.','Limestone|Limestone is carbonate rich.'],'Conglomerate retains rounded gravel within a finer matrix.');
lesson('7.9','Sandstone records several settings',
 '<p>Sandstone preserves sand-sized particles but can form in many environments. Wind dunes tend to be well sorted and can preserve large cross beds. Stream deposits may include channels, gravel, variable sorting, and smaller cross beds. Beach sand is repeatedly reworked by waves, but its composition depends on the local supply.</p><p>Deltas and offshore shelves accumulate sand carried from land. Turbidity currents move sediment into deeper settings. Compare bedding, fossils, grain composition, and adjacent units to distinguish these possibilities. Sand-sized particles alone do not identify a beach or desert.</p><p>Sandstone commonly forms resistant cliffs or ledges where strongly cemented. The landscape depends on cement, fractures, climate, and neighboring rocks. A visible sand grain gives a textural observation; the environment remains an interpretation that needs several supporting attributes.</p>',
 'Well-sorted sand occurs in more than one environment; add structures and contextual clues.',
 'A sandstone has very good sorting and meter-scale cross beds, with no marine fossils reported. Which setting is best supported?',
 ['*Wind-blown dunes|Selective transport and large cross beds support dunes.','Deep quiet lake water|Fine mud usually dominates there.','Glacial till|Till commonly mixes many grain sizes.','Contact metamorphic aureole|This does not explain original cross beds.'],'Large cross beds and well-sorted sand together support dune deposition.',
 'Why is the statement “sandstone means beach” incomplete?',
 ['*Sand also accumulates in rivers, dunes, and offshore settings|Rock texture alone does not uniquely identify environment.','Sandstone contains only shell fragments|It commonly contains mineral grains.','Sand is transported only by waves|Wind and rivers also transport sand.','Every sandstone forms at the same water depth|Its settings vary widely.'],'Use structures, fossils, and neighboring units to interpret a sandstone environment.');
lesson('7.10','Fine-grained clastic rocks',
 '<p>Siltstone, mudstone, and shale preserve particles finer than sand. Silt commonly includes quartz and can feel gritty. Clay-sized particles are finer; clay-rich shale commonly splits into thin sheets because its minerals are aligned. Mud includes silt and clay.</p><p>Fine sediment settles where energetic transport subsides: floodplains, quiet lake centers, sheltered coastal water, and offshore settings. Mud can also remain suspended and be transported far from a river mouth. Deposits may include thin sand layers from stronger events.</p><p>Color, fossils, and structures add environmental information. Dark organic-rich material can support low-oxygen preservation; mudcracks indicate drying and exposure. Fine-grained rocks often weather into gentler slopes, but lithification and local conditions affect their resistance.</p>',
 'Fine grain size indicates low energy during deposition, not necessarily a short transport distance.',
 'Which material commonly makes up the finest fraction of a mud deposit?',
 ['*Clay-sized particles|Clay is finer than silt and sand.','Sand-sized particles|Sand is coarser than mud.','Rounded granules|Granules are gravel.','Angular cobbles|Cobbles are coarse gravel.'],'Mud includes silt and clay, with clay the finer size fraction.',
 'Fine mud containing polygonal drying cracks is preserved beside a channel. Which inference is strongest?',
 ['*The sediment was exposed and dried|Drying produces mudcracks.','The sediment stayed continuously submerged|Drying cracks argue against continuous submergence.','The deposit formed from molten lava|The described texture is sedimentary.','The grains settled in a strong gravel-moving current|The fine material and drying require a different explanation.'],'Mudcracks support exposure of wet sediment followed by drying.');
lesson('7.11','Carbonate rocks and their environments',
 '<p>Limestone consists mainly of calcite; dolostone consists mainly of dolomite. Carbonate rocks may form through chemical precipitation, biological accumulation, or later chemical replacement. Shells, reef frameworks, carbonate mud, and rounded coated grains can contribute to limestone.</p><p>Warm, shallow marine water is an important carbonate setting, especially where little land-derived mud obscures the water. Reefs build skeletal material. Lakes and springs can also deposit carbonate, so limestone alone is not proof of a tropical ocean. Dissolution can give exposed limestone pits or irregular surfaces; dilute acid helps identify calcite.</p><p>Read fossils, grain types, bedding, and associated deposits to reconstruct conditions. Carbonate cliffs versus rounded slopes depend partly on climate and erosion. Do not confuse a carbonate sedimentary rock with marble: marble records later metamorphism of carbonate rock.</p>',
 'Limestone is not restricted to reefs, and marble is a metamorphic product rather than an original sedimentary environment.',
 'Marine organisms remove calcium carbonate from water to build shells that accumulate on the seafloor. Which rock can form?',
 ['*Limestone|Carbonate skeletal debris can lithify into limestone.','Quartz sandstone|Its defining grains are sand-sized quartz.','Rock salt|Halite forms by salt precipitation.','Slate|Slate is a metamorphic rock.'],'Biological extraction and accumulation of calcium carbonate can form limestone.',
 'Which observation most directly distinguishes dolostone from limestone?',
 ['*Its dominant carbonate mineral is dolomite|Mineral composition distinguishes the rocks.','It always contains coarse rounded gravel|This describes conglomerate.','It occurs only in deserts|Carbonate rocks have varied settings.','It is necessarily metamorphic|Dolostone is sedimentary.'],'Dolostone is dominated by dolomite rather than calcite.');
lesson('7.12','Transgression, regression, and facies',
 '<p>A <b>facies</b> is a body of sediment or rock with characteristics representing an environment. Moving shorelines shift facies laterally, producing a vertical succession at a fixed location.</p><p>In a <b>transgression</b>, the sea advances over land because sea level rises relative to the land. Beach sand may be overlain by offshore mud and then carbonate material: the site becomes more marine through time. In a <b>regression</b>, the sea retreats and shallower-water or land deposits overlie deeper-water deposits. Relative sea-level change can result from changing water level or vertical land movement.</p><p>Follow both the shoreline and one fixed observation point in the source sequence. Lateral shifts and vertical stacking are different views of the same change. The exact rock sequence depends on which environments and sediment supplies exist; do not memorize sandstone–shale–limestone as a universal rule.</p>',
 'Transgression describes relative sea advance; it does not require sea level to change without any land movement.',
 'At one site, beach sandstone is overlain by offshore mudstone and marine limestone. What change is supported?',
 ['*Transgression|The site became more marine as the shoreline moved landward.','Regression|This would favor shallower or land facies above marine units.','Contact metamorphism|This would alter rocks near heat, not shift the shoreline.','Strike-slip displacement|This moves rocks laterally rather than explaining this depositional stack.'],'The supplied model places progressively more marine facies above shoreline deposits during transgression.',
 'During a regression, where do shoreline environments shift?',
 ['*Toward the sea|The sea retreats and exposes land.','Toward the interior of the land|This is sea advance.','Only vertically downward|Facies also shift laterally.','They remain fixed in place|Retreat moves the shoreline.'],'Regression moves the shoreline and associated facies seaward.');
lesson('7.13','Interpreting a sedimentary sequence',
 '<p>Begin with observations: grain size and sorting, composition, fossils, color, bedding, cross beds, and contacts. Then infer an environment. Keep an observation such as “large cross beds” distinct from an interpretation such as “wind dunes.”</p><p>Read an undisturbed sequence from older at the bottom toward younger at the top. Use changes between units to reconstruct changes in environment. Red beds can reflect oxidation; dark organic-rich deposits may reflect limited oxygen. Neither color alone proves a unique setting. Several clues should agree.</p><p>Interpret erosional contacts and missing intervals explicitly. A marine unit above land deposits can support transgression; land deposits above marine material can support regression. Explain both the environment of each unit and the transition between them.</p>',
 'Color is supporting evidence, not a unique environmental diagnosis.',
 'Which statement is an observation rather than an environmental interpretation?',
 ['*The sandstone contains large inclined internal beds|This describes a visible feature.','The sandstone formed in a desert|This is an inferred setting.','The sea advanced over the site|This is an inferred change.','The region experienced a humid climate|This is an inferred climate.'],'Describe the evidence before proposing how the rock formed.',
 'What strengthens an interpretation that a unit formed in shallow marine water?',
 ['*Marine fossils together with sedimentary texture and context|Independent clues support the interpretation.','Red color alone|Oxidation does not uniquely identify marine water.','The unit is sandstone alone|Sandstone forms in several settings.','A single fracture across the outcrop|A later fracture does not establish deposition.'],'Combine fossils, rock characteristics, and surrounding units rather than relying on one clue.');
lesson('7.14','Sedimentary resources and records',
 '<p>Sediment and sedimentary rocks store groundwater in pores and fractures. Connected pore spaces allow water to move; pore volume and connectivity are different properties. Sand and gravel are useful construction materials, and limestone supplies carbonate for cement and other uses.</p><p>Sedimentary basins can preserve coal, petroleum, and natural gas. Organic material supplies the starting carbon; burial and chemical change contribute to fuel formation. Reservoir rock stores fluids, while less permeable layers can help trap them. Resources occur through a sequence of processes, not merely because a rock has one name.</p><p>Layers also record past environments, biological remains, and events. Fossils, sedimentary structures, and sequences help reconstruct Earth history. The supplied lecture ending introduces this societal importance but does not establish a new exam weighting.</p>',
 'Porosity is space; permeability concerns the ability of connected pathways to transmit fluid.',
 'Where is much groundwater stored in a sandstone aquifer?',
 ['*Pores between grains and fractures|These spaces hold water.','Only inside quartz crystal lattices|That is not the principal reservoir.','Only in large underground rivers|Most groundwater is not in open rivers.','Only above the land surface|Groundwater is below the surface.'],'Sedimentary grains and fractures create spaces that store groundwater.',
 'A rock has many pores, but those pores do not connect well. Which description fits?',
 ['*High pore volume with limited fluid transmission|Porosity and permeability can differ.','No porosity and rapid fluid transmission|This reverses the observation.','No pores and no fractures|Pores were observed.','A guarantee of an excellent aquifer|Poor connection can restrict flow.'],'Many pores do not guarantee high permeability.');
lesson('7.15','Sedimentary history west of Denver',
 '<p>The Front Range exposes older crystalline basement. Younger sedimentary layers record sediment shed from mountains, wind-blown sand, shoreline deposits, and marine environments. The supplied map, cross section, and photographs show the relations used to reconstruct that changing history.</p><p>The lowest coarse reddish sediment includes sandstone, conglomerate, and breccia deposited by streams and debris flows from the Ancestral Rockies. Overlying units record later environments; interpret each with its grains, structures, and fossils. The present steep dips also record deformation after deposition.</p><p>Separate deposition from later tilting and erosion. A coarse unit can indicate nearby relief during deposition, whereas its present inclination need not be the slope on which it originally formed. Use the source sequence rather than assigning an age from color alone.</p>',
 'Present dip and original depositional environment are separate pieces of the history.',
 'Coarse conglomerate and breccia at the base of the Denver sequence contain debris derived from nearby crystalline mountains. What do they record?',
 ['*Sediment shed from nearby highlands|Streams and debris flows carried coarse material.','Quiet deposition far from any sediment source|This poorly explains coarse mountain debris.','Crystallization from a deep magma chamber|The observed rock is clastic.','Growth of a carbonate reef|The material is mountain-derived clasts.'],'Coarse mountain-derived deposits support erosion of nearby highlands.',
 'A sedimentary bed now dips steeply beside the Front Range. What distinction is needed when reconstructing its history?',
 ['*Deposition and later tilting may be separate events|Present orientation can result from deformation.','All sediment was deposited at its present angle|This assumes away later deformation.','Every tilted layer is metamorphic|Tilting does not require metamorphism.','Dip proves the grains were transported by wind|Dip is not a unique transport clue.'],'Reconstruct deposition first, then examine evidence for deformation and erosion.');
lesson('7.16','Reconstructing the history of a plateau',
 '<p>The supplied investigation combines four units, their grain types, fossils, and structures. Identify at least two useful attributes of each unit before assigning an environment. Coal and plant remains support vegetation-rich land settings; mudcracks support exposure and drying; marine fossils support marine deposition.</p><p>Large cross beds in well-sorted sand support dunes, while smaller cross beds can occur in channels or shoreline deposits. Distinguish sandstone from carbonate rock by composition and fossils, not merely cliff color. Read the succession upward to infer environmental change.</p><p>This lab uses original practice scenarios based on those relationships. It does not treat a missing or unreadable worksheet label as a verified answer. For the full original investigation, inspect the source pages and make your own observation-to-interpretation table.</p>',
 'A rock name alone is an incomplete answer when a question asks for supporting attributes and changing environments.',
 'A plateau unit contains coal, plant fossils, and mudstone with drying cracks. Which environment is best supported?',
 ['*A lowland with wetlands and intermittently exposed sediment|The clues support vegetation and periodic drying.','A deep-ocean basin far from land|Plant accumulation and drying need explanation.','A hot magma chamber|These are sedimentary clues.','A continuously submerged coral reef|Coal and drying cracks argue for a different setting.'],'Use the combination of organic remains and exposure structures to interpret the unit.',
 'When interpreting four stacked units, what should follow the description of each unit’s environment?',
 ['*An explanation of how environments changed upward|The sequence records change through time.','A mineral name for only the top unit|This leaves most of the sequence unexplained.','A claim that each bed took equal time to form|Equal durations are not established.','A conclusion based only on cliff color|Color alone is insufficient.'],'A sequence interpretation connects the separate environments in chronological order.');

lesson('8.1','Stress, strain, and strength with depth',
 '<p><b>Stress</b> is force applied over an area. Confining pressure acts approximately equally in all directions; differential stress varies with direction. Compression shortens, tension stretches, and shear moves neighboring material past itself. <b>Strain</b> is the resulting change in shape or size. Displacement and rotation can also change a rock’s position or orientation.</p><p>The classroom diagram shows rock strength against depth. In shallow crust, increasing confinement resists fracture and slip, so strength generally increases downward. At greater depth, temperature permits ductile deformation and strength decreases. The curve reaches a maximum near the brittle–ductile transition; it does not imply rock melts there.</p><p>Read the axes first: depth increases downward and strength increases rightward. A rock can remain intact below its strength threshold and deform or fracture when imposed stress exceeds it. Depth is a proxy for changing conditions, not a universal fixed boundary.</p>',
 'Ductile flow can occur while rock is solid. Stress is the cause; strain is the change in shape or size.',
 'A rock sample changes from circular to elliptical under compression. What name applies to its change in shape?',
 ['*Strain|Strain is the resulting size or shape change.','Stress|Stress is applied force per area.','Confining pressure|This describes the loading condition.','Displacement|This refers to a change of position.'],'Stress produces strain; the elliptical geometry records strain.',
 'Why does the continental-crust strength curve weaken below its maximum in the supplied model?',
 ['*Higher temperature allows solid rock to deform ductilely|Deep rock can flow without melting.','All deep crust becomes liquid|Ductility does not require melting.','Confining pressure becomes zero|Pressure generally increases downward.','The surface rock becomes older|Age is not the explanation for this depth trend.'],'At depth, increasing temperature favors ductile behavior and lowers the stress needed for deformation.');
lesson('8.2','Conditions control rock response',
 '<p>The same differential stress can produce different structures under different conditions. At cool shallow levels, compression, tension, or shear can produce brittle failure and faults. At warmer depths, material can fold, stretch, or shear through distributed deformation while remaining solid.</p><p>Temperature, pressure, rock type, fluids, and the conditions of deformation affect behavior. Hotter rock generally deforms more easily. Fluids can alter minerals, move dissolved material, and form veins by precipitating in openings. A shear zone distributes deformation through a broader volume; a brittle fault concentrates movement along a fracture.</p><p>Compare one changing condition at a time. “Deep” and “shallow” describe the course’s general model rather than exact universal depths. Do not infer a unique stress type solely from the fact that a rock is brittle or ductile.</p>',
 'Compression, tension, and shear can each produce brittle or ductile structures depending on conditions.',
 'Two samples have the same composition and loading. The warmer sample flows while the cooler one fractures. Which variable best explains the difference?',
 ['*Temperature|Higher temperature favors ductile response.','Original depositional color|Color is not the controlling condition here.','Sample name|A name does not change mechanical behavior.','Relative age alone|Age alone is not the stated contrast.'],'Warmer conditions permit solid-state deformation more readily.',
 'Minerals precipitate in a fracture after fluid enters it. What feature is formed?',
 ['*Vein|Mineral-filled fractures are veins.','Cross bed|Cross beds form during sediment deposition.','Graded bed|This is a grain-size trend in sediment.','Delta|A delta accumulates at a river mouth.'],'Fluids carry dissolved material into fractures where it can precipitate as a vein.');
lesson('8.3','Joints, unloading, cooling, and orientation',
 '<p>A <b>joint</b> is a fracture with little or no shear displacement. A fault records relative displacement across a fracture. Joint sets have similar orientations and may divide rock into blocks. Tectonic stress can produce joints; cooling and contraction can produce columnar joints; removal of overlying weight can produce curved unloading joints.</p><p>Columnar joints develop as solidified igneous rock cools and contracts. Their polygonal geometry records contraction rather than sedimentary layering. Unloading changes stress near the surface and can form sheetlike fractures roughly parallel to a curved exposed surface.</p><p><b>Strike</b> is the compass orientation of a horizontal line on a plane. <b>Dip</b> is the inclination of the plane, measured downward from horizontal and perpendicular to strike. Read orientation from the source diagram; the supplied lecture explicitly does not require detailed compass operation.</p>',
 'A crack is not a fault unless displacement is demonstrated; strike and dip describe different aspects of a plane.',
 'A fracture cuts a bed, but the bed remains aligned across it. Which description best fits?',
 ['*Joint|There is no demonstrated shear offset.','Fault|A fault requires relative displacement.','Syncline|A syncline is a fold.','Foliation|Foliation is a planar metamorphic fabric.'],'A joint is a fracture with little or no shear displacement.',
 'Hexagonal columns develop in a cooled lava flow. Which process accounts for the joints?',
 ['*Cooling and contraction|Contraction produces columnar joints.','Overbank sediment deposition|This makes floodplain layers.','Dissolution of marine shells|This changes carbonate material.','Growth of aligned mica|This makes metamorphic fabric.'],'Columnar joints form as solidified igneous rock contracts during cooling.');
lesson('8.4','Faults and block movement',
 '<p>A fault is a fracture with relative movement. On an inclined fault, the <b>hanging wall</b> is above the plane and the <b>footwall</b> is below it. Name the blocks geometrically before describing their motion.</p><p>On a <b>normal fault</b>, the hanging wall moves down relative to the footwall; extension commonly produces these faults. On a <b>reverse fault</b>, the hanging wall moves up; shortening commonly produces them. A low-angle reverse fault is a thrust. On a <b>strike-slip fault</b>, relative movement is predominantly horizontal. Oblique slip combines components.</p><p>Several normal faults can bound uplifted horsts and downdropped grabens. Infer relative movement from matching offset layers, arrows, or other markers. A photograph of a steep cliff by itself does not establish the movement direction.</p>',
 'Identify the hanging wall from the fault plane, not from whichever block currently has the higher ground surface.',
 'Across an inclined fault, the hanging wall has moved downward relative to the footwall. What type is it?',
 ['*Normal fault|The hanging wall moves down.','Reverse fault|Its hanging wall moves up.','Strike-slip fault|Its movement is mainly horizontal.','Unloading joint|A joint does not show this shear displacement.'],'Normal-fault movement lowers the hanging wall relative to the footwall.',
 'Two matching stream channels are horizontally offset across a fault. Which slip type is most directly supported?',
 ['*Strike-slip|The observed component is horizontal.','Normal dip-slip|This primarily lowers the hanging wall.','Reverse dip-slip|This primarily raises the hanging wall.','No displacement|The matching channels are offset.'],'Horizontal offset supports strike-slip movement.');
lesson('8.5','Fold geometry and orientation',
 '<p>A <b>fold</b> bends layers. In a simple upright sequence, an anticline arches upward and a syncline forms a trough. A monocline has one main dipping segment between flatter portions. A dome dips outward in several directions; a basin dips inward. Use rock ages where needed to distinguish overturned anticlines and synclines reliably.</p><p>The <b>hinge</b> is the region of greatest curvature, the limbs are the sides, and the axial surface connects hinges through successive layers. Symmetric and asymmetric folds differ in limb geometry. An inclined or overturned axial surface is different from a plunging fold axis; one does not automatically imply the other.</p><p>Compression commonly shortens layered rock through folding. Infer shortening from geometric evidence, and state the viewing direction before translating a cross-section direction into compass directions. Inspect the original examples to distinguish upright, inclined, overturned, and plunging configurations.</p>',
 'Asymmetric and plunging are different descriptions; an arch in one cross section does not by itself establish plunge.',
 'Upright beds bend downward into a trough, and younger beds occupy the center. What fold is shown?',
 ['*Syncline|An upright syncline has a trough and younger central beds.','Anticline|An upright anticline arches upward with older central beds.','Monocline|It has one major dipping step.','Dome|A dome has outward dip in multiple directions.'],'The described upright fold is a syncline.',
 'Which term identifies the surface connecting fold hinges through successive layers?',
 ['*Axial surface|This surface joins the hinges.','Fault plane|This is a surface of displacement.','Bedding plane|This is an original layer boundary.','Dip slope|This is a land surface following bed inclination.'],'The axial surface connects hinges in the folded layers.');
lesson('8.6','Cleavage, foliation, lineation, and relict features',
 '<p><b>Foliation</b> is a planar metamorphic fabric. It can result from aligned platy minerals, mineral bands, flattened objects, or distributed shearing. Slaty cleavage allows fine-grained rock to split along closely spaced planes. Schistosity reflects aligned visible platy minerals. Gneissic foliation is expressed as alternating mineral-rich bands.</p><p><b>Lineation</b> is a linear feature, such as aligned elongated crystals or stretched objects. A rock can contain both foliation and lineation. Bedding is an inherited sedimentary layer; cleavage can cut across it, so the two must be traced separately.</p><p>Relict features are preserved from the parent rock, including bedding, clasts, or other textures. Shearing can deform grains into lenses and rotate minerals. Diagnose the feature from its geometry before assigning a rock name, and avoid treating every planar surface as original bedding.</p>',
 'Foliation is planar, lineation is linear, and bedding can predate both.',
 'Elongated crystals align along one common direction within a metamorphic rock. Which feature is described?',
 ['*Lineation|The fabric is linear.','Cross-bedding|This is an internal sedimentary layering pattern.','Columnar jointing|This is a cooling-fracture pattern.','Graded bedding|This is a grain-size trend.'],'Aligned elongated features define lineation.',
 'A metamorphic rock retains sedimentary layers that are cut by a later cleavage. What are those layers?',
 ['*Relict bedding|Original bedding survived metamorphism.','New cross beds|Cross beds are deposited, not generated by cleavage.','Fault striations|These are scratches along a slip surface.','An axial surface|This joins fold hinges.'],'Relict features preserve evidence of the rock before metamorphism.');
lesson('8.7','Identify metamorphic rocks and parent material',
 '<p>In the supplied progressive shale sequence, <b>slate → phyllite → schist → gneiss</b> records increasing metamorphic conditions. Slate is fine grained and dull with cleavage; phyllite has a sheen; schist has visible aligned minerals; gneiss has mineral banding. This is a course model for suitable parent composition, not a universal path followed by every rock.</p><p>Quartz sandstone can become <b>quartzite</b>, whose interlocking grains make it strong and can cause fractures to cross grains. Limestone can become <b>marble</b>, dominated by recrystallized carbonate minerals. Basalt and other suitable volcanic rocks can form greenstone; hotter conditions can form amphibolite. Contact metamorphism can produce hornfels; partial melting can form migmatite.</p><p>Identify grain size, fabric, minerals, and preserved parent features together. Schist is named partly by texture, so the mineral assemblage can vary. Marble and quartzite often lack strong foliation, even though both are metamorphic.</p>',
 'Every metamorphic rock need not be foliated, and every parent rock need not pass through the shale sequence.',
 'A hard rock derived from sandstone fractures across its interlocking quartz grains. Which name fits?',
 ['*Quartzite|Recrystallized quartz grains form quartzite.','Marble|Marble is carbonate rich.','Slate|Slate is fine grained and cleaved.','Greenstone|Greenstone commonly derives from mafic volcanic rock.'],'Quartzite commonly forms from quartz-rich sandstone.',
 'Which order follows increasing conditions in the supplied shale-derived sequence?',
 ['*Slate, phyllite, schist, gneiss|The sequence progresses from fine cleavage to coarse banded rock.','Gneiss, schist, phyllite, slate|This reverses the sequence.','Slate, gneiss, phyllite, schist|This places high-grade gneiss too early.','Phyllite, slate, gneiss, schist|This reverses two relationships.'],'The course sequence is slate through phyllite and schist to gneiss.');
lesson('8.8','Processes and causes of metamorphism',
 '<p>Metamorphism changes minerals, textures, or both through heat, pressure, stress, and fluids while the rock remains predominantly solid. Burial and tectonic thickening raise pressure and temperature. Magma heats neighboring rocks; circulating hot fluids can alter minerals. Shearing can deform and heat rock locally.</p><p><b>Recrystallization</b> changes crystal size and texture. <b>Neocrystallization</b> grows new minerals as old minerals become unstable. Pressure solution dissolves material where stress is greatest and can move it elsewhere. Chemical remobilization concentrates different minerals into bands. Rotation, flattening, and stretching change geometry.</p><p>Foliation develops through alignment, growth, dissolution, and deformation. Metamorphism and deformation can occur together or independently. Crossing into melting is a separate transition; do not describe solid-state recrystallization as simply melting and freezing again.</p>',
 'Growth of larger existing crystals and growth of a new mineral are different processes.',
 'Existing mineral grains grow into larger crystals during metamorphism. Which process is described?',
 ['*Recrystallization|Existing minerals change crystal size and texture.','Neocrystallization|This produces new mineral species.','Deposition|This lays down sediment.','Frost wedging|This physically opens near-surface cracks.'],'Recrystallization can coarsen existing mineral grains without requiring melting.',
 'Which relationship between deformation and metamorphism is supported by the supplied material?',
 ['*They can occur together or independently|Mechanical and mineral changes need not always coincide.','They must always occur together|This is too restrictive.','They can never occur together|Regional settings often include both.','Deformation must always occur first|No universal order is established.'],'The processes are related but can occur together or separately.');
lesson('8.9','Pressure–temperature conditions and settings',
 '<p>Metamorphic grade reflects the conditions a rock experienced and can be constrained by mineral assemblages. In the course pressure–temperature model, normal regional conditions increase pressure and temperature together. <b>High-temperature/low-pressure</b> conditions occur near shallow magma bodies; <b>high-pressure/low-temperature</b> conditions occur where relatively cold material is subducted.</p><p>At an ocean–continent convergent margin, a subducting slab, the overriding mountain belt, and a shallow intrusion experience different conditions. Contact metamorphism surrounds heat sources; regional metamorphism affects broader buried or thickened regions. Continental collision can thicken crust and produce extensive metamorphism.</p><p>Read the axes and fields on the supplied graph. A location on a pressure–temperature diagram is not automatically a geographic depth with a single universal temperature. The October 6 lecture reaches subduction and contact settings; its collision discussion is explicitly left for later.</p>',
 'High pressure does not imply the highest temperature; a cold subducting slab is the key comparison.',
 'Which setting most directly supports high pressure with relatively low temperature?',
 ['*A cold slab descending in a subduction zone|Pressure rises faster than the slab warms.','Shallow wall rock around a magma intrusion|This favors high temperature at lower pressure.','An exposed sand dune|This is a surface sedimentary setting.','A drying tidal flat|This is also a surface setting.'],'Relatively cold subducted rocks can experience high-P/low-T metamorphism.',
 'A small aureole surrounds a shallow intrusive magma body. Which condition best fits?',
 ['*High temperature at relatively low pressure|Shallow magma heats neighboring rock.','High pressure at relatively low temperature|This better fits cold subduction.','No change in temperature or minerals|An aureole records metamorphic change.','Only sediment compaction at the surface|Contact heating is a different process.'],'Contact metamorphism near a shallow intrusion is a high-T/low-P setting.');
lesson('8.10','Extension and strike-slip settings',
 '<p>Extension can form continental rifts, normal faults, tilted blocks, and grabens. Crust becomes thinner as it stretches. Magma and hot fluids can alter rock during rifting and ocean opening. Hydrothermal metamorphism is especially important where seawater circulates through hot rock at mid-ocean ridges.</p><p>Strike-slip faults accommodate predominantly horizontal motion and can occur at transform boundaries or within continents. Shearing changes structures at depth. A bend can make neighboring material converge or separate, creating local uplift or subsidence even though the main motion is lateral.</p><p>Interpret the entire geometry: arrows, fault trace, matching displaced features, and the bend direction. Straight horizontal motion should not be assigned the same vertical effect as every bend. Keep plate-scale setting separate from the smaller local stress field.</p>',
 'Strike-slip motion is mostly horizontal, but bends can create local shortening or extension.',
 'A continental rift develops paired normal faults and a downdropped central block. What is the block called?',
 ['*Graben|A graben is the relatively downthrown block.','Horst|A horst is relatively uplifted.','Anticline|This is a fold.','Contact aureole|This is a metamorphic zone.'],'Extension can form a graben bounded by normal faults.',
 'Where is hot-water metamorphism especially prominent during development of an ocean basin?',
 ['*At a mid-ocean ridge|Water circulates through newly formed hot oceanic rock.','In a dry surface dune|The relevant hot circulation is absent.','On a quiet floodplain|This is sediment deposition.','Above an unheated lake bottom|The heat source is absent.'],'Hydrothermal circulation through hot ridge rock drives metamorphic alteration.');
lesson('8.11','Structures form in related systems',
 '<p>Faults, folds, joints, and cleavage can form during the same deformation episode. A fault propagating upward can bend overlying beds into a monocline. Beds moving over a bend in a thrust can fold into anticlines and synclines. Thrust belts combine shortening, stacked sheets, and related fabrics.</p><p>Cleavage commonly lies approximately parallel to the axial surfaces of folds formed in the same event, and it can cut original bedding. This relation helps locate fold geometry where only parts of the rock are exposed. The relation is a structural clue, not proof that all fabrics everywhere formed simultaneously.</p><p>Use cross-cutting and overprinting to distinguish separate events. Older thrusts can later be folded or faulted. Observations must support a shared history; visual proximity alone does not establish age or cause.</p>',
 'A fold and a nearby fault may be related, but that relationship must be supported by geometry and timing.',
 'Layered rock is pushed over a bend in a thrust fault. Which response is expected?',
 ['*The layers can fold as they conform to the bend|Thrust movement can generate folds.','All bedding must disappear immediately|Deformation can preserve bedding.','The layers must become loose sediment|Thrusting does not require weathering.','The fault must change to a joint|Movement remains faulting.'],'Fault geometry can force moving layers to bend.',
 'Cleavage formed during folding is most commonly compared with which fold feature?',
 ['*The axial surface|Cleavage commonly aligns with that surface.','Only the present ground surface|The ground surface may cut across structures.','Only the youngest bedding plane|Cleavage can cut bedding.','Only the stream direction|A stream is not the defining reference.'],'A consistent bedding–cleavage relation can help interpret a fold.');
lesson('8.12','Landscape clues to structure',
 '<p>Weathering and erosion exploit joints, faults, and cleavage. Joint sets divide rock into blocks and influence cliffs. Fault scarps offset the land surface; fault breccia, crushed zones, and aligned notches can expose traces. Striations on a fault surface record slip direction.</p><p>Erosion of inclined resistant layers can form dip slopes and hogbacks. A ridge is not automatically an anticline: landforms depend on resistance and erosion as well as structure. Metamorphic foliation can create slabs, shiny outcrops, or complex ridges and folds.</p><p>Infer geometry by tracing beds and fabrics, then comparing their orientation with the landscape. Distinguish the modern erosional surface from the original rock structure. Multiple observations are needed before locating a fault or determining its motion.</p>',
 'A topographic high can be an erosion-resistant layer rather than the crest of an anticline.',
 'A straight notch contains intensely shattered rock and truncates matching layers. What feature is most strongly suggested?',
 ['*Fault zone|Crushed rock and layer truncation support faulting.','Undeformed dune|This does not explain shattered rock or truncation.','Reef crest|This does not explain the structural evidence.','Unfractured intrusive core|The rock is intensely fractured.'],'Fault zones commonly contain crushed material and disrupted layers that erode into notches.',
 'A hill slope parallels an inclined resistant rock layer. Which term describes the land surface?',
 ['*Dip slope|It follows the dip of the layer.','Axial surface|This joins fold hinges through layers.','Tidal flat|This is a coastal depositional setting.','Graben|This is a fault-bounded downthrown block.'],'A dip slope follows an inclined bedding surface.');
lesson('8.13','Determine structural timing from relations',
 '<p>Structural fieldwork records observations, sketches, orientations, maps, and samples. Measurements of strike and dip help project structures below the surface. Laboratory work can identify minerals, textures, and chemical conditions.</p><p>A fault is younger than units it cuts. An unfaulted intrusion or deposit that crosses and seals a fault constrains the fault to be older than that feature. Sediment accumulating during fault movement can record changing relief and tilting. The available evidence may constrain an interval rather than one exact date.</p><p>Minerals can grow before, during, or after deformation. Their relationship to fabrics helps distinguish these possibilities. Preserve uncertainty where an exposure or age is missing. Reconstruct the event sequence from several relations, not from a rock name alone.</p>',
 'A sealing layer constrains the latest movement represented at that exposure; it does not establish that the fault never moved anywhere else.',
 'An unfaulted lava flow lies across a fault that offsets older layers below. Which order is supported?',
 ['*The observed fault movement predates the lava flow|The flow seals the offset.','The flow was faulted after it formed|No offset is observed in the flow.','The older layers formed after the flow|The stratigraphy says otherwise.','All events were simultaneous|The relations establish an order.'],'A feature crossing and sealing a fault is younger than the movement it seals.',
 'A fault cuts a dated sedimentary unit. What can be concluded about the fault movement?',
 ['*It occurred after that unit formed|The fault must be younger than what it cuts.','It occurred before that unit formed|This reverses the cross-cutting relation.','It has the same age as every nearby intrusion|Proximity does not establish age.','It predates all rocks in the region|The observation does not support that.'],'Cross-cutting establishes a relative age constraint.');
lesson('8.14','New England: multiple events and metamorphic history',
 '<p>The New England maps and cross section show belts of rock, faults, folds, and metamorphic variation. Older crystalline rocks and Paleozoic units record deformation and metamorphism; younger Mesozoic rocks occur in rift-related fault blocks. Recent deposits record still later glacial and shoreline processes.</p><p>Distinguish the collision history associated with assembly of the Appalachians from later rifting between North America and Africa. Metamorphic mineral patterns and pressure–temperature paths help reconstruct burial, heating, and later change. Different locations have different histories, so read the map legend and cross-section direction.</p><p>Do not equate every fault on the map with the same episode. The sequence includes older deformation, metamorphism, younger extension, and erosion/deposition. Exact ages and geographic labels must follow the supplied figures.</p>',
 'The Paleozoic collision and later Mesozoic rifting are separate tectonic events.',
 'Which contrast is supported by the supplied New England history?',
 ['*Older collision-related deformation followed by later rifting|Different structures record different episodes.','All structures formed during one recent glaciation|The rocks record a much longer history.','Rifting must precede every collision everywhere|No universal event order follows.','Every mapped fault has the same age|Multiple episodes are represented.'],'The region preserves deformation and metamorphism followed by younger rift-related structures.',
 'Which evidence is most useful for comparing metamorphic conditions across a region?',
 ['*Mineral assemblages and metamorphic textures|These constrain metamorphic conditions.','Fault orientations and fracture spacing|These constrain structure but do not directly identify metamorphic grade.','Sedimentary grain size and sorting|These mainly record the depositional history of clastic rocks.','Modern relief and drainage patterns|These reflect erosion and several controls beyond metamorphic conditions.'],'Minerals and textures provide geological evidence for metamorphic conditions.');
lesson('8.15','Integrate folds, faults, and metamorphic rocks',
 '<p>The supplied investigation combines bedding, cleavage, rock samples, and a linear fractured zone. First identify the rocks from mineral and texture evidence: fine dull cleavage supports slate; quartz-rich interlocking sand grains support quartzite; recrystallized calcite supports marble; coarse mineral bands support gneiss.</p><p>Trace bedding to interpret the fold, then compare cleavage and the viewing direction to infer shortening. A highly fractured boundary may be a fault, but fault type requires movement or an independently verified geometric relation. Differences in metamorphic grade across a boundary help constrain the structural history.</p><p>Keep each reasoning step explicit: observation → rock or structure → parent material or process → integrated sequence. Written Connect summaries support style calibration; missing original screenshots are not a basis for grading their unseen numbered locations.</p>',
 'Do not grade unseen photograph labels, compass directions, or fault slip solely from a written summary.',
 'One sample is dull, fine grained, and splits along cleavage; another has coarse light and dark mineral bands. Which comparison fits?',
 ['*Slate versus gneiss|These fabrics support the two rock names.','Marble versus conglomerate|These do not fit the reported textures.','Quartzite versus rock salt|These do not fit the reported fabrics.','Basalt versus coal|These do not fit the metamorphic evidence.'],'Combine texture and mineral banding to distinguish slate from gneiss.',
 'Why should an investigation record observations before assigning a structural history?',
 ['*Each interpretation needs a visible supporting relation|This keeps inference tied to evidence.','Rock names determine all fault directions|They do not determine movement.','One photograph proves every regional event|Regional history needs several relations.','A summary replaces missing original figures|It cannot verify unseen locations.'],'An integrated history must be supported by actual observations and relations.');

L.EXAM2.topics.forEach(function(t){
 var c=t.concepts[0],src=t.sources;
 A.teach('e2-'+t.id+'-teach',c,'Explain '+t.title.toLowerCase()+'. Name the key distinctions, describe the process, and give a supported geological example.',
 t.sections.map(function(n){return L.GUIDE['c'+n.replace('.','s')][0].html;}).join(''),
 ['Names the relevant structures, materials, or processes correctly.','Distinguishes the major alternatives in this topic.','Connects a visible observation to the process that produces it.','Gives a geological example supported by the topic sources.'],src,
 {examId:'exam2',mock:false,topics:[t.id],hint:'Use the observe → identify → explain sequence.',evidence:'docs/EXAM2_SOURCE_LEDGER.md'});
});
})(window.L);
