/* Original Exam 2 applications. Publisher items are evidence, never copied questions. */
(function(L){
'use strict';var A=L.A,U=L.util;
function c(n){return 'c'+n.replace('.','-')+'-core';}
function src(n){return ['TB'+n.split('.')[0]+':'+n];}
function extra(t,n){return {examId:'exam2',mock:false,topics:[t],sourceSection:n,evidence:'docs/EXAM2_SOURCE_LEDGER.md'};}
function svg(body,title){return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 960 460" role="img" aria-label="'+U.esc(title)+'"><defs><marker id="e2arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10" fill="#f2bc67"/></marker></defs><rect width="960" height="460" fill="#0c1a2b"/>'+body+'</svg>';}
function tx(x,y,s,size){return '<text x="'+x+'" y="'+y+'" text-anchor="middle" fill="#e7eef4" font-size="'+(size||24)+'" font-family="Arial,sans-serif">'+U.esc(s)+'</text>';}
function line(x1,y1,x2,y2,color,w){return '<path d="M'+x1+' '+y1+'L'+x2+' '+y2+'" stroke="'+(color||'#a6c9d8')+'" stroke-width="'+(w||4)+'" fill="none"/>';}
function ar(x1,y1,x2,y2){return '<path d="M'+x1+' '+y1+'L'+x2+' '+y2+'" stroke="#f2bc67" stroke-width="5" marker-end="url(#e2arrow)"/>';}
function rect(x,y,w,h,col){return '<rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" rx="3" fill="'+(col||'#b99870')+'"/>';}
function circ(x,y,r,col){return '<circle cx="'+x+'" cy="'+y+'" r="'+r+'" fill="'+(col||'#dcb678')+'"/>';}
function panel(x,title){return rect(x,64,205,320,'#182b40')+tx(x+102,97,title,21);}
var D={};
D.E2T1=function(){var b='<path d="M40 345L160 120L250 340L640 340L740 365L920 380L920 420L40 420Z" fill="#b7976b"/>'+rect(680,340,240,80,'#286e91')+'<path d="M185 220Q260 250 310 320T615 340" stroke="#62c8e0" stroke-width="12" fill="none"/>';
 b+='<path d="M620 330L730 350L620 375Z" fill="#edc588"/>'+tx(660,400,'C')+tx(150,175,'A')+tx(445,310,'B');
 b+='<path d="M370 200Q420 160 440 200Q485 170 505 210L370 210Z" fill="#e2b977"/>'+tx(440,160,'D');return svg(b,'Landscape with steep angular debris A, low river margin B, a river-mouth deposit C, and wind-built sand ridges D.');};
D.E2T2=function(){var b='';['A','B','C','D'].forEach(function(l,i){var x=30+i*235;b+=panel(x,l);if(i===0)b+=rect(x+50,160,100,160)+'<path d="M'+(x+95)+' 160l-15 60 25 40-18 60" stroke="#102235" stroke-width="8" fill="none"/>';if(i===1){b+=ar(x+30,200,x+175,300);for(var k=0;k<6;k++)b+=circ(x+40+k*26,200+k*17,9);}if(i===2){b+=rect(x+25,130,155,190,'#246c90');for(var j=0;j<14;j++)b+=circ(x+40+(j%5)*26,290-Math.floor(j/5)*13,7);b+=ar(x+110,170,x+110,275);}if(i===3){b+=rect(x+30,205,145,110,'#c9b58c');for(var m=0;m<15;m++)b+=circ(x+44+(m%5)*26,220+Math.floor(m/5)*27,10);b+=ar(x+100,130,x+100,196)+ar(x+100,370,x+100,323);}});return svg(b,'Four stages: A rock fractures in place, B grains move, C grains settle, D grains pack together and bind.');};
D.E2T3=function(){var b='';['A · >2 mm','B · >2 mm','C · sand','D · mud'].forEach(function(l,i){var x=30+i*235;b+=panel(x,l);for(var k=0;k<(i===3?55:18);k++){var xx=x+30+(k%5)*31,yy=160+Math.floor(k/5)*(i===3?15:48);if(i===0)b+='<path d="M'+xx+' '+yy+'l20 3 6 17-18 14-13-16Z" fill="#c6ac83"/>';else b+=circ(xx,yy,i===1?15:i===2?6:2);}});return svg(b,'Four sediment textures: coarse angular clasts A, coarse rounded clasts B, sand grains C, and very fine particles D.');};
D.E2T4=function(){var b='';['A · shells','B · dissolved ions','C · plant remains','D · tiny skeletons'].forEach(function(l,i){var x=30+i*235;b+=panel(x,l);if(i===0||i===3){for(var k=0;k<12;k++){var xx=x+44+k%3*52,yy=170+Math.floor(k/3)*40;b+='<path d="M'+(xx-14)+' '+yy+'q14-25 28 0q-14 14-28 0Z" fill="#d9ded4"/>';}}if(i===1){b+=ar(x+80,145,x+80,220);for(var j=0;j<8;j++)b+=rect(x+44+j%3*39,240+Math.floor(j/3)*36,27,27,'#d7e9f2');}if(i===2){b+=rect(x+25,260,155,65,'#3e3937');for(var m=0;m<8;m++)b+=line(x+40+m*15,190,x+70+m*12,257,'#a8c375',3);}});return svg(b,'Origins: shell-rich carbonate A, cubic crystals after evaporation B, compressed plant material C, tiny carbonate skeletons D.');};
D.E2T5=function(){var b=panel(70,'A')+panel(375,'B')+panel(680,'C');for(var k=0;k<36;k++){var row=Math.floor(k/9);b+=circ(100+k%9*16,180+row*38,2+row*2);}b+=rect(395,155,165,170)+'<defs><clipPath id="label5-bed"><rect x="395" y="155" width="165" height="170"/></clipPath></defs><g clip-path="url(#label5-bed)">';for(var j=0;j<8;j++)b+=line(397,160+j*17,558,213+j*17,'#685540',3);b+='</g>';b+=line(395,155,560,155,'#f2bc67',5)+line(395,325,560,325,'#f2bc67',5);for(var m=0;m<4;m++)b+=rect(700,155+m*43,165,37,m%2?'#7c98a5':'#bca27d');return svg(b,'A has coarse grains at its base and progressively finer grains upward. B has inclined internal layers between bounding surfaces. C has distinct horizontal beds.');};
D.E2T6=function(){var b=panel(70,'A · time ↑')+panel(375,'B · time ↑')+panel(680,'C');b+=rect(90,155,165,70,'#5d8398')+tx(172,192,'marine mud',19)+rect(90,225,165,90)+tx(172,270,'coastal sand',19);b+=rect(395,155,165,70)+tx(477,192,'coastal sand',19)+rect(395,225,165,90,'#5d8398')+tx(477,270,'marine mud',19);for(var k=0;k<3;k++)b+=rect(700,250+k*28,165,25,k%2?'#6d8797':'#b89b72');b+='<path d="M700 250q20-30 40 0t40 0t40 0t40 0" stroke="#f2bc67" stroke-width="5" fill="none"/>'+tx(780,215,'erosion surface',18);return svg(b,'Continuous marine and coastal successions A and B, read upward through time, and an erosional boundary C. Assume no later overturning.');};
D.E2T7=function(){return svg(rect(180,70,620,300,'#337383')+rect(180,235,620,135,'#94594a')+line(180,70,180,370,'#e4eef2',4)+line(180,70,800,70,'#e4eef2',4)+tx(490,38,'Increasing strength →')+tx(110,205,'Depth',23)+tx(153,83,'0',21)+tx(145,380,'30 km',20)+'<path d="M180 70C300 135 555 192 607 228C688 276 342 255 298 370" stroke="#f2bc67" stroke-width="6" fill="none"/>'+tx(725,157,'A')+tx(665,238,'B')+tx(700,337,'C')+tx(500,423,'Schematic geometry follows textbook 8.1, PDF page 7.',18),'Strength–depth profile. Depth increases downward; strength increases rightward. A is the upper region, B is the curve maximum and transition region, C is the lower region.');};
D.E2T8=function(){var b='';['A','B','C','D'].forEach(function(l,i){var x=30+i*235;b+=panel(x,l);if(i<2){b+=rect(x+20,185,70,130)+rect(x+120,i===0?225:145,65,130)+line(x+95,125,x+135,350,'#e7e9e8',4)+line(x+20,245,x+85,245,'#637d9d',10)+line(x+130,i===0?285:205,x+185,i===0?285:205,'#637d9d',10)+ar(x+163,i===0?178:303,x+163,i===0?217:258);b+=tx(x+102,380,'plane dips right',17);}if(i===2)b+=rect(x+25,135,155,205)+line(x+100,140,x+100,340,'#0d1723',7)+line(x+28,210,x+96,210,'#627f97',12)+line(x+104,270,x+178,270,'#627f97',12)+ar(x+60,290,x+60,245)+ar(x+142,160,x+142,203)+tx(x+103,382,'map view',18);if(i===3)b+=rect(x+25,135,155,205)+line(x+102,140,x+102,340,'#172436',5)+line(x+25,225,x+180,225,'#617f99',12)+tx(x+102,382,'no offset',18);});return svg(b,'A and B show opposite vertical movement of the hanging wall on right-dipping planes. C is a map-view horizontal offset. D has a fracture without displacement.');};
D.E2T9=function(){var b='';['A','B','C','D'].forEach(function(l,i){var x=30+i*235;b+=panel(x,l);for(var k=0;k<4;k++){var yy=180+k*30;if(i===0)b+='<path d="M'+(x+25)+' '+(yy+60)+'Q'+(x+103)+' '+(yy-100)+' '+(x+180)+' '+(yy+60)+'" stroke="'+(k%2?'#c9a97c':'#72a7b9')+'" stroke-width="15" fill="none"/>';if(i===1)b+='<path d="M'+(x+25)+' '+yy+'Q'+(x+103)+' '+(yy+150)+' '+(x+180)+' '+yy+'" stroke="'+(k%2?'#c9a97c':'#72a7b9')+'" stroke-width="15" fill="none"/>';if(i===2)b+='<path d="M'+(x+25)+' '+yy+'L'+(x+80)+' '+yy+'L'+(x+120)+' '+(yy+60)+'L'+(x+180)+' '+(yy+60)+'" stroke="'+(k%2?'#c9a97c':'#72a7b9')+'" stroke-width="14" fill="none"/>';}if(i===3)b+=line(x+104,150,x+104,345,'#f2bc67',8)+tx(x+102,382,'through hinges',17);if(i<2)b+=tx(x+102,382,i===0?'oldest in center':'youngest in center',17);});return svg(b,'A arches upward with oldest layers in the center. B bends downward with youngest layers in the center. C is a step-like bend. D is a surface connecting fold hinges.');};
D.E2T10=function(){var b='';['A · dull, fine','B · visible mica','C · coarse bands','D · calcite'].forEach(function(l,i){var x=30+i*235;b+=panel(x,l);b+=rect(x+20,145,165,195,i===3?'#d2d0c4':'#686e77');if(i===0||i===1){for(var k=0;k<20;k++)b+=line(x+30+k%4*38,170+Math.floor(k/4)*30,x+53+k%4*38,162+Math.floor(k/4)*30,i===0?'#969b9f':'#d2bb76',i===0?2:7);}if(i===2)for(var j=0;j<5;j++)b+=rect(x+20,165+j*35,165,16,j%2?'#303842':'#dfd9c5');if(i===3)for(var m=0;m<18;m++)b+='<path d="M'+(x+32+m%4*36)+' '+(170+Math.floor(m/4)*31)+'l25-8 9 21-25 9Z" stroke="#6b7778" fill="none"/>';});return svg(b,'Four metamorphic textures: fine dull cleavage A, large aligned mica B, coarse light/dark bands C, and interlocking calcite D.');};
D.E2T11=function(){return svg(rect(170,70,650,290,'#233b51')+ar(170,360,820,360)+ar(170,75,170,355)+tx(495,402,'Temperature increases →',23)+tx(100,208,'Pressure',22)+tx(300,117,'A')+ar(285,145,285,278)+tx(617,145,'B')+ar(480,164,730,164)+tx(589,318,'C')+ar(410,260,672,339)+tx(510,435,'All three paths remain in solid-state metamorphic conditions.',18),'Pressure–temperature paths: A increases pressure at similar temperature, B heats at similar pressure, C increases both pressure and temperature. No path crosses a melting boundary.');};
D.E2T12=function(){var b='';['A','B','C','D'].forEach(function(l,i){var x=30+i*235;b+=panel(x,l);if(i===0)b+=rect(x+25,175,155,145)+ar(x+78,150,x+30,150)+ar(x+130,150,x+177,150)+line(x+68,178,x+100,320,'#0e1b2b',8)+line(x+132,178,x+100,320,'#0e1b2b',8);if(i===1)b+=rect(x+25,175,155,145)+ar(x+30,150,x+80,150)+ar(x+177,150,x+127,150)+'<path d="M'+(x+25)+' 240Q'+(x+100)+' 150 '+(x+180)+' 240" stroke="#6fabc0" stroke-width="18" fill="none"/>';if(i===2)b+=rect(x+25,175,155,145)+line(x+101,178,x+101,320,'#0a1829',8)+ar(x+72,190,x+72,260)+ar(x+138,285,x+138,215);if(i===3){for(var k=0;k<4;k++)b+=rect(x+25,230+k*22,155,18,k%2?'#99adae':'#b89b76');b+=line(x+92,220,x+133,320,'#f2bc67',7)+rect(x+25,170,155,50,'#637f93')+tx(x+101,375,'upper layer seals break',15);}});return svg(b,'A blocks pull apart, B rocks shorten and fold, C blocks slide sideways, D a younger continuous unit seals an older fault.');};
Object.keys(D).forEach(function(t){L.MEDIA['e2-'+t]=D[t];});

var figures=[
 ['E2T1','7.1',[['A · steep angular debris','Mountain slope'],['B · flat river margin','Floodplain'],['C · river-mouth deposit','Delta'],['D · wind-built sand','Dune field']],'Transport agents and places of deposition separate the environments.'],
 ['E2T2','7.5',[['A · breaking in place','Weathering'],['B · grains moving','Transport'],['C · grains settle','Deposition'],['D · grains packed and bound','Lithification']],'Weathering makes sediment; transport moves it; deposition drops it; lithification forms rock.'],
 ['E2T3','7.8',[['A · angular gravel','Breccia'],['B · rounded gravel','Conglomerate'],['C · sand grains','Sandstone'],['D · mud particles','Mudstone']],'Classify by clast size first, then shape and other texture. Mudstone need not split into shale sheets.'],
 ['E2T4','7.6',[['A · shell-rich carbonate','Limestone'],['B · cubic salt crystals','Rock salt'],['C · preserved plant carbon','Coal'],['D · tiny carbonate skeletons','Chalk']],'Composition and mode of formation distinguish these nonclastic examples.'],
 ['E2T5','7.7',[['A · fining upward','Graded bed'],['B · inclined internal layers','Cross beds'],['C · distinct horizontal layers','Bedding']],'A graded bed records changing grain size; cross beds record migrating bedforms.'],
 ['E2T6','7.12',[['A · marine mud above coastal sand','Transgression'],['B · coastal sand above marine mud','Regression'],['C · erosion and missing record','Unconformity']],'These simplified uninterrupted facies successions record shoreline migration. Deposition and sediment supply also influence real shorelines.'],
 ['E2T7','8.1',[['A · upper region','Brittle deformation'],['B · transition near strength maximum','Brittle–ductile transition'],['C · lower region','Ductile deformation']],'Confining pressure strengthens the brittle upper crust; high temperature weakens the deeper ductile crust. Exact transition depth varies.'],
 ['E2T8','8.4',[['A · hanging wall moves down','Normal fault'],['B · hanging wall moves up','Reverse fault'],['C · sideways map offset','Strike-slip fault'],['D · break without slip','Joint']],'The hanging wall is above the inclined plane. Movement is relative to the footwall.'],
 ['E2T9','8.5',[['A · arch, older center','Anticline'],['B · trough, younger center','Syncline'],['C · step-like bend','Monocline'],['D · surface through hinges','Axial surface']],'The ages establish anticline and syncline; the axial surface is a geometric surface, not a rock layer.'],
 ['E2T10','8.7',[['A · fine dull cleavage','Slate'],['B · large aligned mica','Schist'],['C · coarse mineral bands','Gneiss'],['D · interlocking calcite','Marble']],'Mineral composition and texture are both needed; banding is not simply grain size.'],
 ['E2T11','8.9',[['A · pressure mainly increases','Burial at limited heating'],['B · temperature mainly increases','Heating near an intrusion'],['C · pressure and temperature increase','Regional burial and heating']],'These are simplified paths. A tectonic setting is inferred by combining the path with field relations.'],
 ['E2T12','8.10',[['A · pulling apart','Extension'],['B · shortening','Compression'],['C · sideways sliding','Shear'],['D · sealed older break','Faulting before the upper unit']],'Geometry supports the process or relative order; exact dates require additional evidence.']
];
figures.forEach(function(f){var t=f[0],n=f[1],e=extra(t,n);e.media={kind:'svg',name:'e2-'+t,alt:'Original teaching reconstruction; compare the supplied course figures after checking.',cap:'Authored schematic · source relationships from textbook '+n+'. Not to scale.'};e.mk='figure';
 A.match('e2-'+t+'-label',c(n),'Use the shuffled word bank to identify the marked features in this schematic.',f[2],f[3],src(n),e);
});

var fills=[
 ['E2T1','7.2','A sediment-laden underwater flow moving down a continental slope is a _____ current.',['turbidity'],'The sediment–water mixture forms a turbidity current.'],
 ['E2T2','7.5','What single term includes compaction and cementation turning sediment into rock?',['lithification'],'Lithification turns loose sediment into solid sedimentary rock.'],
 ['E2T3','7.10','A fine-grained sedimentary rock that splits readily along thin bedding planes is called _____.',['shale'],'Fissility distinguishes shale from other mudrocks.'],
 ['E2T4','7.11','A limestone made mostly of small, rounded carbonate-coated grains is _____ limestone.',['oolitic'],'Ooids form coatings as grains are rolled in shallow agitated water.'],
 ['E2T5','7.7','A bed whose grains become progressively finer upward is a _____ bed.',['graded'],'A graded bed often records settling as flow wanes.'],
 ['E2T6','7.12','Landward migration of the sea over previously exposed land is called _____.',['transgression','marine transgression'],'Transgression moves shoreline environments landward.'],
 ['E2T7','8.1','A change in rock shape or volume in response to stress is called _____.',['strain'],'Stress is force per area; strain is the resulting deformation.'],
 ['E2T8','8.3','A fracture without appreciable displacement parallel to its surface is a _____.',['joint'],'A fault includes displacement; a joint does not.'],
 ['E2T9','8.5','What surface connects the hinges of successive layers in a fold?',['axial surface','axial plane'],'An axial surface connects the hinges; an axial plane is the planar case.'],
 ['E2T10','8.6','A planar metamorphic fabric produced by mineral alignment or compositional layering is _____.',['foliation'],'Foliation records a planar fabric; its expression varies by rock.'],
 ['E2T11','8.8','During cleavage formation, material dissolves from highly stressed grain edges and precipitates elsewhere. This process is pressure _____.',['solution'],'Pressure solution redistributes material in response to differential stress.'],
 ['E2T12','8.12','A land surface that follows the inclination of a resistant rock layer is a _____ slope.',['dip'],'A dip slope follows bedding dip; relief alone does not identify a fold.']
];
fills.forEach(function(f){A.fill('e2-'+f[0]+'-fill',c(f[1]),f[2],f[3],f[4],src(f[1]),extra(f[0],f[1]));});

var situations=[
 ['E2T1','7.1','River mouth and offshore core','A river enters standing water. Near the mouth, coarse sand accumulates; farther away, quiet water receives silt and mud.',
  'Why is finer sediment more common farther from the active channel?',['*It stays suspended longer in weaker flow|Small grains settle more slowly.','It always has a higher mineral density|Size and density both matter; this is not established.','It requires faster flow than gravel to settle|This reverses the usual deposition pattern.','It can form only by dissolving sand|Fine sediment can be transported particles.'],'Settling and transport sort sediment as flow energy declines.',
  'Which additional observation would best support a delta interpretation?',['*Channels branching toward a growing river-mouth deposit|The channel geometry and outward growth support a delta.','A sheltered basin with no sediment input|This does not show a river-mouth deposit.','Ice carrying unsorted blocks onto land|This supports glacial deposition.','Sand ridges migrating across dry ground|This supports wind deposition.'],'Several observations together make the interpretation stronger.'],
 ['E2T2','7.4','From a broken outcrop to buried grains','A cliff sheds angular fragments. A nearby stream moves them; farther downstream, sampled grains are smaller and rounder. Older buried deposits have little pore space.',
  'What best explains the downstream rounding?',['*Abrasion during transport|Impacts remove projecting corners.','Cement growing on corners|Cement binds deposited grains.','Compression during burial|This occurs after deposition.','Dissolved ions replacing every grain|Replacement is not required.'],'Abrasion and breakage modify clasts during transport.',
  'What best explains much of the decrease in pore space after burial?',['*Compaction of the sediment|Overlying weight packs grains together.','Hydraulic sorting in the stream|Sorting occurs during transport and deposition.','Physical weathering of the cliff|This produces new loose material.','Deflation from wind erosion|This removes fine grains near the surface.'],'Compaction reduces pore space; cement can fill additional pore space.'],
 ['E2T3','7.8','Two coarse sedimentary samples','Both rocks contain mostly clasts larger than 2 millimeters. Sample A has sharp, angular fragments; B has rounded clasts. Both have a finer matrix.',
  'Which classification fits?',['*A breccia; B conglomerate|Both are gravel-sized, with different clast shapes.','A conglomerate; B breccia|This reverses the shape distinction.','A sandstone; B siltstone|Both reported clast sizes exceed sand.','A shale; B mudstone|Both are coarse rather than mud dominated.'],'Texture supports breccia versus conglomerate.',
  'Which environmental interpretation is best justified by the texture alone?',['*B experienced abrasion; its precise setting needs more clues|Rounding can occur in streams or beaches.','B must have traveled hundreds of kilometers|Repeated local wave abrasion can also round clasts.','A must be a deep-ocean deposit|Angular fragments occur in several settings.','A and B must have the same transport history|The shapes differ.'],'Shape records processing but does not uniquely identify an environment.'],
 ['E2T4','7.11','Shallow carbonate bank','A rock contains rounded carbonate grains with concentric coatings. Nearby clear warm seawater is repeatedly agitated; another sample contains recognizable shell fragments.',
  'What best identifies the coated-grain rock?',['*Oolitic limestone|Coated carbonate grains are ooids.','Coquina|Coquina is dominated by recognizable shell fragments.','Chalk|Chalk consists mainly of very small carbonate skeletons.','Dolostone|Dolomite composition, not grain coating, defines it.'],'Identify the grain type and composition together.',
  'Why does repeated agitation matter to coated-grain growth?',['*It rolls grains while carbonate precipitates around them|Coatings form on moving grains.','It makes all shells dissolve completely|Dissolution is not the described process.','It converts carbonate into quartz sand|The minerals differ.','It compacts the sediment at great depth|This is a shallow depositional process.'],'Motion and precipitation build concentric carbonate coatings.'],
 ['E2T5','7.7','Read a storm deposit','An upright bed begins with sand at its base and becomes silt near its top. A second exposure contains inclined laminae inside nearly horizontal bounding beds.',
  'What process best explains the first bed?',['*A sediment-bearing flow waned and grains settled|Larger grains settled before finer grains.','A current increased steadily throughout deposition|This commonly favors coarsening rather than this sequence.','A buried layer tilted after lithification|Tilting does not explain systematic fining within the bed.','Carbonate replaced every sand grain|Replacement is not required.'],'The grain-size trend records changing deposition within one bed.',
  'What best explains the second exposure?',['*A dune or ripple migrated during deposition|The inclined laminae are cross beds.','A uniform horizontal surface received still-water mud|This does not produce inclined internal laminae.','Solid layers folded after cementation|Look for folded boundaries rather than cross-bed truncations.','A fracture cut across all the layers|A fracture is not a depositional lamina.'],'Cross beds record the migration and burial of inclined bedform slopes.'],
 ['E2T6','7.12','A changing shoreline','At one upright location, continuous coastal sandstone is overlain by offshore marine mudstone. Farther inland, similar marine deposits occur above former land surfaces.',
  'Which change fits both observations?',['*The shoreline migrated landward|Marine environments advanced over former coastal and land settings.','The shoreline migrated seaward|This would commonly bring shallower settings over deeper ones.','The basin lost all accommodation before deposition|The marine deposits require space and water.','The layers must have been inverted by a fold|No inversion evidence is given.'],'The succession supports transgression under the stated upright, continuous conditions.',
  'Which cause could produce this migration without requiring global sea-level rise?',['*Subsidence of the land and basin|Relative sea level can rise as land sinks.','Uplift of the entire basin|This commonly moves marine environments seaward.','Rapid sand supply outpacing available space|This tends to prograde a coast.','Removal of every marine sediment layer|This is not migration during deposition.'],'Shoreline position reflects relative sea level and sediment supply.'],
 ['E2T7','8.1','Two identical rocks at different depths','Shallow rock fractures under differential stress. A hotter buried equivalent bends and flows in the solid state. The source strength profile reaches a maximum between the two regimes.',
  'Why does the deeper rock become easier to deform in the profile?',['*Higher temperature promotes ductile flow|Thermal effects dominate in the deeper regime.','Confining pressure vanishes at depth|Confining pressure increases downward.','Every deeper rock becomes a liquid|Ductile rock can remain solid.','Stress no longer acts on buried rock|Buried rock still experiences stress.'],'The brittle and ductile regimes have different strength controls.',
  'What is the correct distinction between stress and strain here?',['*Stress is force per area; strain is deformation|They describe the cause and response.','Stress is deformation; strain is force per area|This reverses the definitions.','Both describe only chemical replacement|Neither term is limited to chemistry.','Both require a fracture to exist|Strain also includes ductile change.'],'Identify the imposed load separately from the resulting change.'],
 ['E2T8','8.4','An inclined break through marker beds','A fault plane dips to the right. Marker beds on the block above the plane are lower than matching beds in the block below. Movement arrows point down on the hanging-wall side.',
  'What type of fault is shown?',['*Normal|The hanging wall moved down.','Reverse|A reverse fault has hanging-wall-up movement.','Thrust|A thrust is a low-angle reverse fault.','Strike-slip|Its defining displacement is horizontal.'],'Identify the hanging wall, then compare relative vertical displacement.',
  'What stress pattern is most consistent with this displacement?',['*Extension across the fault system|Normal faulting commonly accommodates extension.','Horizontal shortening across the fault system|This commonly produces reverse faulting.','Pure sideways shear with no vertical motion|The stated displacement has a vertical component.','Equal pressure on all faces with no differential stress|This alone does not explain the directional slip.'],'Fault movement connects structure to deformation.'],
 ['E2T9','8.5','Trace a folded marker layer','Upright strata curve into an arch. Older units occupy its core, and the two limbs dip away from the center. A surface through successive hinges is inclined rather than vertical.',
  'Which structure fits the age and geometry?',['*Anticline|An anticline has older strata in the core.','Syncline|A syncline has younger strata in the core.','Basin|A basin closes in map view and generally has younger central layers.','Monocline|A monocline is a step-like bend.'],'Use both layer ages and orientation.',
  'What does the inclined hinge-connecting surface describe?',['*The axial surface orientation|It helps describe the fold geometry.','The age of the youngest sediment|Orientation does not date deposition.','The fault slip direction|No fault is established here.','The original shoreline position|The fold surface is a structural feature.'],'The axial surface connects hinges across folded layers.'],
 ['E2T10','8.7','Identify a metamorphic collection','Three samples show: A fine dull cleavage; B visible aligned mica; C alternating coarse light and dark mineral bands. None contains quenched glass.',
  'Which order correctly names A, B, and C?',['*Slate, schist, gneiss|The fabrics match these rock names.','Schist, slate, gneiss|This reverses the first two textures.','Slate, gneiss, schist|This reverses mica-rich and banded textures.','Quartzite, marble, slate|Composition and texture do not match.'],'Fabrics and grain visibility support classification.',
  'Which additional observation best distinguishes marble from quartzite?',['*Mineral composition and reaction with dilute acid|Marble is calcite-rich; quartzite is quartz-rich.','Only the presence of interlocking grains|Both can have interlocking grains.','Only a pale color|Both can be pale.','Only the lack of foliation|Both commonly lack foliation.'],'Shared texture alone cannot separate different mineral compositions.'],
 ['E2T11','8.9','Two thermal and burial histories','Rock beside an intrusion heats strongly without major additional burial. Rock in a subducting slab reaches high pressure while remaining relatively cool for its depth.',
  'Which comparison fits these histories?',['*Contact heating versus high-pressure, low-temperature metamorphism|The pressure–temperature paths differ.','Identical pressure–temperature paths|The stated histories differ.','Both require complete melting of the host|Metamorphism is a solid-state process.','Both require the lowest possible pressure|Subduction increases pressure.'],'Combine heating, burial, and tectonic relations.',
  'What additional evidence would support chemical change by fluids?',['*Addition or removal of components from the rock|Bulk chemical change supports chemical exchange.','Only larger crystals of the same minerals|This may be recrystallization without bulk change.','Only a rigid rotation of the entire outcrop|Rotation is geometric deformation.','Only a decrease in surface elevation|Elevation change does not establish chemical exchange.'],'Fluids can cause mineral reactions and transfer components.'],
 ['E2T12','8.13','Reconstruct a cut and a seal','An inclined fault offsets sedimentary layers. An unfaulted younger deposit rests continuously over the break. Farther away, a resistant dipping layer supports a long sloping ridge.',
  'Which order is established at the sealed fault?',['*Older deposition, fault movement, younger deposition|The fault cuts the older layers and is sealed by the younger unit.','Fault movement, older deposition, younger deposition|The older layers must exist before they are offset.','Older deposition, younger deposition, fault movement|Later slip would normally offset the younger deposit too.','All three events happened simultaneously|Cross-cutting and sealing establish order.'],'This constrains the observed movement rather than every possible later event elsewhere.',
  'What is the sloping ridge surface called if it follows bedding?',['*Dip slope|The surface follows the inclination of resistant bedding.','Axial surface|This connects fold hinges.','Fault plane|This is a slip surface.','Horizontal terrace|Its defining orientation is different.'],'Structure, resistance, and erosion together shape landscapes.']
];
function raw(id,n,q,o,x,t){return {id:id,c:c(n),t:'mc',q:q,o:A.opts(o),x:x,s:src(n),examId:'exam2',mock:false,topics:[t]};}
situations.forEach(function(f){var t=f[0],n=f[1];A.kase({id:'e2-case-'+t,ch:+n.split('.')[0],examId:'exam2',inv:true,title:f[2],stem:'<p>'+f[3]+'</p>',items:[raw('e2-case-'+t+'-1',n,f[4],f[5],f[6],t),raw('e2-case-'+t+'-2',n,f[7],f[8],f[9],t)]});});

var boss=[
 ['7.3','A feldspar-rich granite weathers in a wet climate. Which product is most consistent with hydrolysis?',['*Clay and dissolved ions|Hydrolysis changes silicate minerals.','Only rounded feldspar pebbles|Rounding is abrasion, not chemical reaction.','A new bed of halite|Halite requires appropriate dissolved brines and precipitation.','A glassy volcanic matrix|This is an igneous texture.'],'Water–mineral reactions can produce clay and dissolved material.'],
 ['7.4','Which transported sediment is most likely to remain suspended longest in quiet water, at comparable density?',['*Clay-sized particles|Their small size slows settling.','Sand-sized grains|These generally settle faster.','Rounded pebbles|These are much coarser.','Angular boulders|These are far coarser.'],'Grain size affects settling; transport medium and density also matter.'],
 ['7.5','Which statement correctly separates compaction from cementation?',['*Compaction packs grains; cementation binds them|These are different lithification processes.','Compaction binds grains; cementation packs them|This reverses the processes.','Both require a rock to melt|Both occur without melting.','Both are transport by moving water|They act on deposited sediment.'],'Burial pressure and mineral precipitation both help form rock.'],
 ['7.6','A closed-basin brine evaporates until dissolved minerals crystallize. Which formation pathway is illustrated?',['*Chemical precipitation|Dissolved components form solid crystals.','Mechanical fragmentation|This produces clasts from existing rock.','Contact metamorphism|This transforms solid rock beside heat.','Volcanic crystallization|This starts from magma rather than brine.'],'Evaporites precipitate from increasingly concentrated water.'],
 ['7.7','A sandstone has inclined internal laminae truncated at the top of each set. What is the best interpretation?',['*Migrating bedforms deposited cross beds|The laminae record the lee sides of bedforms.','All sediment settled vertically in still water|This does not explain the inclined sets.','A fault displaced each lamina equally|No offset is described.','Every set was tilted as a single solid slab|Truncations inside sets support deposition.'],'Cross beds are primary sedimentary structures.'],
 ['7.8','Which pair is classified primarily by coarse clast shape?',['*Breccia and conglomerate|Angular versus rounded gravel is diagnostic.','Shale and mudstone|Their distinction includes fissility.','Chalk and coquina|Their carbonate components differ.','Rock salt and gypsum|Their minerals differ.'],'First identify gravel size, then angularity.'],
 ['7.9','A sandstone contains abundant sand-sized quartz and feldspar grains. Which name best fits its feldspar-rich composition?',['*Arkose|Arkose is feldspar-rich sandstone.','Shale|Shale is mud-sized and fissile.','Coquina|Coquina is shell-rich limestone.','Chert|Chert consists of microcrystalline silica.'],'Composition refines the clastic grain-size classification.'],
 ['7.10','Why does mudstone alone provide a less specific setting than mudstone with marine fossils and deep-water structures?',['*Fine sediment accumulates in several quiet settings|Additional clues narrow the alternatives.','Mud cannot occur in lakes|Lakes commonly receive mud.','All mud forms only beneath reefs|Mud occurs in many environments.','Grain size establishes exact water depth|Supply and transport also matter.'],'Use multiple independent observations to interpret an environment.'],
 ['7.11','Which origin best explains dolostone in many carbonate sequences?',['*Dolomite replaces preexisting carbonate|Magnesium-bearing fluids commonly contribute.','Quartz grains become rounded|This changes texture rather than carbonate mineralogy.','Halite evaporates into limestone|These minerals and processes differ.','Magma crystallizes into shell fragments|Shell fragments are biological material.'],'Dolomitization changes carbonate mineralogy through fluid interaction.'],
 ['7.12','In an upright continuous succession, coastal sand overlies offshore mud. Which trend is most consistent?',['*Shoreline progradation or regression|Shallower settings have moved over deeper ones.','Landward marine transgression|This commonly places deeper deposits over shallower ones.','Overturning must have occurred|No inversion evidence is supplied.','The entire sequence is an unconformity|Continuity is stated.'],'Read vertical succession as changing environments through time.'],
 ['7.13','Which combination best reconstructs an ancient depositional environment?',['*Texture, structures, fossils, and regional relations|Independent clues support interpretation.','Only the present elevation|Uplift and erosion can alter it.','Only the current weather|Present weather does not identify ancient deposition.','Only the thickness of one sample|Several environments can produce similar thickness.'],'Integrate observations rather than rely on one clue.'],
 ['7.14','Which geometry commonly helps trap migrated petroleum?',['*A porous reservoir sealed beneath impermeable rock|The seal limits further movement.','A porous reservoir open continuously to the surface|This permits escape.','An impermeable rock with no storage space|It does not provide a useful reservoir.','Any sandstone with no source or seal|A reservoir alone is insufficient.'],'Source, migration, reservoir, and seal all matter.'],
 ['8.1','A sample returns to its original shape when a small stress is removed. What behavior is illustrated?',['*Elastic strain|The deformation is recoverable.','Permanent ductile strain|Permanent strain remains after unloading.','Brittle fracture|A fracture does not restore the original intact sample.','Metasomatism|This involves chemical exchange.'],'Elastic change is reversible within the elastic range.'],
 ['8.2','How does elevated temperature commonly influence deformation under sustained stress?',['*It promotes ductile deformation|Mineral-scale processes become easier.','It makes all rock permanently stronger|Deeper thermal weakening contradicts this.','It prevents strain from occurring|Rock can still deform.','It removes the role of time|Strain rate remains important.'],'Rock response depends on temperature, pressure, composition, and deformation rate.'],
 ['8.3','Why can columnar joints form in cooling lava?',['*Contraction creates fractures|Cooling rock shrinks and cracks.','Each column is a separate fault block|Joints need not have fault displacement.','The lava grows bedding by compaction|This is an igneous cooling structure.','Minerals dissolve into vertical channels|Dissolution is not required for columnar joints.'],'Cooling contraction can organize joint networks.'],
 ['8.4','On an inclined reverse fault, which block moves upward relative to the other?',['*Hanging wall|It lies above the fault plane.','Footwall|The hanging wall moves up relative to it.','Both blocks equally with no relative motion|A fault requires relative displacement.','Only an overlying sedimentary bed|Movement affects the fault-bounded block.'],'Identify wall position before interpreting relative slip.'],
 ['8.5','A fold axis slopes down into the ground. Which term describes this orientation?',['*Plunging|Plunge describes the axis inclination.','Unconformable|This describes a missing stratigraphic interval.','Fissile|This describes splitting in a mudrock.','Nonfoliated|This describes a metamorphic fabric.'],'A plunging axis changes the fold pattern in map view.'],
 ['8.6','Which process directly produces a preferred orientation of platy metamorphic minerals?',['*Growth or rotation under differential stress|Mineral alignment can create foliation.','Uniform settling from a river current|This creates sedimentary deposition.','Gas bubbles freezing in lava|This creates vesicles.','Equal expansion without orientation|This does not create preferred alignment.'],'Foliation relates mineral fabric to deformation and growth.'],
 ['8.7','Quartz-rich sandstone recrystallizes so neighboring quartz grains interlock. What rock commonly results?',['*Quartzite|Quartzite forms from quartz-rich sandstone.','Marble|Marble forms from carbonate rocks.','Slate|Slate commonly forms from mudrock.','Coal|Coal preserves plant-derived carbon.'],'Match parent material with metamorphic mineral composition.'],
 ['8.8','Minerals change into new stable minerals while the rock remains solid. Which process is described?',['*Metamorphic reaction|New minerals form under changed conditions.','Complete melting|The rock remains solid.','Sediment sorting|This separates transported particles.','Volcanic quenching|This cools molten material rapidly.'],'Metamorphism includes mineral reactions without requiring melt.'],
 ['8.9','Which combination most strongly supports a subduction metamorphic setting?',['*High pressure and relatively low temperature|A descending cool slab produces this combination.','Low pressure and strong local heating|This fits many contact settings.','Shallow pressure and no mineral change|This does not establish subduction metamorphism.','Complete melting at surface pressure|This is not the stated metamorphic regime.'],'Pressure and temperature must be interpreted together.'],
 ['8.10','Two normal faults bound a block that moved down relative to its neighbors. What is the block called?',['*Graben|A graben is relatively down-dropped.','Horst|A horst is relatively raised.','Anticline|This is a fold with older central layers.','Thrust sheet|This moves over a low-angle reverse fault.'],'Normal-fault systems can form paired horsts and grabens.'],
 ['8.11','Why can cleavage and bedding point in different directions?',['*They can form during different stages of the rock history|Bedding is deposited; cleavage can form during later deformation.','They are always the same physical surface|They need not coincide.','Both must be produced by the same current|Cleavage is a structural fabric.','Their difference proves every layer is igneous|Sedimentary rocks can develop cleavage.'],'Preserve the distinction between original layering and later fabric.'],
 ['8.14','Which New England sequence separates two supported tectonic episodes?',['*Paleozoic collision, then Mesozoic rifting|The supplied maps and text distinguish these events.','Mesozoic collision, then Paleozoic rifting|This reverses the supplied chronology.','Recent glaciation, then Paleozoic collision|The older collision predates recent glaciation.','Paleozoic collision and Mesozoic rifting simultaneously|They are separate periods and processes.'],'Regional history integrates deformation, metamorphism, rifting, and later erosion.']
];
boss.forEach(function(b,i){var n=b[0],t=L.EXAM2.topics.find(function(t){return t.sections.indexOf(n)>=0;});var e=extra(t.id,n);e.pool='boss';A.mc('e2-boss-'+(i+1),c(n),b[1],b[2],b[3],src(n),e);});
[7,8].forEach(function(ch){var only=boss.map(function(b,i){return +b[0].split('.')[0]===ch?'e2-boss-'+(i+1):null;}).filter(Boolean),core=L.ITEMS.filter(function(it){return it.examId==='exam2'&&it.t==='mc'&&it.pool!=='boss'&&it.c.indexOf('c'+ch+'-')===0;}).filter(function(it,i){return i%2===0;}).slice(0,13).map(function(it){return it.id;});
 L.BOSSES.push({id:'e2-boss-ch'+ch,ch:ch,chs:[ch],examId:'exam2',pass:0.8,title:'Chapter '+ch+' · integrated Boss',desc:'25 original questions across the available chapter. First answers determine the score; corrections remain separate.',refs:only.concat(core),bossOnly:only,cases:[],gens:[]});});

/* October 6 ILEA: verified graph readback, not the supplied answer screenshot as authority. */
A.kase({id:'e2-ilea-moho',ch:8,examId:'exam2',inv:true,title:'October 6 application · Moho and isostasy',stem:'<p>Read the '+(L.EXAM2_SOURCE_MODE==='private'?'original worksheet graph':'course-based Moho schematic')+'. Depth is plotted as negative elevation below the surface. The line deepens beneath the Cascade–Sierra region, shallows beneath much of Basin and Range, and deepens again beneath the Rocky Mountain divisions. Compare approximate regional depths; avoid treating one point as a regional average.</p>',media:L.EXAM2_SOURCE_MODE==='private'?{kind:'img',src:'assets/img/exam2/ilea-moho.jpg',alt:'Original October 6 worksheet with Moho depth cross section and map.',cap:'Supplied October 6 ILEA photograph · original worksheet; answer screenshot is not an official key.'}:{kind:'img',src:'assets/diagrams/exam2/moho.svg',alt:'Schematic of approximate Moho depths across the western United States.',cap:'Original lab schematic from course observations · depths approximate; horizontal distance schematic.'},items:[
 {id:'e2-ilea-1',c:c('8.1'),t:'mc',examId:'exam2',mock:false,q:'What boundary does the Moho identify?',o:A.opts(['*Crust–mantle boundary|It is a compositional boundary identified by seismic velocity change.','Lithosphere–asthenosphere boundary|This is a different mechanical boundary.','Upper–lower mantle boundary|This lies deeper within the mantle.','Mantle–core boundary|This is far deeper.']),x:'Moho and LAB are different boundaries. The October 6 lecture explicitly distinguishes crust and mantle from mechanical layers.',s:['E2ILEA','E2T1006']},
 {id:'e2-ilea-2',c:c('8.10'),t:'mc',examId:'exam2',mock:false,q:'Which broad comparison is supported by this cross section?',o:A.opts(['*Basin and Range is generally thinner-crusted than the Rocky divisions|Its Moho is shallower over much of the profile.','Basin and Range is uniformly the deepest region|The profile shows much shallower depths there.','All three regions have equal Moho depth|Depth changes along the profile.','The Moho rises monotonically from coast to interior|It deepens, shallows, then deepens again.']),x:'Much of Basin and Range is approximately 15–25 km in the photograph; the Rocky divisions are closer to 35–40 km. Cascade–Sierra also includes a deep root around 40 km. These are approximate readings of this profile, not a general elevation ranking of every peak.',s:['E2ILEA','E2T1006']},
 {id:'e2-ilea-write',c:c('8.9'),t:'teach',examId:'exam2',mock:false,q:'Explain how crustal thickness can help support elevation, then state one limit when using the worksheet to compare regional average elevations.',model:'At comparable density, thicker crust floats higher while extending a deeper crustal root into denser mantle: isostatic balance. The worksheet supports thicker crust beneath the Rocky divisions than much of Basin and Range. Cascade–Sierra has a locally deep root too, so a single deepest point does not establish a regional average. Temperature, density, and dynamic support also affect elevation; the mantle need not be a liquid.',rubric:['Defines isostasy as gravitational or buoyant balance of lithospheric material.','Connects greater thickness at comparable density to higher elevation and a deeper root.','Uses the profile to compare the Rocky divisions with much of Basin and Range.','Separates a local deep root from a regional average and notes an additional control.'],s:['E2ILEA','E2T1006']}
]});
})(window.L);
