import json, pathlib, hashlib, zipfile,xml.etree.ElementTree as E
r=pathlib.Path.cwd(); out=r/'source-materials/lecture-03-audit'
if (r/'study-guides/chapter-03-modules.js').exists():
 raise SystemExit('Lecture 3 already exists. Refusing to replace stable records or duplicate script entries.')
# Each record supplies teaching, exact source slides, and two independent original retrieval prompts.
data=[
('surface','Reading the tectonic landscape',2,10,'Earth’s large features form patterns. The Pacific Northwest combines an offshore ridge and seafloor steps with Cascade volcanoes. Western South America has a trench and the Andes, while its eastern side has a continental shelf and a low-relief interior. The South Atlantic has a ridge with offsets and fracture zones, shelves on both sides, and smoother deep seafloor away from the ridge. Tibet stands above the Indian lowlands beside the Himalaya. Japan has curving ridges and trenches. The Arabian region includes the Red Sea, Gulf of Aden, Afar, and an oceanic ridge.',[
('Which pair characterizes the western edge of South America in the lecture?',['Andes and an oceanic trench','A smooth shelf and no mountains','A mid-ocean ridge on land','Afar and the Red Sea'],0,'Read the western edge of the map.','The Andes and offshore trench occur together on the western side.'),
('What distinguishes the South Atlantic margins shown in the deck?',['Trenches on both continental margins','Continental shelves on both sides with no trenches','A continuous volcanic island arc','The Himalaya on its eastern edge'],1,'Compare the ocean edges with the central ridge.','The deck labels shelves on both sides, no trenches, and a central ridge with fracture zones.')]),
('drift','Continental drift evidence',11,15,'Continental drift connects several observations with one historical explanation. Continental shapes fit across the Atlantic, fossils of land organisms occur on continents now separated by oceans, and glacial scratches record flow directions that become coherent when continents are restored. The observations support former connection and later separation. A major historical weakness was an adequate mechanism for motion; unfamiliarity with distant evidence also hindered acceptance.',[
('Why do matching land fossils across an ocean support former continental connection?',['They require all continents to be motionless','Former connection allowed land organisms to move between the regions','Fossils measure modern plate velocity directly','Land organisms created the ocean'],1,'Think about the barrier separating the fossil locations today.','A former land connection explains the distribution without requiring those organisms to cross the present ocean.'),
('Which was a key problem for the early continental-drift hypothesis?',['No continents have matching shapes','It lacked an adequate motion mechanism','It predicted no glaciation','Every fossil occurred on only one continent'],1,'Separate evidence for motion from the force producing motion.','The lecture identifies mechanism as a major problem despite geographic, fossil, and glacial evidence.')]),
('belts','Mapping tectonic activity',16,19,'Earthquakes, volcanoes, and high mountain belts are unevenly distributed. Their overlapping belts identify tectonic activity and outline lithospheric plates. Mid-ocean ridges, trenches, island arcs, and southern Eurasian mountains help reveal these patterns. Some regions are comparatively quiet; volcanoes also occur on oceanic islands. A single point does not establish a boundary as well as a coherent regional belt.',[
('What do the overlapping belts of earthquakes, volcanism, and mountain building outline?',['Daily weather systems','Tectonic plates in the lithosphere','Only political borders','The liquid outer core'],1,'Compare all three maps.','Belts of tectonic activity divide the lithosphere into plates.'),
('Which observation best supports a plate boundary?',['One isolated high hill','A regional belt of earthquakes associated with a trench','One sediment grain','An arbitrary straight line across a quiet continent'],1,'Look for a spatial pattern of tectonic activity.','The lecture uses coherent belts of tectonic activity to identify plate boundaries.')]),
('motion','Three relative plate motions',20,21,'A boundary is classified by relative motion. Divergent plates move apart, convergent plates approach, and transform plates move horizontally past each other. Relative motion compares both plates; it is not simply the compass direction of one plate. Compare mapped boundary types with ridges, trenches, mountains, and island chains.',[
('Two plates separate across a boundary. Which type is it?',['Convergent','Transform','Divergent','Passive margin'],2,'Name the motion before the landform.','Divergence is relative motion apart.'),
('Which motion defines a transform boundary?',['Horizontal sliding past the other plate','Moving directly toward the other plate','Moving directly away from the other plate','No relative motion'],0,'Distinguish sliding from opening and closing.','Transform motion is horizontal relative sliding.')]),
('ridge','Mid-ocean ridges and new crust',22,23,'At an oceanic divergent boundary, plates separate and asthenosphere rises and melts. Magma rises through fractures, then erupts or solidifies at depth to form new oceanic crust. A narrow rift can mark the ridge crest. Hot rocks and thin lithosphere help keep the ridge elevated. Seafloor spreading continually carries the newly formed crust away from the spreading center.',[
('Where does new oceanic crust form in seafloor spreading?',['At a mid-ocean ridge','Only beneath a continental collision','At every passive margin','Only in a trench'],0,'Find where magma fills space opened by separation.','Magma erupts or solidifies at oceanic divergent boundaries, forming new crust.'),
('Which sequence matches the ridge model?',['Asthenosphere rises and melts, magma enters fractures, new crust forms','Crust sinks into a trench, the trench becomes a continent','Continents collide, all mantle stops moving','Sediment turns directly into a new ocean'],0,'Follow the material upward.','The lecture links rising and melting asthenosphere to magma movement and crust formation.')]),
('rift','Continental rifting to an ocean',24,24,'Continental rifting may begin with uplift over rising mantle, followed by stretching and faulting that form a rift. Melting supplies magma. Continued separation can establish seafloor spreading and a new ocean basin, which then widens. The lecture compares the East African Rift, the Red Sea, and the modern Atlantic as examples of stages; it does not claim every rift must complete the sequence.',[
('Which example illustrates an early continental rift in the lecture?',['East African Rift','Andes trench','Himalayan collision','Japan island arc'],0,'Look for continental stretching and faulting.','East Africa illustrates the rift stage.'),
('Continued continental separation establishes seafloor spreading. What can develop next?',['A widening ocean basin','A continent-continent collision immediately','A permanently closed fracture','An end to all magma formation'],0,'Follow the lecture’s Red Sea to Atlantic comparison.','Sustained spreading can widen the new ocean basin.')]),
('subduction','Oceanic subduction and island arcs',25,26,'When oceanic plates converge, one can descend beneath the other at a subduction zone. A trench marks the descending plate’s entry, and an accretionary prism develops near the boundary. The slab releases water, which promotes melting in the mantle above it. Magma rises through mantle and crust, and eruptions build a volcanic island arc. Distinguish the descending slab from the mantle where the lecture places melting.',[
('What promotes mantle melting above a subducting oceanic slab in the lecture model?',['Water released by the slab','Cold seawater freezing the entire mantle','The absence of any fluids','Sediment blocking all heat'],0,'Follow the labeled water arrow.','The descending slab releases water that causes melting in the overlying mantle.'),
('Which combination fits ocean-ocean convergence?',['Trench and volcanic island arc','Only a passive shelf','A continent split by a new Atlantic','No descending plate and no trench'],0,'Identify both the plate-entry feature and the volcanic feature.','Oceanic subduction produces a trench and a volcanic island arc.')]),
('ring','The Pacific Ring of Fire',27,28,'Subduction around much of the Pacific explains the belts of volcanoes. Subduction beneath oceanic plates creates island arcs such as Japan. Subduction beneath continental plates creates volcanic mountain belts such as the Andes. Oceanic plates descend on both sides of the Pacific, but the overriding plate differs. The East Pacific Rise is a spreading boundary within this wider system.',[
('Why does Japan form an island arc while the Andes form a continental volcanic mountain belt?',['The overriding plate differs','Japan has no plate interactions','The Andes sit on a passive margin','All Pacific margins are divergent'],0,'Ask what lies above the descending plate.','The lecture contrasts subduction beneath oceanic and continental plates.'),
('Which Pacific feature is a spreading boundary?',['East Pacific Rise','Andean trench','Japanese trench','Himalayan collision'],0,'A rise or ridge can mark a spreading center.','The lecture explicitly identifies spreading at the East Pacific Rise.')]),
('collision','Continental collision and high mountains',29,30,'Oceanic subduction can bring two continents together. When buoyant continental material reaches the collision, the lecture model shows subduction ending and deformation spreading across a broad zone. Pieces are sliced off and crust thickens. Thick crust supports high elevation, with few volcanoes compared with a subduction volcanic arc. The Himalaya and Tibetan Plateau provide the geographic context earlier in the deck.',[
('Why does continental collision build high terrain in the lecture model?',['Thickening of continental crust','Complete removal of all crust','Oceanic spreading through the collision center','Cooling instantly lowers the entire region below sea level'],0,'Connect the crustal cross section to elevation.','Collision thickens crust, producing high elevation.'),
('Which feature best distinguishes the lecture’s continental collision from a volcanic island arc?',['A broad deformation zone with thick crust and few volcanoes','A central spreading ridge making new ocean floor','No deformation at all','A chain produced only by a hot spot'],0,'Compare the collision sketch with the subduction sketch.','The collision diagram emphasizes broad deformation, thick crust, and few volcanoes.')]),
('transform','Transforms and changing boundary orientation',31,33,'Transform boundaries accommodate horizontal plate motion and link other boundary segments. At mid-ocean ridges, transforms connect offset spreading segments. The seafloor’s zigzag ridge pattern records the combination of spreading and transform geometry. The western North American map supplies additional transform examples; boundary type should be read from motion and the map legend.',[
('What links offset spreading segments on a mid-ocean ridge?',['Transform boundaries','Continental collision zones only','Passive margins only','Hot spots only'],0,'Look between neighboring ridge segments.','Transforms link spreading segments and accommodate horizontal relative motion.'),
('A ridge is offset in a zigzag pattern. Why should each segment be examined separately?',['Spreading segments and transform links have different relative motions','Every segment is necessarily convergent','The map cannot contain plate information','Offsets prove there is no motion'],0,'Distinguish the links from the spreading centers.','The pattern combines divergent ridge segments with transform connections.')]),
('forces','Plate-driving forces and rates',34,35,'The lecture identifies ridge push, slab pull, and mantle convection among the forces associated with plate motion. Plate velocities are measured in centimeters per year, and rates differ among boundaries. A map’s rate labels are needed for numerical comparisons; the mere presence of a boundary does not establish its speed.',[
('Which set names the forces listed in the lecture?',['Ridge push, slab pull, mantle convection','Tides alone and surface winds','Glacial scratches and fossil walking','Sediment color and coastline names'],0,'Recall the force diagram.','The lecture names ridge push, slab pull, and other forces such as mantle convection.'),
('Which statement matches the lecture’s rate comparison?',['Plates move in centimeters per year at differing rates','Every plate moves at exactly the same speed','Plates move kilometers each second','Motion has no measurable rate'],0,'Attend to both units and variation.','Relative plate rates differ and are expressed in cm/year.')]),
('geometry','Motion arrows and boundary geometry',36,38,'Motion arrows show direction and encode higher rates with greater length. Some curve because plates rotate on a sphere. The same pair of plates can have different boundary types where the boundary changes orientation: motion can open one segment and slide along another. The lecture contrasts transform motion on the Queen Charlotte fault with convergence and Pacific-plate subduction where the North America–Pacific boundary bends.',[
('On the lecture’s motion map, what does a longer arrow represent?',['Higher movement rate','Older continental crust','Greater sediment thickness','A larger earthquake magnitude'],0,'Use the arrow encoding rather than the map color.','Arrow length represents movement rate; direction gives motion direction.'),
('How can the same two plates have transform and convergent boundary segments?',['Boundary orientation changes relative to their motion','One plate must stop existing','Plate motion must always be zero','All maps use the words interchangeably'],0,'Compare motion across the boundary with motion along it.','Changing boundary orientation changes the component of relative motion across the boundary.')]),
('magnetism','Magnetic reversals and seafloor stripes',39,41,'The lecture connects Earth’s magnetic field with convection currents in the liquid outer core and distinguishes normal from reversed polarity. As crust forms at a ridge, it records the polarity at that time. Spreading carries an older stripe away while new crust records the current polarity. Successive reversals build a spatial sequence of magnetic stripes, which can be compared with measured magnetic patterns.',[
('Why does an older magnetic stripe move away from a ridge?',['Seafloor spreading carries its crust outward','The entire magnetic field drags continents through air','The stripe turns into a trench instantly','The ridge stops producing crust permanently'],0,'Separate crustal motion from a change in field polarity.','Spreading transports previously formed crust while younger crust forms at the ridge.'),
('What builds alternating magnetic stripes over time?',['New crust recording successive normal and reversed polarities during spreading','Only changes in sediment color','Continental shelves remaining motionless','A single permanent polarity with no crust formation'],0,'Combine the time sequence with outward motion.','New crust records successive polarities, and spreading preserves the sequence in stripes.')]),
('seafloor','Seafloor age and sediment tests',42,42,'Seafloor spreading predicts an age pattern: volcanic oceanic crust is youngest near the ridge because it has just formed. Farther away, crust has had more time to move and accumulate sediment. Drill cores test the pattern using both volcanic-rock ages and sediment thickness. These are independent observations that should fit the same history.',[
('Where should the youngest volcanic oceanic crust occur in the lecture model?',['Near the mid-ocean ridge','Always at the greatest distance from the ridge','Only beneath Tibet','Only on a passive continental shelf'],0,'Find where new crust forms.','Crust forms at the ridge, so volcanic rocks nearest it are youngest.'),
('Why does sediment generally thicken away from the ridge in this model?',['Older seafloor has had more time for sediment accumulation','The ridge creates the oldest crust','All sediment melts at continental margins','Plate motion requires identical thickness everywhere'],0,'Compare time available for deposition.','Older crust farther from the ridge has had longer to accumulate sediment.')]),
('hotspot','Island and seamount chains',43,43,'A plate moving over a hot spot forms a line of volcanoes. A volcano forms over the hot spot, becomes inactive as plate motion carries it away, and can later become a seamount as the plate cools and subsides. Hawaii is the lecture example. Track the moving plate separately from the hot spot in this model.',[
('Why does a volcano become inactive in the lecture’s hot-spot chain model?',['Plate motion carries it away from the hot spot','Every island is a transform boundary','Sediment reverses the outer core','The entire ocean stops moving'],0,'Follow the volcano with the plate.','A volcano loses its position over the hot spot as the plate moves.'),
('How can an island become a seamount in the lecture sequence?',['The plate cools and subsides after moving away','Continental collision lifts it above the Himalaya','The hot spot turns it into a continental shelf','A magnetic reversal instantly removes its crust'],0,'Connect cooling with vertical motion.','Cooling and subsidence can carry an inactive volcanic island below sea level.')]),
('samerica','South America across an entire plate system',44,45,'A west-to-east cross section links the offshore trench, subduction beneath western South America, Andes mountains and volcanoes, the continental interior, a passive eastern continental margin, and the Mid-Atlantic Ridge. A continental edge is not automatically a plate boundary. The east coast lies within the larger plate system, while active spreading occurs farther offshore at the ridge.',[
('Why is South America’s eastern continental edge a passive margin in the lecture?',['It is not a plate boundary','All plate motion ends at the coastline','It is the Andean subduction trench','It is the Mid-Atlantic Ridge itself'],0,'Distinguish a continent edge from a plate edge.','The cross section labels the eastern edge as a passive margin, not a plate boundary.'),
('Which west-to-east sequence matches the lecture cross section?',['Trench and subduction, Andes, passive east margin, Mid-Atlantic Ridge','Mid-Atlantic Ridge, Andes, Japan, trench','Passive west margin, central trench, east-coast Andes','Himalaya, East Africa, Japan, Hawaii'],0,'Trace the section from the Pacific toward the Atlantic.','Western subduction supports the Andes; the eastern continental margin is passive and the spreading ridge lies offshore.')])]
modules=[]; visuals={}; questions=[]
for mi in range(8):
 pair=data[mi*2:mi*2+2]; mid='ch3-'+['evidence','plates','divergence','subduction','collision-transform','dynamics','spreading-tests','synthesis'][mi]
 titles=['Landscape and Continental Drift','Tectonic Belts and Plate Motions','Ridges and Continental Rifting','Subduction and the Ring of Fire','Collision and Transform Boundaries','Plate Forces, Rates, and Geometry','Magnetic Stripes and Seafloor Tests','Hot Spots and South America']
 m=dict(id=mid,number=14+mi,title=titles[mi],kicker='Chapter 3 · Plate tectonics',description='Study the lecture models, interpret the source figures, and retrieve the causal relationships.',source=f'Lecture 3 slides {pair[0][2]}–{pair[-1][3]}',emphasis='Full supplied deck; classroom cutoff unconfirmed',concepts=[],activities=[])
 vv=[]
 for slug,label,start,end,body,qs in pair:
  cid='ch3-'+slug;m['concepts'].append(dict(id=cid,label=label));src=f'Lecture 3 slides {start}–{end}'
  m['activities'].append(dict(id=cid+'-lesson',type='lesson',title=label,body=[body],keyPoints=[qs[0][4],qs[1][4]],source=src))
  for j,(prompt,choices,answer,hint,explanation) in enumerate(qs):
   q=dict(id=cid+f'-q{j+1}',type='single',concept=cid,topic=label,prompt=prompt,choices=choices,answer=answer,hint=hint,explanation=explanation,source=src,provenance='original',evidenceStatus='verified-deck')
   m['activities'].append(q);questions.append(q.copy())
  for s in range(start,end+1):
   vv.append(dict(id=f'ch3-slide-{s}',title=f'Lecture 3 · Slide {s}',src=f'assets/visuals/slides/l3/slide-{s}.png',alt=f'Original lecture slide {s} for {label}, with source labels and diagrams.',caption=f'{label}: original lecture figure and annotations.',notice=qs[0][4]+' '+qs[1][4],source=f'Lecture 3 slide {s}',status='verified'))
 m['activities'].append(dict(id=mid+'-sketch',type='teachback',concept=m['concepts'][-1]['id'],prompt=f'Without the slides, sketch or explain the relationships in “{titles[mi]}”. Then use the rubric to check your account.',rubric=[pair[0][4],pair[1][4]],hint='Name the observed features, motion or process, and the resulting interpretation.',explanation='Compare your reconstruction with the source figures and the two teaching sections. Self-rate only after checking each relationship.',source=m['source'],provenance='original'))
 modules.append(m);visuals[mid]=dict(label=titles[mi]+' · source atlas',intro='Full source slides. Open any image to zoom. The supplied deck has no classroom stopping marker.',visuals=vv)
(r/'study-guides/chapter-03-modules.js').write_text('window.GEOL_MODULES.push(...'+json.dumps(modules,indent=2)+');\n')
(r/'study-guides/chapter-03-visuals.js').write_text('Object.assign(window.GEOL_VISUALS, '+json.dumps(visuals,indent=2)+');\n')
(r/'quizzes/chapter-03-bank.js').write_text('window.GEOL_QUIZZES.push('+json.dumps(dict(id='chapter-three-boss-drill',title='Chapter 3 Boss Drill',description='32 original questions on the full plate tectonics lecture. Practice items also appear in the guided modules.',lane='Exam 1',chapters='Chapter 3',status='Verified lecture bank',questions=questions),indent=2)+');\n')
p=r/'index.html';s=p.read_text();s=s.replace('  <script src="assets/app.js', '  <script src="study-guides/chapter-03-modules.js?v=lecture3-20260908"></script>\n  <script src="study-guides/chapter-03-visuals.js?v=lecture3-20260908"></script>\n  <script src="quizzes/chapter-03-bank.js?v=lecture3-20260908"></script>\n  <script src="assets/app.js');p.write_text(s)
ppt=pathlib.Path('/Users/ethanheinrick/Desktop/GEOL-1001/LECTURE POWERPOINTS/LECTURE 3/GEOL1001-002 Lecture 3.pptx');z=zipfile.ZipFile(ppt);ns={'a':'http://schemas.openxmlformats.org/drawingml/2006/main'}
slides=[{'slide':i,'text':' | '.join(t.text or '' for t in E.fromstring(z.read(f'ppt/slides/slide{i}.xml')).findall('.//a:t',ns))} for i in range(1,46)]
(out/'source-inventory.json').write_text(json.dumps(dict(path=str(ppt),sha256=hashlib.sha256(ppt.read_bytes()).hexdigest(),count=45,notes='Slide numbers only; no classroom cutoff.',slides=slides),indent=2))
(out/'coverage.md').write_text('# Lecture 3 coverage\n\nSource: '+str(ppt)+'\n\nFull deck, 45 slides; classroom cutoff unconfirmed. Slide 1 is the title. Slides 2–45 appear in the source atlas and are mapped below. Slide 7 is a photographic eight-thousanders overview; no unsupported peak-name questions are added.\n\n'+'\n'.join(f'- Slides {d[2]}–{d[3]}: {d[1]} (`ch3-{d[0]}`).' for d in data)+'\n\n8 modules; 16 concepts; 32 keyed choice activities; 8 rubric-based teach-backs; 32-question Boss Drill reuses the original choice roots. New content is deck-grounded, not proof of instructor emphasis.\n\nCompatibility: existing lab predates the v2 manager and has no course-config.js. Extension follows its established additive chapter scripts; legacy runtime is preserved. Final and Exam 2 remain existing evidence-gated placeholders.\n\nCourse routing: /Users/ethanheinrick/Desktop/MISC SHIZ/OBSIDIAN.MD /ETHAN/wiki/academics/Fall-2026/GEOL-1001/GEOL-1001.md; /Users/ethanheinrick/Desktop/GEOL-1001/SYLLABUS : ADMIN/COURSE_CONTEXT.md.\n')
print('Added 8 modules, 16 concepts, 40 graded activities, 32-question drill')
