const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'../..'),raw=require('./content.cjs');
const inventory=JSON.parse(fs.readFileSync(path.join(__dirname,'source-inventory.json'))),visuals=JSON.parse(fs.readFileSync(path.join(__dirname,'visual-manifest.json')));
const sourceText=c=>`Exploring Geology 6.${c.section}, supplied PDF pp. ${c.pages}; textbook-grounded, classroom emphasis unconfirmed`;
const modules=raw.map((m,i)=>({id:m.id,examId:'exam-one',number:31+i,chapter:6,kicker:'Chapter 6 · Textbook-grounded',title:m.title,description:m.body[0],source:m.concepts.map(sourceText).join(' | '),evidenceStatus:'verified',emphasis:'Textbook evidence; classroom emphasis unconfirmed',concepts:m.concepts.map(c=>({id:c.id,label:c.label})),activities:[{id:m.id+'-lesson',type:'lesson',title:m.title,body:m.body,keyPoints:m.concepts.map(c=>c.rule),source:m.concepts.map(sourceText).join(' | ')},...m.concepts.flatMap(c=>c.questions.map((q,j)=>({id:c.id+'-q'+(j+1),type:'single',concept:c.id,topic:c.label,prompt:q[0],choices:q[1],answer:q[2],explanation:q[3],hint:c.hint,source:sourceText(c),provenance:'original',evidenceStatus:'verified'})))]}));
function extra(mid,a){const m=modules.find(m=>m.id===mid);m.activities.push({...a,source:m.source,provenance:'original',evidenceStatus:'verified'});}
extra('ch6-recognition',{id:'ch6-volcano-match',type:'match',concept:'ch6-types',prompt:'Match each volcano type to its characteristic construction.',rows:[{label:'Shield',answer:'Repeated fluid basalt flows'},{label:'Scoria cone',answer:'Loose fragments around a vent'},{label:'Composite',answer:'Interlayered lava and fragmental deposits'},{label:'Dome',answer:'Viscous lava piled near the vent'}],options:['Repeated fluid basalt flows','Loose fragments around a vent','Interlayered lava and fragmental deposits','Viscous lava piled near the vent'],hint:'Connect the shape to the material and how it is deposited.',explanation:'Volcano types reflect construction processes. A dome or scoria cone can also occur on a larger volcano.'});
extra('ch6-monitoring',{id:'ch6-monitor-match',type:'match',concept:'ch6-monitor-tools',prompt:'Match monitoring observations with the appropriate measurement.',rows:[{label:'Earthquake activity',answer:'Seismometer'},{label:'Change in slope',answer:'Tiltmeter'},{label:'Precise station position',answer:'GPS'},{label:'Heat output',answer:'Thermal sensing'}],options:['Seismometer','Tiltmeter','GPS','Thermal sensing'],hint:'Name the physical quantity before choosing the instrument.',explanation:'Seismometers measure shaking, tiltmeters measure tilt, GPS measures position, and thermal sensing tracks heat. The observations should be interpreted together.'});
extra('ch6-monitoring',{id:'ch6-rainier-teachback',type:'teachback',concept:'ch6-rainier',prompt:'Explain how plate setting, magma, ice, and valleys connect Rainier to risk downstream. Reveal the rubric, then honestly self-rate.',rubric:['Juan de Fuca oceanic lithosphere subducts beneath North America.','Rainier is an intermediate-composition composite volcano.','Water from snow/ice or other sources can mix with volcanic debris into lahars.','Valleys carry debris toward exposed communities; some lahars do not require a new eruption.'],hint:'Follow cause → volcano → hazard → exposure.',explanation:'Use all four links in the rubric. This is self-assessment, not automatic grading of prose.'});
const items=modules.flatMap(m=>m.activities.filter(a=>a.type==='single'));
const quizzes=[{id:'chapter-six-volcanoes-drill',title:'Chapter 6 · Eruptions and Volcano Types',chapters:'Chapter 6 · Sections 6.1–6.5',questions:items.slice(0,16)},{id:'chapter-six-hazards-drill',title:'Chapter 6 · Hazards and Monitoring',chapters:'Chapter 6 · Sections 6.6–6.14',questions:items.slice(16)},{id:'chapter-six-boss-drill',title:'Chapter 6 Boss Drill',chapters:'Chapter 6 · Volcanoes and Volcanic Hazards',kind:'boss',questions:items}].map(q=>({...q,examId:'exam-one',lane:'Exam 1',status:'Ready',description:'Original textbook-grounded practice. Same item roots as topic Labs; use topic Labs for confidence-based mastery. Lecture emphasis unconfirmed.'}));
const groups=Object.fromEntries(modules.map(m=>[m.id,{id:m.id+'-visuals',label:'Textbook visual field guide',intro:'Use the same observe → explain → retrieve routine as the earlier chapters. Click to enlarge; check the source and what-to-notice cue.',visuals:visuals.filter(v=>v.module===m.id)}]));
const runtime=`/* Additive Chapter 6 extension. No browser-storage access; existing records remain untouched. */\n(()=>{'use strict';\nconst modules=${JSON.stringify(modules,null,2)};\nconst quizzes=${JSON.stringify(quizzes,null,2)};\nconst visuals=${JSON.stringify(groups,null,2)};\nconst oldIds=new Set(window.GEOL_MODULES.flatMap(m=>[m.id,...m.concepts.map(c=>c.id),...m.activities.map(a=>a.id)]));\nconst ids=modules.flatMap(m=>[m.id,...m.concepts.map(c=>c.id),...m.activities.map(a=>a.id)]);\nif(new Set(ids).size!==ids.length||ids.some(id=>oldIds.has(id))||quizzes.some(q=>window.GEOL_QUIZZES.some(o=>o.id===q.id))||Object.keys(visuals).some(k=>window.GEOL_VISUALS[k]))throw Error('Chapter 6 collision: refusing to replace existing content');\nwindow.GEOL_MODULES.push(...modules);window.GEOL_QUIZZES.push(...quizzes);Object.assign(window.GEOL_VISUALS,visuals);\n})();\n`;
fs.writeFileSync(path.join(root,'study-guides/chapter-06-extension.js'),runtime);
const sources=inventory.map(({text,...s})=>s),claims=[],concepts=[],gradedItems=[];
const refs=(c)=>[{id:`ch6-source-${c.section}`,locator:`Supplied PDF pages ${c.pages}`,boundary:'verified'},...(c.id==='ch6-flow-textures'?[{id:'ch6-source-4',locator:'PDF page 5, pillow basalt',boundary:'verified'}]:c.id==='ch6-composite'?[{id:'ch6-source-8',locator:'PDF pages 4–6, Mount St. Helens',boundary:'verified'}]:c.id==='ch6-caldera'?[{id:'ch6-source-11',locator:'PDF pages 2–4, Thera/Krakatau',boundary:'verified'}]:[])];
for(const m of modules){for(const c of raw.find(r=>r.id===m.id).concepts){const acts=m.activities.filter(a=>a.concept===c.id),claimIds=[];for(const a of acts){const id=a.id+'-claim';claimIds.push(id);claims.push({id,text:a.explanation,status:'verified',sourceRefs:refs(c)});gradedItems.push({...a,moduleId:m.id,conceptId:c.id,claimIds:[id],sourceRefs:refs(c),status:'verified'});}concepts.push({id:c.id,label:c.label,moduleId:m.id,teaching:m.activities[0].body.join('\n\n'),claimIds,masteryEligible:true});}}
const vrecords=visuals.map(v=>{const id=v.id+'-claim',sourceRefs=[{id:v.sourceId,locator:`PDF page ${v.page}; image ${v.imageIndex}`,boundary:'verified'}];claims.push({id,text:v.notice,status:'verified',sourceRefs});return {...v,moduleId:v.module,src:path.join(root,v.src),claimIds:[id],sourceRefs,status:'verified'};});
const handoff={schemaVersion:'study-lab-handoff-v1',course:{code:'GEOL 1001',title:'General Geology: Physical',term:'Fall 2026'},unit:{examId:'exam-one',label:'Exam 1',coverage:'Chapter 6 sections 6.1–6.14; 6.15 missing investigation figures'},boundaries:{verified:'Supplied textbook factual content and 22 visual source views.',continuation:'Textbook-grounded throughout; no Chapter 6 transcript or quiz available to confirm classroom emphasis.',unresolved:'6.15 export has only one page and omits referenced island map and sample photos. No answer to that investigation is supplied. No current volcano forecasts or historical-interval eruption predictions.'},sources,claims,modules:modules.map(m=>({...m,conceptIds:m.concepts.map(c=>c.id),concepts:undefined,activities:undefined,lesson:m.activities[0]})),concepts,visuals:vrecords,interactions:[],gradedItems,drills:quizzes.map(q=>({...q,itemIds:q.questions.map(a=>a.id),questions:undefined,coverage:q.chapters})),audit:{counts:{}}};
// Textbook facts are supported, but lecture coverage is not confirmed; propagate that boundary.
for(const k of ['claims','modules','concepts','visuals','gradedItems','drills'])for(const record of handoff[k]){record.status='continuation';if(record.sourceRefs)record.sourceRefs=record.sourceRefs.map(r=>({...r,boundary:'continuation'}));}
for(const k of ['sources','claims','modules','concepts','visuals','interactions','gradedItems','drills'])handoff.audit.counts[k]=handoff[k].length;
fs.writeFileSync(path.join(__dirname,'study-lab-handoff-v1.json'),JSON.stringify(handoff,null,2));console.log(handoff.audit.counts);
