// Original teaching and retrieval grounded in the supplied chapter PDFs.
const modules=[];
const c=(id,label,section,pages,rule,hint,questions)=>({id:'ch6-'+id,label,section,pages,rule,hint,questions});
function add(id,title,body,concepts){modules.push({id:'ch6-'+id,title,body,concepts});}
add('recognition','Recognize a Volcano, Not Just a Mountain',[
 'A volcano is a vent where magma and other volcanic products reach the surface. A familiar cone is only one possible expression. Eruptions can also occur along fissures or within broad depressions. Look for the vent, volcanic deposits, and their relationships rather than assuming every mountain is volcanic.',
 'A lava-capped mesa may be an eroded remnant of a flow that traveled away from its vent. The cap is volcanic rock, but the mesa itself was shaped by erosion. This is the same observation-versus-inference distinction practiced in Chapter 1: identify the material, then reconstruct how the landform formed.',
 'Four useful mountain-building types are scoria cones, shields, composite volcanoes, and domes. Scoria cones are comparatively small piles of erupted fragments. Shields are broad and gently sloping, built largely from basalt flows. Composite volcanoes are steeper and layered, with lava and fragmental deposits. Domes are steep accumulations of viscous lava near a vent.',
 'Shape is evidence, not a complete diagnosis. Erosion can obscure craters and slopes, and a scoria cone or dome can sit on a larger volcano. Study sequence is a learning aid, not a prediction of exam weighting. Chapter 6 is textbook-grounded; no Chapter 6 transcript or quiz packet was available for confirming classroom emphasis.'
],[
 c('vent','Vent versus erosional remnant',1,'2–3','Volcanic rock does not prove the hill was built over a volcanic vent.','Separate where lava erupted from where it later cooled.',[
 ['A flat-topped hill has a basalt cap but lies far from the mapped eruptive fissure. What best explains why it need not be a volcano?',['Basalt cannot be volcanic','Erosion can leave a remnant of a lava flow away from its vent','Every lava flow must retain a crater','Only underwater vents count'],1,'The mesa can be an erosional remnant of a lava sheet. A volcanic rock and a volcano built at a vent are different observations.'],
 ['Lava emerges along a long crack without building a conical mountain. How should it be classified?',['Not volcanic because no cone exists','Sedimentary deposition','A volcanic fissure eruption','A glacier'],2,'A volcano need not have a classic cone. Magma reaching the surface through a fissure is volcanic activity.']]),
 c('types','Compare the four volcano forms',1,'4–6','Shield: broad flows; composite: layered cone; scoria: loose fragments; dome: viscous mound.','Connect shape to the material and how far it travels.',[
 ['Which description best identifies a shield volcano?',['A broad edifice built mainly by repeated basalt flows','A small pile made only of loose scoria','An erosional mesa with no vent','A steep mound of highly viscous lava only'],0,'Low-viscosity basalt spreads outward. Repeated flows build a broad shield with gentle slopes.'],
 ['A small cone is mostly loose vesicular fragments ejected around a vent. Which type fits best?',['Caldera','Shield volcano','Volcanic dome','Scoria cone'],3,'Scoria cones grow as ejected fragments fall near a vent. They are not simply miniature domes of intact viscous lava.']])
]);
add('eruption','Why Eruptions Flow or Explode',[
 'Chapter 5 supplies the mechanism: viscosity is resistance to flow. Silica-rich magma generally has a more connected silicate structure and higher viscosity than basaltic magma. Viscosity affects both lava movement and how easily gas bubbles escape.',
 'At depth, confining pressure keeps much volcanic gas dissolved in magma. As magma rises, pressure falls; gas can leave solution and bubbles expand. If viscous magma prevents gas from escaping easily, pressure can build and drive explosive fragmentation. Gas-rich basalt can still fountain, so low viscosity does not mean no explosions.',
 'Lava flows and domes are erupted molten material that moves away from or piles up near a vent. Tephra is ejected fragmental material; its fine fraction is volcanic ash, not the residue of ordinary burning. A buoyant eruption column carries tephra upward; wind spreads ash before it settles.',
 'A pyroclastic flow is a dense, very hot mixture of gas, ash, and fragments moving along the ground. Collapse of an eruption column can produce one; collapse of a dome is another route. It is different from lava and from a water-rich lahar. One volcano can alternate among eruption styles as conditions change.'
],[
 c('gas','Pressure, viscosity, and gas escape',2,'6–8','Falling pressure releases gas; high viscosity impedes its escape.','Think of both dissolved gas and the ability of bubbles to move.',[
 ['What most directly allows dissolved gas to form bubbles as magma rises?',['Increasing confining pressure','A decrease in confining pressure','Conversion of gas to feldspar','Loss of all heat instantly'],1,'Pressure decreases toward the surface, allowing dissolved gases to come out of solution and expand.'],
 ['Two magmas have comparable gas contents. Why can the more viscous one have greater explosive potential?',['It always contains no silica','Its bubbles are necessarily colder','It prevents gravity','It can retain gas rather than allowing easy escape'],3,'High viscosity resists bubble movement and gas escape. Trapped gas can build pressure; composition alone is not the only variable.']]),
 c('products','Distinguish volcanic products and transport',2,'2–5','Column rises and falls out; pyroclastic flow moves hot material along the ground.','Identify what carries the fragments and where they move.',[
 ['A dense, hot cloud of ash and gas races downslope after an eruption column collapses. What is it?',['A pyroclastic flow','A lava tube','A lahar made primarily of water and mud','A slowly advancing intact lava flow'],0,'A collapsed hot ash-and-gas mixture is a pyroclastic flow. A lahar requires water mixed with volcanic debris.'],
 ['Fine volcanic particles blanket a town far downwind. Which transport route best explains this?',['Only a lava flow could reach it','Mineral cleavage moved the particles','Ash rose in an eruption column and was carried by wind','The entire magma chamber slid there'],2,'Fine tephra can be carried far downwind in the atmosphere and deposited as ash fall, unlike valley-confined ground flows.']])
]);
add('basalt','Read Basaltic Flows and Scoria Cones',[
 'Basaltic magma commonly begins an eruption with gas-driven fountains. Clots cool and accumulate as loose scoria around the vent. As less-gassy magma reaches the surface, it may instead emerge as a lava flow, sometimes from the cone base. A single episode can therefore create both a cone and a flow.',
 'Vesicles are preserved bubble spaces. Vesicular basalt and scoria record gas bubbles trapped during cooling; nonvesicular basalt may begin with little gas or lose it before solidifying. Do not confuse a vesicle with a crystal or a mineral cleavage surface.',
 'Aa has a rough surface of jagged, jumbled blocks. Pahoehoe has smoother, folded or ropy surfaces. A lava tube forms when the outer surface solidifies while hot lava continues beneath the insulating roof. Insulation slows cooling and helps lava travel farther.',
 'Lava erupted into water can form rounded pillows. Pillows diagnose the environment of eruption, not simply slow cooling on land. Fresh cones and flows usually retain sharper features and little developed soil; weathering, soil, vegetation, and erosion can obscure them over time.'
],[
 c('scoria','One vent, changing gas content',3,'2–3, 5','Gas-rich fountains can build scoria cones; less-gassy lava can flow afterward.','An eruption can change while composition stays basaltic.',[
 ['A basaltic vent first builds a cone of cinders, then releases a quieter lava flow. Which change best explains the transition?',['The lava must become pure quartz','The plate boundary must reverse direction','Later magma contains less gas available to drive fountains','All rock has become sedimentary'],2,'Early gas-rich magma can fragment in fountains. Later magma with less gas can erupt as a comparatively nonexplosive flow.'],
 ['What do abundant vesicles in a basalt sample record?',['Gas bubbles trapped when the lava solidified','The number of minerals in the rock','Cleavage directions of one crystal','Dissolution by rivers in every case'],0,'Vesicles are former bubbles. Their presence records gas behavior during solidification, not mineral cleavage.']]),
 c('flow-textures','Texture and environment of basalt flows',3,'4; also 6.4 PDF p. 5','Aa is rough; pahoehoe is ropy; tubes insulate; pillows indicate water.','Separate surface shape, heat retention, and eruption environment.',[
 ['Which pairing correctly matches basaltic flow surface textures?',['Aa is ropy; pahoehoe is jagged','Both terms mean volcanic ash','Pahoehoe means pillow basalt only','Aa is jagged and blocky; pahoehoe is ropy'],3,'Aa breaks into rough blocks while pahoehoe develops smoother, folded surfaces. Both describe lava-flow features.'],
 ['Why can a lava flow continue traveling beneath a solid roof?',['The roof adds water until the lava becomes a river','The roof insulates the hot moving interior','The whole flow is already solid','The roof removes gravity'],1,'A lava tube limits heat loss, allowing its molten interior to remain hot and mobile longer than an exposed flow.']])
]);
add('shields-floods','Shields, Fissures, and Flood Basalts',[
 'A shield grows through repeated eruptions of relatively fluid basalt. Lava spreads away from vents and fissures instead of remaining in a steep pile, producing broad, gentle slopes. Shield volcanoes can include summit depressions and scoria cones; those features do not change the overall shield geometry.',
 'Hot spots are important for large oceanic shields such as Hawaii, but shields are not exclusive to one tectonic setting. Keep the Chapter 3 link: setting helps explain magma supply, and composition helps explain viscosity and shape.',
 'Flood basalts are extensive stacks of basalt flows, commonly fed by long fissures or strings of vents. Large magma supply, low viscosity, and high eruption rates permit individual flows to cover broad areas. Exposed dikes can mark the former feeder cracks.',
 'In a common origin model, a mostly solid mantle plume rises, spreads beneath the lithosphere, and produces melting through decompression and heating. Flood-basalt gases can influence climate: sulfur-bearing aerosols can reduce incoming sunlight, whereas carbon dioxide contributes greenhouse warming. Do not reduce all volcanic climate effects to one sign or treat an association with extinction as proof of one sole cause.'
],[
 c('shields','Composition to shield geometry',4,'2–5','Low-viscosity basalt spreads outward, building a broad shield.','Use the Chapter 5 viscosity connection.',[
 ['Why do repeated basalt flows commonly build gentle shield slopes?',['Lava spreads far enough to distribute material broadly','All lava is deposited vertically at the vent','Shields are made only of windblown ash','High viscosity keeps every flow at the summit'],0,'Fluid basalt spreads rather than piling exclusively beside the vent. Repetition builds broad, gentle slopes.'],
 ['Rounded pillow-shaped basalt is exposed on a volcanic island. What is the strongest inference?',['The island must be a composite volcano','The basalt erupted into water','The basalt formed from sandstone','The lava never reached the surface'],1,'Pillow forms develop as lava advances into water. They are evidence of an aquatic eruption environment.']]),
 c('floods','Flood basalt supply and effects',5,'2, 4–7','Long fissures plus abundant fluid basalt can build extensive layered plateaus.','Look for a regional sheet, not only a central cone.',[
 ['A plateau exposes stacked basalt sheets fed by many long dikes. Which eruptive pattern fits?',['One dome of high-viscosity rhyolite','Only a single small scoria cone','A limestone reef','Repeated large fissure-fed flood-basalt eruptions'],3,'Long feeder fissures and extensive basalt sheets characterize flood-basalt systems rather than a single central dome.'],
 ['Why is “volcanism always causes cooling” too simple?',['Volcanoes release no gases','All gases have identical effects','Sulfur aerosols can cool while released carbon dioxide can contribute warming','Only the color of lava controls climate'],2,'The source distinguishes opposing atmospheric effects. Their importance depends on gas amounts, persistence, and other conditions.']])
]);
add('composites','Composite Volcanoes and Their Deposits',[
 'Composite volcanoes, or stratovolcanoes, are built by repeated eruptions over long periods. Their internal record includes lava, tephra, pyroclastic-flow deposits, lahars, and intrusions. Andesite is common, but a composite volcano need not have only one composition or one eruptive style.',
 'They are common above subduction zones, including the Pacific Ring of Fire. Relatively viscous intermediate and felsic lava travels shorter distances and builds steeper slopes. Pyroclastic material and altered rock can make portions unstable, so eruption and collapse hazards can interact.',
 'A lahar is a water-rich flow of volcanic mud and debris. Rain or snow and ice melt can mix with loose volcanic material; landslides can also contribute. It follows valleys and can threaten communities beyond the cone. A pyroclastic flow is instead a hot gas-supported mixture; tuff can form from deposited volcanic ash.',
 'Use disasters to remember mechanisms rather than casualty trivia. Vesuvius and Mount Pelée illustrate lethal pyroclastic activity. At Mount St. Helens in 1980, earthquakes and a growing bulge preceded collapse of the north flank; unloading reduced pressure and helped trigger a lateral blast. The important chain is deformation → instability → collapse/unloading → explosive release.'
],[
 c('composite','Layered history and collapse',7,'2–8; also 6.8 PDF pp. 4–6','Composite means a layered history of different eruptive and surface processes.','Combine the internal deposits with the process that formed each.',[
 ['Why is the term composite appropriate for a stratovolcano?',['Its layers record lava, pyroclastic activity, and debris or mudflows','It is entirely one giant mineral','It forms in only one brief fountain','It has no intrusive structures'],0,'Composite volcanoes combine deposits from multiple eruption styles and surface processes over repeated episodes.'],
 ['In the 1980 Mount St. Helens sequence, why did removal of the north-flank bulge matter?',['It increased confinement on the magma','It converted all magma into water','It decreased pressure on magma and helped trigger a lateral blast','It prevented gas expansion'],2,'The landslide unloaded the volcano, reducing confining pressure and permitting explosive release.']]),
 c('lahar','Water-rich lahar versus pyroclastic flow',7,'3–7','Lahar: water and debris. Pyroclastic flow: hot gas, ash, and fragments.','Identify the fluid carrying the material.',[
 ['Heavy rain remobilizes loose volcanic ash into a muddy flow down a river valley. What is it?',['An eruption column','A lahar','A lava fountain','A mantle plume'],1,'Water mixed with volcanic sediment creates a lahar. It need not be a new lava eruption.'],
 ['An ash-rich deposit was emplaced hot and compacted into welded tuff. Which source process is most consistent?',['Cold river transport of only rounded gravel','Slow growth of one crystal','Deposition of carbonate mud','A pyroclastic flow'],3,'Hot pyroclastic material may compact and weld. A lahar is a water-rich sediment flow and is not the same process.']])
]);
add('domes-calderas','Dome Growth and Caldera Collapse',[
 'A dome forms when intermediate or felsic lava is too viscous to spread far. It can inflate from within as magma is injected, or grow outward as thick lava breaks through the surface. The solid outer crust fractures into angular blocks, creating a rubbly exterior.',
 'A dome can fail by gravitational collapse or explode when gas is trapped beneath a plug. Collapse can send hot blocks and ash downslope as a pyroclastic flow. Domes may occupy the craters of composite volcanoes or form within calderas after a larger eruption.',
 'A caldera is a large volcanic depression formed when the roof above a magma reservoir subsides as magma is withdrawn. Eruption and collapse can occur together. It is not simply a hole excavated by an outward explosion. Faulted blocks drop, thick ash accumulates inside, and later domes, lava, sediment, or a lake may fill part of the basin.',
 'Crater Lake occupies a caldera formed during the Mount Mazama eruption; later activity built Wizard Island. Thera and Krakatau illustrate how eruption and coastal collapse can generate destructive sea waves. Yellowstone illustrates hot-spot-related continental caldera volcanism and widespread ash deposits. These are mechanism examples, not forecasts: historical intervals do not establish the date of the next eruption.'
],[
 c('dome','Dome growth and failure',9,'1–3, 5–6','High-viscosity lava builds near a vent; collapse can send blocks and ash downhill.','Growth and destruction are different parts of the dome cycle.',[
 ['New magma enters the interior of a dome and fractures its solid outer shell. What is happening?',['Caldera roof collapse only','Erosion of a nonvolcanic mesa','Internal growth and inflation of a viscous lava dome','Formation of pillows under water'],2,'Injection inside the dome expands it and fractures the outer crust. Domes can also grow by lava breaking out externally.'],
 ['Why can a slowly growing dome still produce a fast-moving hazard?',['Its unstable flank can collapse into a pyroclastic flow of hot blocks and ash','Slow growth guarantees no hazard','Only basalt can move downslope','Dome material cannot fragment'],0,'Slow extrusion does not guarantee stability. Collapse releases material downslope and can form a dangerous pyroclastic flow.']]),
 c('caldera','Withdrawal causes roof subsidence',10,'2–6; also 6.11 PDF pp. 2–4','Caldera collapse follows loss of magma support beneath the roof.','Track what leaves the chamber and what drops into the vacated space.',[
 ['Which causal sequence best describes caldera formation?',['Rain fills a crater, then manufactures magma','Magma withdrawal during eruption → roof subsidence along faults','A glacier freezes the magma chamber into a hill','A mountain simply dissolves without volcanism'],1,'As magma is withdrawn, the overlying roof subsides along fractures. The eruption and subsidence can occur simultaneously.'],
 ['A small volcanic dome sits inside a broad caldera. Which interpretation is reasonable?',['Calderas cannot contain later volcanic activity','The dome proves the depression is nonvolcanic','Every caldera is made only by wind erosion','Residual magma erupted after the main collapse'],3,'Later magma can reach the surface within or around a caldera and construct domes or other volcanic features.']])
]);
add('risk','Hazard Is Not the Same as Risk',[
 'A hazard is a potentially dangerous process or condition. Risk concerns its possible consequences for people, property, and society. A remote submarine eruption and one through a developed neighborhood can involve comparable physical processes but very different societal exposure.',
 'Basaltic lava can burn or bury structures even when people have time to move away. Scoria and larger projectiles are especially dangerous near vents. Ash can spread downwind, volcanic gases can be hazardous, and eruption beneath ice can cause catastrophic meltwater floods. Relatively nonexplosive does not mean harmless.',
 'Assess paths as well as distance. Valleys can channel lava, lahars, and some pyroclastic flows. Ash follows atmospheric winds. A village farther away in a valley may be more exposed to a particular flow than a closer ridge site. A ridge is not universally safe from ash, blasts, or large flows.',
 'Infer potential behavior from rock types, shape, dated deposits, and past activity, then combine that history with current observations. The section 6.15 PDF contains only the investigation introduction, not its referenced island map or rock photographs. That specific investigation remains incomplete; the practice here uses original scenarios supported by sections 6.6 and 6.12, not invented answers to its missing map.'
],[
 c('hazard-risk','Process versus societal consequences',6,'2–6','Hazard describes the threatening process; risk includes potential societal loss.','Ask whether the statement describes the event or its consequences for people.',[
 ['Which change most directly raises societal risk without changing the lava-flow hazard itself?',['The lava is given a new name','The flow is photographed','A geologist changes the map color','More homes are built in the expected flow path'],3,'Increasing exposed people and structures raises potential loss even if the physical hazard is unchanged.'],
 ['How can a basaltic eruption beneath a glacier produce a flood?',['Heat melts ice and releases water that can carry debris','All basalt is liquid water','The eruption eliminates gravity','Only felsic magma can melt ice'],0,'Eruptive heat can rapidly melt ice. Released meltwater may transport sediment, rock, and ice blocks.']]),
 c('pathways','Valleys, winds, and distance',12,'2–4','Flow paths follow topography; ash dispersal follows wind.','Rank each site for the particular hazard, not by distance alone.',[
 ['Two settlements lie equally far from a volcano. One is in a drainage valley, the other on an adjacent ridge. For a valley-confined lahar, which is generally more exposed?',['The ridge solely because it is higher','Both must have identical exposure','The settlement in the drainage valley','Neither because distance is equal'],2,'Lahars follow drainage paths. Equal distance does not imply equal exposure to a channeled flow.'],
 ['An eruption column rises above a volcano while wind blows east. Where is the greater directional ash-fall concern, all else equal?',['Only directly uphill','East, downwind of the column','Only west because ash moves against wind','Only inside river channels'],1,'Airborne ash is carried downwind. This differs from the topographic control on ground-hugging flows.']])
]);
add('monitoring','Monitor Change and Apply It to Rainier',[
 'Monitoring combines independent evidence. Seismometers record ground shaking associated with rock fracture and magma movement. GPS and surveying track position and elevation; tiltmeters track changes in slope. Repeated satellite radar observations can reveal deformation across a wider area.',
 'Gas measurements, including sulfur dioxide output, and thermal observations can reveal changes associated with rising magma. The strongest interpretation combines seismic, gas, thermal, and deformation evidence. A single signal is not an exact eruption countdown, and absence of a visible lava flow does not prove absence of unrest.',
 'Mount Rainier is an andesitic composite volcano above the Cascadia subduction zone, where oceanic Juan de Fuca lithosphere descends beneath North America. This connects Chapter 3 plate boundaries to Chapter 5 magma processes and Chapter 6 eruption style.',
 'At Rainier, snow and ice, steep or weakened rock, and valleys draining toward communities make lahars especially important. Eruptions can generate them, but landslides unrelated to a new eruption can also contribute. Hazard maps show pathways and potential inundation, while remote sensors can detect a moving lahar and support warnings. The source map is a textbook case study, not a current emergency forecast.'
],[
 c('monitor-tools','Match observations to instruments',13,'2–8','Seismometer: shaking; GPS/tilt/radar: deformation; gas and heat: additional evidence.','First name what is being measured.',[
 ['A station detects a small change in the volcano’s surface slope. Which instrument most directly measures it?',['A mineral streak plate','A tiltmeter','A balance measuring lava mass','A compass alone'],1,'Tiltmeters detect changes in ground tilt, one expression of deformation. Seismometers instead record shaking.'],
 ['Earthquake activity, ground inflation, and sulfur dioxide output all increase. What is the strongest scientific response?',['Declare the exact eruption minute from one reading','Ignore all but the gas data','Conclude that every volcano follows a fixed clock','Integrate the signals to assess unrest and possible eruption'],3,'Multiple independent changes support a more useful interpretation than one measurement. Monitoring improves assessment without guaranteeing exact timing.']]),
 c('rainier','Plate setting to valley risk',14,'2–4','Subduction builds the composite volcano; ice, debris, and valleys connect it to lahar exposure.','Link tectonic cause, volcano properties, and the path to people.',[
 ['Which tectonic relationship underlies Mount Rainier and the Cascades?',['Juan de Fuca lithosphere subducts beneath North America','North America splits at Rainier into two ocean ridges','A transform boundary alone creates all Cascade magma','Rainier is unrelated to a plate boundary'],0,'The Cascades overlie the Cascadia ocean-continent subduction zone. The Juan de Fuca plate descends beneath North America.'],
 ['Why can a town well down a Rainier river valley still face volcanic risk without a new lava flow reaching it?',['All hazards stop at the summit','Only wind matters for water-rich flows','Lahars can travel along drainage paths, including flows triggered by slope failure','A river guarantees protection'],2,'Water and volcanic debris can move far along valleys. Rainier lahars can be associated with eruptions or with noneruptive slope failures.']])
]);
module.exports=modules;
