/* Integration checks without a browser: all study modes, old data, immutable scores and reloads. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),cp=require('child_process');
const root=path.resolve(__dirname,'..');
let clock=1800000000000,checks=0;
class Clock extends Date { constructor(...a){super(...(a.length?a:[clock]));}static now(){return ++clock;} }
function load(storage={},backup){
 const c={console,Math,Date:Clock,JSON,setTimeout(){},document:{readyState:'loading',addEventListener(){}},localStorage:{getItem(k){return storage[k]||null;},setItem(k,v){storage[k]=v;}}};c.window=c;c.globalThis=c;vm.createContext(c);
 const read=f=>backup?cp.execFileSync('tar',['-xOf',backup,f],{encoding:'utf8'}):fs.readFileSync(path.join(root,f),'utf8');
 for(const [,f] of read('index.html').matchAll(/<script src="([^"]+)"/g)){if(f!=='js/app.js')vm.runInContext(read(f),c,{filename:f});}
 c.L.engine.build();return c.L;
}
function test(name,fn){fn();checks++;console.log('PASS '+name);}
const disk={},L=load(disk),E=L.engine,S=L.store,X=L.exam1;
const answer=it=>it.t==='mc'||it.t==='tf'?it.o.findIndex(o=>o.ok):it.t==='ms'?it.o.flatMap((o,i)=>o.ok?[i]:[]):it.t==='fill'?it.acc[0]:it.t==='num'?it.a:it.t==='match'?it.pairs.map(p=>p[1]):it.t==='parts'?it.parts.map(p=>p.a):it.t==='order'?it.seq:({self:'got',response:it.model,rubric:it.rubric.map(()=>true)});
function blank(){S._setMem(S._blank());S.save();}
const backup=process.env.GEOL_BASELINE;
if(backup)test('All 613 September 24 questions retain IDs, prompts and keys',()=>{const old=load({},backup);assert.equal(Object.keys(old.engine.REG()).length,613);for(const id of Object.keys(old.engine.REG()))assert.equal(JSON.stringify(E.REG()[id]),JSON.stringify(old.engine.REG()[id]),id);assert.equal(S.KEY,old.store.KEY);});
test('Every promoted foundation item exists',()=>L.EXAM1.foundationIds.forEach(id=>assert.ok(E.resolve({id}),id)));
for(const mode of ['practice','review','case','boss'])test(mode+' records answers in the same concept history',()=>{blank();const it=E.itemsFor(x=>x.t==='mc'&&!x.caseId)[0];E.newSession(mode,mode,[{id:it.id}],{noRetry:true});E.answerInSession(answer(it),'h',false);assert.equal(E.allAttempts().length,1);assert.equal(E.conceptStats()[it.c].autoAtt,1);E.advance();E.endSession();assert.equal(S.load().sessionHistory.length,1);assert.equal(S.load().sessionHistory[0].results.length,1);});
test('Rubric self-checks enter mastery once, and survive older teach storage',()=>{blank();const it=E.itemsFor(x=>x.t==='teach')[0];E.record(it,{id:it.id},answer(it),'m','case');assert.equal(E.allAttempts().length,1);assert.equal(E.conceptStats()[it.c].selfAtt,1);const state=S._blank();state.teach[it.id]={ts:1,self:'got',response:'Saved older work'};S._setMem(state);assert.equal(E.allAttempts().length,1);assert.equal(E.allAttempts()[0].self,true);});
test('Legacy submitted mock answers enter mastery exactly once',()=>{blank();const m=E.buildMock(Object.keys(L.MOCKS)[0]);m.refs.forEach((r,i)=>m.answers[i]=answer(E.resolve(r)));E.submitMock();assert.equal(E.allAttempts().length,m.refs.length);assert.equal(S.load().mocks.length,1);});
test('Exam first results are immutable and corrections cannot manufacture mastery',()=>{blank();const r=X.startForm('A'),id=r.groups[0].ids[0],it=E.resolve({id}),a=X.answer(r,id);a.draft=it.o.findIndex(o=>!o.ok);X.check(r,id,'h');const first=JSON.stringify(a.first);X.retry(r,id);a.draft=answer(it);X.check(r,id,'h');assert.equal(JSON.stringify(a.first),first);assert.equal(E.allAttempts()[1].h,1);assert.equal(X.metrics(r).autoCorrect,0);assert.equal(X.metrics(r).corrected,1);assert.ok(E.conceptStats()[it.c].highConfidenceMiss);assert.ok(X.misses().some(x=>x.c===it.c));assert.ok(X.topicMetrics(X.topic(L.examTopics(it)[0])).needs.includes(it.c));});
test('Mastery stays earned; later misses clear only with two independent later answers',()=>{blank();const c='c1-cycle',s=S.load();const add=(i,ok,cf,h)=>{s.attempts.push({i,c,ok,cf,h,m:'practice',t:Clock.now()});S.save();};add('one',true,'m');add('two',true,'h');add('three',false,'h');let st=E.conceptStats()[c];assert.equal(st.status,'mastered');assert.ok(st.reviewOpen&&st.highConfidenceMiss);add('three',true,'h',1);assert.ok(E.conceptStats()[c].reviewOpen);add('four',true,'m');assert.ok(E.conceptStats()[c].reviewOpen);add('five',true,'h');st=E.conceptStats()[c];assert.equal(st.status,'mastered');assert.equal(st.reviewOpen,false);assert.equal(st.highConfidenceMiss,false);assert.equal(S.load().masteryCredits[c],'earned');});
test('Same-millisecond events have consistent queue and high-confidence state',()=>{blank();const s=S.load(),c='c1-cycle';s.attempts=[{i:'a',c,ok:false,cf:'h',t:1},{i:'b',c,ok:true,cf:'m',t:1},{i:'c',c,ok:true,cf:'h',t:1}];const st=E.conceptStats()[c];assert.equal(st.reviewOpen,false);assert.equal(st.highConfidenceMiss,false);});
test('Hints and duplicate question roots cannot independently earn mastery',()=>{blank();const s=S.load(),c='c1-cycle';s.attempts=[{i:'a',c,ok:true,cf:'h',t:1},{i:'a',c,ok:true,cf:'h',t:2},{i:'b',c,ok:true,cf:'h',h:1,t:3}];assert.notEqual(E.conceptStats()[c].status,'mastered');});
test('Practice and Exam 1 work can jointly earn a concept; self-assessment remains labeled',()=>{blank();const r=X.startForm('A'),id=r.groups[0].ids[0],it=E.resolve({id});S.load().attempts.push({i:'other-root',c:it.c,ok:true,cf:'m',t:1,self:true});X.answer(r,id).draft=answer(it);X.check(r,id,'h');const st=E.conceptStats()[it.c];assert.equal(st.status,'mastered');assert.equal(st.masterySource,'self');assert.equal(st.att,2);});
test('Drafts, hints, flags, confidence and first answers survive a fresh load',()=>{blank();const it=E.itemsFor(x=>x.t==='teach')[0],sess=E.newSession('case','Written work',[{id:it.id}]);sess.drafts[0]='My unfinished answer';sess.revealed[0]=true;sess.assisted[0]=true;const r=X.startForm('B');r.flags[3]=true;r.cur=3;const a=X.answer(r,r.groups[3].ids[0]);a.confidence='h';a.draft=2;S.save();const fresh=load(disk);assert.equal(fresh.store.load().session.drafts[0],'My unfinished answer');assert.ok(fresh.store.load().session.revealed[0]);assert.ok(fresh.exam1.active().flags[3]);assert.equal(fresh.exam1.active().answers[r.groups[3].ids[0]].confidence,'h');});
test('Starting another exercise archives the unfinished session with its draft',()=>{const old=S.load().session;E.newSession('practice','Another exercise',E.practiceRefs({n:2}));assert.equal(S.load().sessionHistory.find(x=>x.id===old.id).drafts[0],'My unfinished answer');});
test('Export/import is idempotent and preserves newer drafts and correction history',()=>{blank();const sess=E.newSession('practice','Saved',[{id:L.EXAM1.foundationIds[0]}]);sess.drafts[0]=1;sess.updated=Clock.now();const r=X.startForm('A'),id=r.groups[0].ids[0],a=X.answer(r,id),it=E.resolve({id});a.draft=it.o.findIndex(o=>!o.ok);X.check(r,id,'h');const before=S.exportJSON();X.retry(r,id);a.draft=answer(it);a.confidence='l';X.check(r,id,'l');r.flags[0]=true;r.updated=Clock.now();sess.drafts[0]=2;sess.updated=Clock.now();const after=S.exportJSON();blank();assert.ok(S.importText(before).ok);assert.ok(S.importText(after).ok);assert.ok(S.importText(before).ok);assert.ok(S.importText(after).ok);const merged=X.byId(r.id);assert.equal(merged.answers[id].tries.length,1);assert.equal(merged.answers[id].first.grade.ok,false);assert.equal(merged.answers[id].confidence,'l');assert.equal(merged.flags[0],true);assert.equal(S.load().session.drafts[0],2);assert.equal(S.load().examRuns.length,1);});
test('Every full mock follows 25/8/7 with 54 parts and honest score denominators',()=>{blank();for(const f of ['A','B','C']){const r=X.startForm(f);assert.equal(r.groups.filter(g=>g.section==='mc').length,25);assert.equal(r.groups.filter(g=>g.section==='sa').length,8);assert.equal(r.groups.filter(g=>g.section==='inv').length,7);const m=X.metrics(r);assert.equal(m.autoTotal,43);assert.equal(m.selfTotal,11);assert.equal(m.unanswered,54);assert.equal(new Set(X.allIds(r)).size,54);}});
if(backup)test('Old saved run groups remain answerable after forms are refined',()=>{const old=load({},backup),r=JSON.parse(JSON.stringify(old.exam1.startForm('B')));blank();S.load().examRuns.push(r);for(const id of X.allIds(r)){const it=E.resolve({id}),a=X.answer(r,id);assert.ok(it);a.draft=it.t==='teach'?it.model:answer(it);X.check(r,id,'m');if(it.t==='teach')X.selfMark(r,id,it.rubric.map(()=>true));}assert.equal(X.metrics(r).checked,54);});
test('Reopening a completed Boss session does not duplicate its run',()=>{blank();const b=L.BOSSES[0],sess=E.newSession('boss',b.title,E.bossRefs(b.id),{bossId:b.id,noRetry:true});while(sess.idx<sess.queue.length){const it=E.resolve(sess.queue[sess.idx].ref);E.answerInSession(answer(it),'h',false);E.advance();}E.finishBoss(sess);const backup=S.exportJSON();E.finishBoss(sess);assert.equal(S.load().boss[b.id].runs.length,1);S.importText(backup);assert.equal(S.load().boss[b.id].runs.length,1);assert.equal(S.load().boss[b.id].best,1);});
console.log('TOTAL',checks,'cohesion checks passed');
