/* No browser state used. Verify the new content contract and immutable old assessment records. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),cp=require('child_process');
const root=path.resolve(__dirname,'..'),audit='/Users/ethanheinrick/Desktop/GEOLOGY/exam1-build-20260924';
function load(backup){const c={console,Math,Date,JSON,setTimeout(){},localStorage:{getItem(){return null},setItem(){}},document:{readyState:'loading',addEventListener(){}}};c.window=c;c.globalThis=c;vm.createContext(c);let html=backup?cp.execFileSync('tar',['-xOf',path.join(audit,'before-exam1-code.tar.gz'),'index.html'],{encoding:'utf8'}):fs.readFileSync(path.join(root,'index.html'),'utf8');for(const [,s]of html.matchAll(/<script src="([^"]+)"/g)){if(s==='js/app.js')continue;const source=backup?cp.execFileSync('tar',['-xOf',path.join(audit,'before-exam1-code.tar.gz'),s],{encoding:'utf8'}):fs.readFileSync(path.join(root,s),'utf8');vm.runInContext(source,c,{filename:s});}c.L.engine.build();return c.L;}
const L=load(false),old=load(true),E=L.engine,X=L.exam1;
let checks=0;function ok(name,v){assert.ok(v,name);checks++;console.log('PASS '+name);}
const oldIds=Object.keys(old.engine.REG());ok('Every pre-update assessment ID and answer unchanged',oldIds.every(id=>JSON.stringify(E.REG()[id])===JSON.stringify(old.engine.REG()[id])));
ok('Same storage key and concept IDs',L.store.KEY===old.store.KEY&&JSON.stringify(Object.keys(L.CONCEPTS))===JSON.stringify(Object.keys(old.CONCEPTS)));
const newItems=E.itemsFor(it=>it.pool==='exam1');ok('172 Exam 1 answer parts',newItems.length===172);
let mc=0,long=0;newItems.forEach(it=>{assert.ok(it.s.length);if(it.t==='teach'){assert.ok(it.model&&it.rubric.length>=2);return;}let key;if(it.t==='mc'){key=it.o.findIndex(o=>o.ok);assert.equal(it.o.length,4);assert.equal(it.o.filter(o=>o.ok).length,1);mc++;let max=Math.max(...it.o.map(o=>o.t.length));if(it.o[key].t.length===max&&it.o.filter(o=>o.t.length===max).length===1)long++;}else if(it.t==='fill')key=it.acc[0];else if(it.t==='match')key=it.pairs.map(p=>p[1]);assert.equal(E.grade(it,key).ok,true,it.id);});ok('All automatic keys grade correctly; explanation rubrics present',true);console.log('New multiple-choice longest-keyed option:',long+'/'+mc);
L.EXAM1.topics.forEach(t=>{assert.ok(t.media.length);t.media.forEach(m=>{assert.equal(m.kind,'img');assert.ok(fs.existsSync(path.join(root,m.src)));});});ok('Every topic uses supplied source images',true);
for(const f of ['A','B','C']){let r=X.startForm(f);for(const id of X.allIds(r)){let it=E.resolve({id}),a=X.answer(r,id);a.draft=it.t==='mc'?it.o.findIndex(o=>o.ok):it.t==='fill'?it.acc[0]:it.t==='match'?it.pairs.map(p=>p[1]):it.model;X.check(r,id,'h');if(it.t==='teach')X.selfMark(r,id,it.rubric.map(()=>true));}let m=X.metrics(r);ok('Set '+f+' all 54 parts can complete with separate self/auto scores',m.total===54&&m.checked===54&&m.autoCorrect===43&&m.selfCorrect===11&&m.needs===0&&m.unanswered===0);const mcids=r.groups.filter(g=>g.section==='mc').flatMap(g=>g.ids);assert.equal(X.metrics(r,mcids).autoCorrect*2,50);}
for(let i=1;i<=16;i++){for(const diagram of [false,true]){let r=X.drill('T'+i,diagram);assert.ok(r.groups.length>0);for(const g of r.groups){let it=E.resolve({id:g.ids[0]});assert.ok(it.pool==='exam1'||L.EXAM1.foundationIds.includes(it.id));if(diagram)assert.equal((g.media||it.media).kind,'img');}}}ok('All topic/figure drill entry points have introductory curated content',true);
// Backup merge must retain new corrections even when the old export arrives last.
let r=X.startForm('A'),id=r.groups[0].ids[0],a=X.answer(r,id),it=E.resolve({id});a.draft=it.o.findIndex(o=>!o.ok);X.check(r,id);const first=JSON.stringify(a.first),before=L.store.exportJSON();X.retry(r,id);a.draft=it.o.findIndex(o=>o.ok);X.check(r,id);const after=L.store.exportJSON();L.store._setMem(L.store._blank());L.store.importText(after);L.store.importText(before);let merged=X.byId(r.id).answers[id];ok('Importing an older backup preserves first try and newer correction',JSON.stringify(merged.first)===first&&merged.tries.length===1&&merged.tries[0].grade.ok);
const shared=L.engine.conceptStats();
ok('Checked Exam 1 review attempts feed the shared mastery history',Object.values(shared).some(s=>s.att>0));
const permanent=L.store._blank();
permanent.attempts=[{i:'root-a',c:'c1-cycle',ok:true,cf:'m',t:1},{i:'root-b',c:'c1-cycle',ok:true,cf:'h',t:2},{i:'root-c',c:'c1-cycle',ok:false,cf:'h',t:3}];
L.store._setMem(permanent);
ok('A later incorrect answer cannot regress earned mastery',L.engine.conceptStats()['c1-cycle'].status==='mastered');
console.log('TOTAL',checks,'content/persistence checks passed');
