/* Integration checks in isolated Chrome contexts. Does not read or modify the user's browser profile. */
const assert=require('assert/strict'),fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=process.env.EXAM1_AUDIT_DIR||'/Users/ethanheinrick/Desktop/GEOLOGY/exam1-build-20260924';
let passed=0;function check(name,ok){assert.ok(ok,name);console.log('PASS '+name);passed++;}
async function nav(p,h){await p.evaluate(h=>L.app.go(h),h);await p.waitForFunction(h=>location.hash==='#'+h,h);await p.locator('h1').first().waitFor();await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}
async function key(p,host,correct=true){const info=await p.evaluate(i=>{const r=L.exam1.active(),id=r.groups[r.cur].ids[i];return L.engine.resolve({id});},host);const box=p.locator('#exam-item-'+host);
 if(info.t==='mc'||info.t==='tf'){const idx=info.o.findIndex(o=>!!o.ok===correct);await box.locator('[data-oi="'+idx+'"]').click();}
 else if(info.t==='fill')await box.locator('input[type=text]').fill(correct?info.acc[0]:'incorrect term');
 else if(info.t==='match'){for(let i=0;i<info.pairs.length;i++){const ans=correct||i>0?info.pairs[i][1]:info.pairs.find(q=>q[1]!==info.pairs[i][1])[1];await box.locator('select').nth(i).selectOption(ans);}}
 else if(info.t==='teach')await box.locator('textarea').fill('My saved explanation: '+info.model.replace(/<[^>]*>/g,''));
 await box.locator('[data-check]').click();return info;
}
(async()=>{const server=http.createServer((req,res)=>{let rel=decodeURIComponent(req.url.split('?')[0]).replace(/^\//,'')||'index.html';let f=path.resolve(root,rel);if(!f.startsWith(root+path.sep)&&f!==root){res.writeHead(403).end();return;}if(!fs.existsSync(f)){res.writeHead(404).end();return;}res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.html')?'text/html':f.endsWith('.png')?'image/png':'image/jpeg');fs.createReadStream(f).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;
 const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 try{for(const base of ['file://'+root+'/index.html','http://127.0.0.1:'+port+'/index.html']){
 const ctx=await browser.newContext({viewport:{width:1280,height:900}}),p=await ctx.newPage(),errs=[],remote=[];p.on('pageerror',e=>errs.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:'+port+'/'))remote.push(r.url());});
 await p.goto(base+'#exam1');check('16 topic groups '+base,await p.locator('.exam-topic').count()===16);
 const structural=await p.evaluate(()=>{const X=L.EXAM1,E=L.engine,seen=new Set();return Object.entries(X.forms).map(([f,v])=>{const ids=[...v.mc,...v.sa,...v.cases.flatMap(id=>E.caseById(id).items.map(i=>i.id))];const overlap=ids.some(id=>seen.has(id));ids.forEach(id=>seen.add(id));return {f,counts:[v.mc.length,v.sa.length,v.cases.length],parts:ids.length,overlap,topics:new Set(v.mc.flatMap(id=>L.examTopics(E.resolve({id})))).size,mcOK:v.mc.every(id=>{let i=E.resolve({id});return i.t==='mc'&&i.o.length===4&&i.o.filter(o=>o.ok).length===1;}),short:v.sa.map(id=>E.resolve({id}).t),imgs:v.cases.every(id=>E.caseById(id).media.kind==='img')};});});
 check('A/B/C exact counts, distinct questions, 16-topic MC coverage, source images',structural.every(x=>x.counts.join()==='25,8,7'&&x.parts===54&&!x.overlap&&x.topics===16&&x.mcOK&&x.short.join()==='fill,fill,fill,fill,teach,teach,teach,teach'&&x.imgs));
 // Seed representative pre-update progress in this isolated context; preserve exact serialized old fields.
 const old=await p.evaluate(()=>{const s=L.store.load();s.attempts=[{i:'c1-isostasy-m1',c:'c1-isostasy',ok:true,sc:1,cf:'h',m:'practice',t:11},{i:'c1-isostasy-m2',c:'c1-isostasy',ok:true,sc:1,cf:'h',m:'practice',t:12}];s.boss={boss1:{best:.8,runs:[{score:24,total:30,complete:true,ts:13}]}};s.guideRead={'g1-1a':14};s.teach={old:{ts:15,self:'got'}};s.legacy={signal:{},sources:["Earlier import"],imported:10,mapped:0,oldConcepts:0,unmapped:[]};s.mocks=[{id:'old-finished',title:'Earlier mock',score:2,total:3,ts:16,items:[],bySec:{},byCh:{},byCon:{}}];L.engine.buildMock('short');s.mockActive.id='old-active';localStorage.setItem('geol1001-guided-progress-v1','{"sentinel":true}');L.store.save();return JSON.stringify([s.attempts,s.boss,s.guideRead,s.teach,s.legacy,s.mocks,s.mockActive]);});
 await nav(p,'exam1/sets');await p.locator('[data-form="A"]').first().click();await p.locator('[data-q="39"]').waitFor();check('40 grouped questions; no exam timer',await p.locator('[data-q]').count()===40&&await p.locator('#timer').count()===0);
 await key(p,0,false);check('Immediate wrong feedback before finishing',await p.locator('.verdict').innerText()==='Incorrect');const first=await p.evaluate(()=>JSON.stringify(L.exam1.active().answers[L.exam1.active().groups[0].ids[0]].first));
 await p.locator('[data-retry]').click();await key(p,0,true);check('Correction keeps original first answer',await p.evaluate(first=>JSON.stringify(L.exam1.active().answers[L.exam1.active().groups[0].ids[0]].first)===first,first));check('Separate first-try/correction totals',await p.evaluate(()=>{const m=L.exam1.metrics(L.exam1.active());return m.autoCorrect===0&&m.corrected===1&&m.needs===0;}));
 await p.locator('[data-q="25"]').click();await p.locator('#exam-item-0 input[type=text]').fill('transform');await p.reload();check('Term draft survives reload',await p.locator('#exam-item-0 input[type=text]').inputValue()==='transform');await p.locator('[data-check]').click();check('Accepted term grades immediately',await p.locator('.verdict').innerText()==='Correct');
 await p.locator('[data-q="29"]').click();const draft='Weathering breaks granite down; sediment moves, settles and is cemented.';await p.locator('textarea').fill(draft);await p.reload();check('Prose draft survives reload',await p.locator('textarea').inputValue()===draft);await p.locator('[data-check]').click();await p.reload();check('Revealed rubric and immutable response survive reload',await p.locator('[data-self]').count()===1&&await p.locator('textarea').inputValue()===draft&&await p.locator('textarea').isDisabled());await p.locator('[data-rubric]').first().check();await p.locator('[data-self]').click();check('Partial rubric self-check saved',await p.evaluate(()=>{const r=L.exam1.active(),a=r.answers[r.groups[r.cur].ids[0]];return a.first.self&&a.first.grade.sc>0&&!a.first.grade.ok;}));await p.locator('[data-retry]').click();await key(p,0);for(const el of await p.locator('[data-rubric]').all())await el.check();await p.locator('[data-self]').click();check('Self-assessed correction does not replace first rubric',await p.evaluate(()=>{const r=L.exam1.active(),a=r.answers[r.groups[r.cur].ids[0]];return !a.first.grade.ok&&a.tries[0].grade.ok;}));
 await p.locator('[data-q="33"]').click();check('Investigation is one question, three separately checked parts, one source figure',await p.locator('[id^="exam-item-"]').count()===3&&await p.locator('.exam-figure img').count()===1&&await p.locator('.exam-figure h2').innerText()==='Q34 · Follow a surface-to-depth rock path');await key(p,0,false);check('Partial matching feedback',await p.locator('#exam-item-0 .verdict').innerText().then(t=>t.startsWith('Partly correct')));await p.locator('#exam-item-1 input[type=text]').fill('magma');await p.reload();check('Independent case drafts and checked feedback survive reload',await p.locator('#exam-item-1 input').inputValue()==='magma'&&await p.locator('#exam-item-0 .verdict').count()===1);
	 check('Old attempts, Boss, Guide, teach, legacy, mocks and active mock unchanged',await p.evaluate(old=>{let s=L.store.load();return JSON.stringify([s.attempts,s.boss,s.guideRead,s.teach,s.legacy,s.mocks,s.mockActive])===old&&localStorage.getItem('geol1001-guided-progress-v1')==='{"sentinel":true}';},old));check('Exam answers feed shared mastery while existing progress remains mastered',await p.evaluate(()=>L.engine.conceptStats()['c1-cycle'].att>0&&L.engine.conceptStats()['c1-isostasy'].status==='mastered'));
 const backup=await p.evaluate(()=>L.store.exportJSON()),counts=await p.evaluate(()=>L.store.load().examRuns.length);await p.evaluate(text=>{L.store._setMem(L.store._blank());L.store.save();L.store.importText(text);L.store.importText(text);},backup);await p.reload();check('Export/import restores active review, draft, first and correction; merge is idempotent',await p.evaluate(n=>{const r=L.exam1.active(),a=r.answers[r.groups[0].ids[0]];return L.store.load().examRuns.length===n&&!a.first.grade.ok&&a.tries.length===1&&a.tries[0].grade.ok&&r.answers[r.groups[33].ids[1]].draft==='magma';},counts));
 const runId=await p.evaluate(()=>L.exam1.active().id);await p.close();const p2=await ctx.newPage();p2.on('pageerror',e=>errs.push(e.message));await p2.goto(base+'#exam1/take');check('Close tab and reopen resumes the saved run',await p2.evaluate(id=>L.exam1.active().id===id,runId));
 // Every topic and drill must render using actual image files.
 for(let i=1;i<=16;i++){await nav(p2,'exam1/topic/T'+i);await p2.locator('img').first().waitFor();await p2.waitForFunction(()=>[...document.querySelectorAll('main img')].every(im=>im.complete&&im.naturalWidth>0));assert.equal(await p2.locator('main svg').count(),0);}
 check('All 16 topic pages load real course images without generated SVGs',true);
 await nav(p2,'exam1');await p2.locator('[data-diagram="all"]').click();check('20 diagram prompts all carry course images',await p2.evaluate(()=>{let r=L.exam1.active();return r.groups.length===20&&r.groups.every(g=>g.media&&g.media.kind==='img');}));
 await nav(p2,'exam1/history');await p2.locator('#archiveOld').click();check('Old active mock safely archives',await p2.evaluate(()=>!L.store.load().mockActive&&L.store.load().mockArchived.some(m=>m.id==='old-active')));await p2.locator('[data-old-resume]').click();check('Old active mock safely resumes',await p2.evaluate(()=>L.store.load().mockActive.id==='old-active'));await nav(p2,'exam1');
 for(const h of ['home','guide/c1s7','practice','review','boss','progress','evidence','data']){await nav(p2,h);check('Existing '+h+' view renders',(await p2.locator('h1').count())>0);}
 await p2.setViewportSize({width:390,height:844});for(const h of ['exam1','exam1/sets','exam1/topic/T10','exam1/take','exam1/history']){await nav(p2,h);check('Phone width '+h,await p2.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await nav(p2,'exam1/take');if(base.startsWith('file:')){await p2.screenshot({path:path.join(out,'exam1-phone.png'),fullPage:true});await p2.setViewportSize({width:1280,height:900});await nav(p2,'exam1/topic/T5');await p2.screenshot({path:path.join(out,'exam1-isostasy.png'),fullPage:true});await nav(p2,'exam1/sets');await p2.screenshot({path:path.join(out,'exam1-sets.png'),fullPage:true});}
 if(errs.length)console.log('RUNTIME ERRORS',errs);check('No runtime errors',errs.length===0);check('No external requests',remote.length===0);await ctx.close();
 }
 // Simulated browser quota failure must be visible rather than silently claiming saved state.
 const c=await browser.newContext(),p=await c.newPage();await p.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('quota test','QuotaExceededError');};});await p.goto('file://'+root+'/index.html#exam1/sets');await p.locator('[data-form="A"]').first().click();check('Storage failure surfaced immediately',await p.locator('#examSave').innerText().then(t=>/blocked|failed/.test(t)));await c.close();
 console.log('TOTAL '+passed+' checks passed');
 }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
