/* Generated mocks: frozen content, independent keys, novelty, scoring and storage. No browser automation. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..');let clock=1800000000000,checks=0;
class Clock extends Date{constructor(...a){super(...(a.length?a:[clock]));}static now(){return ++clock;}}
function load(storage={}){const c={console,Math,Date:Clock,JSON,setTimeout(){},document:{readyState:'loading',addEventListener(){}},localStorage:{getItem(k){return storage[k]||null;},setItem(k,v){storage[k]=v;}}};c.window=c;vm.createContext(c);for(const [,url]of fs.readFileSync(path.join(root,'index.html'),'utf8').matchAll(/<script src="([^"]+)"/g)){const f=url.split('?')[0];if(f!=='js/app.js')vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),c,{filename:f});}c.L.engine.build();return c.L;}
function test(name,fn){fn();checks++;console.log('PASS '+name);}
const disk={},L=load(disk),E=L.engine,S=L.store,X=L.exam1,F=L.freshMocks;
function blank(){S._setMem(S._blank());E.build();S.save();}
function expected(it){if(it.t==='mc')return it.o.findIndex(o=>o.ok);const [family,task,pair,part]=it.freshKey.split(':'),f=L.FRESH_FACTS.find(f=>f.id===family),[i,j]=it.observationRows||pair.split('-').map(Number),a=f.rows[i],b=f.rows[j];if(it.t==='teach')return it.model;if(it.t==='match')return [a.label,b.label];if(it.t==='fill')return a.label;throw Error('Unknown item '+it.id);}
const catalog=F.catalog(),flat=[...catalog.mc,...catalog.fill,...catalog.teach,...catalog.cases.flatMap(c=>c.items)];
test('Entire catalog has unique stable IDs, valid keys, sources and concepts',()=>{assert.equal(new Set(flat.map(i=>i.id)).size,flat.length);for(const it of flat){assert.ok(L.CONCEPTS[it.c],it.id+' concept');assert.ok(it.s.length&&it.evidence&&!it.evidence.startsWith('/'));assert.ok(it.topics.length===1);if(it.t==='mc'){assert.equal(new Set(it.o.map(o=>o.t)).size,4);assert.equal(it.o.filter(o=>o.ok).length,1);assert.ok(expected(it)>=0);assert.ok(it.o[expected(it)].ok,it.freshKey);for(let n=0;n<4;n++)assert.equal(E.grade(it,n).ok,n===expected(it),it.freshKey);}else if(it.t!=='teach')assert.ok(E.grade(it,expected(it)).ok,it.freshKey);else assert.ok(it.rubric.length===2&&it.model);}});
test('All investigations use existing course images with explicit target and matching',()=>{for(const c of catalog.cases){const media=Array.isArray(c.media)?c.media:[c.media];assert.ok(media.length);for(const m of media){assert.equal(m.kind,'img');assert.ok(fs.existsSync(path.join(root,m.src)),m.src);}assert.match(c.stem,/For each observation, determine/);assert.equal(c.items[1].t,'match');assert.equal(new Set(c.items.map(i=>i.masteryRoot)).size,1);}});
test('Direction and Bowen keys match independent course-model checks',()=>{const keys={pt:['Rightward','Leftward','Upward','Downward','Up and right','Down and right','Up and left','Down and left'],hotspot:['Northward','Southward','Eastward','Westward','Northeastward','Southwestward','Northwestward','Southeastward']};for(const [family,labels]of Object.entries(keys))assert.deepEqual(Array.from(L.FRESH_FACTS.find(f=>f.id===family).rows,r=>r.label),labels);for(const family of ['bowen','bowen-heating']){const sequence=['Olivine','Pyroxene','Amphibole','Biotite'];for(const r of L.FRESH_FACTS.find(f=>f.id===family).rows){const mentioned=sequence.filter(m=>r.observation.toLowerCase().includes(m.toLowerCase()));assert.equal(mentioned.length,2);assert.equal(r.label,mentioned[family==='bowen'?0:1]);}}});
test('Section 1 uses discrete authored questions and the review-scope quiz bank',()=>{assert.ok(catalog.mc.length>=100);assert.ok(catalog.mc.filter(it=>it.freshKey.startsWith('quiz:')).length>=25);for(const it of catalog.mc){assert.doesNotMatch(it.q,/For each observation|Which pairing correctly interprets|best fits this observation/i);assert.ok(it.q.length>=25);assert.ok(it.x);assert.equal(it.o.length,4);}for(const [tid,count] of Object.entries(F.MC_COUNTS))assert.ok(catalog.mc.filter(it=>it.topics[0]===tid).length>=count*3,tid);assert.equal(Object.keys(E.REG()).length,627);assert.equal(Object.keys(L.CONCEPTS).length,102);});
const frozen=[];
test('A, B and C each save 25/8/7, 54 parts, all 16 topics and no repeated variant',()=>{blank();const used=new Set();for(const [i,f]of ['A','B','C'].entries()){const r=X.startFreshForm(f,202609270+i);frozen.push(JSON.parse(JSON.stringify(r)));for(const [sec,n]of [['mc',25],['sa',8],['inv',7]])assert.equal(r.groups.filter(g=>g.section===sec).length,n);assert.deepEqual(Array.from(r.groups,g=>g.n),Array.from({length:40},(_,i)=>i+1));assert.equal(Object.keys(r.freshItems).length,54);assert.equal(new Set(r.groups.slice(0,25).flatMap(g=>E.resolve({id:g.ids[0]}).topics)).size,16);const local=new Set(r.freshKeys.map(F.novelty));assert.equal(local.size,40);for(const k of local){assert.ok(!used.has(k),k);used.add(k);}assert.equal(X.metrics(r).autoTotal,43);assert.equal(X.metrics(r).selfTotal,11);}});
test('Every answer in three complete forms grades and joins shared mastery',()=>{for(const r of S.load().examRuns){for(const id of X.allIds(r)){const it=E.resolve({id}),a=X.answer(r,id);a.draft=expected(it);assert.ok(X.check(r,id,'h'),id);if(it.t==='teach')X.selfMark(r,id,it.rubric.map(()=>true));}const m=X.metrics(r);assert.equal(m.checked,54);assert.equal(m.autoCorrect,43);assert.equal(m.selfCorrect,11);}assert.equal(E.allAttempts().length,162);assert.ok(Object.values(E.conceptStats()).some(s=>s.status==='mastered'));});
test('Cold reload preserves frozen questions, answer orders, keys and grades',()=>{const fresh=load(disk);for(const r of S.load().examRuns){const rr=fresh.exam1.byId(r.id);assert.equal(JSON.stringify(rr.freshItems),JSON.stringify(r.freshItems));assert.equal(JSON.stringify(rr.orders),JSON.stringify(r.orders));assert.equal(JSON.stringify(rr.matchOrders),JSON.stringify(r.matchOrders));assert.equal(fresh.exam1.metrics(rr).checked,54);for(const id of X.allIds(r))assert.equal(JSON.stringify(fresh.engine.resolve({id})),JSON.stringify(E.resolve({id})));}});
test('Snapshot resolution does not depend on regenerating current templates',()=>{const fresh=load(disk);fresh.FRESH_FACTS.length=0;fresh.freshMocks.catalog=()=>{throw Error('Must not regenerate saved content');};for(const r of fresh.store.load().examRuns)assert.equal(fresh.exam1.metrics(r).checked,54);});
test('Export/import preserves generation history and refuses to recycle exhausted MC',()=>{const backup=S.exportJSON(),other=load();assert.ok(other.store.importText(backup).ok);assert.ok(other.store.importText(backup).ok);assert.equal(other.store.load().examRuns.length,3);assert.throws(()=>other.exam1.startFreshForm('A',202609270),/No unused/);assert.equal(other.exam1.metrics(other.exam1.byId(frozen[0].id)).checked,54);});
test('Generated first scores are immutable and corrections remain assisted',()=>{blank();const r=X.startFreshForm('B',345),id=r.groups[0].ids[0],it=E.resolve({id}),a=X.answer(r,id);a.draft=it.o.findIndex(o=>!o.ok);X.check(r,id,'h');const first=JSON.stringify(a.first),before=S.exportJSON();X.retry(r,id);a.draft=expected(it);X.check(r,id,'m');assert.equal(JSON.stringify(a.first),first);assert.equal(X.metrics(r).autoCorrect,0);assert.equal(X.metrics(r).corrected,1);assert.equal(E.allAttempts()[1].h,1);const after=S.exportJSON();blank();S.importText(after);S.importText(before);const rr=X.byId(r.id);assert.equal(rr.answers[id].first.grade.ok,false);assert.equal(rr.answers[id].tries.length,1);assert.equal(X.metrics(rr).corrected,1);});
test('Linked investigation subparts cannot alone earn mastery or clear a miss',()=>{blank();const r=X.startFreshForm('A',123),g=r.groups.find(g=>g.section==='inv'),it=E.resolve({id:g.ids[0]});for(const id of g.ids){const q=E.resolve({id});X.answer(r,id).draft=expected(q);X.check(r,id,'h');if(q.t==='teach')X.selfMark(r,id,q.rubric.map(()=>true));}assert.equal(E.conceptStats()[it.c].att,3);assert.notEqual(E.conceptStats()[it.c].status,'mastered');assert.equal(new Set(E.allAttempts().map(a=>a.root)).size,1);});
test('Seed reproduces content, while the same seed with history draws new content',()=>{blank();const a=F.create('C',S.load(),0),b=F.create('C',S.load(),0);assert.equal(JSON.stringify(a),JSON.stringify(b));const r=X.startFreshForm('C',0),c=F.create('C',S.load(),0),old=new Set(r.freshKeys.map(F.novelty));for(const k of c.keys)assert.ok(!old.has(F.novelty(k)));});
test('Three successive forms remain valid across 30 independent seeds',()=>{for(let i=1;i<=30;i++){const state=S._blank();for(const form of ['A','B','C']){const made=F.create(form,state,i);state.examRuns.push({freshItems:made.items,freshKeys:made.keys});assert.equal(made.groups.length,40);}}});
test('Exhaustion is explicit, never recycles and never saves a partial exam',()=>{blank();let completed=0,failed=false;for(let n=0;n<100;n++){const before=JSON.stringify(S.load());try{X.startFreshForm(['A','B','C'][n%3],n+777);completed++;}catch(e){assert.match(e.message,/No unused/);assert.equal(JSON.stringify(S.load()),before);failed=true;break;}}assert.ok(failed);assert.ok(completed>=3);console.log('INFO finite-pool stress completed',completed,'full forms before refusing reuse');});
test('Old in-progress mock upgrades only untouched MC; all answers and Sections 2/3 remain intact',()=>{blank();const r=X.startFreshForm('A',333),later=JSON.stringify(r.groups.slice(25).map(g=>[g,g.ids.map(id=>r.freshItems[id])])),original=[];r.freshVersion=1;r.mcVersion=undefined;r.groups.slice(0,25).forEach((g,i)=>{const id='fresh1-legacy-'+i,old=JSON.parse(JSON.stringify(r.freshItems[g.ids[0]]));old.id=id;old.freshKey='legacy:identify:'+i;old.q='Old repeated observation '+i+'; which label fits?';r.freshItems[id]=old;r.orders[id]=r.orders[g.ids[0]];g.ids[0]=id;original.push(id);});r.answers[original[0]]={first:{grade:{ok:false,sc:0},response:1,at:1},tries:[],draft:1};r.answers[original[1]]={first:null,tries:[],draft:2};const beforeAnswers=JSON.stringify(r.answers),beforeLater=JSON.stringify(r.groups.slice(25).map(g=>[g,g.ids.map(id=>r.freshItems[id])]));assert.equal(beforeLater,later);const count=F.upgradeRuns(S.load());assert.equal(count,23);assert.equal(r.mcVersion,2);assert.equal(r.groups[0].ids[0],original[0]);assert.equal(r.groups[1].ids[0],original[1]);assert.ok(r.groups.slice(2,25).every(g=>!g.ids[0].includes('legacy')));assert.equal(JSON.stringify(r.answers),beforeAnswers);assert.equal(JSON.stringify(r.groups.slice(25).map(g=>[g,g.ids.map(id=>r.freshItems[id])])),later);assert.equal(F.upgradeRuns(S.load()),0);S.save();const cold=load(disk),rr=cold.exam1.byId(r.id);assert.equal(JSON.stringify(rr.groups.slice(25).map(g=>[g,g.ids.map(id=>rr.freshItems[id])])),later);assert.equal(JSON.stringify(rr.answers),beforeAnswers);});
if(process.env.FRESH_AUDIT){fs.mkdirSync(process.env.FRESH_AUDIT,{recursive:true});fs.writeFileSync(path.join(process.env.FRESH_AUDIT,'frozen-forms.json'),JSON.stringify(frozen,null,2));fs.writeFileSync(path.join(process.env.FRESH_AUDIT,'catalog-summary.json'),JSON.stringify({mc:catalog.mc.length,fill:catalog.fill.length,teach:catalog.teach.length,investigations:catalog.cases.length,questionParts:flat.length,models:L.FRESH_FACTS.length,seeds:frozen.map(r=>r.seed)},null,2));}
console.log('TOTAL',checks,'fresh mock checks passed');
